smithy-model/src/main/java/software/amazon/smithy/model/shapes/CollectionShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MapShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java

No logic changes, just centralizes the checks for getting a required
member from a builder or from mixins.

Simplify getting required mixin members

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateEnumDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/directed/directed-model.smithy

Use transforms to flatten mixins and change string enums to enum shapes. Added test assertions for these behaviors.

Update CodegenDirector to handle mixin and enum shape

---

.github/workflows/ci.yml

Disables running CI on idl-2.0 branch.

Disable CI on idl-2.0 branch

---

docs/source-2.0/guides/migrating-idl-1-to-2.rst

Adds converting sets to lists section to idl-1 to idl-2 migration guide.
This PR also fixes a missing `smithy` tag to enable syntax highlighting on a code block in the migration guide.

Add set to list doc section

---

docs/source-2.0/quickstart.rst

*Issue*
`properties` reference in quickstart not rendering properly due to typo.
Replace the erroneous `-` with a back tick.

Fix typo in quickstart

---

smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy

Adds missing @readonly traits on HTTP GET protocol tests, eliminating the following warnings:
```
WARNING: aws.protocoltests.restjson#ResponseCodeRequired (HttpMethodSemantics)
@ ~/smithy/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy
|
22 | @http(method: "GET", uri: "/responseCodeRequired", code: 200)
| ^
= This operation uses the `GET` method in the `http` trait, but is not marked with the readonly trait
WARNING: aws.protocoltests.restjson#ResponseCodeHttpFallback (HttpMethodSemantics)
@ ~/smithy/smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy
|
34 | @http(method: "GET", uri: "/responseCodeHttpFallback", code: 201)
| ^
= This operation uses the `GET` method in the `http` trait, but is not marked with the readonly trait
``` …

Add missing readonly traits on HTTP GET tests

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderShapeMap.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/does-not-reparses-synthetic-traits.smithy

Synthetic traits should not be parsed again. That will cause a failure, for instance, if we import a 1.0 model that has @enum traits. If we try to reparse them this will fail with an error
```
Unable to resolve trait `smithy.synthetic#enum`
```

Filter out synthetic traits before turning those into LoadOperations

---

smithy-aws-protocol-tests/model/restJson1/unions.smithy

Without this, TypeScript SSDK was failing
PostUnionWithJsonNameResponse*:ServerResponse tests [because the generated tests
use a request with `{}`](https://github.com/awslabs/smithy-typescript/blob/ac8fb3f406807bfd14a8f7be8d938377bde36189/smithy-typescript-codegen/src/main/java/software/amazon/smithy/typescript/codegen/HttpProtocolTestGenerator.java#L731-L737) but that fails the validation logic since a member was
marked required. So removing the required trait from the input.

Update PostUnionWithJsonName protocol test

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

ModelAssembler event listeners were receiving events twice in some cases,
causing events to appear twice when running the CLI/Gradle/etc.

Fix issue where we emitted events twice

---

docs/source-1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source-1.0/spec/aws/aws-json-1_1-protocol.rst
docs/source-1.0/spec/aws/aws-json.rst.template
docs/source-1.0/spec/aws/aws-query-protocol.rst
docs/source-1.0/spec/aws/aws-query-serialization.rst.template
docs/source-1.0/spec/aws/aws-restjson1-protocol.rst
docs/source-1.0/spec/aws/aws-restxml-protocol.rst
docs/source-1.0/spec/core/behavior-traits.rst
docs/source-1.0/spec/core/idl.rst
docs/source-1.0/spec/core/json-ast.rst
docs/source-1.0/spec/core/model-validation.rst
docs/source-1.0/spec/core/model.rst
docs/source-1.0/spec/core/selectors.rst
docs/source-1.0/spec/core/xml-traits.rst
docs/source-1.0/spec/http-protocol-compliance-tests.rst
docs/source-2.0/spec/idl.rst
docs/source-2.0/spec/protocol-traits.rst
docs/source-2.0/spec/selectors.rst

N/A
---
Update Smithy IDL ABNF Docs:
- Smithy 1.0: Update all ABNF to match ABNF RFC
- Smithy 2.0: Update IDL ABNF, XmlName ABNF, and minor doc fixes
---
*Testing:*
Ran `make clean html`, no warnings / errors.
---

Update Smithy IDL ABNF Docs

---

smithy-build/src/main/java/software/amazon/smithy/build/ProjectionResult.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildPlugin.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildResult.java
smithy-build/src/main/java/software/amazon/smithy/build/model/ProjectionConfig.java
smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildConfig.java
smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildUtils.java
smithy-build/src/main/java/software/amazon/smithy/build/plugins/BuildInfoPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/java/software/amazon/smithy/build/Test1ParallelPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test1SerialPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test2ParallelPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test2SerialPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/model/loads-from-node.json

* Removes the need to create intermediate SmithyBuildConfig classes when loading configurations from JSON files.
* Only perform variable expansion if it's used.
* Adds fromNode for smithy-build classes.
* Removes several instances of Stream that are called in hot paths / don't need stream overhead.
* Switch from custom ForkJoinPool to parallel stream. There's no measurable difference here and this approach is simpler.

Cleanup smithy-build

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java

Generators like smithy-typescript are affected by calling this transform. So making it opt-in, similar to createDedicatedInputsAndOutputs.

Make string enum to enum shape transform opt-in in CodegenDirector

---

smithy-build/src/main/java/software/amazon/smithy/build/plugins/BuildInfoPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/plugins/BuildInfoPluginTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/plugins/build-info/example.smithy

N/A
---
Filter out synthetic traits from build info `traitNames`, as synthetic traits should not be serialized and should only be in-memory.
---
*Testing:*
- Ran `./gradlew clean build check`.
- Added unit test `BuildInfoPluginTest > testFiltersSyntheticEnumTrait()` that tests `smithy.synthetic#enum` is not present in `smithy-build-info.json`(synthetic enum trait generated from enum shape).
```diff
<             "smithy.api#unstable",
<             "smithy.synthetic#enum"
---
>             "smithy.api#unstable"
```
<details>
<summary>
Complete Output Before / After
</summary>
- Before
```json
{
"metadata": {},
"operationShapeIds": [
"smithy.example#ChangeCard"
],
"projection": {
"abstract": false,
"imports": [],
"plugins": {}, …
```

Filter out synthetic traits from build info

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/EnumShapeTest.java

For the case where the enum trait does not have names and synthesizeEnumNames
is false.
There is no functional difference with this change, however a more specific and appropriate log message will be used for case where names aren't defined in the enum trait (i.e., they would need to be synthesized) but the synthesizeEnumNames is set to false.
Without the EnumShape.java change in this PR, the newly added canConvertToEnumWithNamelessEnumTrait test case for `assertFalse(EnumShape.canConvertToEnum(string, false));` would log
```
INFO: Unable to convert string shape `ns.foo#bar` to enum shape because it has at least one value which cannot be safely synthesized into a name: bar
```
With the change, the test case now logs the more appropriate log for this use case
```
INFO: Unable to convert …
```

Fix a log message for unable to convert string enum to enum shape

---

docs/source-2.0/spec/idl.rst

Inlined structures ABNF was missing rule name for structure resources.

Fix ABNF grammar for inlined structures.

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedShapeType.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedShapeTypeTest.java

It isn't an error to migrate a set to a list with the uniqueItems
trait. This is a recommended change because sets are deprecated and
should not be implemented by any tooling.

Ignore valid set->list type change in diff

---

docs/source-1.0/guides/building-models/gradle-plugin.rst
docs/source-2.0/guides/building-models/gradle-plugin.rst

The quick start guide is a good starter example for basic usage of the gradle plugin.
#887 

Update gradle plugin guide to direct to quick start guide for example usage

---

smithy-model/src/main/java/software/amazon/smithy/model/node/NumberNode.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NumberNodeTest.java

Add method to check if NumberNode is set to zero

---

docs/source-2.0/spec/idl.rst

Simple doc update. The code example used operationInputSuffix twice.

docs: Fix operationOutputSuffix in example code snippet

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/IntEnumShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/DowngradeToV1.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ModelSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/DowngradeToV1Test.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/data-mixins.1.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/data-mixins.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/enums.1.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/operation-mixins.1.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/operation-mixins.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/resource-mixins.1.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/service-mixins-with-overrides.1.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/service-mixins.1.0.json

This commit adds the ability to downgrade the in-memory semantic model to 1.0 models, and adds support for serializing 1.0 JSON AST models to ModelSerializer.

Add support for 1.0 downgrades and serialization

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/AstModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/AstModelLoaderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/ast-empty-apply-1.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/ast-empty-apply-2.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/synthetic-boxing-mixins.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/mixins/no-empty-apply-types.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/mixins/no-empty-apply-types.smithy

This commit also fixes an issue where we would sometimes add empty apply statements to the JSON AST because a mixin introduces no traits. The AST parser now handles this without failing, and the model serializer no longer writes out empty apply blocks.

Add test for synthetic box traits on mixins

---

config/spotbugs/filter.xml
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java

The previous implementation could cause a recursive update error when a shape ID is purged from the cache because it attempted to remove an element from the ConcurrentHashMap inside of a computeIfAbsent call. This updated approach is simpler and instead separates prelude shape IDs into a ConcurrentHashMap that just stops caching after 500 entries are in the cache (which does more than cover the shapes currently in the prelude), and uses a synchronized LinkedHashMap to function as an LRU cache for all other shape IDs. The performance of this approach vs what we had previously is essentially the same.

Simplify ShapeId caching

---

docs/source-1.0/spec/aws/aws-json.rst.template
docs/source-2.0/aws/protocols/aws-json.rst.template
smithy-aws-protocol-tests/model/awsJson1_0WithQueryCompatible/errors.smithy
smithy-aws-protocol-tests/model/awsJson1_0WithQueryCompatible/main.smithy
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/AwsQueryCompatibleTrait.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/aws-query-compatible.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-query-compatible-does-not-support-non-aws-json.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-query-compatible-does-not-support-non-aws-json.smithy

This commit adds `aws.protocols#awsQueryCompatible` trait which allows backward compatibility when migrating from `awsQuery` to `awsJson1_0`.

Add AwsQueryCompatible trait

---

docs/source-1.0/spec/core/idl.rst
docs/source-2.0/spec/idl.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java

This fixes an issue where `applySomeShape @someTrait` was valid, without any space between the apply and shape name. The fix makes it so spacing is required, not line breaks as was the case in the old ABNF, to be consistent with other shapes grammar (see [SimpleShapeStatement](https://awslabs.github.io/smithy/2.0/spec/idl.html#grammar-token-smithy-SimpleShapeStatement))

Fix apply statement parsing and ABNF

---

smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PrivateAccessValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/private-access.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/private-access.json

#1369 
`PrivateAccessValidator` was not checking trait relationships which allowed private traits to be referenced in any namespace. The `HttpConfiguration` mixin in aws.protocols was not including private in its `localTraits`, which caused the private trait to be applied to any shape that mixed in `HttpConfiguration`. This issue wasn't apparent because trait relationships were not being validated for private access. The private access validation test was updated to check for this.
This could be a breaking change for any Smithy models that are using private traits in other namespaces, either directly or through a mixin that doesn't have private included in its `localTraits`.
By submitting this pull request, I confirm that my contribution …

Enforce private on traits

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedShape.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedShapeType.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedShapeTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedShapeTypeTest.java

N/A
---
Update smithy-diff for strings with the enum trait to enum shapes
Remove the following noise from smithy-diff:
- Errors for changing shape type from strings with the `enum` trait to enum shapes since the `enum` trait is deprecated.
- Notes for members added to the converted enum shapes.
Updated `ChangedEnumTrait` to not just compare changed `enum` traits, but also changes of an `enum` trait to its converted enum shape.
---
*Testing:*
- Run `./gradlew clean build check :smithy-cli:runtime`
- Included new unit tests
- Copy 2 example 1.0 -> 2.0 models from aws-sdk-go-v2
- Run smithy cli diff on the 2 models and verify logs
---
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Update smithy-diff for strings with the enum trait to enum shapes

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/defers-failure.json

Revert "Defer projection failure until after plugins run (#1416)"

---

docs/source-2.0/spec/simple-types.rst

Fixes the `@enumValue` example for intEnums.

Fix intEnum example

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java

This was missed in https://github.com/awslabs/smithy/pull/1370

Fix javadoc for CodegenDirector.simplifyModelForServiceCodegen

---

docs/source-2.0/aws/amazon-apigateway.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/authorizers.json
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizerDefinition.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTrait.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTraitValidator.java
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.smithy
smithy-aws-apigateway-traits/src/test/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTraitTest.java

This commit adds support for the `authorizerPayloadFormatVersion` and `enableSimpleResponses` members in `apiGateway#authorizers`. These members are used to properly define authorizers for HTTP APIs.

Add support for missing authorizer members

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateIntEnumDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/directed/directed-model.smithy

Adds `intEnum` support to DirectedCodegen.

Add intEnum DirectedCodegen

---

smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.smithy

Added missing doc comments to each of the `PayloadFormatVersion` enum members. This is needed to avoid errors when validating that all enum members have documentation.

Add doc comment to each of the PayloadFormatVersion members

---

smithy-build/src/test/java/software/amazon/smithy/build/transforms/ExcludeShapesByTagTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filter-by-tags.smithy
smithy-model/src/main/java/software/amazon/smithy/model/transform/FilterShapes.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/plugins/CleanStructureAndUnionMembers.java

This fixes a bug that was preventing enum members from being removable from transforms, such as removeShapesByTag.

Allow transforms to remove enum members

---

docs/source-2.0/aws/protocols/aws-json.rst.template
docs/source-2.0/aws/protocols/aws-query-serialization.rst.template
docs/source-2.0/spec/behavior-traits.rst
docs/source-2.0/spec/constraint-traits.rst
docs/source-2.0/spec/endpoint-traits.rst
docs/source-2.0/spec/http-bindings.rst
docs/source-2.0/spec/idl.rst
docs/source-2.0/spec/protocol-traits.rst
docs/source-2.0/spec/selectors.rst

One of our RFC links was broken because it wasn't using the RFC directive. This updates every RFC link in the 2.0 docs to use the directive.

Fix RFC links

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelInteropTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid-1.0-model-upgraded.smithy

We previously did not attempt to perform model interop transforms if a model had errors. For example, if a model referred to an unknown trait, the model wouldn't use the interop transformation. Some use cases might choose to ignore unknown traits and other errors by _not_ unwrapping the assembled model and instead directly accessing the result from ValidatedResult. In these cases, the model would have not gone through the interop transform, resulting in an unexpect model (for example, if performing a diff against a 1.0 and 2.0 model, the upgrade won't run and causes the models to appear to be wildly different).

Always attempt model interop transforms

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/IdentifierBindingIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceIdentifierBindingValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/IdentifierBindingIndexTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-conflicting-bindings.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-conflicting-bindings.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/knowledge/colliding-resource-identifiers.smithy

When loading a model with multiple members bound to the same resource identifier, Smithy failed with an error in IdentifierBindingIndex due to Collectors.toMap:
```
Duplicate key X (attempted merging values y and z)
```
This change updates IdentifierBindingIndex to ignore collisions. However this means that colliding resource identifier bindings would be ignored (which is arguably worse than failing to load the model since it wouldn't ever flag these issues, and retroactively enforcing things is always challenging). To address this, I added validation to detect when members with the resourceIdentifier trait conflict with members of the same binding name or members that have the same resourceIdentifier trait. …

Fix resource identifier collision and validation

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java

This validator now does not emit trait change warnings when the required trait is changed, and instead relies on ChangedNullability (this matches how the box trait is handled too). When the required trait is removed from a member that targets a structure or union, a warning is emitted instead of an error to indicate that this is often allowed in Smithy generators that treat these members as always nullable regardless of the required trait.

Improve ChangedNullability diff evaluator

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/suppression-test.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/suppression-test.smithy

The suppress trait contained a restrictive pattern trait that was not present in validator ID definitions. This meant that validation events could be suppressed in metadata suppressions (where there was no pattern validation), but not using the `@suppress` trait. Adding the pattern from the `@suppress` trait to validation event IDs at this point has the potential to break existing models, so that is not a desirable alternative.
Closes #987

Remove pattern from suppress trait entries

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/default-subsequent-trait.smithy

This commit fixes an issue where documentation comments were dropped for members that follow a member with a default value. Pending docs are only cleared when a default isn't encountered or the container is complete.
Fixes #1457 

Fix dropping doc comments after default values

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedDefault.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/NullableIndex.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/NullableIndexTest.java

Smithy-Diff was flagging acceptable changes of removing `@default(null)` from member when the trait had no effect because the target shape was already nullable. NullableIndex was also giving the `@default(null)` trait precedence over the `@required` trait which is incorrect. Required members are non-nullable, and the `@default(null)` trait doesn't override this. It simply means that there is no default value for the member (so coupled with the required trait, the member is still always present).

Correct precedence in NullableIndex and fix diffs

---

docs/source-1.0/spec/core/stream-traits.rst
docs/source-2.0/spec/streaming.rst

* Clarify that streaming trait members need httpPayload when using an http binding protocol.
* Clarify that servers should interpret streaming members as having a default value of zero bytes.
* Mention this in the v1 docs too.
* Fixed a doc linking issue for the streaming docs where we were using the wrong casing.
Closes #1380
Addresses #1456

Clarify streaming trait values and semantics

---

docs/source-2.0/guides/model-linters.rst
smithy-linters/src/main/java/software/amazon/smithy/linters/ReservedWordsValidator.java
smithy-linters/src/main/java/software/amazon/smithy/linters/WildcardMatcher.java
smithy-linters/src/main/java/software/amazon/smithy/linters/WordBoundaryMatcher.java
smithy-linters/src/test/java/software/amazon/smithy/linters/WildcardMatcherTest.java
smithy-linters/src/test/java/software/amazon/smithy/linters/WordBoundaryMatcherTest.java

Add ability to lint based on word boundaries
This commit introduces a new syntax for matching words with the
ReservedWords linter and is intended to be used with the upcoming
sensitive words linter defined in #1364.
In addition to supporting wildcard searches ("*" prefix, suffix,
and contains), we now support matching based on word boundaries.
This commit introduces the "terms" keyword for word boundary
searches and adds dedicated abstractions for word boundary and
wildcard matching.
For example, "access key id" will match "AccessKeyId",
"access_key_id", "accessKeyID", "access_key_id100", "AccesKeyIDValue".
It will also match when all the words are concatenated together:
"accesskeyid". However, it will not match "accesskey_id" because it
only has two word boundaries ("accesskey" and …

Add ability to lint based on word boundaries

---

docs/source-1.0/spec/core/model.rst
docs/source-2.0/spec/model.rst
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeIdTest.java

N/A
---
Previously, the ABNF did not match the identifier parser.
This commit updates the ABNF to match current parsing behavior, and updates the identifier parser to avoid out of bounds exceptions.
Also, a set of tests are added for ONLY parsing identifiers rather than being mixed with namespace tests.
---

Update identifier ABNF and parser

---

smithy-aws-protocol-tests/model/awsJson1_1/documents.smithy
smithy-aws-protocol-tests/model/awsJson1_1/empty-operation.smithy
smithy-aws-protocol-tests/model/awsJson1_1/endpoint-paths.smithy
smithy-aws-protocol-tests/model/awsJson1_1/endpoints.smithy
smithy-aws-protocol-tests/model/awsJson1_1/enums.smithy
smithy-aws-protocol-tests/model/awsJson1_1/kitchen-sink.smithy
smithy-aws-protocol-tests/model/awsJson1_1/null.smithy

Resolves #1391
*Description of changes:* Add missing `X-Amz-Target` header for AWS JSON 1.1 protocol `@httpRequestTests` listed in #1391

Add `x-amz-target` for missing AWS JSON 1.1 tests

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java

In smithy-diff, traits that have `diff` tags applied to their definitions can be properly evaluated on modification. However, it is possible for models to be loaded without trait definitions, meaning no diff evaluation occurs. This commit updates the ModifiedTrait evaluator to emit events when a trait without a definition is not constant across the compared models.

Warn on unknown trait diffs

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java

Some languages need to generate code before shapes are generated. Previously such languages could have used the service generation hook to perform this, but that was moved to occur after generating the other shapes.
Python particularly needs this because the language has this cool feature where it can't intelligently resolve everything at the top level of a file. For example, you have to define a parent class earlier in the file than any subclasses. Python generates service-specific errors so this is fairly critical.

Add custom codegen hook before shape generation

---

docs/source-1.0/spec/core/protocol-traits.rst

The previous link redirects to https://bib.ietf.org/public/rfc/html/rfc3339.html#anchor14, which displays a generic "404 not found" page.

Fix dead link to RFC3339

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-map.smithy

Fix `@httpMalformedRequestTests` being applied to the wrong operation

---

docs/source-2.0/spec/model-validation.rst
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/TestHelper.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidationEvent.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/suppressions/MetadataSuppression.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/suppressions/TraitSuppression.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ValidationEventTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/suppressions/MetadataSuppressionTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/suppressions/TraitSuppressionTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/suppression-hierarchy.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/suppression-hierarchy.smithy

Many of the validators in Smithy and Smithy Diff today emit events for various reasons. A single validator might event different events with different severities, and there is currently no way to suppress just one specific type of event for a given validator. For example, the ChangedNullability SmithyDiff validator emits events for various reasons, some of which different tools may choose to suppress. However, without inspecting the message of the event, there's no way to know what you're suppressing.
To give existing validators the ability to emit more granular validation events without breaking current validators, this change introduces event ID hierarchies and hierarchical suppression IDs using dots (.). For example, ChangedNullability.RemovedRequiredTrait is now emitted, and tools can …

Add support for hierarchical event IDs

---

docs/source-1.0/spec/core/model.rst
docs/source-2.0/spec/service-types.rst
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/IdentifierBindingIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceIdentifierBindingValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/IdentifierBindingIndexTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-conflicting-bindings.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-conflicting-bindings.smithy

This commit updates the validation for resource identifier collisions to warn instead of error. When an explicit and implicit binding for the same resource identifier are found, the explicit binding is preferred.

Lower resource identifier collisions to warning

---

.github/dependabot.yml

This PR adds dependabot updates for dependencies in GitHub Action workflows.
> Actions are often updated with bug fixes and new features to make automated processes more reliable, faster, and safer. When you enable Dependabot version updates for GitHub Actions, Dependabot will help ensure that references to actions in a repository's workflow.yml file are kept up to date.
>
> https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
~Here should go an example line of code which is outdated in this repo: ...~
https://github.com/awslabs/smithy/blob/main/.github/workflows/ci.yml#L19 - checkout v3 is available
This branch+commit+pr was generated by IdiosApps, by using [IdiosApp's Dependendabot discovery …

Add Dependabot for GitHub Action ecosystem

---

smithy-rules-engine/src/main/resources/software/amazon/smithy/rulesengine/language/partitions.json

While there are plans to remove partitions.json from the smithy repository, it is currently being used and contains typos (`af-east-1` and is missing a few regions).  

Add missing regions and fix typo in partitions.json

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-content-type.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-map.smithy

Some tests are applied to the wrong operations.

Protocol tests applied to the wrong operations

---

smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy
smithy-aws-protocol-tests/model/restJson1/json-structs.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy

*Issue #, if available:* (none)
*Description of changes:* Adds additional protocol tests of correct timestamp de/serialization of members which target shapes which have the `timestampFormat` trait applied. The need for these additional tests was discovered when [a bug identified incorrect de/serialization behavior in the Kotlin SDK](https://github.com/awslabs/smithy-kotlin/issues/714).

Add protocol tests of timestampFormat on target shapes

---

docs/source-1.0/spec/core/json-ast.rst
docs/source-2.0/spec/json-ast.rst

Prior to this change, the docs incorrectly lists the [(JSON AST) Resource shape Type](https://awslabs.github.io/smithy/2.0/spec/json-ast.html#resource-shape) as "AST shape reference", but as per the Description column, and the [Model docs for Resource Properties](https://awslabs.github.io/smithy/2.0/spec/service-types.html#resource-properties), as well as the [Introducing Smithy IDL 2.0 blog post](https://aws.amazon.com/blogs/developer/introducing-smithy-idl-2-0/), this Type should be a map of strings to shape ID.
ie the following blue-highlighted cell is incorrect:
This PR changes it to `Map<String, shape ID>`, which matches the Model description and AWS blog post examples.
There's also two other very minor grammar corrections including …

Correct the Resource shape properties Type entry

---

docs/source-2.0/guides/generating-cloudformation-resources.rst
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/integer-types.jsonschema.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/integer-types.smithy
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java

The integer type is a sort of vaugely supported thing in json schema, not jsut OpenAPI. So this moves that configuration up to the generic settings so it can also be applied to cloudformation and any future derivative tooling.
The int32 / int64 formats were kept to openapi since that *isn't* referenced in the the json schema spec.

Move useIntegerType to jsonschema

---

docs/source-2.0/guides/model-linters.rst
smithy-linters/src/main/java/software/amazon/smithy/linters/MissingSensitiveTraitValidator.java
smithy-linters/src/main/java/software/amazon/smithy/linters/WordBoundaryMatcher.java
smithy-linters/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.ValidatorService
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-custom.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-custom.smithy
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-defaults.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-defaults.smithy
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-invalid-config.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-invalid-config.smithy

Based on various existing services for sensitive data detection and current AWS sensitive trait usage, generated a default list of words and phrases that likely indicate the data stored inside is sensitive. It is configurable the way the non inclusive terms validator is.

Sensitive validator branch

---

docs/Makefile
docs/conf.py
docs/source-1.0/conf.py
docs/source-1.0/spec/aws/aws-json.rst.template
docs/source-1.0/spec/aws/aws-query-protocol.rst
docs/source-2.0/aws/protocols/aws-json.rst.template
docs/source-2.0/aws/protocols/aws-query-protocol.rst
docs/source-2.0/conf.py

Fixes docs so that they don't emit warnings and will now fail doc builds on nitpicky documentation warnings.

Fix docs and fail on nitpicky doc warnings

---

mkdocs

This updates the mkdocs script to perform git operations over SSH instead of HTTPS.
With this change, the resulting temp directory used for publishing docs is setup with the correct remotes:
```
╰─⠠⠵ git remote -v
origin	git@github.com:awslabs/smithy.git (fetch)
origin	git@github.com:awslabs/smithy.git (push)
```
When the script then performs the docs branch push, `git push origin gh-pages`, it will be over SSH instead of HTTPS.

publish docs via SSH

---

smithy-build/src/test/java/software/amazon/smithy/build/transforms/ExcludeShapesByTagTest.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/ExcludeTraitsByTagTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filter-by-tags.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/tree-shaking-traits.json
smithy-model/src/main/java/software/amazon/smithy/model/loader/TopologicalShapeSort.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ReplaceShapes.java

This PR fixes how mixin shapes are updated in the ReplaceShapes transform, which is used by other transforms, such as the `excludeShapesByTag` or `excludeTraitsByTag`.
Take this model:
```
namespace ns.example
@trait()
@tags(["internal"])
string mytrait
@mixin
structure MyMixin {
foo: String
}
structure StructForMixin with [MyMixin] {
bar: String
}
apply StructForMixin$foo mytrait("baz")
```
With this smithy-build.json:
```
{
"version": "1.0",
"projections": {
"mytransform": {
"transforms": [
{
"name": "excludeTraitsByTag",
"args": {
"tags": ["internal"]
}
}
]
}
}
}
```
Currently, when traits are applied to mixed-in members via an apply statement, a spurious CycleDetection error is thrown when attempting to update the mixed in`ns.example#StructForMixin$foo` member to …

Fix replacing shapes when traits applied to mixed-in members

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/EndpointRuleSet.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/IntegrationTest.java
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/bool-equals-unset.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/cant-template-bool.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/empty-tree-rule.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/field-in-wrong-tree.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/invalid-slice.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/no-shadowing-assignments.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/no-shadowing-params.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/only-refs-coerce-isset.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/string-equals-unset.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/unknown-field.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/unset-in-wrong-tree.json5
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-rules/wrong-default-type.json5

Typechecking was previously not done during build - it required users to explicitly call typecheck on their rules - resulting in invalid rulesets not being caught.

Add typechecking to EndpointRuleset build

---

docs/source-1.0/spec/aws/aws-restjson1-protocol.rst

The spec already allows for an error response to containe the full Shape ID (including namespace), but this wording makes it clearer.

Make it clearer that assembly-name stripping is not a MUST in `restJson1`

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceOperationInputOutputValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-properties/invalid-output-identifier.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-properties/resource-properties-errors.errors

When a resource properties block is present in a resource shape, all members of instance operations must be an identifier, property, or somehow marked as `@notProperty`. Implicit identifier bindings are formed through indirect requirements (name, target shape match, required) but the modeler may miss any of them -- likely the  `@required` trait, especially when using target elision syntax. The validator for properties uses the identifier binding index as a filter, however this binding index won't see an intended ID as such if it's missing the @required trait as clearly as the modeler does and leads to an error message that may be confusing in isolation. This change attempts to orient a modeler correctly to more correctly understand what possible mistakes were …

Improve member not targeting a property error message to better hint at fix

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PrivateAccessValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/private-access.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/private-access.json

Previously, it was possible to refer to a trait marked with `@private` from another namespace. This commit makes doing this cause a warning. A warning is used instead of an error to maintain backward compatibility, but it will be upgraded to an error in the future.

Add warnings for private access on traits

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/stdlib/Substring.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expr/Expression.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/RulesetTestUtil.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/EndpointRuleSetTest.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/TypeIntrospectionTest.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/eval/RuleEngineTest.java

*Description of changes:* The type signature of the `substring` endpoint method was incorrect—substring will return `None` when the resulting input string is shorter than the substring operation requires.
This could lead to invalid rules being accepted by the rules engine.

Fix return type of substring method

---

docs/source-2.0/guides/evolving-models.rst

Document it is generally breaking to add/remove input trait

---

docs/source-2.0/spec/idl.rst
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/maps-2.0.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/maps-2.0.smithy

MapMembers grammar was incorrectly stating a BR was required between the key and value, but actually WS is required. This was already reflected in the implementation, and the previous grammar was at odds with being able to use a comma to separate the key and value members. I added a new test case for 2.0 models and map parsing.
Closes #1511

Fix grammar for MapMembers

---

smithy-model/src/test/java/software/amazon/smithy/model/node/IdentityClassCacheTest.java

Fixes a typo in https://github.com/awslabs/smithy/pull/1518.

Fix typo in class cache tweak PR

---

config/checkstyle/checkstyle.xml
smithy-cli/src/it/java/software/amazon/smithy/cli/IntegUtils.java
smithy-cli/src/it/java/software/amazon/smithy/cli/RootCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Ansi.java
smithy-cli/src/main/java/software/amazon/smithy/cli/AnsiColorFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ArgumentReceiver.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/CliPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Command.java
smithy-cli/src/main/java/software/amazon/smithy/cli/EnvironmentVariable.java
smithy-cli/src/main/java/software/amazon/smithy/cli/HelpPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/LoggingUtil.java
smithy-cli/src/main/java/software/amazon/smithy/cli/StandardOptions.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Style.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SimpleCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SmithyCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Validator.java
smithy-cli/src/test/java/software/amazon/smithy/cli/BufferPrinter.java
smithy-cli/src/test/java/software/amazon/smithy/cli/CliTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/CliUtils.java
smithy-cli/src/test/java/software/amazon/smithy/cli/ColorFormatterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/HelpPrinterTest.java

Printing from the CLI previously often resulted in hard to read output because messages were flushed on each newline rather than each log message/write to stdout/stderr, causing contiguous strings of text that contain newlines (like model validation events) to be interleaved between threads. This change updates the CLI to use a PrintWriter instead of a PrintStream to fix this. Additionally, added a new API for creating grouped sections of text from a CliPrinter that includes styling methods.
Forcing color/no_color is now also done through environment variables (FORCE_COLOR, NO_COLOR). This matches lots of other CLI tools.
The way in which colors are detected and rendered is updated too. This change introduces ColorFormatter, and an Ansi enum that contains AUTO, FORCE_COLOR, and NO_COLOR …

Refactor CLI printing and colors

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/CreateDedicatedInputAndOutput.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/CreateDedicatedInputAndOutputTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/dedicated-input-output/creates-dedicated-heuristic-for-shared-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/dedicated-input-output/creates-dedicated-heuristic-for-shared-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/dedicated-input-output/removes-disconnected-shared-shape-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/dedicated-input-output/removes-disconnected-shared-shape-before.smithy

This commit changes the way `CreateDedicatedInputOutput` transform checks for singular references to a shape being used as input or output in an operation. It now checks to make sure the shape is only referenced by the specified operation. This fixes an edge case where a shape was being used as both the input and output for an operation, and would be left unused in the model after the transformation was applied.  Two new test cases were added to verify the behavior when a shape is used as both input and output.
*Issue #, if available:* #1373

Fix dedicated io transform leaving unused shapes

---

docs/source-2.0/spec/idl.rst

Grammar no longer requires a trailing line break after shape bodies, only between shapes, 
and list members are now optional, because they can be mixed in.
https://github.com/awslabs/smithy/issues/1522

Update trailing line break, list member grammar

---

docs/source-2.0/spec/idl.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTextParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlTextParserTest.java

Updates Smithy ABNF for QuotedChar and TextBlock, and updates IdlTextParser to properly parse QuotedChar and TextBlock. Previously, IdlTextParser was allowing any character to be used as a QuotedChar, despite QuotedChar having certain restrictions in the grammar. IdlTextParser was updated to follow the grammar's restrictions properly. The grammar restrictions were also loosened to allow tab characters in QuotedChar and double quotes in TextBlock, both of which were already in use. Specifically for double quotes in a TextBlock, one or two are allowed in a row, and must be followed by a QuotedChar.
https://github.com/awslabs/smithy/issues/1491

Fix quoted text grammar and parsing

---

docs/source-2.0/spec/idl.rst
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/mixins/loads-mixins.flattened.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/mixins/loads-mixins.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/mixins/loads-mixins.smithy

In IDL 2, map members can be mixed in, so Smithy grammar should reflect their optionality. https://github.com/awslabs/smithy/pull/1533 incorrectly changed MapMembers grammar to make both MapKey and MapValue optional together, when they are optional separately. This PR fixes the MapMembers grammar to allow MapKey and MapValue to be optional separately, and updates a test case to reflect that.

Fix MapMembers grammar and update test

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/TraitBreakingChange.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/TraitBreakingChangeTest.java

This commit adds the ChangeType and TraitId to the ValidationEventId emitted by the TraitBreakingChange diff evaluator.

Add details to TraitBreakingChange EventId

---

config/spotbugs/filter.xml
smithy-cli/build.gradle
smithy-cli/src/it/java/software/amazon/smithy/cli/WarmupTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/LoggingUtil.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SmithyCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/WarmupCommand.java

The Java class data sharing archive can now be created by the CLI using the warmup command. This makes it possible to build the CDS archive during an install step so that the archive uses the right paths. Creating the archive before distributing the CLI results in the archive using absolute paths pointing to the where the CLI was built rather than where it is installed on end user machines.

Move CDS warmup to the CLI directly

---

build.gradle

After the addition of jar shadowing for the CLI in https://github.com/awslabs/smithy/pull/1526, javadoc fails to find packages and symbols, causing it to fail:
```
> Task :javadoc
/Volumes/workplace/smithy/smithy-cli/src/main/java/software/amazon/smithy/cli/dependencies/MavenDependencyResolver.java:18: error: package org.eclipse.aether.util.artifact does not exist
import static org.eclipse.aether.util.artifact.JavaScopes.COMPILE;
```
This PR sets the javadoc classpath to the compileClasspath from each of the subprojects, including smithy-cli, so that javadoc can find the appropriate packages.
After this fix, javadoc can run successfully and the output is copied to `build/docs/javadoc/latest`. Cli docs are successfully written to `build/docs/javadoc/latest/software/amazon/smithy/cli`:
``` …
```

Fix javadoc with cli shadowing

---

smithy-aws-protocol-tests/model/restXml/datetime-offsets.smithy

Fixes restXml payload output for datetime offset tests.

Fix datetime offset restXml payload

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-range.smithy

The current tests only cover byte and float shapes.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license._

Add protocol tests to cover @range for short, long and integer shapes

---

.github/workflows/ci.yml

This PR adds running javadoc on CI. It will not succeed until the fix for javadoc in https://github.com/awslabs/smithy/pull/1556 is merged.

Run javadoc on CI

---

.github/workflows/checkout-and-build-smithy/action.yml
.github/workflows/sdk-codegen-ci.yml
CONTRIBUTING.md

> In the past, Smithy changes have been released without integration testing with Smithy-based SDK code generators. In addition, SDK code generators often fall behind in Smithy versions. As a result, we don’t have visibility on code generators’ failures until they are upgraded to the latest smithy version. 
> Upgrading versions and building all the code generators manually is also a labor-intensive task. Hence, the goal is to design a continuous integration system for testing the latest Smithy implementation with the SDK code generators.
This PR adds a new Github action for integration testing with Smithy based SDKs. (See [example execution](https://github.com/AndrewFossAWS/smithy/actions/runs/3653031602))
Note:
- Most SDK generators' build or protocol tests are …

Add github action for CI testing with SDK generators.

---

docs/source-1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source-1.0/spec/aws/aws-json-1_0-protocol.rst
docs/source-1.0/spec/aws/aws-json-1_1-protocol.rst
docs/source-1.0/spec/aws/aws-query-protocol.rst
docs/source-1.0/spec/aws/aws-restjson1-protocol.rst
docs/source-1.0/spec/aws/aws-restxml-protocol.rst
docs/source-1.0/spec/aws/error-rename-simple.rst.template
docs/source-1.0/spec/aws/error-rename.rst.template
docs/source-1.0/spec/core/model.rst
docs/source-2.0/aws/protocols/aws-ec2-query-protocol.rst
docs/source-2.0/aws/protocols/aws-json-1_0-protocol.rst
docs/source-2.0/aws/protocols/aws-json-1_1-protocol.rst
docs/source-2.0/aws/protocols/aws-query-protocol.rst
docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst
docs/source-2.0/aws/protocols/aws-restxml-protocol.rst
docs/source-2.0/aws/protocols/error-rename-simple.rst.template
docs/source-2.0/aws/protocols/error-rename.rst.template
docs/source-2.0/spec/service-types.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ErrorRenameValidator.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/error-rename.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/error-rename.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ServiceValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/service-rename/error-rename-invalid.errors

https://github.com/awslabs/smithy/issues/1545
* Allow error shapes rename
* Disallow error shapes rename for all AWS protocols (until we have verified SDKs can support error rename)

Allow error rename and disallow error rename for all AWS protocols

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/eval/Scope.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/eval/Type.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/eval/Value.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expr/Literal.java
smithy-rules-engine/src/main/resources/software/amazon/smithy/rulesengine/testutil/valid-rules/minimal-ruleset.json
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/RulesetTestUtil.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/EndpointRuleSetTest.java

*Issue #, if available:* https://github.com/awslabs/smithy-rs/issues/2119
*Description of changes:* Fix a few HashMaps that should be LinkedHashMaps—this caused visitors to iterate over properties in an inconsistent order. A test has been added that previously failed because property order was not preserved.

Fix deterministic order of properties

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/parameters/Parameter.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/ClientContextParamsTrait.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/syntax/ParameterTest.java

*Description of changes:* Fix two bugs in the `toBuilder` methods.
In `Parameter`, fields were dropped.
In `ClientContextParameter`, `toBuilder` returned an interface which made it impossible to use from calling code.

Fix parameters to builder

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

Fix `RestJsonAllQueryStringTypes` protocol test

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

Fix `RestJsonQueryStringEscaping` protocol test

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Upgrade1to2Command.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/box.v2.smithy
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/list.v1.smithy
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/list.v2.smithy

Smithy IDL 1 contains set shapes, but IDL 2 does not. When upgrading from IDL 1, set shapes should be converted to list shapes. The upgrade command currently does not perform this conversion.

Fix Upgrade1to2Command for Set shape

---

docs/source-2.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/ExcludeShapesBySelector.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/IncludeShapesBySelector.java
smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer
smithy-build/src/test/java/software/amazon/smithy/build/transforms/ExcludeShapesBySelectorTest.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/IncludeShapesBySelectorTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/transform-by-selector.smithy

Added include/exclude transforms using selectors. Using selectors is a generic way to include or exclude shapes, instead of adding specific transforms such as `byShapeType` (e.g., [this PR](https://github.com/awslabs/smithy/pull/1330)) a selector can be used to replace that and other use cases.

Add exclude/include tranforms using selectors

---

docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst

One of the code blocks used `awsJson1_1` instead of `restJson`

Minor fix to restJson1 docs

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/ExternalDocumentation.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/TagObject.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/model/ExternalDocumentationTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/model/TagObjectTest.java

The `OpenAPI` class sorts `TagObject`s [here](https://github.com/awslabs/smithy/blob/main/smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OpenApi.java#L136)  but `TagObject` is not comparable.
Implement `Comparable` inteface for `TagObject` and  `ExternalDocumentation`

implement Comparable interface for TagObject and ExternalDocumentation

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

This PR adds intEnum coverage to the `queryParamsMapOfStringList` that was added in https://github.com/awslabs/smithy/pull/1564/.

Add intEnum coverage on map of string list

---

.github/workflows/labeler.yml

This workflow will add the GitHub issue labels in a .github/labels.yml file. It does not delete our existing labels.
GitHub doesn't seem to have a way to run a workflow on PR merge, so this workflow just runs on pushes to main. After this PR is merged, a commit will have to be made into main with the .github/labels.yml file. After the labeler workflow runs, the workflow file (in this commit) and the labels.yml file should be deleted.
The labels to be added are the standard labels that AWS SDKs use, and having these labels will bring consistency across repos.

Add labeler workflow for adding github labels

---

.github/labels.yml

Used by #1593 to add the standard sdks labels to the repo. #1593 must be merged before this commit is.
This file can be deleted after the labeler workflow in #1593 runs.

Add standard sdks labels

---

config/checkstyle/checkstyle.xml

Update checkstyle to allow Apache 2.0 short-form license header, that does not include the copyright year.
Existing, long-form copyright headers with years through 2023 are still allowed.
As files are added or re-written, they should use the short-form license header:
```
/*
* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
* SPDX-License-Identifier: Apache-2.0
*/
```

Prefer short-form license header

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ShapeGenerationOrder.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java

* Add shapes generation ordering in CodegenDirector
* This allows code generators to decide the ordering of the shapes which get passed to them. 
* E.g. `smithy-ruby` needs the shapes ordered alphabetically by their names because generated ruby code needs to be alphabetic in a ruby file.

Add shapes generation order in CodegenDirector

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OpenApi.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OperationObject.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/tagged-service-order-supported-tags.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/tagged-service-order.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/tagged-service-order.openapi.json

Fixes #1603
Instead of sorting them lexicographically, preserve the user-specified order of tags.
eg.
`@tags(["one", "two", "three", "four"])`
becomes:
`"tags": ["one", "two", "three", "four"]`
instead of:
`"tags": ["four", "one", "three", "two"]`

Preserve tag order in generated OpenAPI specification

---

docs/source-1.0/spec/core/protocol-traits.rst
docs/source-2.0/spec/protocol-traits.rst

This PR clarifies the `timestampFormat` trait documentation concerning UTC offsets.

Clarify handling of date-time offsets

---

docs/source-2.0/implementations.rst

Lists the [Tree Sitter grammar for Smithy](https://github.com/indoorvivants/tree-sitter-smithy) and notes its inclusion in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter) on the implementations doc page.

Add Tree Sitter to implementations docs

---

docs/source-2.0/spec/streaming.rst

Remove invalid streaming strings from docs

---

smithy-model/src/main/java/software/amazon/smithy/model/selector/ScopedAttributeSelector.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/enums.smithy

A bug was discovered when using `,` (OR condition) in scoped attribute selector
```
enum Suit {
DIAMOND = "diamond"
CLUB = "club"
HEART = "heart"
SPADE = "spade"
}
enum Color {
RED
BLACK
}
```
`[@trait|enum|(values): @{name} ^= DIA, BLA]`  (return enums with names starting with `DIA` or `BLA`
Expected: `smithy.example#Suit`, `smithy.example#Color`
Acutal: `smithy.example#Suit`
Fix OR condition in scoped attribute selector

Fix OR condition in scoped attribute selector

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponents.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponentsTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mappers/small-service.smithy

Customer reported referenced component being removed in openapi schema. 
In [RemoveUnusedComponents](https://github.com/awslabs/smithy/blob/main/smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponents.java#L125), it only keeps referenced components if the field object size is 1.
However there are cases where the field object size is greater than 1.
For example:
__smithy:__
```
structure OperationInput {
@default({})
payload: StringMap
}
map StringMap {
key: String
value: String
}
```
__openapi:__
(`StringMap` is removed in the `schemas` object.)
```
"schemas": {
"OperationRequestContent": {
"properties": {
"payload": {
"$ref": "#/components/schemas/StringMap",
"default": {}
}
}
}
}
```
Remove …

fix referenced components removed in openapi schema

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

This PR adds a protocol test to clarify clients should omit empty lists when serializing a query string.
When serializing an empty string for param `Foo`, `Foo=` is serialized in the query string. An empty list for param `Foo` cannot also be serialized as `Foo=` as one might expect. Instead, it is omitted to clearly differentiate between an empty string, and an empty list.

Omit serializing empty http-query lists

---

docs/source-1.0/spec/core/documentation-traits.rst
docs/source-2.0/spec/documentation-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExamplesTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java

*Issue #, if available:* 
#1582 
This change  modifies the behavior of the ExamplesTraitValidator when
both output and error are defined. This is achieved by treating the
output member as optional, only validating it if it's present and
failing when it's defined alongside the error member.

Modifies ExamplesTraitValidator to handle cases where both output and error are defined

---

smithy-aws-protocol-tests/model/restJson1/validation/main.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-enum.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-length.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-pattern.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-range.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-required.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-uniqueItems.smithy
smithy-aws-protocol-tests/model/restJson1/validation/recursive-structures.smithy
smithy-aws-protocol-tests/model/shared-types.smithy

This PR updates the validation protocol tests to remove the input value from being returned in the validation message.
It also adds coverage for uniqueItems validation.

Remove reflected values from validation tests

---

docs/source-1.0/spec/core/http-traits.rst
docs/source-2.0/spec/http-bindings.rst

This updates the rules for escaping values of shapes bound to the HTTP URI according to the rules of RFC3986. The list of characters to escape was replaced with a list of safe characters. Initially that was created by subtracting the reserved characters in section 2.2 from the relevant valid characters defined in the productions for the particular binding locations, but those all ended up being equivalent to the unreserved characters production in section 2.3.
closes #1011

Clarify rules for escaping shapes bound to URIs

---

smithy-build/src/main/java/software/amazon/smithy/build/transforms/FilterSuppressions.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/FilterSuppressionsTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/eventHierarchy.removeUnused.json
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/eventHierarchy.removeUnused.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/eventHierarchy.smithy

Hierarchical eventIds were added in https://github.com/awslabs/smithy/pull/1527.
This PR fixes the FilterSuppressions transform to keep suppressions that match a prefix when using the `removeUnused` transform configuration.
Currently, `@suppress(['A'])` will be removed as unused if a validation event does not match `A` exactly.
This PR updates the transform retain `@suppress(['A'])` when a validation event for `A.B` has been emitted for the shape where the suppression was applied.

Fix FilterSuppressions to match on hierarchy

---

smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceIndex.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/nested-properties.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/nested-properties.smithy

Resource properties can be nested if the `nestedProperties` trait is used. This fixes an issue where the cfn resource schema generation wasn't respecting that trait.

Handle nested properties in cfn schema generation

---

smithy-aws-protocol-tests/model/ec2Query/fractional-seconds.smithy

Fixes the ec2Query fractional seconds tests to comply with the [response serialization](https://smithy.io/2.0/aws/protocols/aws-ec2-query-protocol.html#response-serialization) specification.

Fix ec2Query fractional seconds response

---

smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-prefix-headers.smithy

Fixes https://github.com/awslabs/smithy/issues/1633.
This PR makes HTTP request protocol tests for serializing empty maps client-only.
Clients should omit the empty map when serializing the request. Servers however should not instantiate an optional parameter when it is not set as a header.

Make empty map HTTP header tests client-only

---

smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java

We previously deserialized lists with generic types incorrectly, causing the list to be created, but storing invalid types in the list. This caused the use of the list at runtime to fail due to a ClassCastException.

Fix NodeMapper handling of lists with generic types

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/core-events.smithy

Previously, core validation events resulted in errors, which could not be suppressed.
Now, events from the TargetValidator can result in warnings, which could be suppressed.
This PR updates the ModelValidator to check core validation events for matching suppressions with tests covering both metadata suppressions and suppressions through the `@suppress` trait.

Allow core validation events to be suppressible

---

smithy-aws-protocol-tests/model/ec2Query/fractional-seconds.smithy

Fixes the ec2Query fractional seconds value.

Fix ec2Query fractional seconds value

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/CfnConfig.java
smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeMapper.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/suppression-test.smithy
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/ExampleObject.java

N/A.
Fix typos for "ignore":
- Fix typos on "Ignored" in smithy-aws-protocol-tests
- Fix typos on "IgnoreMe" in smithy-model
- Fix typos for NodeMapper.WhenMissing.IGNORE

Fix typos for "ignore"

---

docs/source-2.0/guides/model-linters.rst

Default behavior for CamelCase Validator is out-of-date and should be updated to explain how member names are treated based on the current service's set of member names.

fix docs for camelCase Validator default behavior

---

docs/source-2.0/guides/building-codegen/configuring-the-generator.rst

Fix typo in example of codegen plugin name

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-enum.smithy

This PR updates the enum validation protocol tests to exclude returning enum values that have been marked as internal with the `@internal` trait or tagged as `internal`.

Do not return internal enum values

---

smithy-linters/src/main/java/software/amazon/smithy/linters/MissingSensitiveTraitValidator.java
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/missing-sensitive-trait-defaults.smithy

Enum members do not need to be marked sensitive, so we can exclude them from this validator.
Ex: 
https://github.com/awslabs/smithy/blob/30201cb49e9017d4ef7e3622d3e46aec12a0c60e/smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json#L211

Skip enum members when looking for potentially sensitive shapes/data

---

docs/source-1.0/spec/core/selectors.rst
docs/source-2.0/spec/selectors.rst
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorRunnerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/attribute-existence.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/functions.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/id-attribute.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/neighbors.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/node-attributes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/numeric-comparators.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/projection-attributes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/scope-attribute.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/service-attribute.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/string-comparators.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/trait-attributes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/variables.smithy

Create self-contained compliance tests for selectors to make them safer to evolve and bugfix, and to make it possible for other implementations to just copy/paste our self-contained directory of test cases.
Most of the test cases are based on examples in the [selectors documentation](https://smithy.io/2.0/spec/selectors.html?highlight=selector#)
TODO: Create a follow-up PR for porting existing selector test cases into this format

Add selector compliance tests

---

smithy-cli/build.gradle
smithy-cli/config/README.md
smithy-cli/config/install
smithy-cli/config/install.bat
smithy-cli/config/install.bats

N/A
Adds install scripts to be used to install the smithy-cli distributable (and is included within it)
*Testing*
- Build the smithy-cli distributables via `gradlew :smithy-cli:runtime`, and navigate to the respective image for your machine (`smithy-cli/build/image/smithy-cli-<platfrm>/`)
For the shell script, you can:
- Run the install script via `sudo ./install`
- Optionally, you may configure a custom install and bin directory to use instead of the defaults.
- Run the `bats` tests, according to the README instructions (added in this PR)
For the batch script, you can:
- Generate the windows runtime, `./gradlew :smithy-cli:runtime`, and download it to a windows environment
- Run install.bat as administrator
- Or, you can do a mock …

Add unix install script for smithy-cli

---

docs/source-2.0/guides/style-guide.rst

Adds missing braces to style guide for mixin examples.

Fix mixins in style guide

---

designs/defaults-and-model-evolution.md
docs/source-2.0/spec/type-refinement-traits.rst

This commit removes the recommendation for using presence tracking default values, and instead advocates for serializing default values. This ensures that whatever an implementation thinks the default value is currently is unambiguoulsy honored by anything that deserializes the message later at any point in time, including if the default value for that member has since changed in the model. This also removes the large amount of complexity that presence tracking brings with it. While this does make it harder for a default value to change in clients, changing defaults is meant to be very rare anyways. So the tradeoff here seems worth it given changing defaults was and continues to be so strongly discouraged.
By submitting this pull request, …

Remove presence tracking from default values

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateOperationDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java

- Adds an optional (directive defaults to no action) directive to generate operation shapes separate from resources and services
There are use cases where the operation shapes need to be generated separately from the Resource/Service shapes. For example in an SSDKs generator where you might generate an abstract class per operation or in a UML generator where the operation would be generated separately and linked to a service only via a relationship.
In most cases this will go unused, which is why it is set to default to do nothing. However, it would be a nice functionality to provide to users so they can cleanly generate operations separate from Resources or Services when required.
By submitting this pull request, I confirm that my contribution is made under the …

Add GenerateOperationDirective

---

docs/source-2.0/guides/migrating-idl-1-to-2.rst

Minor correction in an example provided in documentation for migration from Smithy v1 to v2
`MyPrimitiveInteger` was typed as `boolean`, it should be `integer`

docs: type correction in primitive root-level example

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuild.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/projection-model-import.json

Previously if SmithyBuild had a projection that imported a model that had an unknown trait, the allowUnknownTraits option wasn't allowing it.
Added BuildCommand unit tests to show the broken behavior and fix working. Previously, the test case `projectionUnknownTraitsAreAllowedWithFlag` did not work without the code changes in this PR. Note, the test case `allowsUnknownTraitWithFlag` (not using import) worked even before this change.

Fix allowUnknownTraits for projection with import

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedOperationError.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedOperationErrorTest.java

Arguments were reversed, resulting in nonsense such as:
[In com.amazonaws.servicediscovery#ListOperations] The com.amazonaws.servicediscovery#ListOperations error was removed from the com.amazonaws.servicediscovery#RequestLimitExceeded operation.
Swapped the argument order to fix

Fix diff message for RemovedOperationError

---

docs/source-2.0/spec/selectors.rst
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-model/src/main/java/software/amazon/smithy/model/Model.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AbstractNeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AndSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AttributeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/Context.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ForwardNeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/InSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/InternalSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/IsSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/NotSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/RecursiveNeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ReverseNeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/RootSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ScopedAttributeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/SelectorParser.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ShapeTypeCategorySelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ShapeTypeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/TestSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/TopDownSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/VariableStoreSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/WrappedSelector.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/ShapeTypeCategorySelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/in-function.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/root-function.smithy

This commit adds support for the `:in` and `:root` functions. The `:in` function is a simpler way to check if a shape is in an expression, typically used to test if a variable contains a shape or if a root expression contains a shape. `:root` is used to create rooted common subexpressions that are evaluated once against every shape in the model. `:root` expressions are evaluate in an isolated context, so any variables used or stored by them are not accessible outside the root selector. `:root` selectors allows selection to be broken into multiple steps and evaluate globally.
Let's say you want all number shapes that are used in operation inputs, but not used in operation outputs. This can be done today using the following expression:
```
service
$outputs(~> operation -[output]-> ~> …
```

Add :root and :in selectors, fix variable bug

---

smithy-cli/src/it/java/software/amazon/smithy/cli/SelectTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java

The --show-traits option will include the serialize value of specific traits for each shape matched by the --select command. The output format is the same as the format used with --vars, but also included in the output is a 'traits' property that contains a map of trait shape IDs to trait values. --show-traits is a comma separated list of trait shape IDs, where omitting a namespace assumes the trait is in the prelude (e.g., 'required' is the same as 'smithy.api#required'). Matches are not required to have the traits defined in --show-traits, so if that is the desired filtering, the selector provided in --selector needs to ensure each shape has the required traits.
This option can be useful to answer questions like: "what are all the HTTP headers used in my service?" or "what are the …

Add --show-traits to select command

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceOperationInputOutputValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-properties/resource-properties-errors.errors

Minor cleanup to resource property validation to remove an unused parameter, add "resource" to the properties conflict error message, and make the error about conflicting resource property targets easier to understand.

Improve resource property validation and errors

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionNameTrait.java
smithy-aws-iam-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ActionNameTraitTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/actionname-override.smithy

Adds the ActionName trait to override using the API operation name as the IAM action name. Also, allows adding additional actions using the input member field if the value is not null in the request.

Adding IAM Action name trait to override using the API operation name

---

smithy-cli/src/it/java/software/amazon/smithy/cli/SelectTest.java
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/model-with-warning/model/main.smithy
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/model-with-warning/smithy-build.json
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/AstCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildOptions.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Upgrade1to2Command.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidationFlag.java

The select command doesn't need to perform validation or show validation summary information. This commit updates the select command to only show validation information if the model can't be loaded.

Disable validation for select command

---

docs/source-1.0/spec/core/idl.rst
docs/source-2.0/spec/idl.rst

https://github.com/awslabs/smithy/issues/1249
A grammar containing
```
WS = *1{ ... }
... = ... *WS ...
```
defines multiple parse trees.
We can eliminate the ambiguity by replacing `*WS` with `[WS]`.

Reduce IDL ambiguity by replacing `*WS` with `[WS]`

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildOptions.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildCommandTest.java

The diff command does not use the positional MODEL argument like other commands. I'd like to do a more involved refactor to make this a little cleaner later, but I want to get this help text and validation in place before that lands.

Remove unused positional [<MODEL>] from diff command

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoadOperationProcessor.java

Currently not all events are passed to the listener given the way this is implemented, e.g., if some part of logic add a set of events directly to the list using `addAll`. In particular`LoaderShapeMap` adds all the events to the events list for each `ShapeModifier` [here](https://github.com/awslabs/smithy/blob/1f0da40ff2ee24f863f4895189c4c3ec89d275e2/smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderShapeMap.java#L380) which are then not shown in the output. Validation for the following model
```
namespace com.amazon.example
structure Mixin1 {
a: String
}
structure Valid with [Mixin1] {
a: Integer
}
```
Will currently output
```
$ smithy validate ~/tmp/test-model5.smithy
FAILURE: Validated 211 shapes (ERROR: 1)
```
After this …

Ensure that the event listener gets all the events

---

smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/validator-configuration-test.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/validator-configuration-test.smithy
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorDefinition.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ValidatorDefinitionTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/validator-filtering-and-mapping.smithy

n/a
Previously, hierarchical event ids would be lost when specifying either a custom Smithy linter validator id or severity level. This fixes that and adds some test cases 

bugfix for validator ids and hierarchical subparts

---

docs/source-2.0/spec/idl.rst

https://github.com/awslabs/smithy/issues/1249
A grammar containing
```
*[ ... ]
```
will match the empty string indefinitely.
We can remove an instance of this in `OperationBody`.

Remove `OperationBody` indefinite repition in IDL

---

smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceIndex.java
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/errorfiles/invalid-additional-schemas-shape.errors
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/errorfiles/invalid-additional-schemas-shape.smithy

Update the logic that gets process the shape of the `additionalSchema` property to avoid attempting to dereference a non-structure shape. Without this the `Optional::get` throws and exception when the shape is not an `structure` and hides out the actual error.

Gracefully handle the case when additionSchema targets an invalid shape

---

smithy-cli/src/main/java/software/amazon/smithy/cli/AnsiColorFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/CliPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorBuffer.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CodeFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/MigrateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ModelBuilder.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/PrettyAnsiValidationFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Validator.java
smithy-cli/src/test/java/software/amazon/smithy/cli/AnsiColorFormatterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/BufferPrinter.java
smithy-cli/src/test/java/software/amazon/smithy/cli/CliPrinterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/ColorFormatterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/CodeFormatterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/PrettyAnsiValidationFormatterTest.java

This commit cleans up how ColorFormatter, CliPrinter, and ColorBuffer all interact.
* CliPrinter no longer creates ColorBuffers. Use `ColorBuffer.of` and pass an Appendable or a CliPrinter
* ColorBuffer now handles writing to a Consumer and coloring output rather than ColorFormatter
* CliPrinter now implements Appendable
* Removed unused method from CliPrinter to create a printer from a Writer
* Removed unnecessary use of buffering from CliPrinter that wraps an OutputStream
* ColorFormatter now provides various default method implementation and relies primarily on `startStyle` and `endStyle`
* Cleaned up several places that used buffering but not ColorBuffer

Refactor CLI color printing and buffering

---

config/spotbugs/filter.xml
smithy-cli/src/it/java/software/amazon/smithy/cli/DiffCommandTest.java
smithy-cli/src/it/java/software/amazon/smithy/cli/IntegUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/CliPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorBuffer.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorTheme.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Command.java
smithy-cli/src/main/java/software/amazon/smithy/cli/HelpPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/LoggingArgumentsHandler.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Style.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CodeFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/MigrateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ModelBuilder.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/PrettyAnsiValidationFormatter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SmithyCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Validator.java
smithy-cli/src/test/java/software/amazon/smithy/cli/BufferPrinter.java
smithy-cli/src/test/java/software/amazon/smithy/cli/CliPrinterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/PrettyAnsiValidationFormatterTest.java

Smithy diff and build now uses the pretty validation output and color theming options.
Because Styles were copied and repated multiple times, I introduced a ColorTheme class to store reusable styles. This isn't a swappable color scheme system, but could be evolved into one in the future if needed.
For Smithy Diff:
The old and new models are both validated, but only build-failing errors are shown. When the original model fails, a label is added before ERROR/DANGER to show it's on the OLD model. When the new model fails, it shows a NEW label.
When running the diff with two valid models, events have a label of DIFF. The events shown here use the --severity option and default to WARNING when not set.
For Smithy Build:
Each projection output is contained in a titled section using a colored …

Use updated output with smithy build and diff

---

docs/source-2.0/spec/authentication-traits.rst

It wasn't super obvious what scheme actually was or how to use it, so I added some clarifying links to the relevant rfc.

Clairfy api key auth's scheme

---

docs/source-1.0/spec/core/idl.rst
docs/source-2.0/spec/idl.rst

https://github.com/awslabs/smithy/issues/1249
This is the same change as https://github.com/awslabs/smithy/pull/1699

Reduce IDL ambiguity by replacing `*SP` with `[SP]`

---

smithy-cli/src/it/java/software/amazon/smithy/cli/AstCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/AstCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiscoveryOptions.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/MigrateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ModelBuilder.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/AstCommandTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/MigrateCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/directory-cases/with-jar/v1/smithy-build.json

The --discover and --discover-classpath options are only necessary for smithy build and smithy validate to support the Gradle pluing and the internal build tool within Amazon. This commit removes those options from ast, diff, migrate, and select, and removes / fixes tests that relied on them.
We should figure out if we can remove these options from build/validate or if we're comfortable with them as public options.

Remove hidden --discover option from some commands

---

smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json

Remove member from actionName as type is string
Update aws.iam.json - Remove member from actionName as type is string

Update aws.iam.json - Remove member from actionName as type is string

---

smithy-cli/src/it/java/software/amazon/smithy/cli/AstCommandTest.java
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/model-with-mixins/model/main.smithy
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/model-with-mixins/smithy-build.json
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/AstCommand.java

Adds a new `--flatten` flag to the AST command that will flatten and remove the mixins from the model. This helps a lot with understanding how the model looks like without any mixins.

Add --flatten flag to the AST command

---

smithy-cli/build.gradle
smithy-cli/src/it/java/software/amazon/smithy/cli/DiffCommandTest.java
smithy-cli/src/it/java/software/amazon/smithy/cli/IntegUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/HelpPrinter.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildOptions.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ClasspathAction.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/HelpPrinterTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildOptionsTest.java

This commit adds support for running Smithy diff using a "git" mode so that the current state of a project is compared against the previous state of a project. By default, the previous state is the last commit of the current branch:
```
smithy diff --mode git
```
You can compare against a differet commit using:
```
smithy diff --mode git --old HEAD~2
smithy diff --mode git --old main
```
The way this works it that `git` mode is a wrapper around `project` mode. Smithy will create a git worktree for a specific branch named `__smithy-diff-worktree` located at
"build/smithy/diff-worktree". Each time the command is run, the worktree is either created and pointed at the correct commit, or uses `git reset --hard $COMMIT`. When creating the worktree, we first call "git worktree prune" in case the …

Add git diff mode to CLI

---

docs/source-2.0/guides/index.rst
docs/source-2.0/guides/model-validation-examples.rst
docs/source-2.0/spec/model-validation-examples.rst
docs/source-2.0/spec/model-validation.rst

This pull request adds a number of example linters to as a subpage of the Validator page. 
These examples are not exhaustive, but are intended to show users some of the ways smithy validators can prevent common bugs and enforce a common style in their Smithy models.
*Testing* 
I checked each validator against a local model to make sure error messages formatted correctly and that they could be parsed. Then I generated the docs using the `make html` command and visually checked the generated html.

Add examples of validators to documentation

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/OperationValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/operation/input-output-traits/invalid-input-output-operation-bindings.errors

Fixes issue #1719, which pointed out that error messages when operation input targeted structures with the `@output` trait (and vice-versa) were incorrect. The error message was built using the operation <-> target relationship name for the name of the invalid trait, instead of using it as the operation property which targeted an invalid shape.
The error message was also updated to include the shape id of the targeted shape, and existing tests were updated to reflect that change.

fix error msg for invalid operation io bindings

---

docs/source-2.0/guides/smithy-cli/cli_installation.rst
gradle.properties

Remove prompts (`$`, `PS >`) from code-blocks to be coped in the CLI installation guide, so that reader can copy and paste and execute more easily
Add UTF-8 encoding to gradle.properties so that the new cli printing code will always build correctly

Remove prompt from install-codeblocks, add utf8 file-encoding property

---

smithy-linters/src/main/java/software/amazon/smithy/linters/CamelCaseValidator.java
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.json

n/a
Ignore list and map "members" for the purpose of camel case validating, as they are _always_ fixed to the strings "member", "key", and "value".

ignore lists and maps for camelcase validation

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-uniqueItems.smithy

*Issue #, if available:* https://github.com/awslabs/smithy-typescript/pull/732

Add restJson1 validation test for `uniqueItems` missing required keys inside lists of objects

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTokenizer.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ParserUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/linters/EmitEachSelectorValidator.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/MediaType.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SimpleParser.java

This commit makes minor performance improvements to parsing so that we can use consumeWhile with an IntPredicate rather than needing to box a char with a Predicate<Character>. To accommodate this, I deprecated `consumeUntilNoLongerMatches(Predicate<Character>)` in favor of `consumeWhile(IntPredicate)`. I also added overloads to ParserUtils to accept int in addition to char, matching how other classes in the JDK work like Character.isDigit.

Use IntPredicate and inline end of line parsing

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTokenizer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/error-recovery/in-metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/error-recovery/to-docs.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/error-recovery/to-dollar.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/error-recovery/to-identifier.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/error-recovery/to-trait.smithy

When we encounter a parser error, we'll now attempt some basic error recovery by simply skipping token until we reach a token at the start of a line that is an identifier, documentation comment, or '@'. This should help with things like LSPs that still should be able to utilize jump to definition even with a broken or in-progress model.
(still need to test the experience out in the LSP before merging)

Add rudimentary form of error recovery to parser

---

.github/workflows/update-brew.yml

Adds a github action to update a homebrew-tap with the latest release information automatically (via Pull-Request)
*Testing:*
https://github.com/haydenbaker/homebrew-tap/pull/5
Above PR* shows the expected PR created as a result of this action, and you can see the action-run in
description of the PR for further verification
*intentionally marked as draft for testing purposes

Add action to update homebrew-tap on release

---

docs/source-2.0/guides/building-codegen/using-the-semantic-model.rst
docs/source-2.0/spec/selectors.rst

Adds a link to the Semantic model doc from the Selector spec. The goal here was just to make it easier to discover the Semantic model section on selectors.
*testing*
Built docs and confirmed that the added link worked as expected.

Add link to Semantic model doc from Selector spec

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/EnumShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ChangeShapeTypeTest.java

This PR updates how EnumShapes are converted from strings with the deprecated `@enum` trait by adding the `@internal` trait to the resulting Enum shape member when when the source enum value was tagged with `internal`.

Convert to internal trait from tag

---

docs/source-1.0/guides/building-models/build-config.rst
docs/source-2.0/guides/building-models/build-config.rst
docs/source-2.0/spec/constraint-traits.rst

Adds docs for changeStringEnumsToEnumShapes transformer, including behavior from https://github.com/awslabs/smithy/pull/1739
Additionally, it updates the `changeTypes` documentation to include its ability to transform Strings with `@enum` traits to Enums.

Document changeStringEnumsToEnumShapes transformer

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-enum.smithy

This PR updates the `restJson1` validation protocol tests so that `internal` tagged enums shape members are no longer suppressed from the validation message. Only enum shape members tagged with the `@internal` trait are suppressed from a validation message.
Enum traits that are tagged as "internal" are still expected to be suppressed from the validation message, as traits cannot be applied to an enum trait definition, leaving the "internal" tag as the only way to suppress an enum value from the validation message.
See https://github.com/awslabs/smithy/issues/1737.

Remove suppressing internal tagged enum shape members

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTokenizer.java

Let's use the tokenizer in the parser, but don't yet expose it so that we can refactor as needed while the token-tree is being built.

Make IDL tokenizer package-private for now

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelLoader.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/inline-io.smithy

When there was no space between the `:=` and `with` tokens when parsing an inline io statement, for example:
```
operation Foo {
input :=with [Bar] {}
}
```
the parser would skip the `with` and so not realize its parsing a mixin, failing when it sees a `[` instead of a `{`. This was due to an extra call to `tokenizer.next()`, which skipped the `with`. Usually the `next()` would just skip the space before the `with`, but when the space wasn't present it skipped the `with`.
The inline-io test was updated to include this case.

Fix inline io parsing with mixins

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/defers-failure.json

#1277 
This changes `SmithyBuildImpl` to continue applying plugins after one fails, throwing the error (if present) after they have all completed. This is useful for example when you want to see the serialized output of a model you know is valid but a plugin is causing the whole build to fail. A new test case was added to ensure that artifacts produced by valid plugins are still created despite the build failing.
This was originally implemented in #1416, but was rolled back in #1429 as a precaution since we had an unrelated issue ocurring at the time.

Defer projection failure until after plugins run

---

docs/source-2.0/guides/smithy-cli/cli_installation.rst

Reworked the scripts in the docs for installing the Smithy CLI.
* Replaced `wget` with `Invoke-WebRequest` since `wget` is not a standard tool installed on Windows
* Removed the usage of `-and` because it results in a confusing `false` being printed every time you run the scripts. Replaced with `;` for running multiple commands.
* Used the ` token to break up long lines to make it more readable
* Replaced the `mkdir` with `New-Item` to follow the cmdlet pattern.

Update CLI install PowerShell instructions

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/MigrateCommand.java

*Issue:*
> The Smithy CLI has a command that allows you to update IDL 1 models to IDL 2 models in place, overwriting the IDL 1 files. However, the resulting IDL 2 model isn't guaranteed to be valid, because no validation is done on the upgraded model within the CLI. The upgrade command needs to be updated to always produce valid IDL 2 models, by building and validating the upgraded model before writing out the files.
Validate upgraded models before writing out files in MigrateCommand.

validate upgraded models in MigrateCommand

---

docs/source-2.0/aws/amazon-apigateway.rst

Adds a small warning to remind users that API Gateway uses an older version of JSON Schema that may not meet their needs. This is added because we have had a number of users surprised by the validation behavior in API Gateway applications
*Testing* 
Generated docs use `make html` and manually reviewed.

Add warning about API Gateway request validation limitations

---

smithy-linters/src/main/java/software/amazon/smithy/linters/MissingPaginatedTraitValidator.java

Adds a couple new default input/output member names that will flag an operation for missing pagination

update default list of members for pagination flagging

---

docs/source-2.0/guides/building-models/build-config.rst

Fix the example in the `includeShapesBySelector` example. The correct selector should use `:is` instead of just `is`.

Add a missing colon to the includeShapesBySelector example

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/detects-default-out-of-range.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/detects-default-out-of-range.smithy

When specifying an invalid default, it may be invalid for both the member range and the targeted shape root range. This previously resulted in two violations with the same target shape and eventId, which this PR improves by making the eventId include the specific range scope

add hierarchical IDs for DefaultTrait collisions

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedRequiredMember.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/main/resources/META-INF/services/software.amazon.smithy.diff.DiffEvaluator
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedRequiredMemberTest.java

Validates that no members are newly created with the required trait (but no default trait) in existing structures.
Emits an event "AddedRequiredMember" for such cases

New diff evaluator for added required members

---

smithy-aws-protocol-tests/model/restJson1/http-labels.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restXml/http-labels.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy
smithy-aws-protocol-tests/model/restXml/services/s3.smithy

Adds an httpRequestTests case to restXml protocol tests to verify that httpLabel bindings in the request URI are percent-encoded. restJson1 had an existing test case for this, but was updated to verify the space character is encoded. An operation was also added to the testing S3 service model with httpRequestTests to verify the same thing, but with S3's virtual host addressing. No other protocols had tests added, because restJson1 and restXml are the only protocols that support httpLabel bindings.
Changes were tested by generating and running protocol tests in aws-sdk-go-v2 and aws-sdk-js-v3, confirming the new test case is generated and runs successfully.
By submitting this pull request, I confirm that my contribution is made under the …

Add restXml protocol test for http label escaping

---

docs/source-1.0/spec/core/idl.rst
docs/source-2.0/spec/idl.rst

Replaced "EnumShapeStatement" rule with "EnumStatement" because other shape statements don't include the word "Shape".
Renamed "NodeKeywords" to "NodeKeyword" since grammar rules aren't generally plural like this.
Added "Comma" production, which is now used in WS and can be optionally used after defining an enum member.
Members that support value assignment can now have a trailing comma.
Fixed WS loop handling for several productions.
Fixed OperationErrors to actually support a list of ShapeId, rather than just a list of Identifier. Identifier implies that you can only use errors in the local namespace which isn't the case.

Fix grammar issues, add Comma production

---

docs/source-2.0/spec/idl.rst

ServiceStatement and ResourceStatement differed only by the type name, so they were merged into EntityStatement.

Merge service and resource grammar

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java

Differentiates between an inserted enum event, and the other ChangedEnumTrait events

Emit specific ids for ChangedEnumTrait ERROR events

---

docs/source-2.0/spec/idl.rst

Adds an EnumShapeMember production to the grammar for consistency with ShapeMember, and moves TraitStatements from EnumShapeMembers and ShapeMembers into EnumShapeMember and ShapeMember respectively.

Add EnumShapeMember, move TraitStatements grammar

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/mixins/empty-enum-mixin.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/mixins/empty-enum-mixin.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/mixins/non-empty-enum-mixin.smithy

Customer tries to apply a non-empty enum mixin to an empty enum:
```
@mixin
enum EnumMixin {
VALUE = "value"
}
enum EmptyEnum with [EnumMixin] {}
```
Smithy build fails with enum must have at least one entry. This was caused by mixin enum members not getting populated to the synthetic enum trait.
Allow empty enum with non-empty mixins

Allow empty enum with non-empty mixins

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturingTokenizer.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeTypeTest.java

This commit adds a test for almost every implementation of the parse method for TreeType. OperationInput/Output/Errors, and number nodes aren't covered yet. These tests only include valid cases, and are not comprehensive yet. More cases are needed to check edge cases and different code paths for some TreeTypes, as well as error behavior. The test assertions check that the parser has produced the correct TreeTypes for the root node and its immediate children.
Various minor bugs were fixed, and updates made while writing these tests:
- CapturingTokenizer was updated to avoid a bug where the first character, $, was not included in the list of captured tokens.
- An enum member with no ws around the '=' could have the value assingment skipped.
- Members with a value assignment could consume …

Add tests for individual parse methods

---

smithy-model/src/main/java/software/amazon/smithy/model/pattern/UriPattern.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpQueryTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict1.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict1.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict2.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict2.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict3.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-query-literals-and-bindings-conflict3.smithy

Validate that query literal do not conflict with query params. Currently is possible to define a model like the following, that defines `code` as a query literal in the URI part of the `@http` trait and also the same query param in the `OperationOneShape`. This change will disallow this model that is not valid in practice.
```smithy
$version: "2"
namespace smithy.example
// OperationOne defines a query literal `code` that conflicts with the
// query param defined in the input structure.
service SmithyExample {
operations: [
OperationOne
]
}
@http(code: 200, method: "GET", uri: "/example?code")
@readonly
operation OperationOne {
input: OperationOneInput
output: OperationOneOutput
}
structure OperationOneInput {
@httpQuery("code")
code: …
```

Validate that query literal do not conflict with query params

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/externaldocs-test.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/externaldocs-test.smithy

Supports converting the `@externalDocumentation` trait on operations into the `externalDocs` property when converting to OpenAPI.

Support `externalDocs` when converting operations to OpenAPI

---

docs/source-2.0/spec/idl.rst

Previously, the LineComment grammar was a superset of DocumentationComment. This commit removes the ambiguity.

Update LineComment grammar

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturingTokenizer.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeTypeTest.java

All TreeTypeTests now expect the entire tree to be valid. This helps us find ambiguity and inconsistencies in the parser for cases when parsing a child tree is invalid only due to the context of the parent. Fixes minor bugs that caused trees to be invalid:
- enumMember test didn't have a BR after VALUE_ASSIGNMENT
Fills in missing tests for:
- Operations
- Block apply statements
- Entity type name
- Aggregate type name
Other minor changes and improvements:
- Adds util methods for parsing optional for-resource, mixins, and value assignment productions.
- Adds util method for parsing any shape type and name.
- Updates peekPastSpaces to not skip the current token, in case it is not SP. This simplifies parsing value assignments, and has more intuitive behavior.
- Removes peekPastWs, which was …

Assert trees are valid, fill in missing tests

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java

Previously, when a member was changed (for ex. docs are added) at the same time as the @input trait was added or removed for the parent, there would be identical duplicate diff events for ChangedNullability. This fixes that.

Fix duplicated events for ChangedNullability Added/RemovedInputTrait

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedOperationError.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedOperationError.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedOperationErrorTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedOperationErrorTest.java

Adds the shape ids of the errors themselves to the event ids

Extend event ids for Added/RemovedOperationError events

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java

Adds the enum indices to the event ids
eg. `ChangedEnumTrait.Removed.4`

Added enum values to ids for ChangedEnumTrait events

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedEntityBinding.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedEntityBinding.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedEntityBindingTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedEntityBindingTest.java

Extended AddedResourceBinding, AddedOperationBinding, RemovedResourceBinding,  RemovedOperationBinding event ids with
1. the type of the parent entity
2. the id of the child shape being added/removed

Extended AddedEntityBinding/RemovedEntityBinding event ids with granularity

---

docs/source-2.0/guides/model-linters.rst

https://github.com/awslabs/smithy/pull/1764#issuecomment-1581372547
Updated the 2.0 docs to reflect the newest default list of member names that indicate pagination is needed

Update stale docs around MissingPaginatedTrait

---

build.gradle
smithy-cli/build.gradle
smithy-syntax/build.gradle

Testing:
(1) All code builds correctly using `./gradlew clean build :smithy-cli:integ`.
(2) Verified a single JAR is created by smithy-syntax:
```
❯ ls -l smithy-syntax/build/libs/
╭───┬───────────────────────────────────────────────────┬──────┬────────┬──────────┬───────────┬───────────┬───────────┬─────────┬───────┬──────────┬──────────────┬──────────────┬──────────────╮
│ # │                       name                        │ type │ target │ readonly │   mode    │ num_links │   inode   │   uid   │ group │   size   │   created    │   accessed   │   modified   │
├───┼───────────────────────────────────────────────────┼──────┼────────┼──────────┼───────────┼───────────┼───────────┼─────────┼───────┼──────────┼──────────────┼──────────────┼──────────────┤
│ 0 │ …
```

Shade prettier4j in smithy-syntax

---

docs/source-1.0/spec/core/http-traits.rst

N/A
Update the spec to mention that HTTP code SHOULD be between 200 and 299. This aligns with the [validator's current implementation](https://github.com/awslabs/smithy/blob/c619a9a4a16f8cffbf4adcc06d32ecbe73ade669/smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpResponseCodeSemanticsValidator.java#L55-L57) which throws a `danger`-level error when it's outside of this range. 

Recommend HTTP code SHOULD be between 200 and 299

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/Formatter.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/RemoveUnusedUseStatements.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeTypeTest.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/awkward-comments.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/awkward-comments.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/remove-unusued-use.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/remove-unusued-use.smithy

Node string values should parse as a SHAPE_ID not as an IDENTIFIER.

Remove unused use statements and fix node parsing

---

docs/source-1.0/spec/core/selectors.rst
docs/source-2.0/spec/selectors.rst

Fixes examples for `*=` string comparator.

Fix ends with selector example

---

docs/source-2.0/guides/evolving-models.rst

*Issue #, if available:* #1775
Added a note to the evolving models document to note that adding or updating constraint traits is not backwards compatible. While there, fix the docs to point to enum shapes instead of mentioning the deprecated `enum` traits.

Add a note about how constraint traits affect backward compatibility

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeTypeTest.java

Adds test cases that validate the parser fails when expected by asserting that any descendant of the root is an error tree. There is a test per-production, if that production has terminal tokens, or represents an alternation of productions that are distinguished by terminal tokens. For example, SHAPE_OR_APPLY_STATEMENT chooses between shape and apply statements based on whether the current lexemme is "apply".
Only cases where the terminal tokens are invalid are tested because if a non-terminal (ie. another production) is invalid, the error tree is a child of the tree for that production. Since we also have tests that make sure the correct children are present for each production, we should have enough coverage to only test invalid non-terminals. For example, when parsing this shape …

Add parse failure tests

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java
smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java

* Add templates listing to smithy init command
* Allow copying templates to nested output directory in smithy init command
*Testing:*
* `smithy init --template quickstart-cli --output hello/world`
* `smithy init --template quickstart-cli --output ./hello/world`
* `smithy init --template quickstart-cli --output /Volume/workspace/hello/world`
* `smithy init --list`
Output:
```
NAME                           DOCUMENTATION
----------------------------   ----------------------------------------------------------------------------------
custom-annotation-trait        Gradle project for creating a package for a custom annotation trait.              
quickstart-cli                 Smithy Quickstart example weather service using the Smithy CLI. …
```

Add templates listing to smithy init command

---

docs/source-1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source-1.0/spec/core/behavior-traits.rst
docs/source-2.0/aws/protocols/aws-ec2-query-protocol.rst
docs/source-2.0/spec/behavior-traits.rst
docs/source-2.0/spec/http-bindings.rst
smithy-aws-protocol-tests/model/awsJson1_0/requestCompression.smithy
smithy-aws-protocol-tests/model/awsJson1_1/requestCompression.smithy
smithy-aws-protocol-tests/model/awsQuery/requestCompression.smithy
smithy-aws-protocol-tests/model/ec2Query/requestCompression.smithy
smithy-aws-protocol-tests/model/restJson1/requestCompression.smithy
smithy-aws-protocol-tests/model/restXml/requestCompression.smithy

#1827
Fix typo in requestCompression trait spec.
Update request compression trait protocol tests with regard to HTTP bindings.
Also fix minor issues throughout docs.

Update Request Compression Trait specification

---

smithy-cli/build.gradle
smithy-cli/src/it/java/software/amazon/smithy/cli/MavenResolverTest.java
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/maven-auth/smithy-build.json
smithy-cli/src/main/java/software/amazon/smithy/cli/dependencies/MavenDependencyResolver.java

*Issue #1837 *
Fixes broken http authentication.
Replace `MavenAuth` with existing aether builder to configure the repository auth context.
Modify the auth test to use a mock server to actually run the authentication flow.

Fix basic HTTP authentication when resolving dependencies

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java

Previous bugfix PR https://github.com/awslabs/smithy/pull/1806/files was incomplete as it turns out. Because of the deduping logic, when the second instance of the same event would have been added, nothing happens (this is intentional). However this ends up triggering the fallback codepath that emits a generic event when it thinks no more-specific event was emitted. 

Fixes the fix for duplicate ChangedNullability events

---

docs/source-1.0/spec/core/protocol-traits.rst
docs/source-2.0/spec/model.rst
docs/source-2.0/spec/protocol-traits.rst

Minor timestamp description update. 
The description was slightly confusing as I thought it was no (UTC offset and fractional milliseconds) instead of (no UTC) and (fractional milliseconds). 

(doc): Minor rephrase for Timestamp description.

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Makes the `quickstart-cli` example ([here](https://github.com/smithy-lang/smithy-examples/tree/main/quickstart-examples/quickstart-cli)) the default example template. 
This allows customers to call `smithy init` with no`-t` or `--template` flag.
*Testing*: 
Executed `smithy init` with no `-t` flag using locally build CLI. Confirmed `quickstart-cli` folder was created and builds correctly.

Add default template

---

docs/source-1.0/spec/core/protocol-traits.rst
docs/source-2.0/spec/protocol-traits.rst
smithy-aws-protocol-tests/model/awsJson1_1/fractional-seconds.smithy
smithy-aws-protocol-tests/model/awsQuery/fractional-seconds.smithy
smithy-aws-protocol-tests/model/ec2Query/fractional-seconds.smithy
smithy-aws-protocol-tests/model/restJson1/fractional-seconds.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-body.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-header.smithy
smithy-aws-protocol-tests/model/restJson1/validation/malformed-uniqueItems.smithy
smithy-aws-protocol-tests/model/restXml/fractional-seconds.smithy

The description of http-date previously stated that implementations MUST support fractional seconds. However, fractional seconds are not permitted by the imf-fixdate grammar. The original intent of this wording in the specification was that clients can gracefully handle parsing these timestamps with fractional precision, but not send fractional precision to avoid client/server incompatibilities. However, this caused confusion in implementations, and when clients send http-date timestamps with optional fractional precision, some servers, including S3, cannot parse the timestamp.
To avoid these issues altogether, this commit removes any kind of specification and protocol test for handling optional fractional seconds with `http-date` timestamps.
By submitting this …

Remove fractional seconds from http-date

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuild.java
smithy-build/src/main/java/software/amazon/smithy/build/plugins/SourcesPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/java/software/amazon/smithy/build/plugins/SourcesPluginTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/plugins/sources-ignores-unrecognized-files/a.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/plugins/sources-ignores-unrecognized-files/foo.md
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java

Smithy-Build is often invoked from the Smithy CLI, and developers often provide directories that contain model files. If a directory contains files other than recognized Smithy models, those unknown files are treated as "sources" and ultimately wind up in the sources plugin manifest file. Files that are not Smithy model files should not show up in the manifest as this can cause invalid JARs to get created by tooling like the Smithy Gradle plugin.
Sources are now eagerly filtered when they are added to SmithyBuild. If someone, somehow, manually configures the sources plugin to use unrecognized Smithy model files, the plugin will skip those files and log a warning rather than create an invalid manifest.
By submitting this pull request, I confirm that my …

Omit unrecognized models from sources

---

smithy-cli/src/it/java/software/amazon/smithy/cli/MavenResolverTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/dependencies/FileCacheResolver.java
smithy-cli/src/main/java/software/amazon/smithy/cli/dependencies/MavenDependencyResolver.java
smithy-cli/src/test/java/software/amazon/smithy/cli/dependencies/FileCacheResolverTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/dependencies/MavenDependencyResolverTest.java

*Issue #, if available:* #1850
We will no longer fail when a SNAPSHOT dependency is used. In order to make sure that SNAPSHOTs are periodically re-resolved, a TTL of 1 day was added to the cache file so that the cache is invalidated every 24 hours. The cache can be manually invalidated using `smithy clean`.
When implementing a TTL, I noticed that caching wasn't actually working and was always invalidated. That's fixed now by using the correct timestamp comparisons, and several new test cases were added.
Closes #1850

Support SNAPSHOTs and fix dependency cache

---

smithy-cli/src/it/java/software/amazon/smithy/cli/DiffCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java

Rather than fail when `smithy diff` is called with no arguments, we will insteadd assume that the caller meant `smithy diff --mode git` and use `git` mode against HEAD.
So now:
```
smithy diff # mode is --diff
smithy diff --old some-file --new some-file # mode is --arbitary
smithy diff --old some-file # Fails due to --arbitrary missing --new
smithy diff --new some-file # Fails due to --arbitrary missing --old
```

Make default diff mode `--git` when using no arguments

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuild.java

Fixes #1859 
Modifies the changes in https://github.com/smithy-lang/smithy/pull/1851, specifically `SmithyBuild::addSources`, to not check subdirectories for Smithy files. The previous behavior was to just add whatever path was given to the method, *not* everything in subdirectories. However, the change didn't recursively search subdirectores, so you could get build errors due to missing shapes when running the sources plugin.
This change reverts the behavior of `SmithyBuild::addSource` to only add whichever path it was given, but still checks to see if the path is a valid Smithy model.

Fix building models in subdirs

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/enum-mixin-input.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/enum-mixin-output.smithy

Fixes #1864 
This commit fixes an issue where the IDL serializer would write an empty apply statement on an enum member that was mixed in, as the value was written using the special IDL syntax for enum values.

Fix IDL serialization of enums with mixins

---

docs/source-1.0/spec/core/behavior-traits.rst
docs/source-2.0/spec/behavior-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated/paginated-invalid.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated/paginated-invalid.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated/paginated-map-tokens.errors

Slightly relax paginated pageSize types

---

docs/source-1.0/spec/aws/aws-core.rst
docs/source-2.0/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.smithy
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/EventSourceValidatorTest.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/ServiceTraitTest.java

*Description of changes:* Add documentationIdentifier value to aws.api#service trait. This value is used to implement linking between service and sdk documentation for AWS services.

Add documentationIdentifier value to aws.api#service trait

---

docs/source-1.0/spec/aws/aws-restjson1-protocol.rst
docs/source-1.0/spec/aws/aws-restxml-protocol.rst
docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst
docs/source-2.0/aws/protocols/aws-restxml-protocol.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpBindingsMissingValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-bindings-missing-validator.errors

This commit updates validation of protocols that support the `http` trait to cover a case where no operations on a service with the protocol applied had the `http` trait was valid.
Resolves #1438 

Improve validation for http binding protocols

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/Formatter.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/node-text-blocks.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/node-text-blocks.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/trait-textblock.formatted.smithy

Updates the formatter to indent the node value of a node kvp when they are text blocks.
A test case was added for a text block as the node value of a node kvp, and a test case was updated for when text blocks are in traits.

Fix indentation when formatting text blocks

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/ServiceTraitTest.java

This commit fixes the serialization of the target property of ServiceTrait by serializing the ShapeId with it's namespace qualifier.

Fix ServiceTrait serialization

---

docs/source-1.0/spec/core/http-traits.rst
docs/source-2.0/spec/http-bindings.rst
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-protocols-do-not-support-list-set-map-payloads.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-protocols-do-not-support-list-set-map-payloads.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

This commit updates the httpPayload trait to allow targeting a structure member that targets any type. Documentation is updated to clarify how the values of other types are serialized.
AWS protocol support for new types of httpPayload marked member targets is unchanged.
Resolves #1528 

Expand valid targets of httpPayload

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/EventSourceValidatorTest.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/ServiceTraitTest.java

*Description of changes:* This commit changes the resolution of the default docId property of the service trait by removing the reference to the target from the trait and passing the targeted shape itself as a parameter.

Update docId resolution method

---

designs/defining-timestamps.md
docs/source-1.0/spec/core/model.rst
docs/source-1.0/spec/core/protocol-traits.rst
docs/source-2.0/spec/protocol-traits.rst
docs/source-2.0/spec/simple-types.rst

Timestamps have so far been under-defined by omitting the temporal resolution and allowable date range.

Define timestamp with more specificity

---

smithy-build/src/main/java/software/amazon/smithy/build/model/MavenRepository.java
smithy-cli/src/it/java/software/amazon/smithy/cli/MavenResolverMultipleReposTest.java
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/maven-multiple-repos/smithy-build.json
smithy-cli/src/main/java/software/amazon/smithy/cli/dependencies/MavenDependencyResolver.java

*Closes #1883 *
Add an optional id for the maven repository definition.

Fix snapshot dependency resolution

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Updates the smithy init command to fail fast if the directory it is attempting to use as an output directory already exists.
Previously the command did not fail until after cloning the repo to a temp directory

Check for existing directory when creating template with init

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Update the `smithy init` command to honor the `--quiet` setting.
Also adds a unit test to ensure the init command continues to honor the quiet option with future revisions.

Update init command to honor quiet setting

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturingTokenizer.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeCursor.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeCursorTest.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/incorrect-indentation.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/incorrect-indentation.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/missing-trailing-newline.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/missing-trailing-newline.smithy

Fixes an issue in TokenTree where if the smithy file was missing a trailing newline, any trees containing the last piece of text in the file would have an end location of (0, 0). This happened because the BR TreeType didn't append any tokens for the EOF case, so the BR tree had no end location.
Fixes an issue in TreeCursor::findAt where if you tried to get the tree at a location right at the start of a tree, you would get the previous tree.
Tests were added for both of these cases in TreeCursorTest.

Fix off-by-one issues in TokenTree and TreeCursor

---

docs/source-2.0/guides/style-guide.rst

Add naming recommendations

---

docs/source-2.0/guides/smithy-cli/cli_installation.rst

Updates the docs to point to the new [smithy-lang tap](https://github.com/smithy-lang/homebrew-tap)

Update to use new smithy-lang tap

---

docs/source-2.0/guides/converting-to-openapi.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultConfigSettings.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/omits-default-trait.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/omits-default-trait.smithy
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/default-values-disabled.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/default-values.smithy

Fixes https://github.com/smithy-lang/smithy/issues/1844.
According to both the [3.1.0 spec](https://spec.openapis.org/oas/latest.html#referenceObject), and the [3.0.2 spec](https://spec.openapis.org/oas/v3.0.2#referenceObject), additional fields on `referenceObjects` are ignored.
This PR adds a JsonSchema configuration option, `enableDefaultValues` which is enabled by default. JsonSchemaShapeVisitor is updated to wrap any members with a `@default` trait applied which target a `$ref` with an `allOf` so that the default can be handled correctly by OpenAPI when this configuration option is enabled.
While JsonSchema's configuration will use this setting by default, it is disabled by default for API Gateway. API Gateway does not support default values anyways, so disabling this option will …

Wrap refs with defaults in an allOf

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Use the standard output instead of standard error for the init command output when appropriate. Also removed some unneeded `final`s.

Use standard output for regular messages

---

docs/source-2.0/spec/model.rst

*Issue #, if available:* Closes #1744

Better document trait merging

---

.github/workflows/update-brew.yml

Updates the brew update workflow to use the new [smithy-lang tap](https://github.com/smithy-lang/homebrew-tap)
Also updates the automation to use the Github CLI directly and removes the need to maintain a fork for the repo. This is how the [smithy-examples update workflow](https://github.com/smithy-lang/smithy-examples/blob/main/.github/workflows/update-smithy-version.yml) works.

Update brew workflow to use new smithy tap

---

docs/source-2.0/spec/constraint-traits.rst

Clarify constraint trait enforcement

---

docs/source-2.0/guides/converting-to-openapi.rst
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/DefaultRefStrategy.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/SchemaTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/int-enums-disabled.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/int-enums.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/int-enums.smithy

This PR adds support for intEnums when converting to json-schema and OpenAPI and closes: https://github.com/smithy-lang/smithy/issues/1667. This feature is enabled by default, but can be disabled by setting the `disableIntEnums` configuration property to `true`.
Currently, an intEnum is only represented as a "number".
The following Smithy model:
```
structure Foo {
bar: TestIntEnum
}
intEnum TestIntEnum {
FOO = 1
BAR = 2
}
```
Is converted as:
```
{
"definitions": {
"Foo": {
"type": "object",
"properties": {
"bar": {
"type": "number"
}
}
}
}
}
```
This PR adds the `enum` property to the output, and updates the ref strategy so that intEnums use a `$ref` the same way as enum shapes.
```
{
"definitions": {
"Foo": {
"type": "object",
"properties": {
"bar": {
"$ref": …
```

Add intEnum support for json-schema

---

docs/source-2.0/guides/converting-to-openapi.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultConfigSettings.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java

Fixes: https://github.com/smithy-lang/smithy/issues/1899
This PR adds a configuration option, `disableIntegerFormat`, which removes the `format` property which is set when integer types are enabled with `useIntegerType`.
API Gateway does not support `int32` or `int64` formats on numbers as noted in [API Gateway Known Issues](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html):
> Numbers of the Int32 or Int64 type are not supported.
These formats are disabled by default for API Gateway conversions, but are otherwise enabled when using the `useIntegerType` configuration.

Allow disabling format on integers

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/ColorTheme.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

This PR updates the appearance of the `smithy init --list` output. It also adds wrapping on descriptions that would cause the table output to exceed a fixed size of 100 characters.
Before: 
After: 

Update appearance of smithy init list output

---

smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/smithy-templates/smithy-templates.json
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Throws an error if the `include` files or the root template path specified in the `smithy-templates.json` are invalid.

Add exceptions for invalid paths in template definition

---

.github/workflows/ci.yml
smithy-cli/src/it/java/software/amazon/smithy/cli/CleanCommandTest.java
smithy-cli/src/it/java/software/amazon/smithy/cli/InitCommandTest.java
smithy-cli/src/it/java/software/amazon/smithy/cli/IntegUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CleanCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CliCache.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java
smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java

Caches a copy of the smithy init template directory in the default system temp directory. This greatly speeds up subsequent executions of both the list and create template subcommands of the `smithy init`. 
Previously, creating a template could take up to 6 seconds. With this change that time is down to ~0.3sec after the initial caching of the template repo.
---
*Example Executions*
Create a Template
List Templates 
Note: the gif recorder used here adds additional lag so these do not accurately represent the time these commands take to execute.
___

Cache template directory in init command

---

CHANGELOG.md

Include smithy init cache template directory change in release 1.36.0 changelog

---

docs/source-2.0/spec/model.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

Include the prelude in the spec by pulling in the prelude that's used in the reference implementation.
Note: I ran the prelude through the formatter, and limited docs to 80 characters.
Closes #489

Include prelude in spec

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiVersion.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/nullability-and-format.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/openapi-3-0-2.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/openapi-3-1-0.openapi.json

Closes: https://github.com/smithy-lang/smithy/issues/1664
This PR updates OpenAPI configuration to allow `propertyNames` to be set when using version `3.1.0`.
Previously, `propertyNames` was stripped from outputs as an unsupported keyword, since OpenAPI 3.0 did not support it.
By allowing `propertyNames`, enums can be used as map keys, without discarding all of the enum information.

Support enum map keys on OpenAPI 3.1.0

---

docs/source-2.0/guides/converting-to-openapi.rst
docs/source-2.0/guides/generating-cloudformation-resources.rst

Fix version number on smithy-build.json examples in docs.
Also adds captions for smithy-build.json examples.

Fix smithy-build.json version numbers

---

docs/source-2.0/spec/type-refinement-traits.rst

Add clarifications for default and clientOptional

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/ServiceIndex.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/ServiceIndexTest.java

Updates the docs for getEffectiveAuthSchemes to clarify that the returned auth schemes will be in alphabetical order by shape id if there is no `auth` trait present. This was always the case due to the usage of TreeMap, but the documentation didn't explicitly state it.
Tests were also updated to ensure this ordering.

Clarify ordering of auth schemes in ServiceIndex

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTree.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TokenTreeTest.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeTypeTest.java

Adds method to TokenTree that allows creating a tree with a specific TreeType. Previously, there was no way to do this since the parse methods on TreeType are package private. This addition supports use cases where new trees need to be added to a root tree.
A test was added for this method, and other tests were updated to use it.

Allow creating specific tree types

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

Fixes this that I was seeing in the build
```
> Task :smithy-cli:checkstyleMain
[ant:checkstyle] [WARN] /Volumes/workplace/github/smithy/smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java:163:20: Abbreviation in name 'getCacheDirFromURL' must contain no more than '2' consecutive capital letters. [AbbreviationAsWordInName]
Checkstyle rule violations were found. See the report at: file:///Volumes/workplace/github/smithy/smithy-cli/build/reports/checkstyle/main.html
Checkstyle files with violations: 1
Checkstyle violations by severity: [warning:1]
```

Fix AbbreviationAsWordInName checkstyle warning

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

Fix assembler addTraits for some model sources

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/ServiceIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/synthetic/NoAuthTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/ServiceIndexTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/knowledge/service-index-finds-auth-schemes.smithy

Add a new `getNoAuthAwareEffectiveAuthSchemes` method to ServiceIndex that wraps `getEffectiveAuthSchemes` to account for `smithy.api#noAuth` scheme.

Add ServiceIndex method to account for smithy.api#noAuth

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/ServiceIndex.java

Updates javadoc for ServiceIndex::getAuthSchemes to say the returned order is alphabetical. Tests were updated in [#1915](https://github.com/smithy-lang/smithy/pull/1915)to assert this ordering for ServiceIndex::getEffectiveAuthSchemes, but it also made the same update for the ServiceIndex::getAuthSchemes test. The PR didn't include a javadoc update, so the purpose of this PR is to fix that.

Update getAuthSchemes javadoc

---

docs/source-2.0/spec/authentication-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ServiceAuthDefinitionsValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/auth/auth-trait-must-target-service-schemes.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/service-auth-definitions/multiple-auth-schemes.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/service-auth-definitions/multiple-auth-schemes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/service-auth-definitions/one-auth-scheme.smithy

Adds a validator that warns when there's a service shape that has multiple authDefinition traits applied, but no auth trait. This encourages the use of the auth trait so auth scheme priority is being modeled explicitly. It also allows for tooling to look for and use this validation event.
Documentation was also updated to explain that without the auth trait, auth scheme ordering is alphabetical.
A test for the auth trait (auth-trait-must-target-service-schemes) was updated to avoid getting the warning message from the new validator.

Add validator for services with no auth trait

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionNameTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionPermissionDescriptionTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeyValueTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysValidator.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ServiceResolvedConditionKeysTrait.java
smithy-aws-iam-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeyValueTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ServiceResolvedConditionKeysTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/SmithyErrorFilesTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/condition-key-value.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-key-also-service-resolved.errors
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-key-also-service-resolved.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-key-value.errors
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-key-value.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-keys-service-resolved.errors
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-keys-service-resolved.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/valid-condition-key-value.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/valid-condition-keys-service-resolved.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/service-resolved-condition-keys.smithy

Adding conditionKeyValue and conditionKeysResolvedByService traits 
conditionKeyValue
Uses the associated member’s value as this condition key’s value. Needed when the member name doesn't match the condition key name.
conditionKeysResolvedByService
Specifies the list of IAM condition keys which must be resolved by the service, as opposed to being pulled from the request.

Adding conditionKeyValue and conditionKeysResolvedByService traits 

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/Formatter.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/errors-always-multiple-lines.smithy

Rather than keep operation errors on a single line if it fits, this PR forces errors to appear on multiple lines.
Further PRs will be added to make the same treatment to service and resource "resources" and "operations" properties (though that's more involved).

Force operation errors on multiple lines

---

.github/workflows/stale-issues.yml

Workflow wrongly tagged some of the issues due to running v3 version of the action which does not support multiple exemption labels. This change upgrades it to v4, which does have that support, and sets the workflow to dryrun to allow us to verify the run before actually turning the workflow on next time.
Closes #1937 

Bump action version to v6 and set to dryrun

---

.github/workflows/stale-issues.yml

Enable stale-issues workflow by removing the `dryrun` flag. I verified the execution logs from latest run and checked that the new version properly skips issues tagged with at least one of the exempt labels.

Enable stale-issues workflow

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/FormatVisitor.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/null-trait-body.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/null-trait-body.smithy

This PR fixes smithy-syntax throwing a NullPointerException when encountering a trait with an implicit null.
Following this fix, if a trait is encountered with an empty body, the parentheses will be omitted.
This:
```
structure Struct {
@default()
a: String
@default( )
b: String
@default(null)
c: String
}
```
Will now be formatted to this:
```
structure Struct {
@default
a: String
@default
b: String
@default(null)
c: String
}
```

Fix NPE on trait with implicit null

---

docs/source-2.0/aws/protocols/aws-json.rst.template
docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst
smithy-aws-protocol-tests/model/awsJson1_0/unions.smithy
smithy-aws-protocol-tests/model/awsJson1_1/unions.smithy
smithy-aws-protocol-tests/model/restJson1/unions.smithy

Some older implementations of AWS JSON protocols will unnecessarily serialize a `__type` property, even for unions. This behavior can't be changed. To account for this, deserializers should be updated to ignore an unrecognized `__type` when deserializing unions for AWS restJson1, awsJson1_0, and awsJson1_1.

Update AWS docs to ignore __type in unions

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderTraitMap.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

Some traits like the http trait will throw exceptions that are not SourceExceptions. This previously would cause the CLI to stop on the first exception and not show pretty error output. This fixes that by catching RuntimeExceptions to turn them into ValidationEvents.

Catch exceptions when creating traits

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampFormatPlugin.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ValidationEventDecoratorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/validation/node-validator.json

The NodeValidationVisitor vists shapes, members, and then the targets of members. When visiting the target of a member, the context of the referring member was lost, which meant a member with a timestampFormat trait like http-date isn't something the target shape has access to, which will cause validation to fail. We now pass in the referring member as part of the validation context.
Closes #1946

Fix member timestamp format node validation

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildOptions.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildCommandTest.java

`--allow-unknown-traits` bugs me every time I use it, so I added `--aut` as a short alias.

Add short --aut for --allow-unknown-traits

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/FlattenAndRemoveMixins.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ModelTransformerTest.java

[FlattenAndRemoveMixins](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/transform/FlattenAndRemoveMixins.java) only removes mixins if it flattened 1 or more shapes. 
This can cause mixins to leak into downstream code generators (when we really want them inlined).
Specifically, if a Model has mixins which are *all* unused, it will trigger this behavior. But if at least 1 mixin was flattened into a shape, all mixins will be removed (including unused ones). This can happen in shared Smithy model packages that are meant to be used by multiple downstream services.

Support removing unused mixins

---

docs/Makefile
docs/source-1.0/spec/core/constraint-traits.rst
docs/source-2.0/spec/constraint-traits.rst

Also adds back the `openhtml` make command, routing to the top-level index.

Add length trait to trait index

---

smithy-cli/src/it/java/software/amazon/smithy/cli/SelectTest.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/SelectCommandTest.java

--show is used to include additional data in select command output, including the shape type, file where the shape is defined, and/or variables captured when the shape was matched.
For example:
```
smithy select --selector 'structure $neighbors(>)' --show-traits documentation --show type,file,vars --aut s3.json
```
Outputs:
```
[
{
"shape": "com.amazonaws.s3#CSVInput",
"type": "structure",
"file": "/path/to/s3.json:16224:34",
"vars": {
"neighbors": [
"com.amazonaws.s3#CSVInput$AllowQuotedRecordDelimiter",
"com.amazonaws.s3#CSVInput$Comments",
"com.amazonaws.s3#CSVInput$FieldDelimiter",
"com.amazonaws.s3#CSVInput$FileHeaderInfo",
"com.amazonaws.s3#CSVInput$QuoteCharacter",
"com.amazonaws.s3#CSVInput$QuoteEscapeCharacter",
"com.amazonaws.s3#CSVInput$RecordDelimiter"
]
},
"traits": { …
```

Add --show to select command

---

smithy-model/src/main/java/software/amazon/smithy/model/node/NumberNode.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NumberNodeTest.java

Attempts to use the most optimal comparisons of number nodes, using .equals if both number values are of the same type, then the string representation of each value, finally followed by comparing the BigDecimal representation of each value using the string cache. If a BigDecimal is needed, it is cached on the number node for future checks.
Closes #1378

Improve node number equality

---

docs/source-2.0/additional-specs/waiters.rst
docs/source-2.0/guides/building-codegen/mapping-shapes-to-languages.rst
docs/source-2.0/guides/converting-to-openapi.rst
docs/source-2.0/index.rst
docs/source-2.0/spec/aggregate-types.rst
docs/source-2.0/spec/documentation-traits.rst
docs/source-2.0/spec/http-bindings.rst
docs/source-2.0/spec/index.rst
docs/source-2.0/spec/model.rst
docs/source-2.0/spec/protocol-traits.rst
docs/source-2.0/spec/resource-traits.rst
docs/source-2.0/spec/selectors.rst
docs/source-2.0/spec/service-types.rst
docs/source-2.0/spec/type-refinement-traits.rst

Resolves #1381 
Includes minor reordering of some sections. A few rubrics were changed to note/important as they're informative content.

Replace rubrics with linkable titles

---

smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

Add tests for unions as httpPayloads

---

docs/source-2.0/guides/building-models/build-config.rst
docs/source-2.0/spec/documentation-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/BlobLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/MapLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/PatternTraitPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExamplesTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/ExamplesTraitTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ExamplesTraitValidatorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.json

This PR adds a `disableConstraints` boolean to the @examples trait, allowing for input constraint trait validations to be lowered from `ERROR` to `WARNING`.
By lowering the severity from an `ERROR`, Smithy model authors can include examples of invalid inputs and their corresponding errors.

Allow constraint trait errors on error example inputs

---

smithy-model/src/main/java/software/amazon/smithy/model/node/NumberNode.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NumberNodeTest.java

This change now makes the BigDecimal get created eagerly, and accounts
for NaN and Infinity. The previous implementation would have failed
in these cases. NodeValidationVisitor now uses the computed BigDecimal
rather than create a one-off each time. It also doesn't recreate the
already available BigDecimcal of the range trait.
This change deprecates isNaturalNumber since that method was poorly
named. A natural number is an integer >= 1, but we were including 0
(which is likely why some callers assumed it asserts >= 0).
This also adds an isNegative method since multiple callers need to
assert that a NumberNode contains a non-negative value.

Improve NumberNode

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/RemoveInvalidDefaults.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/RemoveInvalidDefaultsTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/bad-defaults-range-trait.fixed.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/bad-defaults-range-trait.smithy

If a default trait is incompatible with the range trait of the member or the member target, then the shape is essentially in a state where the member is invalid: omit a value for the member at it is automatically incompatible with the range trait of the member.
This transformer finds such cases and removes invalid default values. It is likely that services with such a model did not intend for the members to actually have a default value, and this typically only happens with members that have a default value of `0`.

Add transform that can remove invalid defaults

---

smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/ExamplesTraitTest.java

Updates the Examples trait to only serialize the `allowConstraintErrors` when true. If not set, or false, it will not be serialized.

Only serialize allowConstraintErrors when true

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java

These messages reflect a previous design in Smithy that was refactored to rename @nullable to @clientOptional, but these error messages and IDs were missed in Smithy-Diff. This change also simplifies the error message for adding a required trait to remove extra detail (this message is only presented when relevant so the detail isn't needed).

Correct smithy-diff nullability error messages

---

docs/source-2.0/quickstart.rst

The `City` resource had the `list: ListCities` operation defined; however, the code snippet directly following removed it again, very likely by accident

Retain previous examples operations

---

smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/http-payload.smithy

Some HTTP clients will automatically set this value to 0, but others will explicitly not set the header. The length has no effect on service behavior, so it is relaxed by removing the assertion.

Relax Content-Length in unset union payloads

---

docs/Makefile
docs/source-2.0/additional-specs/rules-engine/specification.rst
docs/source-2.0/aws/rules-engine/auth-schemes.rst
docs/source-2.0/aws/rules-engine/index.rst
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/EndpointAuthUtils.java
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/invalid/signing-optional-properties-mistyped.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/invalid/signing-optional-properties-mistyped.smithy
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/valid/signing-optional-properties.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/valid/signing-optional-properties.smithy
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/validators/AuthSchemeValidator.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/validators/RuleSetAuthSchemesValidator.java
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-auth-name-type.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-auth-name-type.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-duplicate-auth-name.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-duplicate-auth-name.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-missing-auth-name.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-missing-auth-name.smithy

This commit fixes several issues with validating authSchemes properties in defined endpoints within an endpoints rule set. It now properly enforces the typing and uniqueness of names of schemes defined within an authSchemes property.
It also fixes several issues validating the presence and typing of properties configuring the sigv4, sigv4a, and "beta" schemes.
A specification has been added to clearly detail how clients should choose schemes, detail what properties of the above schemes will be validated, and explain how to add new validators.
-----

Update rules engine authSchemes validation

---

docs/source-2.0/guides/converting-to-openapi.rst
smithy-model/src/main/java/software/amazon/smithy/model/transform/DeconflictErrorsWithSharedStatusCode.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/DeconflictErrorsWithSharedStatusCodeTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/conflicting-errors-with-conflicting-headers.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/conflicting-errors.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deconflicted-errors.smithy
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test-use-oneof.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test.smithy

This PR closes #1649. See also: #1265.
It re-introduces a subset of the changes that were added previously in #1304, but later reverted in #1334. The docs changes from #1304 were not entirely reverted, so those are modified here to reflect the new changes, which include only allowing for the `oneOf` option to deconflict errors. Contrary to the docs for the previous PR, `oneOf` *is* supported by API Gateway when the `oneOf` is included within a component schema and referenced via a `$ref`. Using `oneOf` within the path content directly is not allowed.
Deconflicting errors is opt-in when converting to OpenAPI by setting the following in smithy-build.json:
```
{
"plugins": {
"openapi": {
"service": "smithy.example#Weather",
"onErrorStatusConflict": "oneOf"
}
}
}
``` …

Add option to deconflict errors with same status code for OpenAPI

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsRuleSetExtension.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/EndpointAuthUtils.java
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/valid/sigv4subscheme-auth-scheme.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/valid/sigv4subscheme-auth-scheme.smithy

Add sigv4 subscheme auth validation

---

docs/source-2.0/aws/rules-engine/built-ins.rst
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsBuiltIns.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsRuleSetExtension.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/validators/RuleSetAwsBuiltInValidator.java
smithy-aws-endpoints/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/invalid/additional-consideration-built-ins.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/invalid/additional-consideration-built-ins.smithy

Add AccountId and CredentialScope BuiltIns

Add AccountId and CredentialScope BuiltIns

---

docs/source-2.0/index.rst

Adds a link to the sidebar to the smithy-examples repo.

Add examples link to sidebar

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedOperationError.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedRequiredMember.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedNullability.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedTraitDefinition.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedOperationErrorTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedRequiredMemberTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedTraitDefinitionTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedMemberTargetTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedNullabilityTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedEntityBindingTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedOperationErrorTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedTraitDefinitionTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ServiceRenameTest.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java

This PR updates smithy-diff evaluators to set source locations on the emitted events where the source location was missing previously.
For events where something is removed from a model (member, trait definition, etc), the location from the old model is used. For events where something is added or modified within a model, the location from the new model is used.

Set source locations on smithy-diff events

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyIntegration.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CapturingIntegration.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java
smithy-codegen-core/src/test/resources/META-INF/services/software.amazon.smithy.codegen.core.directed.TestIntegration

This adds a configuration step for integrations, allowing them to use `smithy-build.json` settings that aren't used by the generator that they target.
Generators using the node mapper helper for their settings will have this set for free. Others will need to grab it themselves.
Yes that's the *ideal* but some things just don't make sense as traits. For example, a trait that controls whether a documentation generator scans your system for the presence of a build tool and all the other dependencies you need doesn't make sense as a trait.

Add automatic integration configuration

---

smithy-aws-protocol-tests/model/awsJson1_0/defaults.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_0/nestedDefaults.smithy
smithy-aws-protocol-tests/model/awsJson1_0/required.smithy

* Add protocol tests for default values
* Verified tests passed with the latest smithy-rs SDK

Add protocol tests for default values

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PrivateAccessValidator.java

*Issue #, if available:* n/a
Within `PrivateAccessValidator#getPrivateAccessValiationEvent`, an unchecked call to `Optional#get` occurs. This might throw a `NoSuchElementException` if the optional is indeed empty.

Mitigate possible NSE exception in PrivateAccessValidator.java

---

smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/ModelTest.java

Found this issue through:
```scala
val modelString =
"""|$version: "2"
|
|namespace foo
|
|@examples([
|  {
|    title: "Test This"
|    input: {
|      test: "something"
|    }
|  }
|])
|operation Foo {
|  input := {
|    test: String
|  }
|}
|""".stripMargin
val one = Model
.assembler()
.addUnparsedModel("foo.smithy", modelString)
.assemble()
.unwrap()
val two = Model
.assembler()
.addUnparsedModel("foo.smithy", modelString)
.assemble()
.unwrap()
one == two // false
```
I've allowed edits from maintainers, feel free to change as you see fit or tell me what to change.
YES

fix for ExampleTrait.Example equality

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTraitParser.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/traits/annotation-unclosed-object1.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/traits/invalid-trait-shape-id-key.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits/reference-shape-from-trait.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits/reference-shape-from-trait.smithy

Fix trait parse error for shape IDs

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-union.smithy

Add unknown union malformed request test

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/disable-condition-key-inference-for-resources.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/disable-condition-key-inference-for-service.smithy

Enable `aws.iam#disableConditionKeyInference` trait for service shape

Enable `aws.iam#disableConditionKeyInference` trait for service shape

---

docs/_templates/base.html

Adds basic website analytics to the Smithy documentation site. The script header added in this PR will be added to the `<head>` of every page on the docs site.
In particular we will be tracking the following as a way to gauge external adoption of and engagement around Smithy: 
- Page views per page
- Number of unique visitors
- Referring domain

Add basic website analytics

---

docs/source-1.0/spec/core/selectors.rst
docs/source-2.0/spec/selectors.rst
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/TopDownIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/NeighborVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/RelationshipType.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/NeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/RecursiveNeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/SelectorParser.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/MarkAndSweep.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/BottomUpNeighborVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/NeighborVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/NeighborSelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/RecursiveNeighborSelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/linters/emit-each-selector-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/selector/cases/neighbors.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/neighbor-test.smithy

This commit fixes a few fundamental issues with how neighbors and model graph traversal was implemented. These changes are bug fixes and correctness fixes, though they could potentially impact existing selectors of a very small set of users (e.g., there is no known impact to Amazon's very large corpus of Smithy models).
The theme of this change is more accurately exposing the Smithy model as a graph, making graph traversal unambiguous. There are a few major issues addressed in this CR.
1. The bound relationship is no longer emitted or documented. It can still be used if referred to explicitly in a directed neighbor selector.
2. instanceOperation relationship is now "synthetic", deprecated, and not documented. It is no longer emitted from a NeighborVisitor but can be used if referred to …

Correct issues and bugs with neighbor traversal

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeyDefinition.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTrait.java
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.smithy
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/iam-resource.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/successful-condition-keys.smithy

Add relativeDocumentation to aws.iam#iamResource and aws.iam#defineConditionKeys traits

Add relativeDocumentation to aws.iam#iamResource and aws.iam#defineConditionKeys traits

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateIntEnumDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/GenerateIntEnumDirectiveTest.java

Adds convenience method to get an IntEnumShape from the `GenerateIntEnumDirective`.
This provides parity with the `GenerateEnumDirective` that has an `expectEnumShape` method [see here](https://github.com/smithy-lang/smithy/blob/3ea52156715f7e30de026763021ef78447bf965d/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateEnumDirective.java#L79)

Add convenience method to get IntEnumShape from GenerateIntEnumDirective

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderTraitMap.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/mixins/apply-to-mixed-member.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/mixins/member-apply-other-namespace.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/mixins/mixed-member.smithy

Fixes https://github.com/smithy-lang/smithy/issues/2004.
When an apply statement targets a mixed in member, the trait application is stored until the mixed in member has been synthesized. However, if you load the same model file multiple times in the same loader, the trait application is only stored once, and removed when it is claimed, so when de-conflicting the duplicate mixed-in member definitions, only one of them will have the trait applied, resulting in a conflict.
This commit updates the loader to keep track of when these unclaimed traits have been claimed, rather than just removing them when claimed. As long as the traits have been claimed once, we know they aren't being applied to a non-existent shape. This allows the traits to be claimed multiple times if necessary.
Test cases …

Resolve dupe apply to mixed members

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTrait.java
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.smithy
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/iam-resource.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/successful-condition-keys.smithy

This commit adds a `disableConditionKeyInheritance` property to the `iamResource` trait, which can be set to `true` to decouple an IAM resource's condition keys from those of its parent resource(s). This can be combined with the `conditionKeys` trait to explicitly configure an IAM resource's condition keys.

Add `disableConditionKeyInheritance` to `iamResource`

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidatedResult.java

The documentation of `unwrap` currently mentions only `ERROR`, but in the implementation, `isBroken` with following implementation is used:
```
public boolean isBroken() {
for (ValidationEvent event : events) {
if (event.getSeverity() == Severity.ERROR || event.getSeverity() == Severity.DANGER) {
return true;
}
}
return false;
}
```

Update unwrap docs

---

smithy-model/src/main/java/software/amazon/smithy/model/traits/RecommendedTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/RecommendedTraitTest.java

This fixes the trait provider for the recommended trait, which was discarding the `reason` by accidentally creating a new builder after it was set.

Fix recommended trait provider

---

smithy-model/src/main/java/software/amazon/smithy/model/neighbor/UnreferencedTraitDefinitions.java
smithy-model/src/test/resources/software/amazon/smithy/model/neighbor/unreferenced-test.json

Fix removal of applied non-prelude meta traits

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelInteropTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelInteropTransformerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/upgrade-box/2-to-1/intEnumSetToZeroValueToNonNullable.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/v2/enums.1.0.json

Primitive root shapes without the default trait have a synthetic box trait appplied when the shape is built in the loader (see https://github.com/smithy-lang/smithy/blob/d457aabb80feb4088caa3ac27d337b84e3ebc43d/smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderShapeMap.java#L366) if the shape would have a default of 0 in Smithy 1.0. Previously, this didn't include intEnum, so if you convert to 1.0, the intEnum which previously had no default in 2.0 will have a default of 0.
This commit updates ModelInteropTransformer to consider intEnum as a shape that has a default value in 1.0, so the loader applies the synthetic box trait to root intEnums.
Tests were updated to make sure box is added to root intEnums, and to fix some incorrect assertions. …

Add synthetic box to root intEnums w/o a default

---

smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

This rephrases the documentation for auth traits to read more like documentation for the auth type rather than documentation for a function. This allows it to be more naturally used in documentation generation without change. This also adds inline links to external documentation rather than solely relying on the external docs trait. While that trait is useful still, rendered docs are more natural if there's inline links too.

Rephrase auth trait documentation

---

smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy

This adds timestampFormat to the restXml protocol traits list. It also reorders the traits list on the other protocols so that all of them begin with those handful of shared traits so that it's easy to compare visually.

Add timestampFormat to restXml protocol traits

---

docs/root/robots.txt

- Submitting queries for smithy docs returns hits for 1.0 docs (usually at or near the top of results), adding a robots.txt with a disallow for 1.0 will make this less likely to happen

Add robots.txt with a single disallow for 1.0 pages

---

docs/source-2.0/aws/aws-auth.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/auth/SigV4ATrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/auth/SigV4TraitsValidator.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.smithy
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/auth/SigV4ATraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-service-mismatch.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-service-mismatch.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-sigv4a-mismatch.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-sigv4a-mismatch.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-empty-name.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-empty-name.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-no-sigv4.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-no-sigv4.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-service-mismatch.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4a-service-mismatch.smithy

N/A.
This PR adds the `@aws.auth#sigv4a` trait implementation, documentation, and additional validation of the trait respective to the `@aws.auth#sigv4` and `@aws.api#service` traits.

Add `@aws.auth#sigv4a` trait

---

smithy-aws-protocol-tests/model/restXml/document-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-aws-protocol-tests/model/restXml/document-unions.smithy
smithy-aws-protocol-tests/model/restXml/document-xml-attributes.smithy
smithy-aws-protocol-tests/model/restXml/endpoints.smithy

This PR splits InputOutput shapes into separate request and response shapes for rest-xml protocol tests.

Split input and output shapes for rest-xml tests

---

build.gradle

Adds the jreleaser plugin and configuration for publishing to Maven Central. Using the plugin is configurable with a Gradle property, so we can continue to use the old release method if necessary. The `closeRepository` and `releaseRepository` props in the jreleaser config are set to false right now so we can check the staged artifacts before actually releasing, but can be changed later to automatically release.

Add JReleaser config

---

smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy

The ABAP codegen strictly tests XML using XSLT which makes it sensitive to incorrect outer tags. We stumbled on these errors in the protocol tests, introduced in a recent commit.
Correcting the outer tags in three protocol tests.  These have been tested against the ABAP codegen.

Correcting erroneous outer tags

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/ReplaceShapes.java

Only build container shapes once when multiple members of the shape are changed as part of the commonly used replaceShapes transform.

Make replaceShapes more efficient

---

docs/source-2.0/guides/building-models/build-config.rst

Adds documentation for the proxy configuration parameters and environment variables added in https://github.com/smithy-lang/smithy/pull/2076

Add documentation for proxy configuration

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestSuite.java

This makes the `parameterizedTestSource` method of the test suite class public, allowing people to use a customized suite as a source for JUnit parameterized tests. Previously the only way to use the test suite as a parameterized test source was to use the default method that only lets you customize the class loader by passing in a class to source it from.

Make parameterizedTestSource public

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedShape.java
smithy-diff/src/test/java/software/amazon/smithy/diff/ModelDiffTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedShapeTest.java

For scalar shapes (and non-enum strings), removing them is safe and therefore can be lowered from an ERROR to a NOTE

Scalar RemovedShape events from ERROR -> NOTE

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/SortUseStatements.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTreeLeaf.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTreeNode.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/TokenTreeTest.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/br-comments-with-multiple-use.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/br-comments-with-multiple-use.smithy

Some tree types are guaranteed to have certain children, even if those children are empty. For example, SHAPE_STATEMENT always has a TRAIT_STATEMENT as its first child. Since trees with children have their start/end line and column locations computed from the respective locations of their first and last child, trees with 0 children ("empty" trees) will have a location of (0,0)-(0,0). If an empty child is the first or last child of its parent, the 0 location will bubble up to that parent.
This commit changes the way start/end line and column locations are computed for trees with children, such that empty children are ignored. This required a change to use statement sorting, which relied on the 0 location bubbling up to the parent to indicate to the formatter whether the use statement has a …

Fix tree node start and end locations

---

CHANGELOG.md
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapper.java
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapperTest.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/simple.smithy

Support iamAction for CFN handler permissions

---

docs/source-2.0/aws/aws-iam.rst
docs/source-2.0/guides/generating-cloudformation-resources.rst
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapper.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionNameTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionPermissionDescriptionTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamActionTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamActionValidator.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/RequiredActionsTrait.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ActionNameTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ActionPermissionDescriptionTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/IamActionTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/RequiredActionsTraitTest.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/Version.java

This commit formally deprecates the traits superseded by `@iamAction`
in Java code. Methods are added to IamAction to aid users in the
resolution of properties.
A resolution aid is also added to IamResource.
-----
Update IAM trait documentation
- Supersedes #2055 
-----

Improve deprecation of IAM Action traits

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/EndpointModifierIndex.java
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/EndpointModifierIndexTest.java

Skip indexing endpoint modifier traits without shape definition

Skip indexing endpoint modifier traits without shape definition

---

docs/requirements.txt
docs/setup.py

- Doc builds are failing in CI due to `The sphinxcontrib.applehelp extension used by this project needs at least Sphinx v5.0; it therefore cannot be built with this version.`
- A few other sphinx plugins are also updating to require >=5, so this change updates our version

Upgrade sphinx for docs

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/EnumShapeTest.java

When converting the normal enum trait to an enum shape, we convert the `"internal"` tag into the `@internal` trait. This updates the opposite direction conversion used to generate the synthetic enum trait to add the `"internal"` tag if the member had the `@internal` trait if it isn't already in the list of tags.
I also added a few other test cases for the member -> enum trait definition test that didn't seem to be covered, at least from the perspective of an enum shape that wasn't itself generated by converting a string shape.

Support internal trait when building synthetic enum trait

---

smithy-build/src/main/java/software/amazon/smithy/build/transforms/FlattenNamespaces.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/FlattenNamespacesTest.java

flattenNamespaces applies all service renames to disambiguate shapes that could be in conflict after flattening. But when consumers try to reload the transformed model, they get an error like:
```
"Service rename for `foo` does not actually change the name from `bar`"
```
because the rename has already been applied. This commit changes FlattenTransformer to also update the service shape by removing all renames, so consumers of a flattened model don't run into validation issues.

Remove service renames after flattenNamespaces

---

smithy-cli/src/it/java/software/amazon/smithy/cli/FormatCommandTest.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/TraitBreakingChange.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedPaginatedTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/TraitBreakingChangeTest.java
smithy-model/src/main/java/software/amazon/smithy/model/node/Node.java
smithy-model/src/main/java/software/amazon/smithy/model/node/internal/PrettyPrintWriter.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidationUtils.java
smithy-model/src/test/java/software/amazon/smithy/model/node/DefaultNodeWriterTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ContextualValidationEventFormatterTest.java

Adds backticks (or triple backticks) around trait values within diff event messages. This better supports markdown rendering of the messages.
Also changes pretty-printing to use platform-specific line separator through "%n"

Add backticks to diff messages for trait changes

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/BracketFormatter.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/FormatVisitor.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/ParseAndFormatTest.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/array-of-objects.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/array-of-objects.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/brackets.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/brackets.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/entity-shapes-line-break.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/entity-shapes.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/nested-arrays-and-objects.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/nested-arrays-and-objects.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/section-statement-blank-lines.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/single-line-object.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/single-line-object.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/trait-textblock.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/trait-textblock.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/traits-lots-of-tags.formatted.smithy

This commit updates how the formatter decides whether or not to put a line break after an opening bracket and before the closing bracket (bracket meaning `()`, `{}`, and `[]`). Previously, all bracket types followed the same logic - which included breaking when there are any array or object descendants. This lead to trait bodies being formatted like:
```
@someTrait(
[
{
key: "value"
}
]
)
structure SomeStruct {}
```
With this change, it will be formatted like:
```
@someTrait([
{
key: "value"
}
])
structure SomeStruct {}
```
the same also applies if the trait has a single object member:
```
@someTrait({
foo: "bar"
// ... more members to cause break onto separate lines
})
structure SomeStruct {}
```
Object nodes now also have a single space of padding inside the brackets when on a single …

Change line break formatting in brackets

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy

Previously we didn't have protocol tests specifically for 0/false in query params, which allowed for situations like
https://github.com/smithy-lang/smithy-rs/pull/3252 to occur.

Add protocol tests for 0/false in query params

---

smithy-aws-protocol-tests/model/awsJson1_0/defaults.smithy

Adds to existing json1_0 protocol tests for default values to include members with 0 default values - ie. empty string, 0, false. Also has an additional case for when _the_ default value is explicitly provided in parameters, it should not be ignored. A case was also added for members that are clientOptional.

Expand default value protocol tests

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/trailing-space-in-docs.smithy

Keep trailing doc comment spaces in IDL serializer

---

smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy
smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy

Add more traits to protocol test services

---

docs/source-2.0/guides/model-validation-examples.rst

*Description of changes:* There is a typo in one of the examples for model validation. In the text, it should say `strings` instead of `integers` since the example refers to requiring the use of the `@pattern` trait for all strings.

Correct typo in @pattern validation example

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

The new RestJsonZeroAndFalseQueryValues test that was released in Smithy 1.44 has incorrect parameters for servers. Other protocol tests that use `@httpQueryParams` explicitly set a `params` value for the member(s) with that trait, but this [new test is not](https://github.com/smithy-lang/smithy/blob/1.44.0/smithy-aws-protocol-tests/model/restJson1/http-query.smithy#L221-L236). This causes the smithy-rs server protocol tests to fail upon upgrading despite code generating the correct behavior.

Fix the `RestJsonZeroAndFalseQueryValues` protocol test for servers

---

smithy-aws-protocol-tests/model/restJson1/documents.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

(none)
This change adds tests for serializing/deserializing maps which use the document shape as a value. The AWS SDK for Kotlin previously did not handle these correctly, leading to a customer contact.

Add JSON protocol tests for document-valued maps

---

build.gradle

* Updates the gradle build to enable the use of Jreleaser for closing and releasing the repository
* The past 2 releases have used jreleaser for staging with nexus. 
---

Turn on closing and releasing of repository with jreleaser

---

docs/source-2.0/guides/gradle-plugin/gradle-migration-guide.rst
docs/source-2.0/guides/gradle-plugin/index.rst

* Adds a migration guide to help users move from the old version of the Smithy gradle plugin to the newer versions without breaking their existing projects.
Built locally with `make html`
[Built artifacts link](https://github.com/smithy-lang/smithy/actions/runs/7934810756/artifacts/1252081313)
---

Add gradle plugin migration guide

---

docs/source-2.0/quickstart.rst

Updates the Quickstart examples to: 
1. Use the updated Gradle plugin
2. Include examples of building with CLI as well as Gradle plugin
3. Add captions to files
4. Include instructions to clone quickstart with `init` command.
Built locally with `make html` 
[Download Zip archive of doc artifacts](https://github.com/smithy-lang/smithy/actions/runs/7921805367/artifacts/1249248736)
---

Update quickstart example with new gradle plugin and cli

---

docs/source-2.0/guides/gradle-plugin/index.rst

Adds a number of minor changes to the Gradle plugin guide based on initial feedback
1. Re-orders sections to pull the `Building Smithy models` section up
2. Changes out openapi plugin for `smithy-typescript` code generator
3. Clarifies language around projections and projection tags.
[Doc artifact link](https://github.com/smithy-lang/smithy/actions/runs/7963073887/artifacts/1257208335)
---

Update gradle plugin guide

---

docs/source-2.0/quickstart.rst

Updates quickstart example to include an empty smithy-build.json.
N/A
* The following Gradle plugin update will require either an empty build config or an explicit opt-out: https://github.com/smithy-lang/smithy-gradle-plugin/pull/123
---

Update gradle quickstart example to include empty smithy-build.json

---

.github/workflows/make-docs.yml
docs/Makefile

- To reduce effort in releasing new versions of smithy, we can automate doc-publishing
- The `mkdocs` script is mostly 1-1 with this workflow, but this workflow will also allow us to do off-cycle docs releases without releasing javadocs (which may contain docs for new code not officially release yet)
- There are two flags that can be toggled: `javadocs` and `release`L
- `javadoc`: whether to build javadocs as part of the workflow
- `release`: whether to release the artifacts as part of the workflow
- One potential use case of toggling release off is to generate docs for PRs, so that we can see the rendered docs instead of a diff view
- Tested in personal fork of smithy
- Ran workflow by hand with each flag combo (javadoc, release, javadoc + release)
- Triggered workflow by creating a new …

Add docs-publishing workflow

---

README.md
docs/source-2.0/conf.py

* Adds a banner to smithy Docs site with a link to a customer survey for smithy 
* Adds a link to the survey to the README.md
NOTE: We plan to keep this banner up for one month and after that period, revert this commit to remove the banner.
[Document Artifact link](https://github.com/smithy-lang/smithy/actions/runs/7980085314/artifacts/1260924812)
---

Add survey banner

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ApplyMixin.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMemberUtils.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/StructureShapeTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/mixins/multiple-inheritance-with-introduction.smithy

Fixes two bugs regarding member shapes that have multiple mixins:
1. Fixes a bug where mixed members that also applied local traits would drop all but the last mixin from their list of mixins.
2. Fixes a bug where shape constructors attempting to fix missing mixins from member mixin lists would drop all but the last mixin from the list.
Correctness is a virtue.
The specific customer case was tested manually, unit tests derived from that were added.
* Issue #, if applicable (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for a list of keywords …

Fix member mixin lists

---

smithy-cli/build.gradle

- gradle file got mangled in the process of #2134 
- adds back the mistakenly removed section for cli integ task
- `./gradlew :smithy-cli:integ`
---

Fix mistakenly removed section in smithy-cli gradle build

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/inferred-io/default.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/inferred-io/main.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/inferred-io/mixed.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/inferred-io/shared.smithy

This updates the IDL serializer to be able to optionally determine if the operations in a given file all have inputs / outputs that share suffixes, and then use that to enable inlining operation IO during serialization.

Infer default inline io suffixes

---

docs/source-2.0/guides/model-translations/converting-to-openapi.rst
docs/source-2.0/quickstart.rst

Updates the `Converting Smithy to OpenAPI` guide to: 
1. Use the new 0.10.0+ gradle plugins
2. Have both kotlin and groovy examples
3. Include CLI examples alongside the gradle examples
* See: [Docs artifact download link](https://github.com/smithy-lang/smithy/actions/runs/8052578578/artifacts/1275918903)
---

Update openApi guide to use new gradle plugin and cli

---

docs/source-2.0/guides/model-translations/generating-cloudformation-resources.rst

* Update the `Generating CloudFormation Resource Schemas from Smithy`: 
1.  Update Gradle examples to use new plugin version
2. Add kotlin and groovy versions of gradle examples.
3. Add CLI examples
* [Generated docs](https://github.com/smithy-lang/smithy/actions/runs/8053548585/artifacts/1276161112)
---

Update cloudformation guide to use updated plugins and cli

---

docs/source-2.0/quickstart.rst

Updates the Quickstart guide for the Smithy.io site to use the terse `:=` "walrus" operator syntax and elision syntax where appropriate. Also applies smithy format to all examples
* [Doc artifact link](https://github.com/smithy-lang/smithy/actions/runs/8054397682/artifacts/1276355214)
---

Update quickstart example to use terse input/output syntax

---

docs/conf.py
docs/source-2.0/guides/gradle-plugin/gradle-migration-guide.rst
docs/source-2.0/guides/gradle-plugin/index.rst
docs/source-2.0/guides/model-translations/converting-to-openapi.rst
docs/source-2.0/guides/model-translations/generating-cloudformation-resources.rst
docs/source-2.0/quickstart.rst

* Uses a placeholder, `__smithy_gradle_version__`, in docs instead of a static value so the docs stay up to date with the latest gradle plugin releases.
* The placeholder is replaced with the latest tagged version in the gradle plugin repo.
* Built docs locally with `make html`
* [Docs build link](https://github.com/smithy-lang/smithy/actions/runs/8055439080/artifacts/1276630495)
---

Use placeholder instead of static gradle plugin version

---

smithy-aws-protocol-tests/model/restXml/services/s3.smithy

Adds test to enforce S3 URI resolution behavior when dealing with object keys that contain dot segments. 
https://nvd.nist.gov/vuln/detail/CVE-2023-51651
---

Add s3 dot segment protocol tests

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/InitCommand.java

* Trying to fix issue with windows CI.
* See integ tests
* Previous failure: https://github.com/smithy-lang/smithy/actions/runs/8084081393/job/22090560577?pr=2168
---

Remove no-cone on add in init command

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeVisitor.java

* While working on trait codegen (see: https://github.com/smithy-lang/smithy/pull/2074) I have encountered quite a few cases where generators need to visit all data shapes types, but should fail on service shapes (resource, operation, service). This PR adds a new abstract class to provide this behavior as a common abstract class. 
* N/A 
---

Add data-shape-only visitor class

---

docs/conf.py
docs/source-2.0/guides/gradle-plugin/index.rst
docs/source-2.0/guides/using-code-generation/generating-a-client.rst

* Adds a placeholder, `__smithy_typescript_version__` for the smithy typescript code generator version. 
* The version number is determined by querying the latest version of the `smithy-typescript-codegen` package from Maven.
* This will keep the typescript version up to date without any additional action beyond just releasing the docs.
* local docs build
* [Doc artifact link](https://github.com/smithy-lang/smithy/actions/runs/8206427849/artifacts/1309960389)
---

Add placeholder for typescript versions

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/PartitionSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/StandardRegionalEndpointsTrait.java
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/StandardRegionalEndpointsTraitTest.java

Fixes multiple issues serializing the `@standardRegionalEndpoints` trait.
If not fixed, serializing this trait may include incorrect values.
Added a test case.
---

Fix creating @standardRegionalEndpoints nodes

---

.github/workflows/update-gradle-plugin.yml
gradle.properties
smithy-aws-protocol-tests/build.gradle
smithy-validation-model/build.gradle
smithy-validation-model/model/smithy.framework.validation.smithy

* Updates the protocol test and validation model packages to use the updated gradle plugins. 
* Adds a new workflow to automatically check for updates to the gradle plugin and update the plugin if the main repo is behind.
* Commits the formatter changes applied by the plugin to the validation model.
* N/A
* The periodic auto-update workflow is copied from the workflow used in the examples repo: https://github.com/smithy-lang/smithy-examples/blob/main/.github/workflows/update-smithy-gradle-plugin-version.yml
---

Use new gradle plugins for validation model and protocol tests

---

smithy-aws-protocol-tests/build.gradle
smithy-validation-model/build.gradle

* Corrects an issue introduced in PR: https://github.com/smithy-lang/smithy/pull/2176
* Gradle requires an explicit dependency on `smithyJarStaging` for the publish task. Before this commit the following error was encountered when running `./gradlew publishToMavenLocal`:
```
* What went wrong:
A problem was found with the configuration of task ':smithy-aws-protocol-tests:sourcesJar' (type 'Jar').
- Gradle detected a problem with the following location: '/Users/example/code/smithy/smithy-aws-protocol-tests/build/tmp/staging-smithyJarStaging'.
Reason: Task ':smithy-aws-protocol-tests:sourcesJar' uses this output of task ':smithy-aws-protocol-tests:smithyJarStaging' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what …
```

Fix gradle dependency error for publishing to maven local

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-protocol-traits/src/main/resources/META-INF/smithy/smithy.protocols.rpcv2.smithy
smithy-protocol-traits/src/test/resources/software/amazon/smithy/protocol/traits/errorfiles/no-document-support.errors
smithy-protocol-traits/src/test/resources/software/amazon/smithy/protocol/traits/errorfiles/no-document-support.smithy

Disallow `document` types in RPCv2 services per spec.
To enforce the protocol's requirements on services using it.
New test files.
---

Add no document types validation to rpcv2Cbor

---

docs/source-2.0/aws/protocols/aws-json.rst.template

Remove an incorrect line about `@jsonName` support in `awsJson` protocols.
Consistency of specification
Built docs locally.
#1026 
---

Remove incorrect jsonName protocol info

---

smithy-aws-protocol-tests/model/rpcV2/cbor-lists.smithy
smithy-aws-protocol-tests/model/rpcV2/cbor-maps.smithy
smithy-aws-protocol-tests/model/rpcV2/cbor-structs.smithy
smithy-aws-protocol-tests/model/rpcV2/empty-input-output.smithy
smithy-aws-protocol-tests/model/rpcV2/errors.smithy
smithy-aws-protocol-tests/model/rpcV2/fractional-seconds.smithy
smithy-aws-protocol-tests/model/rpcV2/main.smithy

1. Fix tests where the CBOR-encoded body doesn't match the JSON 'params' key.  
2. Add tests for default values.  
3. Add missing headers in tests.  
4. Add tests for indefinite-length text and byte strings.  
5. Add tests for structures encoded with definite-length maps.

Add default test, fix missing headers and body/params conflict

---

smithy-aws-protocol-tests/model/ec2Query/input.smithy

Bring `@ec2QueryName` trait usage in line with real use.
The discrepancies cause issues when integrating.
Ran tests in aws-js-sdk-v3.
---

Update ec2QueryName tests to reflect usage

---

smithy-aws-protocol-tests/model/rpcV2/defaults.smithy

Timestamp tags were missing in the encoded CBOR body and have now been added.

Fix timestamp encoding used in default value tests

---

smithy-aws-protocol-tests/model/awsJson1_0/unions.smithy

Servers are allowed (but not recommended) to send `"key": null` for unset fields in unions. However, this behavior was not covered by protocol tests.
These tests were dry-run on the Rust SDK.
* https://github.com/awslabs/aws-sdk-rust/issues/1095
---

Protocol test for `: null` values in unions

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

The structure `TraitValidator` was added in #2156 was marked as `@internal` but it needs to be marked as `@private` otherwise it gets included in some projections.
Tested locally by verifying this the structure is not longer included in my projections.
---

Fix `TraitValidator` scope, it should be `@private` not `@internal`

---

docs/source-2.0/guides/using-code-generation/generating-a-client.rst

closes: https://github.com/smithy-lang/smithy/pull/2193
* The `Generating a Client` only has yarn workspacees set up assuming the reader is using Gradle, but the rest of the guide uses both CLI and Gradle
* This PR updates the guide to include versions for both Gradle and CLI.
* Built and viewed documentation site changes locally.
[Built artifact link](https://github.com/smithy-lang/smithy/actions/runs/8365028445/artifacts/1343964141)
Issue first brought up here: https://github.com/smithy-lang/smithy/pull/2193
---

Update Generating a Client guide  yarn workspaces

---

smithy-aws-protocol-tests/model/rpcV2/cbor-structs.smithy
smithy-aws-protocol-tests/model/rpcV2/defaults.smithy

There was a bug in the encoding of the following data types in the default value tests:
1. defaultFloats should have been encoded using 4 bytes.
2. defaultBlobs should have been encoded as byte strings.
Additionally, extra fields and two more client tests have been ported from AWS_JSON.

Fix encoded floats to be 4 bytes. Add clientOptionalTest

---

smithy-aws-protocol-tests/model/rpcV2/cbor-maps.smithy

. Adds `ValidationException` to `RpcV2CborSparseMaps` because of member shape `SparseSetMap`
. `smithy-rs` raises an error otherwise.
- Local test using `smithy-rs` implementation.

Add ValidationException to RpcV2CborSparseMaps

---

build.gradle

* While executing 1.46.0 release, issues were encountered when staging JARS:
```
Execution failed for task ':smithy-cli:publishMavenJavaPublicationToMavenLocal'.
> Failed to publish publication 'mavenJava' to repository 'mavenLocal'
> Invalid publication 'mavenJava': artifact file does not exist: '/Users/sugmanue/Sources/smithy/smithy-cli/build/libs/smithy-cli-1.46.0-all.jar'
```
* Tracked it down to bug fixes in latest version of `shadow`, where `-all` is the expected suffix …

Downgrade shadow dependency to fix staging command

---

.github/workflows/make-docs.yml

The latest automated release run of this workflow failed because a few off-cycle docs updates were done: https://github.com/smithy-lang/smithy/actions/runs/8394668276
We should pull the changes, copy the docs, and then push.
---

Update make-docs to pull before pushing

---

docs/source-1.0/spec/http-protocol-compliance-tests.rst
docs/source-2.0/additional-specs/http-protocol-compliance-tests.rst

Update docs for the usage of the `params` member in HTTP compliance test traits.
To clarify usage for clients and servers.
Build and review docs.
---

Clarify HTTP compliance test params field

---

smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
smithy-aws-protocol-tests/model/awsJson1_1/null.smithy
smithy-aws-protocol-tests/model/restJson1/json-lists.smithy
smithy-aws-protocol-tests/model/restJson1/json-maps.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

Create new operations in protocol tests for sparse tests.
Makes it easier to support sparse vs dense collections when working with protocols.
Ran generated tests in AWS SDK for JSv3
---

Split sparse collection tests to new operations

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderShapeMap.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

Found this when working on the language server - if you have a model like:
```
$version: "2"
namespace com.foo
string Foo
@mixin
structure Bar {}
structure Baz with [Unknown] {}
```
loading it will result in `Foo` and `Bar` also not being loaded. It seems like the reason for this was that if TopologicalShapeSort failed, we wouldn't build _any_ shapes into the model, despite TopologicalShapeSort being able to resolve some shapes.
Practically speaking I'm not sure if this means much in general, but for the language server its big because without it, you can't have mixin completions unless you either don't reload the model on changes (which means you can't type a mixin, then get completions to use it), or don't update the server's version of the model if the new version is broken (which …

Load other shapes when a mixin can't be resolved

---

smithy-cli/build.gradle

- For the next release (1.47.0), we should set dry-run to be enabled for the cli config, so that it does not try to do an actual release
- The other change is needed so that JReleaser runs _after_ the image zips are created
---

Update smithy-cli jreleaser distribution to depend on runtimeZip

---

docs/conf.py

Noticed on https://smithy.io/2.0/guides/gradle-plugin/index.html that the version of gradle plugin is `0.20.0`. Was expecting to see the new `1.0.0` or even the older `0.10.0` but `0.20.0` meant something is quite wrong. Found that we had a typo in the docs/conf.py
```
make install
make html
open build/html/2.0/index.html
```
to see the new expected output.
---

Fix gradle plugin version in docs

---

docs/source-2.0/guides/gradle-plugin/index.rst

Guide is now for 0.10.0, so caption needs update to match
```
make install
make html
open build/html/2.0/index.html
```
to see the expected output
---

[docs] Update caption for gradle migration guide to 0.10.0

---

docs/source-2.0/spec/json-ast.rst

Fix minor typos in JSON AST docs

JSON AST docs missing commas

---

smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/simple-service-aws.cfn.json
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/DeprecatedTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/DeprecatedTraitTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java

The objective is to add `@deprecated` to the description of the definition in OpenAPI.
Let me know if this makes sense or if the way the description is built makes sense.
Added a couple of tests.

Use `@deprecated` info when building OpenAPI description

---

smithy-aws-protocol-tests/model/restXml/document-maps.smithy

Adds a protocol test for the restXml protocol for unmarshalling a response that contains a nested xml map with the `@xmlName `trait applied to both key and value pairs
While implementing other protocol tests we realized that this was a gap in our generator, but it was hard to fix without an existing protocol test. This drives TDD for us.
```
./gradlew :smithy-aws-protocol-tests:build 
PS C:\Dev\Repos\smithy-fork> ./gradlew :smithy-aws-protocol-tests:build
Picked up JAVA_TOOL_OPTIONS: -Dlog4j2.formatMsgNoLookups=true
> Configure project :
Smithy version: '1.47.0'
> Task :smithy-validation-model:smithyFormat
Running smithy format
> Task :smithy-aws-protocol-tests:smithyBuild
Running smithy build …
```

Nested xml map with xml name

---

smithy-protocol-tests/model/rpcv2Cbor/cbor-lists.smithy
smithy-protocol-tests/model/rpcv2Cbor/cbor-maps.smithy
smithy-protocol-tests/model/rpcv2Cbor/cbor-structs.smithy
smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy
smithy-protocol-tests/model/rpcv2Cbor/empty-input-output.smithy

1. Add Content-Length expectation for requests with bodies
2. Remove Accept headers from authoritative tests
---

Fix issues with RPCv2 CBOR protocol tests

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Property.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TypedPropertiesBag.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolTest.java

Adds a strongly typed Key to the typed properties bag used by Symbols in codegen. These changes are intended to improve the experience of using Symbol properties in code generators. Usage of these new typed properties would look like: 
```java
Property<String> myStringProperty = Property.named("string property"); 
Symbol symbol = Symbol.builder()
.name("foo")
.putProperty(myStringProperty, "foo")
.build()
String result = symbol.expectProperty(myStringProperty);
```
Added new unit tests
---

Add typed properties for TypedPropertiesBag

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/trait-modified-all-severities-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/trait-modified-all-severities-b.smithy

Fix ModifiedTrait for traits with breaking change rules.
Before this change, if a trait had breaking change rules defined, the diff strategy in ModifiedTrait would eventually resolve the trait as unknown and produce a ModifiedTrait warning on any change.
- Missing registering traits with breaking change rules: https://github.com/smithy-lang/smithy/blob/7c6228f351d85dab343af614181bbaa41893737e/smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java#L148-L151
- Results in treating traits with breaking change rules as unknown and warn on any change: https://github.com/smithy-lang/smithy/blob/7c6228f351d85dab343af614181bbaa41893737e/smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java#L117-L119
Tested with `@jsonName`:
Model A: …

Fix ModifiedTrait for traits with breaking change rules

---

smithy-diff/src/main/java/software/amazon/smithy/diff/testrunner/SmithyDiffTestCase.java
smithy-diff/src/main/java/software/amazon/smithy/diff/testrunner/SmithyDiffTestSuite.java
smithy-diff/src/test/java/software/amazon/smithy/diff/DiffTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/testrunner/SmithyDiffTestCaseTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/testrunner/SmithyDiffTestSuiteTest.java
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/jsonName/change-jsonName-value.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/jsonName/change-jsonName-value.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/jsonName/change-jsonName-value.events
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/tags/change-tags-content.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/tags/change-tags-content.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/diffs/tags/change-tags-content.events
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/diff1.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/diff1.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/diff2.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/diff2.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/nested/diff3.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/nested/diff3.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/invalid/nested/diff3.events
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/diff1.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/diff1.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/diff2.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/diff2.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/diff2.events
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/nested/diff3.a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/nested/diff3.b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/testrunner/testrunner/valid/nested/diff3.events

Add Smithy Diff test runner.
This is strongly based on [`SmithyTestSuite`](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestSuite.java) and [`SmithyTestCase`](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCase.java).
Also adds example diff tests (`change-jsonName-value`, `change-tags-content`).
Added unit tests and example diff tests.
---

Add Smithy Diff test runner

---

smithy-aws-protocol-tests/model/ec2Query/input-lists.smithy

Revert EC2 Query Protocol empty list serialization.
Empty lists are NOT serialized for the EC2 query protocol, which differs from the AWS query protocol.
See "EmptyQueryLists" for the AWS query protocol equivalent test case.
This is needed since SDKs that conform to the broken protocol tests will send invalid requests to EC2.
Tested with aws-sdk-js-v3 locally ([smithy-typescript](https://github.com/syall/smithy-typescript/tree/temp-fork), [aws-sdk-js-v3](https://github.com/syall/aws-sdk-js-v3/tree/temp-fork)) sending a previously failing command with the error `InvalidRequest: The request received was invalid.` now with the correct validation error.
```javascript
const { EC2Client: Client, DescribeKeyPairsCommand: Command } = require("@aws-sdk/client-ec2");
(async () => {
const client = …
```

Revert EC2 Query Protocol empty list serialization

---

smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/LoadsFromModelTest.java
smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/defaults/defaults.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenUtils.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/BuilderGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/ConstructorGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/FromNodeGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/GetterGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/ToNodeGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/defaults/defaults.smithy
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest

Adds support for defaults on trait member values. 
Applying the `@default` trait to a member will cause it to be treated as non-nullable and will set the value as the initial value for the member within the shape's builder.  
A new set of integration tests were added to ensure the defaults for all types of members are set on a structure shape with no value for those default members.
---

Add support for default trait on members

---

docs/source-2.0/spec/model.rst

Updates the table in https://smithy.io/2.0/spec/model.html#shape-types for Aggregate types to use the casing of the actual shape names, like `list` instead of `List`. 
Note, this doesn't change the heading on the page https://smithy.io/2.0/spec/aggregate-types.html#list which is still `List`. We could consider changing the headings to match the shape name too, like for [simple types](https://smithy.io/2.0/spec/simple-types.html), though we use uppercase for [service types](https://smithy.io/2.0/spec/service-types.html). Additional to this PR, if we want to change the headings to match the shape name, can do that separately.
```
cd docs
make install
make html
open build/html/2.0/index.html
```
Ran above and verified table has lower case in type column.
* Links to additional context, if …

Use correct case for aggregate shapes in table

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateListDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateMapDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/directed/directed-model.smithy

This adds lists and maps to directed codegen. This is needed because when generating Python code there needs to be some data generated for lists and maps that must be placed in topological ordering as much as is possible.
While technically possible to generate that information without it being in topological ordering, the workarounds are *extremely* unfortunate.
---

Add maps and lists to directed codegen

---

smithy-aws-protocol-tests/model/restXml/errors.smithy

* Change the http status code from 400 to 403 as specified by the [httpError trait on the error shape](https://github.com/smithy-lang/smithy/blob/main/smithy-aws-protocol-tests/model/restXml/errors.smithy#L84).
* Local build
* The [smithy docs for restXml](https://smithy.io/2.0/aws/protocols/aws-restxml-protocol.html#supported-traits) includes httpError in the list of supported traits.
---

Fix http status code in restXml response protocol test

---

docs/source-2.0/additional-specs/protocols/smithy-rpc-v2.rst

Fix typos in RPCv2 CBOR spec

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/FixBadDocComments.java
smithy-syntax/src/test/java/software/amazon/smithy/syntax/ParseAndFormatTest.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/fixes-invalid-doc-comments.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/fixes-invalid-doc-comments.smithy

- Fixes an issue where a doc-comment above a trait-statement and member may get converted to a line-comment
- Updates the expected formatting of test case file (`.formatted.smithy`)
- Updates tests to use `assertEquals`, since it provides diff functionality in IDEs
- Caveat:
- A trailing doc-comment won't get converted to a line-comment
- TODO was added to handle this case, if it is possible 
- Ran the tests, no failures
---

Fix formatter to correctly convert invalid doc comments

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/BracketFormatter.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/FormatVisitor.java
smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeCursor.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/operation-errors-comments.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/operation-errors-comments.smithy

For operation errors like:
```
errors // foo
: // bar
[
// baz
MyError
]
```
you'd expect formatting of:
```
// foo
// bar
errors: [
// baz
MyError
]
```
Prior to this commit, we were handling the cases of `foo` and `bar`, but inadvertently doing the same thing for `baz`. This is because we were looking for comments to pull out to above `errors` in the direct children of OPERATION_ERRORS, which include all WS within the `[]`.
To make it work as expected, we need to only pull out comments in the first two positions (`foo`, `bar`), and leave the rest for BracketFormatter to format. BracketFormatter was expecting to operate on all the children of a given TreeCursor, so I modified it to act on an arbitrary stream of cursors, and added a way to get all remaining siblings after a cursor.
* …

Fix formatting comments in operation errors list

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java

* Adds a hierarchical subpart of ".Appended.[index]" for enum additions at the end of the list
unit tests
---

Add .Appended id subparts to enum additions

---

docs/source-2.0/aws/aws-iam.rst

Besides missing imports, `aws.iam#conditionKeyValue` was referring to an
undefined condition key.
Error if you build the current model:
```
Shape: smithy.example#OperationAInput$key
File:  /home/ANT.AMAZON.COM/davidpz/code/smithy-rs-main/codegen-server-test/../codegen-core/common-test-models/simple.smithy:22:9
19| @conditionKeys(["myservice:ActionContextKey1"])
20| operation OperationA {
21|     input := {
22|         @conditionKeyValue("ActionContextKey1")
|         ^
This operation `smithy.example#OperationA` scoped within the
`smithy.example#MyService` service with member
`smithy.example#OperationAInput$key` refers to an undefined condition key
`ActionContextKey1`. Expected one of the following defined condition keys:
[`myservice:ActionContextKey1`]
```
--- …

Fix docs for `aws.iam#serviceResolvedConditionKeys` and `aws.iam#conditionKeyValue`

---

docs/source-1.0/spec/aws/aws-json.rst.template
docs/source-1.0/spec/aws/aws-query-serialization.rst.template
docs/source-1.0/spec/core/http-traits.rst
docs/source-1.0/spec/core/model.rst
docs/source-1.0/spec/core/protocol-traits.rst
docs/source-2.0/additional-specs/protocols/smithy-rpc-v2.rst
docs/source-2.0/aws/protocols/aws-json.rst.template
docs/source-2.0/spec/behavior-traits.rst
docs/source-2.0/spec/http-bindings.rst
docs/source-2.0/spec/protocol-traits.rst
docs/source-2.0/spec/service-types.rst
smithy-model/src/main/java/software/amazon/smithy/model/pattern/UriPattern.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampFormatPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpHeaderTraitValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpMethodSemanticsValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-header-tchar-validator.errors
smithy-utils/src/main/java/software/amazon/smithy/utils/MediaType.java

The HTTP RFCs have received some facelifts recently. The vast majority of the HTTP spec is now collected in [RFC 9110](https://datatracker.ietf.org/doc/html/rfc9110) with version-specific information broken out into their own RFCs (HTTP 1.1 is in [RFC 9112](https://datatracker.ietf.org/doc/html/rfc9112) for example).
This PR updates any references we have to RFCs obsoleted by RFC 9110 and RFC 9112 to those newer RFCs. The semantic content of these sections has not changed, only the presentation.
---

Replace outdated RFC references

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/analysis/OperationContextParamsChecker.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/OperationContextParamsTraitValidator.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/validators/RuleSetParameterValidator.java
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/inconsistent-params.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/inconsistent-params.smithy

#2266 added support for the new `operationContextParams` trait, but missed adding support for it to the `RulesetParameterValidator`.   Rulesets that bound a parameter to the service model only through an `operationContextParameter` would trigger validation errors that Parameter "exists in ruleset but not in service model".    In addition, type checking for inconsistent parameters and type mismatches between `operationContextParams` and the bound endpoint parameter were not being done.
*New and existing tests
* See: #2266
---

Add operationContextParams to RulesetParameterValidator

---

smithy-aws-protocol-tests/model/awsJson1_0/content-type.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_1/content-type.smithy
smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
smithy-aws-protocol-tests/model/restJson1/content-type.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/content-type.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

This change adds tests to document/enforce how the Content-Type headers should be handled by servers. They are important to ensure that clients get the same experience regardless of which language the server is written in.
These are being added as smithy-rs was rejecting requests with parameters added to the Content-Type header, but the customer's existing requests were being accepted by existing servers.
* ./gradlew check
* did some local testing in smithy-rs; also had similar tests there (which these will replace): https://github.com/smithy-lang/smithy-rs/pull/3576
* Smithy-rs issue: https://github.com/smithy-lang/smithy-rs/issues/3471
---

Add protocol tests for Content-Type params

---

docs/source-2.0/additional-specs/protocols/smithy-rpc-v2.rst

Clarify when an `Accept` header is needed for Smithy RPCv2 response event streams.
---

Clarify RPCv2 response event stream behavior

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExamplesTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-service-errors.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-service-errors.smithy

This commit enables validating error examples for operations with errors that are bound to services. All services the operation with said example are bound to must bind the error.
Fixes #2299 
---

Allow examples for service level errors

---

smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestDefinition.java
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-malformed-request-features.smithy

This commit adds the bodyMediaType field to request definitions in httpMalformedRequestsTests. Specifying the body media type allows tests to specify protocols that use binary-based serialization formats, like Smithy RPCv2 CBOR, as their bodies must be base64-encoded in models.
Resolves #1932 
---

Add bodyMediaType to malformed request tests

---

docs/source-2.0/spec/http-bindings.rst

Clarify httpResponseCode value range

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-content-type.smithy

The suite already contains a test with ID
`RestJsonWithBodyExpectsApplicationJsonContentType` for when `Content-Type:
aplication/json` is expected by the server but the client sends a wrong value
for the header. However, there is no test testing the case where the client
sends no headers. This commit adds such a test.
* Ran the test in smithy-rs server.
---

Add protocol test for when content-type must be set but no headers are sent

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/coerced-io/after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/coerced-io/before.smithy

This commit adds a new IDL serializer configuration, coerceInlineIo, that will use inline IO to write input and output shapes that are only bound to one operation - even if they don't have the input or output trait applied.
It also fixes a bug where an empty newline was written before empty inline IO shape definitions.
---

Add IDL serializer option to coerce inline IO

---

smithy-protocol-tests/model/rpcv2Cbor/cbor-maps.smithy

A cbor protocol test appears to have an extraneous value in its result matcher.
The description says "Clients SHOULD tolerate seeing a null value in a dense map, and they SHOULD drop the null key-value pair." This means the expected `params.denseSetMap` should not retain the null value present in the base64 payload.
Tested this change while building Smithy RPCv2 CBOR for TypeScript - https://github.com/smithy-lang/smithy-typescript/pull/1280

test(cbor): remove map null value in test assertion

---

smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy

The previous body did not include the top level "default" member and decoded to: 
```
{
"defaultString"=>"hi", 
"defaultBoolean"=>true, 
"defaultList"=>[],
}
```
This adds in the top level "default" so the new body decodes as:
```
{
"defaults"=>{
"defaultString"=>"hi", 
"defaultBoolean"=>true, 
"defaultList"=>[],
}
}
```
* Tested with smithy-ruby RPCV2 implementation.
---

Fix body of RpcV2CborClientPopulatesDefaultValuesInInput protocol test

---

smithy-protocol-tests/model/rpcv2Cbor/cbor-structs.smithy

Some protocol tests were using the value `7.624` for a member shape of float type. However, this value does not align exactly with the IEEE floating-point representation and may lead to ambiguity in implementations when confirming serialization or deserialization correctness.
The tests have been updated to use `7.625`, which can be precisely represented in IEEE format.

Update Value to Exact IEEE Floating Point Representation

---

smithy-aws-protocol-tests/model/restJson1/http-string-payload.smithy
smithy-aws-protocol-tests/model/restXml/http-string-payload.smithy

As per the specs for these protocols, a `Content-Type` header should be
set. Servers should reject requests when an expected `Content-Type`
header is not found (protocol tests for that are added in #2314).
- https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html#content-type
- https://smithy.io/2.0/aws/protocols/aws-restxml-protocol.html#content-type
Ran tests in smithy-rs.
---

Add missing `Content-Type` headers to `@httpPayload` protocol tests

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/WriterDelegator.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/WriterDelegatorTest.java

This adds a method to the `WriterDelegator` to check out a writer from a symbol. This saves on a good amount of space when writing opening files to write, for example, private helper functions that are defined as symbols attached to shape symbols via properties.
---

Add useSymbolWriter function

---

smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restJson1/http-string-payload.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/http-string-payload.smithy

Add protocol tests relating to `Content-Type` and `@httpPayload`
Initial motivation for this stems off #2310, but for when the input is
`@httpPayload`-bound. It's important that we test `Content-Type`
specifically with `@httpPayload` operations, because the header can be
checked without having to inspect the body, and because the spec has
special provisions
(https://smithy.io/2.0/aws/protocols/aws-restjson1-protocol.html#content-type).
There were no protocol tests exercising `Content-Type` when the input is
`@httpPayload`-bound:
- In the case of blobs, servers must accept any (test already exists)
and no `Content-Type` (test added in this commit).
- In other cases, there were protocol tests for `union` and `structure`
shapes. I've added an operation with an `@httpPayload`-bound string …

Add protocol tests relating to `Content-Type` and `@httpPayload`

---

smithy-aws-protocol-tests/model/restJson1/http-content-type.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

- Requests should not have the content-type header added when there is no input shape (and therefore no payload)
- This doesn't appear to be a case in the aws sdk (operations with no input), but could be in generic clients 
- Tested by running protocol tests in the typescript sdk
- Related to https://github.com/smithy-lang/smithy-typescript/pull/1304
---

Add restJson1 protocol test for content-type and operation with no input

---

docs/source-2.0/aws/protocols/aws-ec2-query-protocol.rst
smithy-aws-protocol-tests/model/ec2Query/datetime-offsets.smithy
smithy-aws-protocol-tests/model/ec2Query/empty-input-output.smithy
smithy-aws-protocol-tests/model/ec2Query/fractional-seconds.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-errors.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy

Aligns with EC2 specs:
* Success: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CopyImage.html#API_CopyImage_Examples
* Error: https://docs.aws.amazon.com/AWSEC2/latest/APIReference/errors-overview.html#api-error-response
---

Fix ec2Query request ID names

---

build.gradle
smithy-cli/build.gradle

- We have two JReleaser configurations: one for main smithy releases, and one for releasing the CLI itself
- Currently, when running a release, both configurations are used and therefore both releases happen concurrently
- When something goes wrong, it can be difficult to track down the issue, since the logs for each release become intertwined
- By adding a property to control which configuration to apply, we can easily switch between main releases and CLI releases
- We can also remove the stale configuration from the old way of releasing using `nexus-staging` 
- Also, update to latest version of JReleaser (`1.12.0`)
- To verify configurations, you can run with `--dry-run` to see the task order:
- Do not set a property
- JReleaser is not configured
- Set main: `./gradlew jreleaserConfig …

Add properties for controlling JReleaser configurations

---

smithy-aws-protocol-tests/model/restJson1/json-lists.smithy
smithy-aws-protocol-tests/model/shared-types.smithy

Adds a list of sparse shorts to existing sparse list tests
In some languages, like Java, Strings are naturally nullable and thus handling sparse collections of String values is straightforward, but sparse collection of values with primitives (such as shorts) may introduce complexities.
Ran these tests to verify that serde in a language implementation was broken, and then fixed the implementation and verified that tests pass.
---

Add protocol tests for sparse list primitives

---

smithy-aws-protocol-tests/model/restJson1/http-content-type.smithy

When a header is bound to a member, it should be set in both params and headers or in neither. Other empty blob tests do not set a Content-Type header.
Request deserialization tests will fail if they explicitly check the header binding.
I didn't!
---

Remove header from empty payload test

---

build.gradle
smithy-cli/build.gradle

- Currently, the CLI release is what creates and pushes a version tag, which is backwards
- This change makes it so that the tag is created and pushed as part of the main release instead
- If the tag already exists in the remote, this will (and should) fail
- Also, small change to the release title so that it is consistent with historical release titles
- Tested with personal fork
- Checked out 1.50.0 version bump commit, and ran a main-release
- Confirmed no release is created in GitHub and tag is created and pushed
---

Update JReleaser config to push version tag in main release

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-pattern.smithy

The test was attempted to be fixed as part of https://github.com/smithy-lang/smithy/issues/1506. None of the other
tests echo back the value that failed the regex.
Ran tests in smithy-rs.
---

Fix RestJsonMalformedPatternReDOSString test

---

docs/conf.py
docs/source-2.0/conf.py

- Adds a hiring announcement to the smithy.io site, which links to open positions
- We may revert the announcement color changes when we remove the banner
- Rendered the doc-site locally, screenshots of both light and dark themes are attached
Light
Dark

Add hiring announcement

---

.github/workflows/make-docs.yml

- When running this workflow, `cp -r` causes directories to be merged, instead of overwritten
- This means that files that get renamed or removed will not actually get deleted ([example](https://smithy.io/2.0/guides/gradle-plugin.html) - this shouldn't exist anymore ([stale source](https://github.com/smithy-lang/smithy/blob/gh-pages/2.0/guides/gradle-plugin.html)))
- The solution is to remove the checked-out doc directories first, and then move over doc-build artifacts
- `mv` cannot overwrite non-empty directories, so we have to delete them first
---

Update make-docs.yml to remove old docs first

---

smithy-aws-protocol-tests/model/restJson1/http-content-type.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

- Same as https://github.com/smithy-lang/smithy/pull/2322 but with a POST operation
- We should test both cases explicitly, since code-generation may have faulty assumptions (https://github.com/aws/aws-sdk-net/pull/3338)
---

Add restJson1 protocol test for content-type and POST operation with no input

---

docs/Makefile

MacOS and homebrew don't like installing global Python packages, so this solves that automatically.

Use venv when building docs

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/node/IntEnumPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/validation/node-validator.json

Adds a new plugin to validate intEnums in NodeValidationVisitor. Previously you could provide values outside of the allowed set without failing validation. IntEnum Shapes also qualify as Integer Shapes, so they will pass through the same validation as Integer Shapes in [`validateNaturalNumber()`](https://github.com/smithy-lang/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java#L228-L248) to make sure floats aren't provided.
Added test cases:
- two for valid values defined by the intEnum
- one for wrong shape
- one for a number with a floating point, similar to Integer tests
---

Add intEnum validation to NodeValidationVisitor

---

docs/Makefile
docs/requirements.txt

- We don't have a great doc-writing experience (lots of outdated tooling for rst/sphinx)
- This doesn't make it much better, but it does add incremental autobuild
- Making updates to a doc-file renders in ~2 seconds, making it easier to see your changes live
- run `make dev`, should install and run autobuild
- run `touch requirements.txt`, should re-run install and run autobuild
---

add doc autobuild and dev target

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/IdempotencyTokenIgnoredValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/idempotency-token-trait-ignored.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/idempotency-token-trait-ignored.smithy

Added a validator to warn on ignored use of @idempotencyToken trait. As per [spec](https://smithy.io/2.0/spec/behavior-traits.html#idempotencytoken-trait), 
> Only a single member of the input of an operation can be targeted by the idempotencyToken trait; only top-level structure members of the input of an operation are considered.
This validator warns when we find a member using the trait in a context where it will be ignored. We cannot ERROR here as the structures might be reused in valid and invalid context, thus we only warning about the context where it will be ignored.
* Issue #, if applicable (see …

Add validator to warn on ignored idempotency token trait

---

docs/source-2.0/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTraitValidator.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.smithy

This adds validation to [httpChecksum](https://smithy.io/2.0/aws/aws-core.html#aws-protocols-httpchecksum-trait) trait for response checksumming behavior. When configuring the trait for response checksumming, the list of checksum algorithms to consider must be provided. Else, the client behavior would have no algorithms to validate.
The [docs for response validation](https://smithy.io/2.0/aws/aws-core.html#http-response-checksums) say 
> A client MUST use the list of supported algorithms modeled in the responseAlgorithms property to look up the checksum(s) for which validation MUST be performed.
So, this list should not be empty.
Added tests for this case.
---

More httpChecksum trait validation for responses

---

docs/source-2.0/aws/aws-endpoints-region.rst
smithy-aws-endpoints/src/main/resources/META-INF/smithy/aws.endpoints.smithy

Expand AWS endpoint trait documentation

---

smithy-syntax/src/main/java/software/amazon/smithy/syntax/FormatVisitor.java
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/entity-shapes-line-break.formatted.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/entity-shapes-line-break.smithy
smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/entity-shapes.smithy

Updates the formatting logic to put the key-value pairs of the `identifiers` and `properties` fields of `resource` shapes on individual lines instead of combining them onto a single line
While the existing formatting works for simple single-identifier resources, resources with multiple identifiers quickly become unwieldy due to their identifiers being forced onto a single line.
For identifiers this is only an annoyance because most resources only have 1 or 2 identifiers.  For properties, this can easily get out of hand because resources will generally have many resources.  
For example, this is the current formatted version of a resource within a service I'm currently developing: 
```
resource FooBar {
identifiers: { fooId: FooId, FooBarId: FooBarId }
properties: { previousFooBarId: …
```

Put the KVPs of identifiers and properties fields of resource shapes on their own lines

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ApplyMixin.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderTraitMap.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/mixin-and-apply-model.smithy

On first load, via sources, there's a `DefineShape` `LoadOperation` with an `ApplyMixin` modifier. There's also a pending `@apply` statement in the `LoaderTraitMap`. When the source is assembled, that's fully resolved, the mixin is merged into the shape, then traits applied to mixed content are applied. This is a valid source model that has the trait applied to the mixed member.
The import is then broken out into `LoadOperation`s to be assembled. The shape's `LoadOperations` already exist in the map and a new `DefineShape` load operation is added that also has the `ApplyMixin` modifier. The first, already fully mixed applied and built - the second, unmixed and unapplied.
When we go to `applyTraitsToNonMixinsInShapeMap` on the import pass, we detect if any of the load operations that …

Fix multi-model, mixin member apply bug

---

smithy-cli/build.gradle

Adding this module is necessary to connect to Maven repositories that require elliptic curve ciphers, such as GitHub's package repository.
I can't really write a test for this, because we don't have any official GitHub package repository packages. Maybe we should? We've been asked for them, in snapshot form.
This adds around ~120kb to the bundle size.
Resolves #2370
---

Add the elliptic curve crypto module to jlink

---

.github/workflows/make-docs.yml

- The docs makefile was updated recently (https://github.com/smithy-lang/smithy/pull/2352), workflow needs to be updated to account for this 
---

Update make-docs.yml to use venv

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapper.java
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/DocumentationMapperTest.java
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapperTest.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/simple.smithy

Fix CFN handler permissions for noReplace resources

---

smithy-model/src/jmh/java/software/amazon/smithy/model/jmh/KnowledgeIndicies.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/BottomUpIndex.java

When doing some ad-hoc profiling on the language server using aws service models I noticed that BottomUpIndex was taking up a lot of CPU time. This was because it used selectors and PathFinder to determine the paths from resources/operations up to their enclosing service. Selectors are pretty slow in comparison to regular java code, and when the model is large with many services/operations, this index can take a while to compute. BottomUpIndex is used for validating `@cfnResource` (through CfnResourcePropertyValidator -> CfnResourceIndex), so anyone using this trait is paying this performance cost (in particular, SDK code generators).
To get a rough idea of how much faster this commit makes BottomUpIndex, I ran model validation using the cli on all aws service models with and without this …

Improve BottomUpIndex performance

---

docs/source-2.0/additional-specs/rules-engine/specification.rst

The existing docs are out of date and do not reflect the current process SDK's use to resolve authentication schemes and this has caused service team confusion.
* `make html`
---

Update Endpoint AuthScheme docs to reflect current auth resolution process

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/CfnConverter.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/AwsTagIndex.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/ServiceTaggingValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TagEnabledServiceValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TagResourcePropertyNameValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TagResourcePropertyTypeValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableResourceValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggingShapeUtils.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/tagging/AwsTagIndexTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/tagging-warnings.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/tagging/aws-tag-index-test-model.smithy

This commit fixes several groups of bugs in the AwsTagIndex:
1. The index did not handle nested resource shapes.
2. The index did not handle the put lifecycle operation.
3. The index did not account for the `apiConfig` property of the `@taggable` trait.
A full suite of tests was added to account for the index's behavior and validate its previous functionality along with fixes for the above.
The `getTagsMember` method was stabilized and made non-static.
Minor cleanup was done to other tagging related files.
---

Fix several bugs in AwsTagIndex

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTrait.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/HttpChecksumTraitTest.java

Update supported httpChecksum algorithms

---

docs/source-2.0/tutorials/full-stack-tutorial.rst

- Fixes typos, spelling mistakes, and grammatical errors in the tutorial
---

Fix small typos and grammatical errors in the full-stack-tutorial

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/validation/node-validator.json
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/invalid-static-null-param-value.errors

Previously, a NullNode could be provided as a required structure member without emitting a ValidationEvent. So an example test below would fail. 
```    @Test
public void nullRequiredStructureMember() {
ObjectNode structure = ObjectNode.builder()
.withMember("foo", Node.nullNode())
.build();
NodeValidationVisitor visitor = NodeValidationVisitor.builder()
.value(structure)
.model(MODEL)
.allowOptionalNull(true)
.build();
List<ValidationEvent> events = MODEL
.expectShape(ShapeId.from("ns.foo#Structure"))
.accept(visitor);
assertThat(events, hasSize(1));
assertThat(events.get(0).getMessage(), containsString(
"foo: Required member `foo` for structure ns.foo#Structure for cannot be null"));
}
ns.foo#Structure schema:
"ns.foo#Structure": {
"type": "structure",
"members": {
"foo": {
"target": …
```

Add validation for null members in structures, lists and maps

---

docs/source-2.0/aws/aws-core.rst

Fix httpChecksum algorithm list in spec

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/CreateDedicatedInputAndOutput.java

Downgrades two `info` log statements to `fine`. These log statements create a lot of noise for protocol test runners.
---

Downgrade noisy log statement

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/inferred-io/shared.smithy

This commit updates IDL serialization to use the most common suffix for serializing IDL models when inlining input/output shapes. Before this update, the first suffix encountered would be used, even if it was only used that one time.

Use most common suffix for IDL inline IO

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ServiceBoundResourceOperationValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-misbound-operations.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/detects-misbound-operations.smithy

This commit introduces a new validator that emits warnings when it detects operations that are bound directly to a service when a resource bound to that service may be a better match.

Add validator for service bound resoruce operations

---

smithy-aws-protocol-tests/build.gradle
smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-headers.smithy

* changes header serialization test assertions to include empty strings and lists, but still exclude null
* absence and emptiness of headers differ in meaning
Tested protocol-test codegen and test execution in smithy-typescript + aws-sdk-js-v3
https://github.com/smithy-lang/smithy-typescript/pull/1412

serialize empty strings and lists to headers in restXml and restJson1

---

smithy-aws-protocol-tests/model/restJson1/http-content-type.smithy
smithy-aws-protocol-tests/model/restJson1/http-string-payload.smithy
smithy-aws-protocol-tests/model/restXml/content-type.smithy

Fix several protocol test warnings

---

smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.smithy

Clarifying behavior for when `httpChecksum` trait is used with only `requestChecksumRequired=false`.
Added test case
---

Add test case for requestChecksumRequired=false

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/DeconflictingStrategy.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/DeconflictingStrategyTest.java

This commit updates the DeconflictingStrategy to scrub trait definitions from the model used to pre-compute JSON Schema pointers. These shapes wouldn't have made their way into converted schemas anyways, and existing behavior for non-computed pointers is maintained.
---

Fix JSON Schema pointer conflicts with trait definitions

---

docs/source-2.0/guides/model-translations/converting-to-openapi.rst
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/member-documentation.jsonschema.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/member-documentation.smithy
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test-members.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test-members.smithy

Addresses https://github.com/smithy-lang/smithy/issues/2400.
When a member targets a structure, it becomes a schema reference when converted to JSON Schema. Previously, we didn't add member docs to the converted object, possibly because earlier versions of open api or JSON Schema did not support it. Reading through [this issue](https://github.com/OAI/OpenAPI-Specification/issues/1514) the [OAI spec](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#reference-object), and the [JSON Schema Spec](https://json-schema.org/draft/2020-12/json-schema-core#section-8.2.3), it seems that OpenAPI 3.1 and JSON Schema 2020-12 support the `description` property alongside `$ref`. I wasn't able to find anything about whether it is supported in [JSON Schema …

Allow adding member docs to $ref

---

smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-prefix-headers.smithy

Update protocol tests to catch an issue where SDKs were not serializing empty headers 
Had an issue where calling S3 with metadata with an empty value caused SDKs to not serialize the value and not send the header. While #2403 addresses the general case of headers present but with no values, it wouldn't cover this scenario since S3 metadata headers are not modeled as [httpHeader](https://smithy.io/2.0/spec/http-bindings.html#httpheader-trait) but as [httpPrefixHeader](https://smithy.io/2.0/spec/http-bindings.html#httpprefixheaders-trait)
Generated tests on [smithy-go](https://github.com/aws/smithy-go) and ran the new tests on [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2/)
* Links to additional …

fix: update prefix header tests to allow for empty headers

---

docs/source-2.0/guides/building-codegen/overview-and-concepts.rst

On this page: https://smithy.io/2.0/guides/building-codegen/overview-and-concepts.html#design-documents , the link to smithy-rs design docs is broken and returns a 404. This PR fixes the link to correct docs.
For correct documentation.
Using the process documented at : https://github.com/smithy-lang/smithy/blob/main/docs/README.md
* Links to additional context, if necessary 
N/A 
N/A
---
By submitting this pull request, I confirm that my contribution is made under …

Fix broken link to smithy-rs design document in Code Gen documentation.

---

smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/LoadsFromModelTest.java
smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/enums/enum-list-member-trait.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/BuilderGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/FromNodeGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/enums/enum-list-member-trait.smithy
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest

Corrects 2 related bugs that were preventing enum list traits from being correctly generated: 
1. Added `this` to a number of builder setter values to avoid clashes 
2. Add  missing `fromNode` method to nested enums so that can correctly be created by array node consumer.
---

Fix trait codegen to support lists of enums

---

smithy-aws-protocol-tests/model/restXml/document-maps.smithy

Fix name of XML root nodes in tests

---

smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionResource.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ActionResources.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeyDefinition.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/DefineConditionKeysTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamActionTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTrait.java

This commit foremost fixes an issue where the toNode method on ActionResources does not function properly, omitting all values instead.
It also updates several type signatures for SmithyBuilder generic type responses to use the specific implementation of the interface.
It also includes an simplification of the createNode method for the defineConditionKeys trait.
-----

Fix several issues with IAM trait classes

---

smithy-aws-protocol-tests/model/shared-types.smithy
smithy-protocol-tests/model/shared-types.smithy

Consumers of this package using the `includeServices` transform may not also be running `removeUnusedShapes`, leaving behind operations that then trip this validation and cause an error. Lowering this to a warning still emits a message but doesn't block consumers until we find a better strategy for running this validation at Smithy-only build time.

Lower UnboundTestOperation to WARNING

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedMemberTarget.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedMemberTargetTest.java
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapkey1-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapkey1-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapkey2-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapkey2-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapvalue1-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapvalue1-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapvalue2-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested-mapvalue2-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested2-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested2-b.smithy

This commit updates the ChangedMemberTarget diff evaluator to properly check changes to map keys and values the same way it checks changes to list members.
-----

Improve member target diff checks for maps

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-headers.smithy

`NullAndEmptyHeaderClient` tests were [recently updated](https://github.com/smithy-lang/smithy/pull/2403) to expect empty headers to be serialized. Similar changes were not made for the server variants of those tests. This leads to an unexpected difference in serialization between servers and clients and prevents clients from receiving semantically meaningful headers from the server.
The test now align with the similar tests for clients. They expect empty headers to be serialized as "" and null headers to not be serialized
Confirmed that the same changes made for client header serialization in https://github.com/smithy-lang/smithy-rs/pull/3887 worked for the server tests as well.
* Links to additional …

Update `NullAndEmptyHeadersServer` tests for `restJson1` and `restXml`

---

smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceTrait.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/Handler.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/Property.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/partition/Partition.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/partition/PartitionOutputs.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/partition/RegionOverride.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/PartitionEndpointSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/PartitionSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/RegionSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/StandardPartitionalEndpointsTrait.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/StandardRegionalEndpointsTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientDiscoveredEndpointTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/AwsQueryErrorTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/node/ArrayNode.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumValueTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/RequestCompressionTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/EndpointTestOperationInput.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/ExpectedEndpoint.java
smithy-waiters/src/main/java/software/amazon/smithy/waiters/WaitableTrait.java
smithy-waiters/src/main/java/software/amazon/smithy/waiters/Waiter.java

This commit updates all instances where a generic SmithyBuilder<> was returned to return the specific implementing Builder. This means users of these methods can easily use the Builder's functionality without using a cast.
---

Return Builders instead of SmithyBuilders

---

smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-prefix-headers.smithy

HTTP headers are case-insensitive so using casing in prefix header tests adds unnecessary challenges when implementing rest-xml and rest-json protocol tests. Many HTTP implementations lowercase header names to make them case-insensitive (e.g., Go), and it's even a requirement of h2 (https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2).
This commit updates httpPrefixHeaders tests to use lowercase header names to avoid any kind of header casing issues when implementing these tests.
---

Use lowercase headers for prefix-header test

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/CfnConverter.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/weather-service-wide.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/weather.cfn.json

This value is expected to be a JSON pointer to a property, not just the name of the property.
See: https://github.com/aws-cloudformation/cloudformation-cli/blob/master/src/rpdk/core/data/schema/provider.definition.schema.v1.json#L193-L197
---

Fix for tagsProperty in CFN schema creation

---

smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy

The RPCv2 payloads previously used a text string (major 3) instead of a byte string (major 2) for blobs.

Use the correct CBOR type for blobs in RPCv2 CBOR protocol tests

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/CfnConverter.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/CoreExtension.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/HandlerPermissionMapper.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/TaggingMapper.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/Tagging.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/provider.definition.schema.v1.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/weather-service-wide.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/weather.cfn.json
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableResourceValidator.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/tagging-warnings.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/tagging-warnings.smithy

This commit updates the CFN resource schema generation to fill in the
permissions field of the tagging configuration for resources. The AwsTagIndex
is used to find the APIs and their relevant required actions to invoke.
This also refactors the Tagging updates into a single Mapper so the updates
aren't strewn about the general CfnConverter.
---

Inject tagging operation permissions for CFN

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/DeconflictingStrategy.java

Defers the `scrubTraitDefinitions` call inside JSON Schema deconflicting to happen only when the model is in a state that would have an avoidable conflict.
Resolves #2429 
---

Defer scrubTraitDefinitions for JsonSchema

---

docs/source-2.0/guides/model-translations/converting-to-openapi.rst
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/DefaultRefStrategy.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java

Resolves #2443 
This commit adds the `useInlineMaps` setting to allow users to configure JSON Schema conversion to inline converted `map` shapes instead of creating references.
This is distinct from the `mapStrategy` setting in that it's about the placement of the generated type and not how the type is generated. Combining the two would require two strategies for each type of map converted.
---

Add config for inline JSON Schema maps

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.smithy
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/DefineConditionKeysTraitTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/define-condition-keys.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/successful-condition-keys.smithy

This commit relaxes the pattern on the `@defineConditionKeys` trait's keys to enable inferring the `service` to be the service's `arnNamespace`.
---

Infer defined condition key service

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/FlattenPaginationInfo.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/FlattenPaginationInfoTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/flatten-pagination-before.smithy

Adds a transform that flattens service-level pagination info into pagination traits on operations. 
Code generators may want to use fully-resolved pagination traits for operations. This transform allows code generators to optionally fully-resolve operation-level pagination traits before processing the model.
---

Add pagination flattening transform

---

docs/source-2.0/guides/building-codegen/using-the-semantic-model.rst

Cleans up guide miss called out in #1287 
---

Fix typo in event stream content-type

---

docs/requirements.txt
docs/source-2.0/guides/smithy-build-json.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/RemoveDeprecatedShapes.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/RemoveDeprecatedShapesTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/remove-deprecated.smithy
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/FilterDeprecatedRelativeDate.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/FilterDeprecatedRelativeVersion.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/FilterDeprecatedRelativeDateTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/FilterDeprecatedRelativeVersionTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-members-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-members-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-shapes-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-shapes-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-traits-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-date/deprecated-traits-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-members-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-members-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-shapes-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-shapes-before.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-traits-after.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/transform/deprecated-version/deprecated-traits-before.smithy

Adds two transforms to `smithy-model` and `directed codegen` that allow users to filter out deprecated shapes by version or date. 
These transforms allow a user of directed codegen to quickly implement the recommended [`relativeVersion`](https://smithy.io/2.0/guides/building-codegen/configuring-the-generator.html#relativeversion-client-and-type-codegen-only) and [`relativeDate`](https://smithy.io/2.0/guides/building-codegen/configuring-the-generator.html#relativedate-client-and-type-codegen-only) settings for client and type code generators.
---

Add transforms to remove deprecated shapes

---

docs/source-2.0/spec/documentation-traits.rst
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/title-added.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/title-added.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

Closes: #2406
Expands the selector of the title trait to allow it to be applied to any non-member shape. 
The title trait provides a simple name or description that can be used when referencing the shape from another context.
In a code generator this can be used to provide helpful documentation For example you could use the title trait on the following error:
```smithy
@title("Indicates a failed doodad.") 
@error("client")
structure OopsieDaisyError {...}
```
Which could then referenced in a generated operation (notional java): 
```java
/**
* My Cool operation that does stuff.
* 
* @throws OopsieDaisyError - Indicates a failed doodad.
*/
public MyOuput myOperation(MyInput input) {...}
```
Notice how the title trait provides the user-friendly description to use in the operation context
--- …

Expand usage of title trait

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/Property.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/ResourceSchema.java
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/ResourceSchemaTest.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/aws-sagemaker-domain.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/aws-sagemaker-domain.json
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java

- Before these changes, converting a node to resource-schema is lossy
- These changes include the necessary changes to keep round-trips between node and resource-schema lossless
- Property was adapted to incorporate its separate "properties" as extensions to the schema**
- **only when these "properties" (`insertionOrder`, `dependencies`) is set to a non-default
- Unknown properties are added as extensions to the Schema
- Unit testing
---

Add round-trip convertibility of resource schemas

---

docs/source-2.0/guides/smithy-build-json.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/MakeIdempotencyTokensClientOptional.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/MarkIdempotencyTokensClientOptional.java
smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/MakeIdempotencyTokenClientOptional.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/MakeIdempotencyTokenClientOptionalTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/idempotency-token.smithy

Adds a transform that marks required Idempotency tokens `@clientOptional`. This is important because it changes the nullability of idempotency tokens for code generators, allow customers to leave the field unset and have their client inject the value.
---

Add transform to mark required idempotency tokens client optional

---

docs/source-2.0/spec/type-refinement-traits.rst
smithy-aws-protocol-tests/model/awsJson1_0/required.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/DefaultTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/default-with-invalid-blob.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/default-with-invalid-blob.smithy
smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy

Updates the blob defaults in a few protocol tests to conform with expected values.
Also adds documentation on the expected constraints on default blob values and a validator to warn on incorrect values. A warning is used instead of an error as this could otherwise be a breaking change for consumers 
---

Update blob defaults for protocol tests

---

.changes/README.md
.changes/amend
.changes/new-change
.changes/next-release/documentation-7da019874732a62550914aa13b543b6e4de60a6e.json
.changes/render
.changes/tool/__init__.py
.changes/tool/amend.py
.changes/tool/github.py
.changes/tool/new.py
.changes/tool/release.py
.changes/tool/render.py
.github/workflows/changelog-ci.yml
CONTRIBUTING.md

Writing changelog entries is not super fun. Writing them after the fact, especially when you didn't write the original feature, is even less fun. And merge conflicts because of synchronizing a changelog file are SUPER not-fun.
This PR solves those problems. It introduces a changelog tool similar to what many of the SDK teams use (and indeed cribs some code from them).
* When creating a pull request, you create a changelog entry by running `.changes/new-change`. This creates a JSON file in `.changes/next-release/` containing the changelog entry and its metadata (e.g. whether it's a documentation change, feature change, etc.)
* When the pull request is opened a GitHub action will automatically add a PR comment with a suggestion that you can click on to add the PR number.
* During a release, …

Add a tool to create and render stageable changelog entries

---

.changes/next-release/feature-f1decfa17cc23bd6a2718e7dddfeb8d5eb252163.json
smithy-aws-protocol-tests/model/awsJson1_0/defaults.smithy
smithy-aws-protocol-tests/model/restJson1/defaults.smithy

Convert blob default values to Base64 in `awsJson1_0` & `restJson1` protocol tests.
* Generated to Swift SDK protocol tests.
---

fix: Convert blob default values to Base64

---

.changes/next-release/bugfix-a4eb4361f200aabca46d06a5985bbd4ccc1fc60c.json
smithy-smoke-test-traits/src/main/java/software/amazon/smithy/smoketests/traits/UniqueSmokeTestCaseIdValidator.java
smithy-smoke-test-traits/src/test/resources/software/amazon/smithy/smoketests/traits/errorfiles/duplicate-ids.errors
smithy-smoke-test-traits/src/test/resources/software/amazon/smithy/smoketests/traits/errorfiles/duplicate-ids.smithy

The validator is supposed that all smoke test case ids are unique within a service's closure, but it was only checking operations directly bound to the service shape.
---

Fix unique smoke test id validation

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/AwsTagIndex.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/ServiceTaggingValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TagEnabledServiceValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableResourceValidator.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggingShapeUtils.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-enabled-service-list-broken.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-on-create.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-service-wide-two-services.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-service-wide-two-services.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-types.errors

When a resource is in the closure of more than one service the `TaggableResource` error won't say for which one it failed, e.g.,
```
[ERROR] example.weather#City: Resource does not have tagging CRUD operations and is not compatible with service-wide tagging operations. | TaggableResource 
```
This change add the service to better understand where the issue is.
```
[ERROR] example.weather#City: Resource does not have tagging CRUD operations and is not compatible with service-wide tagging operations for service `example.weather#Weather`.
```
While there I also made minor changes to improve the code around.
* Added tests for this case
* Issue #, if applicable (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull …

Add service id to the error message to aid debugging

---

smithy-linters/src/main/java/software/amazon/smithy/linters/ShouldHaveUsedTimestampValidator.java
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/should-have-used-timestamp-ignore.json

* Reduce false positives of ShouldHaveUsedTimestampValidator, when a member shape targets a list of Timestamps or structure of solely Timestamps
* Also allows timey members to target enums without emitting events
* Improves the CX by reducing unhelpful noise in smithy validator
* added new unit tests
---

Reduce false positives of ShouldHaveUsedTimestampValidator

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/model/ResourceSchema.java

* When trying to get the `required` field from a CFN resourceSchema, I realized that the `required` and `additionalProperties` field do not have a getter making it impossible to retrieve the `required` field in CFN ResourceSchema via the ResourceSchema model.
* `gradle build`
---

Adding missing getters to ResourceSchema

---

.github/workflows/ci.yml
CONTRIBUTING.md
build.gradle.kts
smithy-cli/build.gradle.kts

- Given JDK8 is largely being moved away from, this is a good first step in that direction
- However, for backwards compatibility, we will still target 8 for all current modules
- This means **existing modules cannot use newer features**, but new modules (like docgen) *can* use newer language versions
- Speaking _optimistically_, some day we can remove explicit compatibility and just rely on the toolchain
- `./gradlew clean build integ publish`
- Set global Java to <17, and run again, does not build and shows error
---

Require JDK17+ for development

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceOperationInputOutputValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-properties/invalid-output-identifier.errors

Add help text to ResourceOperationInputOutput event

---

smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildUtils.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/config-with-env.json

- When strings in config files have multiple environment variables, it reads and resolves each of them.
- Referring to Issue https://github.com/smithy-lang/smithy/issues/2490
- Added test to existing function - to resolve multiple variables.

enable multi variable expansion + tests

---

.github/workflows/make-docs.yml

The build docs workflow is failing with
```
* What went wrong:
Building this project requires Java 17 or later. You are currently running Java 11.
```
This change configures the Java version to use 17.
Validated using [`action-validator`](https://github.com/mpalmer/action-validator).
---

Setup Java 17 to generate the docs

---

smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy

The body seems to have been inadvertently malformed [in this commit](https://github.com/smithy-lang/smithy/pull/2447/commits/5adb6b51a43cb8d993d6d791fbc446477efc2764).
---

Fix malformed CBOR body

---

docs/source-2.0/aws/aws-auth.rst
docs/source-2.0/aws/rules-engine/auth-schemes.rst

Add links to SigV4a spec

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableApiConfig.java

Update builder methods visibility to public. Without this, it is impossible to instantiate an instance of `TaggableApiConfig`.
---

Update builder methods visibility to public

---

docs/source-2.0/aws/aws-cloudformation.rst

* Updating documentation to correctly reflect the selector used for @cfnDefaultValue trait in code.
No need to test. Document update.
* The code for @cfnDefaultValue defined [here](https://github.com/smithy-lang/smithy/blob/58753d00ba7a5c7d1ad69b6c510d8624cd0304b0/smithy-aws-cloudformation-traits/src/main/resources/META-INF/smithy/aws.cloudformation.smithy#L42) uses  a selector different than defined on our website: https://smithy.io/2.0/aws/aws-cloudformation.html#aws-cloudformation-cfndefaultvalue-trait
---

Fixing documentation of cfnDefaultValue trait selector to match as defined in code.

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/string-enums-one-of.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/string-enums.jsonschema.v07.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/string-enums.smithy

This adds support for a new json schema setting, `enumStrategy`, that allows for variants `enum` (current behaviour, and default) and `oneOf` (gets converted to a oneOf with const string values, allowing for documentation of individual enum variants.)
I'm new to this codebase, let me know if there are other considerations I may have missed here
Allows for documentation on enum variants in an open-api schema for example.  The current behaviour (which will remain the default), doesn't allow documentation at the variant level
Added unit test cases to `JsonSchemaConverterTest`.
ran `./gradlew build`
For: #2481
---
By submitting this pull request, I confirm that …

Add support for json schema oneOf enumStrategy

---

docs/source-2.0/spec/mixins.rst

This commit updates the service example to use renames for shapes that are not operations, as that is invalid. It also fixes a typo in the operation mixin example.
---

Fix issues in mixin examples

---

gradle/libs.versions.toml
smithy-cli/build.gradle.kts

- Adds a task that generates, checksums, and signs the CLI images
- JReleaser already does this but we will cease using it for CLI releases
- Remove JReleaser from the CLI configuration
- `gradle clean build images`
---

Add CLI image checksum and signing

---

smithy-aws-protocol-tests/model/restXml/document-maps.smithy

This protocol test has had [other fixes](https://github.com/smithy-lang/smithy/pull/2423), but that was only required because it deviated from the `Request`/`Response` paradigm. This PR aligns the setup, fixing other minor confusions caused by it.
---

Align restXml setup test with others

---

docs/source-2.0/java/quickstart.rst

Add link to Java quickstart repo

---

smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTraitValidator.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/iam-resources/invalid-iam-resources.smithy

This commit adds support for more complex ARN formats, including those with colon (':') chars or a combination of colons and foward slashes ('/').
---

Allow more complex ARN templates

---

smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/GetterGenerator.java

The method `get<MemberName>OrEmpty()` for collections, either lists or maps, was supposed to return an empty collection when the collection was not set, instead of null, but somehow we missed to add this expected behavior. This change fixes this, if the collection was not set we return either `Collections.emptyList()` or
`Collections.emptyMap()` depending on the collection type instead of `null`. The user can still find whether the value was set by using the `Optional<...> get<MemberName>()` variant that returns en empty optional when the collection was not set.
Validated the generated code. We don't currently have asserts for the generated code but only tests that asserts that everything compiles as expected. Asserting on the expected generated code would be good but can be added in a …

Return an empty collection instead of null

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggingShapeUtils.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/tagging/TaggingShapeUtilsTest.java

Allows for the resource name component, the arn name component, or both name components to be specified. Empty names, non-matching names, or names that have repeat components will fail.
Other minor interface cleanup is included.
---

Expand allowed tagging arn member names

---

docs/source-2.0/aws/aws-cloudformation.rst
smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceIndex.java
smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourcePropertyValidator.java
smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceTrait.java
smithy-aws-cloudformation-traits/src/main/resources/META-INF/smithy/aws.cloudformation.smithy
smithy-aws-cloudformation-traits/src/test/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceIndexTest.java
smithy-aws-cloudformation-traits/src/test/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceTraitTest.java
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/cfn-resources.smithy
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/errorfiles/primary-identifier-swap.errors
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/errorfiles/primary-identifier-swap.smithy
smithy-aws-cloudformation-traits/src/test/resources/software/amazon/smithy/aws/cloudformation/traits/test-service.smithy
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/rule-example.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/rule-example.smithy

This commit adds the `primaryIdentifier` field to the `@cfnResource` trait. This supports service teams that have CFN support that deviates from their APIs in their primary identifier, normally from a human readable value to an ARN. This field is `@deprecated` from the start, as it is not the preferred path for supporting resource identifiers.
The value of the `primaryIdentifier` field, when set, MUST be the name of a property defined on the resource shape and that property MUST be defined as a `string` or `enum` shape.
---

Add primaryIdentifier to cfnResource trait

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test-use-oneof.openapi.json

OpenAPI only lets you have one error per HTTP response code. This is a problem when converting things because Smithy has no such limitation. To address that, we added a toggle that lets you disambiguate by making the body contents a `oneOf`, which is an untagged union. The problem is that we made this a tagged union by leaning on how Smithy converts Smithy's union shape, which is tagged.
To illustrate the problem, the OpenAPI modeled body technically now declares the following body valid:
```json
{
"Error1" {
"foo": "bar"
}
}
```
But the model for the structure is:
```
@error("client")
@httpError(400)
structure Error1 {
foo: String
}
```
And an actual valid body would be:
```json
{
"foo": "bar"
}
```
This commit turns the OpenAPI body into an untagged union instead, which is how it should …

Don't make oneOf errors tagged unions

---

buildSrc/src/main/kotlin/smithy.java-conventions.gradle.kts
gradle/libs.versions.toml

This is needed as of gradle 8, but has incidentally kept working. Without this, a bump to JUnit 5.12 will fail though (see https://github.com/smithy-lang/smithy-python/pull/388)
see: https://docs.gradle.org/8.12/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
---

Add explicit junit launcher dependency

---

CHANGELOG.md

Add missing changelog entry for 1.55.0

---

smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeyDefinition.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/IamResourceTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ArnTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TagEnabledTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableTrait.java

This makes IDL serialization a lot cleaner. For example, setting a simple `@arn` trait with only a template:
```
@arn(
template: "foo:{fooId}"
)
```
and passing reserializing it through the `SmithyIdlModelSerializer` would then output:
```
@arn(
template: "foo:{fooId}"
absolute: false
noAccount: false
noRegion: false
reusable: false
)
```
This only changes some of the AWS traits for now, but could potentially expand to more traits.
---

Skip serializing default boolean values

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/CleanClientDiscoveryTraitTransformer.java

Improve CleanClientDiscoveryTraitTransformer

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/plugins/CleanOperationStructures.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/plugins/CleanStructureAndUnionMembers.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ResourceIdentifierBindingValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/RemoveShapesTest.java

This commit optimizes two ModelTransformPlugin implementations and one Validator plugin to use fewer intermediate objects and streams.
Helps with #2556 
---

Optimize transforms and validators

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/UnsupportedTraits.java

This path previously created a bunch of extra `ShapeId` garbage from converting `String`s into `ShapeId`s each time a test was performed. The `ShapeId` instances for these already exist, so we use those instead.
---

Use ShapeId instead of name in OAS conversion

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/tagging/TaggableResourceValidator.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-enabled-service-list-broken.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-on-create.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-service-wide-two-services.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/tagging/invalid-tag-types.errors

This commit lowers the severity (ERROR to DANGER) when a resource does not have instance operations for manipulating tags when service level tagging operations are not present.
This is useful for serivces that have operation inputs that vary subtly, making direct instance bindings not possible.
---

Relax TaggableResource instance validation

---

.changes/next-release/feature-4352fb542ea76e90f06860fb12e80bc88b02616f.json
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4.a.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4.b.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4.events
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4a.a.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4a.b.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/diffs/remove-sigv4a.events

* The removal of sigv4 and sigv4a auth events will throw danger events since these are breaking changes
* The addition of these danger events informs the model developer to understand the significant customer impact on the auth scheme removals
* Local build passed with new unit test cases
* Links to additional context, if necessary: N/A
* Issue #, if applicable: N/A
---

Add breakingChanges to the removal of sigv4 and sigv4a traits

---

build.gradle.kts

This pull request updates the build script for Smithy repository to remove a few previous workarounds set in place due to issues in Jreleaser. It also removes redundant tagging of our repository when releasing a new version. These changes were co-ordinated and discussed with @haydenbaker during 1.56.0 release process.
To ensure that future releases occur without the issues.
These changes were pending to be pushed and were required to successfully release version 1.56.0 of Smithy.
---

Updating build script to remove some previous workarounds.

---

docs/source-2.0/aws/protocols/aws-query-protocol.rst
smithy-aws-traits/build.gradle.kts
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/aws-query-compatible.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-query-compatible-does-not-support-non-aws-json.errors

Complete AWS query compatibility for RPC v2 CBOR

---

smithy-aws-protocol-tests/build.gradle.kts
smithy-protocol-tests/build.gradle.kts

- Changes trait dependencies from implementation to api dependencies
- Today, if you try to build either protocol test suites, you need to add explicit dependencies on these trait packages otherwise you will have unresolved trait errors
---

Update trait dependencies to api instead of implementation

---

docs/source-2.0/additional-specs/waiters.rst

Fix wrong member in waiter examples

---

docs/source-2.0/aws/aws-endpoints-region.rst
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/EndpointPatternType.java
smithy-aws-endpoints/src/main/resources/META-INF/smithy/aws.endpoints.smithy
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/StandardPartitionalEndpointsTraitTest.java
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/traits/standardPartitionalEndpoints.smithy

* The two existing patterns do not match what the AWS DNS team recommends to be used for partitional service endpoints
* This PR adds a new third type which will the be recommended flag going forward, and will match the prescribed patterns 1:1 for all partitions
* Added a sanity test
---

add AWS_RECOMMENDED as partitional endpoint pattern

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-length.smithy

[RestJsonWithoutBodyEmptyInputExpectsEmptyContentType](https://github.com/smithy-lang/smithy/blob/e44fd7f91c916c8adfa55ddbef2a1bfe59573989/smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-content-type.smithy#L131) says that when there's no request body input binding, content-type should be omitted. The test this commit fixes,
RestJsonMalformedLengthQueryStringNoValue, is on an operation with no request body input binding, but was specifying content-type, conflicting with the former test.
---

Fix restJson1 malformed length test

---

smithy-build/src/main/java/software/amazon/smithy/build/FileManifest.java
smithy-build/src/main/java/software/amazon/smithy/build/MockManifest.java
smithy-build/src/test/java/software/amazon/smithy/build/FileManifestTest.java

https://github.com/smithy-lang/smithy/pull/2599 introduced FileManifest::writeUsing, which does not return the resolved Path being written to, so its usage in FileManifest::writeJson resulted in the relative Path being returned from that method, instead of the resolved Path like before.
I updated writeUsing to return the resolved Path, and updated some tests.
---

Fix FileManifest::writeUsing

---

docs/source-2.0/guides/model-translations/converting-to-openapi.rst

In https://github.com/smithy-lang/smithy/pull/2597 I missed some apigateway specific settings, so I fixed that here.
---

Add links to openapi apigateway config

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/AstCommand.java

It allows you to get prelude shapes when getting the AST.
Implementations that do not use Smithy in Java will need a way to get prelude shapes in the JSON model. Otherwise, special casing is necessary to handle prelude shapes.
`clean`, `build`, then `smithy-cli:runtime`.
`smithy-cli/build/image/smithy-cli-darwin-aarch64/bin/smithy ast --include-prelude` will include prelude shapes.
---

Support include-prelude in smithy ast

---

smithy-aws-endpoints/src/main/resources/META-INF/smithy/aws.endpoints.smithy
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/invalid/invalid-endpoint-patterns.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/traits/errorfiles/dualstack-only-endpoints-trait.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/traits/errorfiles/standard-partitional-endpoints-trait.errors
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/traits/errorfiles/standard-regional-endpoints-trait.errors

Remove the @unstable trait from the endpoint modifier (declarative endpoints) traits for: @standardRegionalEndpoints, @standardPartitonalEndpoints and @dualStackOnlyEndpoints.
These traits are in use and can now be considered stable.
Note: I did not remove the @unstable trait from the @rulesBasedEndpoints trait as this trait may still change.
Existing unit tests.
---

Remove @unstable from endpoint modifier (declarative endpoints) traits 

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/Template.java

Currently only Literal Parts of Template are exposed. Exposing Dynamic Parts allows for inspecting the parts of a template for more flexibility when processing (allows for not using the streaming based visitor API that doesn't work for my usecase).
---

Expose Dynamic Part, just like Literal Part

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/plugins/CleanOperationStructures.java

This commit pre-computes the set of ShapeIds being removed to streamline its processing. This is now 1 loop through all IDs and 3 contains checks, where previously it was 3 loops and 3 equality checks.
Closes #2557 
---

Optimize work in CleanOperationStructures

---

docs/source-2.0/aws/aws-iam.rst
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeyValueTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysValidator.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ServiceResolvedConditionKeysTrait.java
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.smithy
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeyValueTraitTest.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ServiceResolvedConditionKeysTraitTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/condition-key-value.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/invalid-condition-keys-service-resolved.errors
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/valid-condition-key-value.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/errorfiles/valid-condition-keys-service-resolved.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/service-resolved-condition-keys.smithy
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/successful-condition-keys.smithy

This commit makes an arnNamespace prefix in a full condition key (`arnNamespace:name`) optional in all IAM traits that support specifying the condition keys. Trait definitions are relaxed, utility methods are provided, and validators and the ConditionKeysIndex are updated to use resolve the full names based on the service in context.
Minor optimization of validation and index computation is also done.
---

Optional arnNamespace for condition key traits

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

I noticed this field doesn't have an effect on unions or maps. Should it?
If not, I think it should be clarified (like in this change), and maybe there should be at least a NOTE emitted for non-struct cases where such a conflict is present.
For example:
```smithy
$version: "2"
namespace test
@trait(structurallyExclusive: "member")
structure myTrait {}
map Foo { @myTrait key: String, @myTrait value: String }
```
passes model validation.
---

Clarify behavior of structurallyExclusive

---

.github/workflows/ci.yml

Adds a job to the CI workflow that builds https://github.com/aws/api-models-aws using new Smithy changes.
api-models-aws is a pretty large test suite, so this should give us much more confidence that we aren't making breaking changes to a validator or something.
---

Add CI to build against api-models-aws

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/parameters/Parameter.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/EndpointTestsTraitValidator.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/traits/EndpointTestsTest.java
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/invalid-test-missing-built-in-value.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/invalid-test-missing-built-in-value.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/missing-input-target.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/missing-input-target.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/missing-required-values.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/non-default-builtin-values.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/non-default-builtin-values.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/traits-test-model.smithy

This commit adds new validation for built-in parameters when used with the `endpointTests` trait.
1. Validates that built-in values with defaults are specified to the correct value if they are mismatched in `operationInput` cases.
2. Validates that built-in values without defaults are specified in `operationInput` cases.
Also fixes skipping DANGER/ERROR in endpoint test validation and adds a convenience method to the `Parameter` class.
---

Improve EndpointTests built-in validation

---

smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenSettings.java

Remove the constraint to reject the smithy package for traits codegen.
---

Remove the constraint to reject the smithy package for traits codegen

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/PartitionEndpointSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/PartitionSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/RegionSpecialCase.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/StandardPartitionalEndpointsTrait.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/StandardRegionalEndpointsTrait.java
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/StandardPartitionalEndpointsTraitTest.java
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/StandardRegionalEndpointsTraitTest.java
smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/traits/standardRegionalEndpoints.smithy

Calling `toNode` on standardRegionalEndpoints or standardPartitionalEndpoints can raise NPE when special cases are missing non-required members.
This PR fixes that and adds equals/toHash methods as well.
* Modified existing tests to test that traits converted to node and back are equal.
---

Fix declarative endpoint traits toNode

---

smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java
smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java
smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/resource-condition-keys.smithy

This fixes a bug where collection operations were not being searched by `ConditionKeysIndex`.
---

Search all resource operations for condition keys

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/IsVirtualHostableS3Bucket.java
smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/language/functions/IsVirtualHostableS3BucketTest.java
smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/ParseUrl.java

This commit removes the use of three regular expressions and string splitting when checking if a value is a virtual hostable bucket. This should help with both startup and runtime performance. It also exposes a static method for performing this check that I'll use in smithy-java.
---

Improve isVirtualHostableBucket function

---

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsPartition.java
smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/partition/Partition.java

Only compiles partition regular expressions once.
Reuses a cached AWS_PARTITION values.
Exposes method for smithy-java to use.
---

Improve aws.partition function

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidatorOptions.java

This documents that the suppressed severity can be selected in the validate command. There was already a test for it, but it got missed in the docs.
Resolves #2613
---

Document suppressed severity in validate command

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/validators/RuleSetParameterValidator.java
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-builtins.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/valid/default-values.smithy
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/invalid-test-missing-required-built-in.errors
smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/traits/errorfiles/invalid-test-missing-required-built-in.smithy

This commit removes extraneous code that cause parameters to be double counted in test cases. This would cacade into a mismatch in counts between test cases and parameters.
This extra counting was introduced in the endpoint ruleset refactoring incorrectly. Existing rulesets continue to work and a new test case shows the correct failure mode.
---

Fix endpointTests missing required param validation

---

smithy-aws-protocol-tests/model/restJson1/http-payload.smithy

Add a new protocol tests for the JSON REST protocol. When we have a response object with a member that's bound to the HTTP payload, such as
```smithy
@output
structure HttpPayloadWithStructureInputOutput {
@httpPayload
nested: NestedPayload,
}
```
And the response body is empty, then the member MUST be set to `null`.
Regression for this case was reported to the Java SDK V2 and fixed on [#6111](https://github.com/aws/aws-sdk-java-v2/pull/6111).
--- …

Add a test for explicit payload member and empty body responses

---

build.gradle.kts

- Nexus2 is being sunset and we must move away from it
- This change switches to the central portal deployer
- Nothing else is needed for this migration
---

Migrate from nexus2 to mavenCentral deployer

---

.github/workflows/ci.yml

Recent PR experienced connection errors like the following:
```
Error: Multiple errors returned
Error: Error 0: connect ETIMEDOUT 104.16.72.101:443
Error: connect ETIMEDOUT 104.16.72.101:443
at createConnectionError (node:net:1652:[14](https://github.com/smithy-lang/smithy/actions/runs/15330227683/job/43134921095?pr=2647#step:3:16))
at Timeout.internalConnectMultipleTimeout (node:net:1711:38)
at listOnTimeout (node:internal/timers:583:11)
at process.processTimers (node:internal/timers:519:7)
Error: Error 1: connect ENETUNREACH 2606:4700::6810:4965:443 - Local (:::0)
Error: connect ENETUNREACH 2606:4700::6810:4965:443 - Local (:::0)
at internalConnectMultiple (node:net:1186:[16](https://github.com/smithy-lang/smithy/actions/runs/15330227683/job/43134921095?pr=2647#step:3:18))
at …
```

Update graddle/wrapper-validation-action version from v3 to v4.

---

smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/lists/nested-boolean-list-trait.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/FromNodeMapperVisitor.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/ToNodeGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/lists/nested-boolean-list-trait.smithy
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest

TraitCodegen will generate incorrect `fromNode` code for nested collection like the following:
```java
public static NestedListTrait fromNode(Node node) {
Builder builder = builder();
node.expectArrayNode()
.getElements().stream()
.map(n -> n.expectArrayNode()
.getElements().stream()
.map(n1 -> n1.expectArrayNode()
.getElements().stream()
.map(n12 -> BooleanMember("n12", builder::n12))
.collect(Collectors.toList()))
.collect(Collectors.toList()))
.forEach(builder::addValues);
return builder.build();
}
```
Fixed the incorrect code generated for boolean member in nested collection.
Fixed the problematic lambda variable name like `n12`.
Fixed no new line starting for `.sourceLocation()` `in createNode()` for structure based trait.
The code generated after fix:
```java
public static …
```

Fix trait code generation for collections of boolean.

---

smithy-docgen/src/it/java/software/amazon/smithy/docgen/PluginTest.java
smithy-docgen/src/it/resources/software/amazon/smithy/docgen/main.smithy
smithy-docgen/src/main/java/software/amazon/smithy/docgen/SmithyDocPlugin.java
smithy-docgen/src/main/java/software/amazon/smithy/docgen/generators/StructuredShapeGenerator.java

This commit updates the behavior of `smithy-docgen` to attempt the automatic upgrade of string `@enum`s to Smithy's `enum` shapes. This upgrade does not generate enum names, as they may be different from other sources.
If a shape cannot be upgraded to an `enum`, it is ignored during content generation.
---

Fix docgen when encountering `@enum` trait

---

designs/defaults-and-model-evolution.md
docs/source-2.0/spec/aggregate-types.rst

Part of an action item from an internal ticket. An AWS service wanted to name one of their union members as "Unknown" and it conflicted with the Unknown sub-class that is generated. With this updated guidance, if clients SHOULD generate an Unknown union member, then similarly, the model SHOULD NOT have a shape name that can conflict with that.
None
None
---

Add guidance about Unknown members for unions

---

.github/workflows/checkout-and-build-smithy/action.yml
.github/workflows/sdk-codegen-ci.yml
README.md
designs/defaults-and-model-evolution.md
docs/conf.py
docs/source-2.0/guides/building-codegen/creating-codegen-repo.rst
docs/source-2.0/guides/building-codegen/decoupling-codegen-with-symbols.rst
docs/source-2.0/guides/building-codegen/mapping-shapes-to-languages.rst
docs/source-2.0/guides/building-codegen/overview-and-concepts.rst
docs/source-2.0/guides/glossary.rst
docs/source-2.0/guides/gradle-plugin/gradle-migration-guide.rst
docs/source-2.0/guides/gradle-plugin/index.rst
docs/source-2.0/guides/model-translations/converting-to-openapi.rst
docs/source-2.0/guides/model-translations/generating-cloudformation-resources.rst
docs/source-2.0/quickstart.rst
mkdocs
smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy
smithy-build/README.md

* Renames `awslabs/smithy*` to `smithy-lang/smithy*` outside of CHANGELOG and 1.0 docs
* The `smithy*` were moved from awslabs to smithy-lang
CI
---

Rename `awslabs/smithy*` to `smithy-lang/smithy*`

---

smithy-aws-protocol-tests/model/aws-config.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_0/query-compatible.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-errors.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-errors.smithy
smithy-aws-protocol-tests/model/rpcv2Cbor/main.smithy
smithy-aws-protocol-tests/model/rpcv2Cbor/query-compatible.smithy

This adds protocol tests for the [awsQueryCompatible trait](https://smithy.io/2.0/aws/protocols/aws-query-protocol.html#aws-protocols-awsquerycompatible-trait) for both `rpcv2Cbor` and `awsJson1_0`.
These tests may be successfully run by existing protocol test implementations, but changes must be made to get the full effect. Protocol test implementations must be updated to support the `ErrorCodeParams` vendor params if they generically expose error code or query error type.
---

Add protocol tests for awsQueryCompatible

---

smithy-cli/build.gradle.kts

Maven now has a dependency on it. This change adds it to the relocated dependencies to avoid runtime conflicts with other consumers of the library.
---

Add ASM to the relocated dependencies

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java

The gradle plugin's select isn't very useful without being able to pass along the classpath gradle is responsible for producing.
---

Add model discovery args to smithy select

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/JsonValueNodeTransformer.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/examples-test.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/examples-test.smithy

When converting to OpenAPI for the restJson1 protocol, we convert member names if they have the jsonName trait. However, we were *not* converting those member names in examples. This updates example conversion to respect member name, if present and enabled.
Fixes #2659
---

Fix jsonName conversion for OpenAPI examples

---

smithy-aws-protocol-tests/model/awsJson1_0/query-compatible.smithy
smithy-aws-protocol-tests/model/rpcv2Cbor/query-compatible.smithy

The original property name `"Message"` is causing problem in protocol tests due to name mismatch , so we change this name to `"message"` in this PR.
---

Fix incorrect property name in protocol tests' body

---

smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenSettings.java

Allow namespaces like `smithy4s`, but not `smithy` or `smithy.api` or other sub-`smithy` namespaces.
---

Trait codegen: less restrictive namespace check

---

build.gradle.kts

Add `maxRetries` and `retryDelay` to JReleaser to remedy timeout issues during Maven Central publishing.
---

Add max retry and retry delay setting to JReleaser

---

.changes/next-release/feature-972f78d227a4fe30f8512c53c8e5d2ecb2349fc1.json
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/Topic.java
smithy-mqtt-traits/src/test/java/software/amazon/smithy/mqtt/traits/TopicConflictTest.java
smithy-mqtt-traits/src/test/java/software/amazon/smithy/mqtt/traits/TopicTest.java

Adds support (parsing, validation, conflict-checking) for traits to reference MQTT topic filters.  Topic filter support is required for the new request-response MQTT service clients being released by the IoT SDKs.
Fixes a bug where the topic parser incorrectly skips a trailing or preceding empty topic level.
* Tests have been added for topic filter parsing and conflict checking.
* Tests have been added to cover initial and trailing empty topic levels.
* Further information about topics and topic filters can be found in MQTT specification docs: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901241
---

MQTT Topic Filter Support

---

smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenSettings.java

We are planning to add new traits under the `smithy.*` namespace and want to use the `trait-codegen` plugin to generate classes for the same.  Having this settings restriction does not allow us to use the `trait-codegen` for defining our own traits in `smithy.*` namespace.
So we discussed internally and decided to remove the restriction on using `smithy.*` namespace.
`./gradlew build`
---

Remove restriction on Smithy API namespace to use trait-codegen

---

smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenSettings.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenSettingsTest.java

• **What do these changes do?** 
Adds validation to prevent trait code generation on  `smithy` keyword itself or reserved Smithy namespaces  ( `smithy.api`, `smithy.waiters`, `smithy.test`) and their sub-namespaces but we still want to allow namespaces like `smithy.foo` or `smithy.rules` . 
This change adds a RESERVED_NAMESPACES set to act as a deny list for future extensibility.
For instance: 
`smithy` -> not allowed
`smithy.api` , `smithy.waiters` , and `smithy.test` -> not allowed
`smithy.foo`, `smithyfoo.bar`, -> allowed
• **Why are they important?**
Prevents namespace conflicts with core Smithy functionality and protects framework integrity by blocking user code generation on reserved namespaces.
• **How did you test these changes?**
Added comprehensive unit tests covering reserved …

Add a reserved namespaces deny list to restrict trait-codegen from using smithy specific namespaces.

---

CHANGELOG.md

This updates the changelog to be one rendered by the changelog tool.
Differences are mostly related to ordering of sections and title casing, but there were a few minor formatting issues also.
Note that this was rendered with the updated tool from #2713 and the backported entries from #2714.
---

Use rendered changelog

---

.changes/next-release/bugfix-fa236a86e9ae264be7a639a08634e6f0c7d88d2f.json
.changes/releases/1.61.0.json
CHANGELOG.md

This runs mdformat on the changelog with an 80 character wrap target. No other changes were made. See #2715 to see what changes are made after rendering with the changelog tool. (edit: that pr, which targeted this branch, has been merged) (edit 2: This has also been updated to pull in the 1.61.0 release)
---

Format changelog

---

.changes/README.md
.changes/pyproject.toml
.changes/smithy_changelog/__init__.py
.changes/smithy_changelog/release.py
.changes/smithy_changelog/render.py

This adds a script that handles updating the changelog and version number for a release. This is intended to be run as part of a GitHub workflow, but in the meantime it can be done manually to cut down some effort.
To bump the version and update the changelog you'll just run `uv run release`.
---

Add changelog release script

---

smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/LoadsFromModelTest.java
smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/structures/struct-with-idref-member-trait.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/BuilderGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/FromNodeGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest
smithy-trait-codegen/src/test/resources/META-INF/smithy/structures/struct-with-idref-member-trait.smithy

String shapes with `@idRef` are converted into `ShapeId` objects during the trait codegen.  However, the generated `fromNode()` method and Builder setters for string members with `@idRef` within structures are incorrect.
Because the `@idReft` info is binding with the member shape and those incorrect methods are generated based on member shape's targets.
For example the following smithy model:
```smithy
namespace test.smithy.traitcodegen.structures
@trait
structure StructWithIdrefMember {
@idRef(selector: "structure")
idRefMemberA: String
idRefMemberB: IdRefMemberB
}
@idRef(selector: "structure")
string IdRefMemberB
```
The generated `fromNode()` and builder's setter methods are incorrect.
```java
@SmithyGenerated
public final class StructWithIdrefMemberTrait extends …
```

Fix trait codegen for structure's string member with @idRef

---

smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/FromNodeGenerator.java

Current trait codegen missed the sourceLocation setting in `fromNode()` for list, map and structure traits. This PR will fix #2719 
---

Add missing sourceLocation setting in fromNode() in trait codegen

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ModelBuilder.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidatorOptions.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/DiffCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/diff/new2.smithy
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/diff/old2.smithy

The severity is set to `DANGER` to load the old and new models to avoid events of lesser severity to show up during loading. After this was done the option was mutated and the attempt to restore the default severity didn't work. Now, the validation option keeps a different field to distinguish the value read from the CLI from overrides to be able to tell them apart and properly reset these when needed.
---
By submitting this pull request, I confirm that my contribution is made …

Fix a bug that prevented warning events to show up for diff CLI command

---

smithy-trait-codegen/README.md

Add README.md for trait codegen package
---

Add README.md for trait codegen

---

smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/LoadsFromModelTest.java
smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/structures/struct-with-enum-default-trait.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/BuilderGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest
smithy-trait-codegen/src/test/resources/META-INF/smithy/structures/struct-with-enum-default-trait.smithy

For the following model: 
```smithy
namespace test.smithy.traitcodegen.structures
@trait
structure StructWithEnumDefault {
memberA: EnumA = "1"
memberB: EnumB = 3
}
enum EnumA {
ONE = "1"
TWO = "2"
}
intEnum EnumB {
THREE = 3
FOUR = 4
}
```
The generated code will use the string or integer value directly like:
```java
/**
* Builder for {@link StructWithEnumDefaultTrait}.
*/
public static final class Builder extends AbstractTraitBuilder<StructWithEnumDefaultTrait, Builder> {
private EnumA memberA = "1";
private EnumB memberB = 3;
// other implementation 
}
```
This PR fixed this problem.
---

Fix incorrect builder properties assignment for enum with default value

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

This change updates the RestJsonIgnoreQueryParamsInResponse test to enforce deserializing a body element that is also bound as a query parameter.
This test has a [rest-xml equivalent](https://github.com/smithy-lang/smithy/blob/38032229dd4c97a4792254350bf0ebe618e1738c/smithy-aws-protocol-tests/model/restXml/http-query.smithy#L371) that follows this same pattern.
Additionally, the extra test about "no payload" does not seem to make sense anymore in this context and has been deleted - the description of the test above says that server implementations have been updated to always return an empty json. Additionally, an empty string would never be returned in this case because there will be a payload that needs to be deserialized.
Smithy Ruby
---
By submitting this pull request, I confirm that …

Update query params output test in rest-json

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/FormatCommand.java

Allows specifying multiple files and/or directories to `smithy format`. Fixes https://github.com/smithy-lang/smithy/issues/2563.
---

Allow multiple args to format

---

smithy-trait-codegen/README.md
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/CreatesTraitTest.java
smithy-trait-codegen/src/it/java/software/amazon/smithy/traitcodegen/test/LoadsFromModelTest.java
smithy-trait-codegen/src/it/resources/software/amazon/smithy/traitcodegen/test/enums/with-trait-suffix.smithy
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/TraitCodegenUtils.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/EnumShapeGenerator.java
smithy-trait-codegen/src/main/java/software/amazon/smithy/traitcodegen/generators/GetterGenerator.java
smithy-trait-codegen/src/test/java/software/amazon/smithy/traitcodegen/TraitCodegenPluginTest.java
smithy-trait-codegen/src/test/resources/META-INF/smithy/enums/with-trait-suffix.smithy
smithy-trait-codegen/src/test/resources/META-INF/smithy/manifest

Current trait codegen will generate an inner `enum` java class within the trait's java class using the trait name for `enum` or `intEnum` traits. This is causing name conflicts in the java class.
For the following model:
```smithy
namespace example.traits
@trait
enum MyEnumTrait{
ONE = "1"
}
```
The generated Java code will look like:
```java
@SmithyGenerated
public final class MyEnumTrait extends StringTrait {
public static final ShapeId ID = ShapeId.from("example.traits#MyEnumTrait");
public MyEnumTrait(String value) {
super(ID, value, SourceLocation.NONE);
}
public MyEnumTrait(String value, FromSourceLocation sourceLocation) {
super(ID, value, sourceLocation);
}
/**
* Gets the {@code MyEnumTrait} value as a {@code MyEnumTrait} enum.
*
* @return Returns the {@code …
```

Fix trait codegen for class name conflicts in enum/intenum traits

---

.changes/smithy_changelog/new.py

This fixes a pair of bugs I found in the workflow of new-change where it prompts for missing inputs:
* Fixes an issue where specifying the type was technically required anyway
* Fixes an issue where joining of description lines wasn't working as intended
---

Fix new change

---

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/rule/Rule.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/logic/cfg/CfgTest.java
smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/logic/cfg/SsaTransformTest.java

I didn't realize the onBuild function was used to intercept terminal builder results and rewrite them to a different type. While this is extremely unintuitive, changing it now breaks existing usage of these builders.
---

Revert casting terminal endpoint builder methods

---

.github/workflows/checkout-and-build-smithy/action.yml
.github/workflows/ci.yml
.github/workflows/codeguru-reviewer.yml
.github/workflows/make-docs.yml
.github/workflows/sdk-codegen-ci.yml

* These change add configuration to cache and restore gradle cache in GitHub workflows
* They're important as they shorten the time required for running CI. They also ensure CI can go through if gradle is down.
CI is successful
Gradle build took 9m 27s
https://github.com/smithy-lang/smithy/actions/runs/17485026040/job/49702493915?pr=2767
Gradle is downloaded from network
```
Downloading https://services.gradle.org/distributions/gradle-8.14.3-bin.zip
.............10%.............20%.............30%.............40%.............50%.............60%.............70%.............80%.............90%..............100%
```
Gradle build took 9m 7s
https://github.com/smithy-lang/smithy/actions/runs/17657629935/job/50184162984?pr=2776
Gradle is used from cache
```
Cache hit for: …
```

Cache gradle in GitHub workflows

---

smithy-aws-protocol-tests/model/awsJson1_0/errors.smithy
smithy-aws-protocol-tests/model/awsJson1_1/errors.smithy
smithy-aws-protocol-tests/model/restJson1/errors.smithy

We recently had an issue in the .NET SDK where older versions could not handle the new responses returned by DynamoDB after the service team launched [Enhanced throttling observability](https://aws.amazon.com/blogs/database/enhanced-throttling-observability-in-amazon-dynamodb/).
Although this did not impact the latest versions (we accidentally fixed the bug in June of this year), I'm updating the protocol tests to make sure all clients can parse the response as expected (also, if these test cases existed last year when we made the .NET SDK compliant, we'd have noticed the problem at the time - the incorrect logic had existed since at least 2014).  
* How did you test these changes? Ran `./gradlew clean build` locally and manually updated the existing .NET SDK protocol tests to use the new …

Update JSON error tests to include scenarios with nested "__type" properties

---

.github/workflows/make-docs.yml

This appears to be the issue causing a failure in the build-docs workflow, all other workflows check out the repository first.
See: https://github.com/smithy-lang/smithy/actions/runs/18046074400/job/51357761547
---

Checkout before Java setup in build-docs

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/TopologicalShapeSort.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/TopologicalShapeSortTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ReplaceShapesTest.java

I have, on several occasions, run in to issues with an NPE coming out of the TopologicalShapeSort class. Specifically:
```
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Set.remove(Object)" because "dependentDependencies" is null
at software.amazon.smithy.model.loader.TopologicalShapeSort.dequeueSortedShapes(TopologicalShapeSort.java:83)
at software.amazon.smithy.model.transform.ReplaceShapes.updateMixins(ReplaceShapes.java:183)
at software.amazon.smithy.model.transform.ReplaceShapes.transform(ReplaceShapes.java:80)
at software.amazon.smithy.model.transform.ModelTransformer.replaceShapes(ModelTransformer.java:102)
...
```
In some of these situations, I was able to alleviate the problem by changing the order in which I perform my model transformations, but I finally …

Fix topological sort NPE when re-enqueueing shapes

---

docs/conf.py

Current smithy-java related docs are using `smithy-call` as smithy-java's version, this PR fixed this issue.
---

Fix incorrect tags in smithy-java related docs
