aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
aws/smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/authorizers.json
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/Authorizer.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizerIndex.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizerTrait.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizersTrait.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizersTraitValidator.java
aws/smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
aws/smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/apigateway/AuthorizerIndexTest.java
aws/smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/apigateway/AuthorizersTraitTest.java
aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/apigateway/effective-authorizers.smithy
aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/apigateway/errorfiles/invalid-authorizers.errors
aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/apigateway/errorfiles/invalid-authorizers.json
docs/source/guides/converting-to-openapi.rst
docs/source/spec/amazon-apigateway.rst
smithy-model/src/main/java/software/amazon/smithy/model/selector/PathFinder.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiMapper.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/SecuritySchemeConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponents.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/ComponentsObject.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OpenApi.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponentsTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mappers/small-service.smithy

This commit updates the API Gateway traits to allow Lambda authorizers
to vary per/operation. Authorizers are now only attached to an operation
when the `authorizer` trait is used on a service, resource, or operation.
The OpenApiMapper interface was updated to make this simpler so that you
can now map over the security requirements object of an operation and
rename them from the underlying Smithy authentication scheme (e.g.,
aws.v4) to the custom authorizer security scheme.
Included with this change is an update to the
RemoveUnusedComponents mapper to ensure that any unused security
definitions are stripped from the resulting spec.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Add ability to vary authorizers per/operation

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/smithy-prelude-traits.json

This commit adds the examples trait to the prelude and removes the
special case handling from the LoaderVisitor. This is now possible with
the introduction of the document type.
Closes #83

Add examples trait to prelude

---

build.gradle.kts

Since the root Smithy package has no source, this commit overrides
the root package's javadoc task to aggregate the javadocs of each
subproject.

Update root package javadoc to aggregate

---

docs/source/spec/validation.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidationLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorDefinition.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorFromDefinitionFactory.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ValidatorDefinitionTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ValidatorLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid-validation-selector.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/validator-filtering-and-mapping.smithy

This commit updates the validator logic to properly ignore shapes that
fall outside of the specified namespaces or that don't match a validator
definition selector. Lots more tests were added to ensure that validator
mapping and filtering works.
Closes #68

Add selectors to validators and fix namespaces

---

docs/source/spec/core.rst

I couldn't find a good way to lint CommonMark strings since most parsers
just treat malformed directives as text. Because of this, there was no
need to add new validator or dependency.
Closes #100

Update doc strings to be CommonMark

---

docs/source/quickstart.rst
docs/source/smithy.py
docs/source/spec/language-specification.rst
docs/source/spec/selectors.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/NodeModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLexer.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLoader.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/doc-targets/docs-on-eof.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/doc-targets/docs-on-metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/doc-targets/docs-on-namespace.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/doc-targets/docs-trailing-in-member.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/trait-on-eof.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/trait-trailing.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/traits-before-docs.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/traits-on-apply.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/traits-on-metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/trait-targets/traits-on-namespace.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/traits-on-apply.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/traits-on-metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/traits-on-namespace.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/doc-comments.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/doc-comments.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/list-and-sets.smithy

Closes #60
Also cleans up the validation of traits so that we check that the trait
is applied to something valid rather than check that there are no
pending traits for invalid targets.
This commit cleans up the grammar and presentation of the grammar to
make it more readable.

Add documentation comments

---

docs/source/spec/core.rst

```diff
-        structure GetForecastInput: {
+        structure GetForecastInput {
@required
forecastId: ForecastId,
}
```

Correct Smithy code syntax error in docs

---

docs/source/quickstart.rst
docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginatedIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginationInfo.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/PaginatedTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/smithy-prelude-traits.json
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/PaginatedIndexTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/PaginatedTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.json

This commit updates the paginated trait so that it can be attached to a
service to provide default configuration settings for the entire
service. The inputToken and outputToken members are now optional, but
must be resolved to a value when a paginted operation is bound to a service.
This should help keep services consistent with how they paginated while
still allowing specific operations to override settings when needed.

Allow paginated config to be shared across service

---

smithy-diff/src/main/java/software/amazon/smithy/diff/ChangedShape.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AbstractLengthAndRangeValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/AbstractShapeBuilder.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AbstractTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/Trait.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/RemoveTraitDefinitions.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/EventStreamValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExclusiveStructureMemberTraitValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitConflictValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitTargetValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitValueValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ModelSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/TraitTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/FilterTraitsTest.java
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/TopicBinding.java
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/validators/MqttTopicConflictValidator.java
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/validators/MqttTopicLabelValidator.java
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/validators/MqttUnsupportedErrorsValidator.java

This commit updates the Trait interface to include a "trait" qualifier
in methods defined on the interface to help protect against naming
conflicts with concrete and generated Trait implementations. Because all
traits should have a namespace and you can still find a trait by name
without a namespace using a Shape, the matchesTraitName method was
removed.

Make Trait methods less likely to conflict

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.json

The pagination trait of a service wasn't merged with the trait of an
operation, causing partial pagination trait definitions to fail when
validating.

Fix pagination trait resolution when validating

---

aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.apigateway.json

This commit removes the stuttering of a structure and member name from
the API Gateway Response shape. This fixes some warnings when validating
with the stuttered shape name validator.

Remove API Gateway shape name stuttering

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpMethodSemanticsValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-method-semantics-validator.errors

This commit removes the warning that was issued for POST operations
marked with the idempotent trait. The idempotent trait applied to POST
seems like it will be common enough that it will be encountered in
normal use, and applying the idempotent trait to the operation is a
strong signal that it was intentional. Emitting a warning for something
that is within reason and intentional is just noise.

Remove warning for idempotent POST operations

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/StringUtils.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/StringUtilsTest.java

This commit is a major rehaul of `CodeWriter` that allows it to be extended, cleans up how blank line trimming works, adds a custom format for interpolating calls to `CodeFormatter#write`, and adds named sections that can be intercepted and extended.
Here are the rendered docs:
Helper class for generating code.
A CodeWriter can be used to write basically any kind of code, including whitespace sensitive and brace-based.
The following example generates some Python code:
CodeWriter writer = CodeWriter.createDefault();
writer.write("def Foo(str):")
.indent()
.write("print str")
String code = writer.toString();
Code interpolation
------------------
The `write(java.lang.Object, java.lang.Object...)`, `openBlock(java.lang.String, java.lang.Object...)`, and `closeBlock(java.lang.String, …

Code writer sections and interpolation

---

docs/source/guides/building-models/build-config.rst
smithy-build/README.md
smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/config-with-env.json
smithy-build/src/test/resources/software/amazon/smithy/build/config-with-invalid-env.json

This commit updates smithy-build.json to support system
property/environment variable placeholders in object keys and string
values. A placeholder is in the form of `${NAME}` and can be escaped
using a backslash before the `$`. An exception is thrown if a value
cannot be resolved to a system property or environment variable.
Adding support for environment variables makes it easier to integrate
smithy-build.json files with other build tooling that might be wrapping
it.

Add environment variables to smithy-build.json

---

aws/smithy-aws-apigateway-openapi/build.gradle.kts
aws/smithy-aws-traits/build.gradle.kts
build.gradle.kts
codegen/smithy-codegen-core/build.gradle.kts
codegen/smithy-codegen-freemarker/build.gradle.kts
docs/source/spec/aws-core.rst
smithy-build/build.gradle.kts
smithy-cli/build.gradle.kts
smithy-diff/build.gradle.kts
smithy-jsonschema/build.gradle.kts
smithy-linters/build.gradle.kts
smithy-model/build.gradle.kts
smithy-mqtt-traits/build.gradle.kts
smithy-openapi/build.gradle.kts
smithy-utils/build.gradle.kts

This commit adds support to publish the generated artifacts (jar, pom
sources jar, and javadocs jar) to Maven Central. They are signed using
the standard signing plugin. The generated pom files have been augmented
with additional information for consumers. The nexus-staging plugin is
included to help automate releasing the staged artifacts after testing.
The subprojects' build files have been updated to contain display names
and descriptions for use in the pom files.
This commit also includes a version bump to 0.7.1.
#104 

Configure Gradle for Maven Central publishing

---

aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
docs/source/guides/converting-to-openapi.rst

This commit fixes a bug in the generation of requestTemplates for
API Gateway integrations utilizing CORS where templates would be
generated for response codes, not request content types. Small fixes
to documentation are also included.

Fix CORS request template generation

---

aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ControlPlaneTrait.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/DataPlaneTrait.java
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/PlaneIndex.java
aws/smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
aws/smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/PlaneIndexTest.java
aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/planes.json
docs/source/spec/aws-core.rst

This commit adds the `aws.api#controlPlane` and `aws.api#dataPlane` traits. By making these traits instead of tags, we can more easily query for them using existing abstractions and more easily validate their constraints using trait features.
TODO: We need to followup with a good definition of what control plane and data plane actually mean.
Closes #30

Add controlPlane and dataPlane traits

---

smithy-linters/src/main/java/software/amazon/smithy/linters/CamelCaseValidator.java
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.json

This commit updates the CamelCase validator to not apply the UpperCamel
validation to member shapes, as they are already validated based on the
memberNames setting.

Update CamelCase Member Shape Validation

---

build.gradle.kts
smithy-model/src/main/java/software/amazon/smithy/model/transform/ScrubTraitDefinitions.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ScrubTraitDefinitionsTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/scrub-trait-def.json

This commit updates the ScrubTraitDefinitions model transformer to
remove trait definition shapes from the prelude like intended.
Also includes a version bump to `0.8.1`.

Update ScrubTraitDefinitions prelude interaction

---

docs/source/spec/language-specification.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLexer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/LoaderVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/SmithyModelLexerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/annotation-unclosed-object2.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/metadata.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.smithy

This removes the ability to specify strings using single quotes in the
Smithy IDL. While convenient, having the option to use one style or the
other often leads to projects using both, which harms readability.
Double quotes are kept instead of single quotes due to the frequency of
apostrophes in English text and because they are commonly the only
option in programming languages. There is also slightly less ambiguity,
as it may be difficult to distinguish between a single double quote
character vs two single quote characters depending on font choice.

Remove single-quoted strings from the IDL

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/HttpBindingIndex.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/HttpBindingIndexTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/knowledge/http-index.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/ModelUtils.java

This commit adds support for exposing content-type resolution of
operations that use HTTP bindings. It supports resolving the request or
response content-type of structured payloads, blob payloads, string
payloads, payloads with a @mediaType trait, and operations with no
payloads at all.
This functionality is now used in the OpenAPI conversions, and can be
used in protocol code generators too.

Expose content-type resolution API

---

build.gradle.kts
docs/source/guides/building-models/gradle-plugin.rst
docs/source/guides/converting-to-openapi.rst
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/java/software/amazon/smithy/build/Test1ParallelPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test1SerialPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test2ParallelPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/Test2SerialPlugin.java
smithy-build/src/test/resources/software/amazon/smithy/build/applies-serial-plugins.json

This change allows plugins to declare that they cannot be run in parallel
with other plugins. Any projection with such plugins will be run serially.
Parallelizeable projections will then be run in parallel afterwards.
Note that plugins already ran serially with respect to other plugins in the
same projection, and that behavior persists.

Allow plugins to be run serially

---

.travis.yml
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/applies-global-serial-plugins.json

Previously global plugins were not being included in the determination of
whether a projection was serial or parallel.

Include global plugins in serial/parallel choice

---

smithy-model/src/main/java/software/amazon/smithy/model/node/StringNode.java
smithy-model/src/test/java/software/amazon/smithy/model/node/StringNodeTest.java

Add expectShapeId for fully-qualified shape ID

---

smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/EnumTraitTest.java

This EnumTrait helper function checks if the trait provides a name for
each enum constant. This is useful since it will often determine whether
or not a concrete type should be generated for the enum string or if
codegen should just rely on a normal string type.

Add helper to EnumTrait to check if has names

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolReference.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TypedPropertiesBag.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolReferenceTest.java

Symbol references are used when a symbol's definition or using a symbol
requires that other symbols are also available. This is used for things
like generating or using generic types that refer to other symbols. Code
generators can iterate over references to ensure that all of the
required imports for using a symbol are defined.

Add Symbol references

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/CaseInsensitiveReservedWords.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/MappedReservedWords.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ReservedWordSymbolProvider.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ReservedWordsBuilder.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ReservedWordSymbolProviderTest.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ReservedWordsBuilderTest.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ReservedWordsTest.java
codegen/smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/words.txt
config/checkstyle/suppressions.xml
smithy-utils/src/main/java/software/amazon/smithy/utils/StringUtils.java

The ReservedWordsBuilder can be used to more easily construct a
ReservedWords implementation, including loading reserved words from a
newline delimited file that uses "#" as comments.

Add ReservedWords builder for simpler construction

---

smithy-build/src/main/java/software/amazon/smithy/build/PluginContext.java
smithy-build/src/test/java/software/amazon/smithy/build/PluginContextTest.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ModelTransformerTest.java

This commit adds a method to ModelTransformer to get all shapes from a
model that are not only used as part of a trait or definition of a
trait. This makes it easier for code generators to get a shape index
that contains only shapes that they typically want to generate.
A convenience method was added to PluginContext to make this more
apparent when implementing SmithyBuild plugins. The result is also
cached since it can be an expensive thing to compute.

Add method to get non-trait shapes

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/PaginatedTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.json

This allows the use of path expressions in paginator outputs. This enables
customers to have result wrapper shapes, which is a common pattern in XML
protocols.

Allow using path expressions in paginator outputs

---

smithy-build/src/main/java/software/amazon/smithy/build/FileManifest.java
smithy-build/src/test/java/software/amazon/smithy/build/FileManifestTest.java

Writing a class resource to a file manifest by calling
getClass().getResourceAsStream("...") will trip up static analysis tools
like SpotBugs since the InputStream is never closed. This commit adds
methods to write resources from a class into a FileManifest that avoid
this issue.

Add method to write class resource to manifest

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLoader.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.smithy

Fix parse error when apply is at eof

---

aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
aws/smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/custom-auth-type-authorizer.json
aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizerDefinition.java
aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
docs/source/spec/amazon-apigateway.rst

This lets customers specify the `authType` themselves. Previously we
had always set it to `awsSigv4` or `custom` (depending on the
scheme), and that behavior is still the default.

Allow authType to be specified

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TargetValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator.json

Prevent list/set member from targeting container

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java

*Issue #163*
*Allow model assembling from symlink model files / directory. Model Assembler is currently ignoring symlink directories and files.*

Allow model assembling from symlink model files / directory

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/CachingSymbolProvider.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolProvider.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/CachingSymbolProviderTest.java

Add a caching SymbolProvider

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolReference.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TypedPropertiesBag.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolReferenceTest.java

This commit updates SymbolReference to now have an "alias" to allow a
symbol to be referenced with an alias. By default, the alias is assigned
the same value as the name of the referenced symbol. However, some code
generators may wish to alias referenced symbols to ensure that they do
not conflict with generated symbols (for example, you might want to
alias "SmithyStructure" as "$SmithyStructure" because no generated type
would ever start with '$').
Code generators that do not support or need aliases are free to ignore
this added property.

Add ability to alias referenced symbols

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependency.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolDependencyTest.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolTest.java

Add a way for symbols to introduce dependencies

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependency.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolDependencyTest.java

This commit adds a couple helper methods used to aggregate symbol
dependencies into a map of maps. By default, conflicting package
versions will throw when two packages conflict. The merge behavior
can be customized by providing a custom merge function (for example, it
can de-conflict, throw, implement a better, picking strategy, etc.).

Add method to gather dependencies

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ShapeIdShader.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ShapeIdShaderTest.java

This abstraction can be used when generating code so that code is
generated into a consolidated namespace rather than spread across
all of the namespaces used in a Smithy model. `SymbolProvider`
implementations can use the `ShapeIdShader` to handle renaming
shape IDs before they convert the shape ID into a symbol appropriate
for that language. This abstraction essentially normalizes shape IDs
before the ID is converted into a language-specific symbol.
For example, if you want to generate code into the "EC2" namespace,
could set the `targetNamespace` to "EC2". If the service shape
that is being generated is in the "com.amazon.ec2" namespace, then you
could set the `rootNamespace` to "com.amazon.ec2" to completely
elide that namespace so that "com.amazon.ec2" is mapped to "EC2".
Any …

Add a shape ID shader to help with codegen

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/CachingSymbolProvider.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ReservedWordSymbolProvider.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolProvider.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/CachingSymbolProviderTest.java
codegen/smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ReservedWordSymbolProviderTest.java

This commit adds the ability to manually escape reserved words from a
SymbolProvider for SymbolProviders that need to be re-entrant (e.g.,
when creating symbols for aggregate shapes, you often need to
recursively create a symbol for the member). Re-entrant symbol providers
can't use the decorator approach since they need access to the reserved
words contained in the decorator. In these cases, one needs to pass an
"Escaper" into the SymbolProvider and manually escape symbols.
One other change here is to tighten up the interface of SymbolProvider
to change toMemberName() from accepting a Shape to accepting only a
MemberShape. While technically a breaking change, this was always the
intention but for some reason the change was never made.
By …

Add ability to manually escape reserved words

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

The openBlock method now takes a Runnable that is called inside of the
block. The block is then automatically closed when the Runnable
completes. This makes code the uses CodeWriter easier to follow since it
forces indentation and doesn't require the closing "}" to be explicitly
added.

Add helper methods for CodeWriter#openBlock

---

aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUnusedComponents.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OperationObject.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java

CORS preflight options checks are sent without authentication, and so
the generated OPTIONS integrations should have an empty
"security" list.
To enable this, I made the list of security settings an `Optional` to distinguish between an empty list and a list that wasn't set. This is a bit odd in terms of the rest of the code base where we simply don't serialize empty lists. It's needed so that we can special case the OPTIONS methods from the general "security" setting. The alternative is to explicitly set the "security" setting on every method, which seems like it would be error prone.

Disable authentication on generated CORS options

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/DiffCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidateCommand.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/JarModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java

When running Smithy in a build tool like Gradle, Smithy is run multiple
times within a thread. Java's URLConnection has a cache built-in for
loading JARs, and when a JAR is updated during a Smithy build, it can
cause checksum exceptions when attempting to load that same JAR from a
subsequent run through the cache. This commit disables the cache when
running Smithy through the CLI to prevent this issue (Gradle runs Smithy
via the CLI in a thread).
(I couldn't find a way to test this other than manually test that it fixed the issues I was running into when using it with the Gradle plugin)

Disable URLConnection cache in CLI

---

smithy-build/src/main/java/software/amazon/smithy/build/PluginContext.java
smithy-build/src/test/java/software/amazon/smithy/build/PluginContextTest.java

Some abstractions might want to use the PluginContext as a way to
provide configuration options when building artifacts. This commit makes
it easier to modify specific parts of the PluginContext as needed
without needing to manually copy properties that haven't changed over.

Add toBuilder to PluginContext

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java

Make CodeWriters intercept Object instead of String
This commit makes CodeWriter section interceptors deal with Object
instead of String. This allows for the toString() method of the
intercepted text to be wrapped by classes that extend from CodeWriter in
order to determine if any side effects from the original content should
take effect or be discarded. The general idea is that if toString() was
called on the original content of an intercepted section, then original
contents are also going to be written to the CodeWriter, meaning any
side effects should also occur (for example, adding imports).
Allow pushState and popState to be overridden
When extending CodeWriter, you might need to also track state like
imports in a corresponding stack. This is now possible since pushState
and popState …

Allow state override

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

The contents of captured named states needs to be escaped when writing
it to ensure that any "$" signs that may have been escaped or expanded
in the original content are passed through as-is.

Escape popped state content

---

docs/source/spec/xml.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-flattened.json

Allow the xmlFlattened trait to be on members

---

docs/source/spec/http.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpHeaderTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpHeaderTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-request-response-validator.errors

This moves the validation for the value of the httpHeader trait to
the HttpHeaderTraitValidator and makes that validation a DANGER
instead of an ERROR so that it can be overridden if necesessary.

Make httpHeader value validation produce dangers

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/HttpBindingIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/TimestampFormatTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/HttpBindingIndexTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/TimestampFormatTraitTest.java

Add helper to detect HTTP-based timestampFormats

---

docs/source/spec/xml.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/XmlNamespaceTrait.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/XmlNameTraitTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/XmlNamespaceTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-name.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-name.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-namespace.json

This updates the xmlnamespace trait to allow specifying a prefix to
pull the namespace into. It further updates the pattern for the
xmlname trait to allow specifying a name with a prefix, e.g.
`myprefix:myname`.

Allow specifying xml namespace prefix

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/test-model.json

Shape ID serialization was inconsistent in that members would use
relative IDs when possible, while direct targets from things like input,
output, and operations would always use absolute IDs. This commit
updates model serialization to use relative shape IDs when possible.

Make shape ID serialization consistent

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConverter.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/HttpBindingIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MemberShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EffectiveTraitQuery.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/EffectiveTraitQueryTest.java

This commit fixes a bug in the JSON schema converter where a member was
not being excluded if the shape targeted by the member is marked as
private. To address this in a way that helps other write similar code, I
made an abstractions for querying the effective traits of a member based
on a query object that can be extended in the future. I also moved the
getMemberTrait and findMemberTrait methods to Shape itself rather than
just on MemberShape to make them easier to use in situations where you
want to get traits from a shape in a normalized way across regular
shapes and member shapes.

Improve member trait querys and fix JSON bug

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConverter.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/RefStrategy.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/RefStrategyTest.java

TODO: break this API to make this work more reliably.
This is addressed by temporarily setting a de-conflicting ref
strategy. This is the minimal change needed to fix a reported
bug, but it is a hack and we should break this API before GA.
We want to do the right thing by default. However, the default
that was previously chosen didn't account for the possibility
of shape name conflicts when converting members to JSON schema
pointers. For example, consider the following shapes:
- A member of a list, foo.baz#PageScripts$member
- A member of a structure, foo.baz#Page$scripts
If we only rely on the RefStrategy#createDefaultStrategy, then
we would actually generate the same JSON schema shape name for
both of the above member shapes: FooBazPageScriptsMember. To
avoid this, we need to know the …

Fix an issue where JSON schema member names collided

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependency.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolReference.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TypedPropertiesBag.java

Update equals to include typed bag parent

---

codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolContainer.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependency.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependencyContainer.java
codegen/smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolReference.java

A SymbolContainer is an abstraction over Symbols that allows for more
easily creating and aggregating Symbols together.

Add abstraction over Symbols

---

docs/source/spec/xml.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-flattened.json

Allow XML maps to be flattened

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/CollectionShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MapShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/StructureShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/UnionShape.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/MarkAndSweep.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/RemoveShapes.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ReplaceShapes.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/BottomUpNeighborVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/NeighborVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/PathFinderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ListShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/MapShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeIndexTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/StructureShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/EffectiveTraitQueryTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/adds-query-timestamp-format.openapi.inlined.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/adds-query-timestamp-format.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.not-inlined.json

This commit updates the ShapeIndex to automatically add and remove
members from shapes that have members. This required some extra
functionality be introduced to shapes which then in turn resulted in
cleanup in other places in the codebase.
1. ShapeIndex now automatically adds and removes members when shapes are
added.
2. There is now a members() method on all shapes to return the members
contained in the shape (if any). Shapes that have no members just
return an empty collection by default, and shapes that do contain
members override the abstract method.
3. Because members are now less important to contain a reference to
outside of their containing shapes (since you don't need to
explicitly add them to a shape index), you can now automatically
create member shapes for container shapes by …

Add and remove members to index automatically

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuild.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildResult.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/trigger-plugin-error.json
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/projection-build-failure.json
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/valid-model.smithy

smithy-build used to load every model from every projection into memory
at once. This was not ideal since some use cases utilize hundreds of
projections. For example, in AWS SDKs, we create a projection for every
AWS service, which is hundreds of them with tens-of-thousands of shapes
and operations.
This commit updates smithy-build to support two modes: in-memory and
streaming. The in-memory mode is useful for testing or one-off
integrations. The streaming mode is useful for actually executing
smithy-build from the CLI so that results are outputted to stdout as
they happen and not all models are loaded into memory.
The CLI was updated to significantly change its output to show more
information about things that go wrong and print more statistics. Every
projection and plugin is attempted …

Update smithy-build to be streaming

---

docs/source/spec/core.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait.json

Allow anything but operations, services, and resources to have the
sensitive trait.

Expand sensitive applicability

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/RangeTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/range-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/range-trait.json

This is still a valid configuration, it just only allows a single
value.

Allow min to equal max in range

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/LengthTraitValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/length-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/length-trait.json

Add validation for length trait values

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.errors

This allows the page size member to be required, but still defaults
it to failing the build when it is.

Allow page member to be required

---

aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryValidator.java
aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/errorfiles/no-input.json

The validation for endpoint discovery previously did not allow for
the endpoint operation to have a subset of the allowed inputs, this
change fixes that.

Properly allow omitting endpoint operation inputs

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-trait.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mappers/streaming-service.smithy

Limit streaming traits to top level members

---

docs/source/spec/http-protocol-compliance-tests.rst
docs/source/spec/index.rst
settings.gradle.kts
smithy-protocol-test-traits/build.gradle.kts
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMessageTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestsInputValidator.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestsTrait.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpResponseTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpResponseTestsErrorValidator.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpResponseTestsOutputValidator.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpResponseTestsTrait.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/UniqueProtocolTestCaseIdValidator.java
smithy-protocol-test-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-protocol-test-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/manifest
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/java/software/amazon/smithy/protocoltests/traits/RunnerTest.java
smithy-protocol-test-traits/src/test/java/software/amazon/smithy/protocoltests/traits/TraitTest.java
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-request-features.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-response-features.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-duplicate-ids.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-duplicate-ids.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-params.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-params.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/test-case-on-error.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/say-goodbye.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/say-hello.smithy

Add protocol compliance test traits

---

smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeFactory.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeFactory.java

Node#parse should be used instead. NodeFactory and DefaultNodeFactory
will be removed in 0.10.0.

Mark NodeFactory and DefaultNodeFactory Deprecated

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampValidationStrategy.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/timestamp-validation.smithy

This commit updates the Node validation visitor to allow for a
configurable strategy for validating timestamps. This is needed in order
to validate that the timestamps provided for protocol tests are always
in epoch seconds.

Add ability to configure timestamp validation

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/BoxIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/BoxIndexTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java

Add BoxIndex

---

smithy-model/src/main/java/software/amazon/smithy/model/Model.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
smithy-model/src/test/java/software/amazon/smithy/model/ModelTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTest.java

Add more expect methods to Shape and Model

---

docs/source/spec/http-protocol-compliance-tests.rst
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestCase.java
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-request-features.smithy

queryParams in protocol compliance tests previously used a map of query
string parameter names to values. However, this approach makes it
impossible to define test cases for query string parameter lists where
the serialized query string keys are repeated (which is the default
serialization format used in Smithy HTTP protocol bindings).
Now queryParams is a list of the query string parameter key value pairs
(e.g., `queryParams: ["foo=bar", "foo=baz%20bam"]`. This allows for testing
any kind of query string serialization format, including repeated key
parameters.

Use list of string for queryParams

---

docs/source/spec/xml.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-flattened.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/xml-flattened.json

This commit updates the XML traits spec to be made more generic and
framed in terms of binding to XML. XML traits have been restricted to
only apply to shapes in which they are actually supported. Many more
examples have been added to the XML spec (note that I selectively did
not include a JSON equivalent example when a JSON example adds no
expository value).

Clean up and rewrite spec for XML bindings

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java

This commit further implements the ability to disable JAR file caching
when loading Smithy models. This is necessary to make loading models
from JARs when using build tools like Gradle more reliable.

Disable URLConnection cache

---

.travis.yml
build.gradle.kts
smithy-model/src/main/java/software/amazon/smithy/model/Model.java

This commit adds support for the `-Plog-tests` option. When enabled,
this will generate a log line for each "passed", "skipped", or "failed"
test event.
Fixes #156 

Add log-tests project property

---

config/checkstyle/checkstyle.xml
docs/source/spec/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/Ec2QueryNameTrait.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/ec2-query-name.json

This adds a trait to specify the name of an EC2 structure member when
it is used as an input.

Add ec2QueryNameTrait

---

settings.gradle.kts
smithy-aws-protocol-tests/build.gradle.kts
smithy-aws-protocol-tests/model/json-rpc-1-1/main.json
smithy-aws-protocol-tests/model/rest-xml/document-lists.smithy
smithy-aws-protocol-tests/model/rest-xml/document-maps.smithy
smithy-aws-protocol-tests/model/rest-xml/document-structs.smithy
smithy-aws-protocol-tests/model/rest-xml/document-xml-attributes.smithy
smithy-aws-protocol-tests/model/rest-xml/empty-input-output.smithy
smithy-aws-protocol-tests/model/rest-xml/endpoint-host-trait.smithy
smithy-aws-protocol-tests/model/rest-xml/errors.smithy
smithy-aws-protocol-tests/model/rest-xml/http-headers.smithy
smithy-aws-protocol-tests/model/rest-xml/http-labels.smithy
smithy-aws-protocol-tests/model/rest-xml/http-payload.smithy
smithy-aws-protocol-tests/model/rest-xml/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/rest-xml/http-query.smithy
smithy-aws-protocol-tests/model/rest-xml/main.smithy
smithy-aws-protocol-tests/model/rest-xml/shared-types.smithy

Add AWS REST XML protocol tests

---

smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/empty-input-output.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/input-lists.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/input-maps.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/input.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/xml-errors.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/xml-lists.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/xml-maps.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/xml-structs.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/empty-input-output.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/errors.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/http-headers.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/http-labels.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/http-payload.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/http-prefix-headers.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/http-query.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/json-lists.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/json-maps.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-json/json-structs.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/document-lists.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/document-maps.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/document-structs.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/document-xml-attributes.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/empty-input-output.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/errors.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/http-headers.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/http-labels.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/http-payload.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/http-prefix-headers.smithy
smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/rest-xml/http-query.smithy
smithy-aws-protocol-tests/src/test/java/software/amazon/smithy/aws/protocoltests/ModelTest.java

Migrate protocol tests to new operation syntax

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/LoaderVisitorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

Continuing to parse models after a syntax error will result in many
unintelligible validation events that obscure the actual syntax error.
Fixes #262

Fail model builds early when syntax errors occur

---

docs/source/spec/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/UnsignedPayloadTrait.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/UnsignedPayloadTraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/unsigned-request-payload.json

The aws.api#unsignedPayload trait currently takes a set of signing names to
enable unsigned payloads on. However, I don't think we will ever need this
level of granularity and it makes it more difficult to implement codegen.
Closes #232

[0.10] Simplify unsignedPayload trait to be an annotation

---

docs/source/spec/core.rst
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.json
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-model/src/main/java/software/amazon/smithy/model/traits/AuthDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ProtocolDefinitionTrait.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/AuthDefinitionTraitTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/ProtocolDefinitionTraitTest.java

Protocol traits now list the traits that protocol implementations must
understand in order to successfully implement the protocol. This
provides the ability to better ensure correctness of protocol
implementations as protocols evolve.

[0.10] Add protocol and auth trait requirements

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/UnstableTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/UnstableTraitValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/UnstableTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/unstable-trait-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/unstable-trait-validator.json

Adds `UnstableTrait` that can be used to indicated a shape is unstable and may change in the future.
Adds `UnstableTraitValidator` that emits warnings when a model contains shapes that apply unstable traits.

[0.10] Adds UnstableTrait and UnstableTraitValidator

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/AstModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/LoaderVisitorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/apply-use-1.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/apply-use-2.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/apply-use-3.smithy

* Ensures that JSON IDL models are loaded before IDL models to reduce forward reference lookups when loading IDL models.
* Move IDL specific loading logic to IDL
This commit moves all IDL-specific model loading logic into the IDL loader and out of the LoaderVisitor. This cleans up the LoaderVisitor and also fixes a bug in how the `apply` statement wasn't properly resolving the targeted shape ID (it always assumed that the target was in the current namespace).

[0.10] Clean up LoaderVisitor and IDL loading

---

docs/source/spec/core.rst

Fix formatting on unstable trait documentation

[0.10] Fix unstable trait doc

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeIdTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/boolean-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/collection-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/document-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/documentation-trait.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/number-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/object-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/optional-namespaces-are-stripped.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/service-shapes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/simple-shapes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/string-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/input.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/output/ns.primitives.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/output/ns.structures.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/test-model.json
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

This adds the ability to take an in-memory model and serialize it into the Smithy IDL format.

[0.10] Support Smithy IDL Serialization

---

docs/source/guides/converting-to-openapi.rst
smithy-build/src/main/java/software/amazon/smithy/build/JsonSubstitutions.java
smithy-build/src/test/java/software/amazon/smithy/build/JsonSubstitutionsTest.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/SchemaDocument.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/SchemaDocumentTest.java
smithy-model/src/main/java/software/amazon/smithy/model/node/ArrayNode.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodePointer.java
smithy-model/src/test/java/software/amazon/smithy/model/node/ArrayNodeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodePointerTest.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConstants.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/CoreExtension.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/OpenApiJsonAdd.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/OpenApiJsonSubstitutions.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/mappers/OpenApiJsonAddTest.java

This commit adds a new mapper to OpenAPI that allows changing specific
parts of the generated schema using JSON pointers that inject values
using semantics similar to JSON Patch. This approach is preferred over
string substitutions because it is more explicit and does not encourage
modelers to include placeholders in their models.
The JSON substitutions mapper now allows for any string to be replaced.
This is still basically just as safe since it only replaces exact string
matches (it doesn't replace inside of larger strings). Most importantly,
the use of placeholder like strings encouraged modelers to include
placeholders in their models. By opening up the string to any value, you
can now replace whatever was generated from real model values.
To achieve this, I implemented a JSON Pointer …

[0.10] Add JSON pointer, patch, and OpenAPI mapper

---

docs/source/spec/amazon-apigateway.rst
docs/source/spec/aws-core.rst
docs/source/spec/aws-iam.rst
docs/source/spec/core.rst
docs/source/spec/http-protocol-compliance-tests.rst
docs/source/spec/http.rst
docs/source/spec/xml.rst

Fixes #296
Fixes #295
This updates an example in the docs showcasing the interaction of
collection operations and implicit identifier bindings that had not been
updated when the `collectionOperations` member was added to resource
shapes.
This also improves the consistency of trait value documentation. Primarily it
does this by using Smithy terminology everywhere it references shapes,
where previously there was a lot of JSON terminology usage. In addtion the
following smaller consistency improvements were made:
* Shape types are always given backtick markup
* Parametric shape types now always use java-style carrots in
in shorthand. Previously there were a mix of ways defining them
in shorthand.
By submitting this pull request, I confirm …

Update documentation to improve consistency

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/package-info.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/iam/package-info.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/package-info.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/package-info.java
smithy-mqtt-traits/src/main/java/software/amazon/smithy/mqtt/traits/package-info.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/package-info.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SmithyGenerated.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SmithyInternalApi.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SmithyUnstableApi.java

These annotations allows different parts of the Smithy implementation to
evolve at their own pace and better communicate how end users should use
the code. The SmithyUnstableApi annotations indicates that an API is
subject to change and should be considered experimental. The
SmithyInternalApi annotation indicates that an API should not be relied
on by end users outside of the Smithy software.amazon.smithy packages.
The SmithyGenerated annotation indicates that a package or type was
generated and should not be edited by hand.

Add unstable, internal, and generated annotations

---

smithy-aws-protocol-tests/model/shared-types.smithy

Some of the protocols traits are marked as deprecated. One of the changes picked up from master was a validator that emits warnings for deprecated traits. Since we know those traits are deprecated, this suppresses the warnings.

[0.10] Suppress deprecation warnings in protocol tests

---

smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeSerializers.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java

This commit sorts keys in NodeMapper serializer's output. Methods are
returned in an arbitrary order by default, so using sorted order is
friendlier. Further, this commit cleans up how deserialization finds
methods (it's a non-functional change, just cleanup)

Sort keys alphebetically and cleanup

---

smithy-aws-protocol-tests/model/ec2-query/main.smithy
smithy-aws-protocol-tests/model/query/main.smithy
smithy-aws-protocol-tests/model/rest-json/main.smithy
smithy-aws-protocol-tests/model/rest-xml/main.smithy

This PR adds references to aws-protocol-tests models to unreferenced operations.

Add references to all operations

---

docs/source/spec/core.rst

This PR fixes idRef doc examples to use the correct trait namespace, target type and fully qualified shapeId.

Fix idRef doc examples

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/apply-trait-to-prelude.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/apply-trait-to-prelude.smithy

Applying a trait to a prelude shape is a recipe for disaster. For
example, if someone marked the smithy.api#String shape as private,
virtually every model would break.

Disallow traits applied to public prelude shapes

---

smithy-model/src/main/java/software/amazon/smithy/model/pattern/SmithyPattern.java
smithy-model/src/main/java/software/amazon/smithy/model/pattern/UriPattern.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EndpointTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HostLabelTraitValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpUriConflictValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/pattern/SmithyPatternTest.java
smithy-model/src/test/java/software/amazon/smithy/model/pattern/UriPatternTest.java

SmithyPattern is a lot less annoying to use since it doesn't conflict
with the Java regex Pattern.

Rename Pattern to SmithyPattern

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampFormatPlugin.java

Fix Java ISO_INSTANT timestamp validation

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/Component.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OpenApi.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java

Backports fix from 0.10 to ensure that schemaDocumentExtensions are added.

Ensure that schemaDocumentExtensions are added

---

smithy-aws-protocol-tests/model/ec2-query/input-lists.smithy
smithy-aws-protocol-tests/model/ec2-query/input.smithy
smithy-aws-protocol-tests/model/ec2-query/main.smithy
smithy-aws-protocol-tests/model/ec2-query/xml-lists.smithy
smithy-aws-protocol-tests/model/json-rpc-1-1/main.json
smithy-aws-protocol-tests/model/query/input-maps.smithy
smithy-aws-protocol-tests/model/query/input.smithy
smithy-aws-protocol-tests/model/query/main.smithy
smithy-aws-protocol-tests/model/query/xml-lists.smithy
smithy-aws-protocol-tests/model/query/xml-maps.smithy
smithy-aws-protocol-tests/model/query/xml-structs.smithy
smithy-aws-protocol-tests/model/rest-json/empty-input-output.smithy
smithy-aws-protocol-tests/model/rest-json/errors.smithy
smithy-aws-protocol-tests/model/rest-json/http-headers.smithy
smithy-aws-protocol-tests/model/rest-json/http-labels.smithy
smithy-aws-protocol-tests/model/rest-json/http-query.smithy
smithy-aws-protocol-tests/model/rest-json/json-lists.smithy
smithy-aws-protocol-tests/model/rest-json/json-structs.smithy
smithy-aws-protocol-tests/model/rest-json/main.smithy
smithy-aws-protocol-tests/model/rest-xml/document-lists.smithy
smithy-aws-protocol-tests/model/rest-xml/document-maps.smithy
smithy-aws-protocol-tests/model/rest-xml/document-structs.smithy
smithy-aws-protocol-tests/model/rest-xml/document-xml-attributes.smithy
smithy-aws-protocol-tests/model/rest-xml/empty-input-output.smithy
smithy-aws-protocol-tests/model/rest-xml/http-headers.smithy
smithy-aws-protocol-tests/model/rest-xml/http-labels.smithy
smithy-aws-protocol-tests/model/rest-xml/http-payload.smithy
smithy-aws-protocol-tests/model/rest-xml/http-query.smithy
smithy-aws-protocol-tests/model/rest-xml/main.smithy

Fixes several issues with EC2-Query tests
* Adds an aws.api#service trait, sdkId="EC2 Protocol"
* Uses correct Idempotency token property names
* Uses correct Idempotency token test Action names
* Fixes auto-generated idempotency token value
* Fixes list member name capitalization
* Adds missing "/" to a closing XML element
Fixes several issues with the JSON-RPC-1.1 tests
* Fixes service name in several x-amz-target headers
* Fixes an operation name in x-amz-target header
* Removes errant required header when not supplied
* Fixes several [] vs {} discrepancies for empty structures
* Adds missing body for operation that has a response
Fixes several issues with the Query tests
* Adds an aws.api#service trait, sdkId="Query Protocol"
* Fixes several test Action names
* Fixes auto-generated …

Protocol test fixes

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/RenameShapes.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/RenameShapesTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/rename-shape-test-model.json

This PR adds a RenameShapes model transformer that takes a map of ShapeId to ShapeId pairs.
Shape members are updated for consistency when any member-containing aggregate shape has been renamed.

Add RenameShapes model transformer

---

CHANGELOG.md
build.gradle.kts
docs/source/guides/building-models/gradle-plugin.rst
docs/source/guides/converting-to-openapi.rst
smithy-codegen-freemarker/README.md

* Add `RenameShapes` model transformer ([#318](https://github.com/awslabs/smithy/pull/318))
* Build `ValidationEvents` are now sorted ([#263](https://github.com/awslabs/smithy/pull/263))
* Smithy CLI logging improvements ([#263](https://github.com/awslabs/smithy/pull/263))
* Model builds fail early when syntax errors occur ([#264](https://github.com/awslabs/smithy/pull/264))
* Warn when a deprecated trait is applied to a shape ([#279](https://github.com/awslabs/smithy/pull/279))
* Fix behavior of `schemaDocumentExtensions` when converting to OpenAPI ([#320](https://github.com/awslabs/smithy/pull/320))
* Fix discrepancies in `smithy-aws-protocol-tests` ([#309](https://github.com/awslabs/smithy/pull/309), [#321](https://github.com/awslabs/smithy/pull/321))
* Properly format test case …

Bump version to 0.9.8

---

docs/source/spec/core.rst
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.json
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json
smithy-aws-protocol-tests/model/shared-types.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/test-service.json
smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumDefinition.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringEnumPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/EnumTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/EnumTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enum-trait-validation.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enum-trait-validation.json
smithy-model/src/test/resources/software/amazon/smithy/model/validation/node-validator.json
smithy-mqtt-traits/src/test/resources/software/amazon/smithy/mqtt/traits/errorfiles/job-service.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.json

The enum trait is currently a map of enum value to the enum definition.
This means that models often look like this:
```
@enum(foo: {}, bar: {})
string MyString
```
Ideally, a name and documentation are provided too:
```
@enum(
foo: {name: "FOO", documentation: "foo docs..."},
bar: {name: "BAR", documentation: "bar docs..."})
```
However, the difference between the key and "name" has resulted in
confusion as to which is which. This is caused by a couple things:
1. The key doesn't tell you what it defines. You have to know that the
the key defines the value of the enum to make sense of the trait.
2. The key has to be quoted if it deviates from the allows ABNF for node
object keys. This has also led to confusion.
Although this is a breaking change, using a list of structures where …

Make enum trait a list of structures

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/security/XApiKey.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/security/XApiKeyTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/http-api-key-security.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/http-api-key-security.openapi.json

Ensures that http-x-api-key adds the appropriate CORS headers and that
it uses the lowercase header name to make API Gateway happy.
Closes #327

Fix http-x-api-key

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/effective-authorizers.smithy

We previously weren't adding security to individual operations if the
operation differend from the security of the operation differed from the
service because of an applied authorizer trait.

Adds security to individual operations

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/effective-authorizers.smithy

We previously weren't adding security to individual operations if the
operation differend from the security of the operation differed from the
service because of an applied authorizer trait.
This is equivalent to f434db76a841c062bea1d96985d159c8f7b0f2ed

Adds security to individual operations [0.10]

---

smithy-aws-protocol-tests/model/json-rpc-1-1/main.json

Validate b64 encoding for json-rpc-1.1

---

docs/themes/smithy/landing.html
docs/themes/smithy/layout.html
docs/themes/smithy/static/custom-tabs.css
docs/themes/smithy/static/default.css_t
docs/themes/smithy/theme.conf

This commit updates the website color scheme to be a brownish red / iron
ore color scheme rather than the more clinical feeling blue. Several
other theme changes are made, including putting borders above headings
rather than below, automatically numbering headings in specification
pages using CSS, and adding contrast between the nav sidebar and the
content.
Homepage:
Top of content pages:
Inside of content pages:

Make color scheme less clinical

---

smithy-aws-protocol-tests/model/rest-json/http-headers.smithy
smithy-aws-protocol-tests/model/rest-json/main.smithy
smithy-aws-protocol-tests/model/rest-xml/http-headers.smithy
smithy-aws-protocol-tests/model/rest-xml/main.smithy

This commit splits the NullAndEmpty headers protocol test in to two
distinct operations, one tagged client-only and the other tagged
server-only. This is done for both aws.rest-json-1.1 and aws.rest-xml.

Update NullAndEmptyHeaders protocol tests

---

CHANGELOG.md
build.gradle.kts
docs/source/guides/building-models/gradle-plugin.rst
docs/source/guides/converting-to-openapi.rst
smithy-codegen-freemarker/README.md

* Add security to individual operations in OpenAPI conversion ([#329](https://github.com/awslabs/smithy/pull/329))
* Fix an issue with header casing for `x-api-key` integration with API Gateway ([#330](https://github.com/awslabs/smithy/pull/330))
* Fix discrepancies in `smithy-aws-protocol-tests` ([#333](https://github.com/awslabs/smithy/pull/333), [#335](https://github.com/awslabs/smithy/pull/335),
[#349](https://github.com/awslabs/smithy/pull/349))

Bump version to 0.9.9

---

docs/source/spec/core.rst
docs/themes/smithy/static/default.css_t
docs/themes/smithy/theme.conf
smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/NoReplaceTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/no-replace-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/no-replace-trait.json

Add noReplace trait

---

docs/source/conf.py

Fixes doc build warnings:
```WARNING: html_static_path entry '/...smithy/docs/source/_static' does not exist```
```WARNING: favicon file '_static/favicon.png' does not exist```

Fix doc build warning for favicon

---

docs/source/guides/converting-to-openapi.rst

Adds documentation for ``aws.auth#cognitoUserPools`` to the OpenAPI conversion guide.
Closes #8 

Add Cognito User Pools documentation to OpenAPI guide

---

docs/source/guides/converting-to-openapi.rst
docs/source/spec/aws-auth.rst

Fixes formatting for ```aws.auth#cognitoUserPools``` trait to match other authentication traits.

Fix cognitoUserPools trait documentation formatting

---

smithy-linters/src/main/java/software/amazon/smithy/linters/CamelCaseValidator.java
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/camel-case-validator-defaults-test.json

Closes #354 
This PR updates the CamelCaseValidator to ignore trait shapes marked with authDefinition or protocolDefinition traits.

Ignore CamelCasing on auth and protocol shape traits

---

docs/source/spec/core.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/StreamingTraitValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-trait.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/streaming-service.smithy

This updates the streaming trait to apply directly to shapes instead of
members. This was previously restricted to members because it made the
model easier to validate and grok at a glance. However, keeping it on
members introduces potential errors in code generation. A given blob
could have both the streaming trait and the media type trait, for
instance. Both of these traits could result in a new type being created,
but since the streaming trait is applied to a member that type is
implicit. The code generator would have to try to generate a name that
doesn't conflict with any existing names, which is very error prone and
likely would result in unfortunate names. Moving this trait to the
shape directly makes the naming concern an explicit part of modeling,
where it will only have to be …

[0.10] Apply streaming trait directly to shapes

---

smithy-aws-protocol-tests/model/awsJson1_1/main.json
smithy-aws-protocol-tests/model/awsQuery/input-maps.smithy
smithy-aws-protocol-tests/model/awsQuery/input.smithy
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-maps.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
smithy-aws-protocol-tests/model/ec2Query/input-lists.smithy
smithy-aws-protocol-tests/model/ec2Query/input.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy
smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy
smithy-aws-protocol-tests/model/restJson1/errors.smithy
smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restJson1/http-labels.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restJson1/json-lists.smithy
smithy-aws-protocol-tests/model/restJson1/json-structs.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/document-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-aws-protocol-tests/model/restXml/document-xml-attributes.smithy
smithy-aws-protocol-tests/model/restXml/empty-input-output.smithy
smithy-aws-protocol-tests/model/restXml/http-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-labels.smithy
smithy-aws-protocol-tests/model/restXml/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

This is a reapplication of fixes in the following PRs from master:
#321
#333
#335 
#349
-----
Fixes several issues with EC2-Query tests
* Adds an aws.api#service trait, sdkId="EC2 Protocol"
* Uses correct Idempotency token property names
* Uses correct Idempotency token test Action names
* Fixes auto-generated idempotency token value
* Fixes list member name capitalization
* Adds missing "/" to a closing XML element
Fixes several issues with the JSON-RPC-1.1 tests
* Fixes service name in several x-amz-target headers
* Fixes an operation name in x-amz-target header
* Removes errant required header when not supplied
* Fixes several [] vs {} discrepancies for empty structures
* Adds missing body for operation that has a response
Fixes several issues with the Query tests
* Adds an …

Update Protocol Tests

---

docs/source/guides/converting-to-openapi.rst

Adds documentation for ``smithy.api#cors`` trait to the OpenAPI conversion guide.

Add CORS documentation to OpenAPI guide

---

docs/source/guides/converting-to-openapi.rst
docs/source/spec/core/documentation-traits.rst
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-prefix-headers.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.json
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExternalDocumentationTrait.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/shapes/MemberShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/ExternalDocumentationTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/external-documentation.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/external-documentation.json
smithy-mqtt-traits/src/test/resources/software/amazon/smithy/mqtt/traits/errorfiles/job-service.smithy
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConstants.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java

This commit updates the @externalDocumentation trait to be a map of
named urls instead of a single url. This provides more context for
the given links and enables the ability to have multiple links per
trait application.
An update to the OpenApi conversion has been made to utilize this
when populating "externalDocs" fields. A configurable, priority
ordered list of url names is available through
`"openapi.externalDocs"`; it defaults to "Homepage", "Api
Reference", "User Guide", "Developer Guide", "Reference", and
"Guide". This list is compared case insensitively. This also
fixes an issue where "externalDocs" fields could be generated as
strings instead of the properly formatted external documentation
object in the resulting OpenApi document.
-----
By submitting this pull request, I confirm …

Update externalDocumentation to a named map

---

docs/source/spec/core/stream-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/RequiresLengthTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/StreamingTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/StreamingTraitTest.java

Using `requiresLength` as a property of the `streaming` trait no longer
makes sense because event streams should virtually never have a known or
finite length before they begin.

Make requiresLength a separate trait

---

docs/source/spec/core/stream-traits.rst

Fix target shape id on event stream output json example.

Fix event stream json example

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizerDefinition.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTrait.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTraitValidator.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/IntegrationResponse.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/IntegrationTrait.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/MockIntegrationTrait.java
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-apigateway-traits/src/test/java/software/amazon/smithy/aws/apigateway/traits/IntegrationTraitTest.java
smithy-aws-apigateway-traits/src/test/java/software/amazon/smithy/aws/apigateway/traits/MockIntegrationTraitTest.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeSerializers.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeMapper.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java

Use NodeMapper in API Gateway traits
This commit updates API Gateway traits to use the NodeMapper and changes
different getter/setter methods to use NodeMapper compatible API names.
Further, support for omitting the toNode implementation of a class was
added so that the NodeMapper can be used inside of a toNode method.
Finally, support for omitting empty arrays and objects was added so the
NodeMapper doesn't inject a bunch of empty values when it isn't
desirable.
Add CONVERT_TO_TEXT to OPTIONS and cleanup
CONVERT_TO_TEXT is necessary on OPTIONS request otherwise you may see
500 errors from API Gateway. Further, this commit cleans up several
getters/setters on the IntegrationTrait and MockIntegrationTrait to
match what a code generator would produce and how the NodeMapper works.

Convert options to text

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/BlobLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/CollectionLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/IdRefPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/MapLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/PatternTraitPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringEnumPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringLengthPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampFormatPlugin.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampValidationStrategy.java

NodeValidationVisitors need to be refactored so that they emit
validation events with proper source locations (right now they aren't
tied to any source location). This will require changing the API of
NodeValidatorPlugin implementations, which would be a breaking change.
Because of this, I'm marking these APIs as internal, which will allow us
to safely break these APIs and improve them when we have the time.

Mark node validation visitors internal

---

docs/source/spec/aws/aws-ec2-query-protocol.rst

This documentation is fixed, fleshed out, and updated for consistency
with the `jsonName` trait.
/cc @skmcgrail

Update aws.protocol#ec2QueryName docs

---

docs/source/spec/core/selectors.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorDefinition.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/NeighborProvider.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/RelationshipType.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AndSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AttributeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/EachSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/NeighborSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/NotSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/OfSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/PathFinder.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/Selector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ShapeTypeCategorySelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ShapeTypeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/TestSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/WrappedSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitTargetValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/NeighborProviderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/NeighborSelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/neighbor-test.smithy

A "trait" relationship allows selectors to traverse from shapes to the
the trait shapes applied to the shape. This can be used to query for
things like "services with no protocol traits", "deprecated traits that
are being used on shapes", "traits that aren't referenced by any
shapes", etc.
Trait relationships are not typically needed and add a lot of overhead.
As such, they are opt-in only and enabled in selectors by adding a named
"trait" directed relationship. They're also opt-in in code.
In order to pull this off, I updated the selector API to always require
a Model.

Add "trait" relationship to selectors

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/plugins/CleanTraitDefinitions.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.transform.ModelTransformerPlugin
smithy-model/src/test/java/software/amazon/smithy/model/transform/RemoveShapesTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/remove-shapes.json

Adds CleanTraitDefinitions transformer plugin that removes traits listed on AuthDefinitionTrait and ProtocolDefinitionTrait traits when a shape is removed from a model.

Add CleanTraitDefinitions plugin

---

docs/source/spec/core/documentation-traits.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy

Fixes title trait selector to correctly allow the trait to be applied to services and resources.

Fix title trait selector

---

docs/source/spec/aws/aws-restxml-protocol.rst
docs/source/spec/core/behavior-traits.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/HttpContentMd5Trait.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/httpContentMd5-trait.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/httpContentMd5-trait.json

- add support for `httpContentMd5` trait

`smithy-model`: add support for `httpContentMd5` trait

---

smithy-model/src/main/java/software/amazon/smithy/model/selector/Selector.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitTargetValidator.java

This commit improves the efficiency of the TraitTargetValidator so that
it performs as few checks and selections of the entire model as
possible.

Improve TraitTargetValidator

---

docs/source/spec/aws/aws-cross-protocol.rst
docs/source/spec/aws/aws-restjson1-protocol.rst
docs/source/spec/aws/aws-restxml-protocol.rst
docs/source/spec/aws/index.rst
docs/source/spec/core/xml-traits.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/RestXmlTrait.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/protocols/RestXmlTraitTest.java

This commit adds a `noErrorWrapping` property to the `aws.protocols#restXml`
trait. This property disables the serialization wrapping of error properties
in an 'Error' XML element. This is used to indicate this behavior in services
like Amazon S3.
Along with this change is documentation of many components of the `restXml`
protocol, including examples of the above behavior. Documentation of error
behavior in the `aws.protocols#restJson1` protocol has also been added.

Add noErrorWrapping to AWS restXml

---

CHANGELOG.md
docs/source/spec/aws/aws-cross-protocol.rst

This commit updates the changelog entry for the 1.0.0 release with
contents through PR 394. Breaking changes are annotated with
[BC] or contained in the Breaking Changes section.
-----
*Ed. Note: The minor line break issues below are related to copy/paste into the PR description.*
***Note***: Changes marked with "[BC]" are breaking changes more accurately described in the
specific section. A list of further intended breaking changes have a specific section near
the end of this entry.
* The model format version has beeen updated to `1.0.0` and contains several updates: [BC] ([#357](https://github.com/awslabs/smithy/pull/357), [#381](https://github.com/awslabs/smithy/pull/381)) …

Update 1.0.0 changelog

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cognito-user-pools-security.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-explicit-options.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-custom-gateway-response-headers.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-not-performed.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-performed.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/SecuritySchemeConverter.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mixed-security-service.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/awsv4-security.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/http-api-key-security.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/http-basic-security.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/security/http-digest-security.openapi.json

Adds getOpenApiAuthSchemeName default method which derives an auth scheme name from its shape ID by replacing the `#` with `.`.  Ensures compatibility with  API Gateway authorizer name requirements.

Adjust auth scheme name for compatibility

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.openapi.json

Updates `x-amazon-apigateway-integration` test examples with request parameters and responses to pass validation.

Add request parameters and response members to example

---

docs/source/spec/core/selectors.rst
smithy-model/src/main/java/software/amazon/smithy/model/selector/AttributeSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AttributeValue.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/AttributeValueImpl.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/Parser.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/ScopedAttributeSelector.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/AndSelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/OfSelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/nested-traits.smithy

A shape can now be used as a selector scope allowing for selecting and
comparing multiple top-level attributes of shapes.
This commit also updates AttributeValue to be ready to expose as a
public interface if needed for more advanced selector message formatting
functionality.

Allowing a shape to be selector scope

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-explicit-options.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-explicit-options.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-custom-gateway-response-headers.openapi.json

API Gateway requires a Lambda integration to use Basic Auth.
This PR removes the Basic Auth test cases so that test models will pass validation.

Remove Basic Auth test

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/supports-payloads.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/streaming-service.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

This PR updates the OpenAPI Converter to write requestBody and response content schemas to as references instead of in-line schema definitions.

requestBody and response content schemas as references

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/payloads.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/payloads.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java

When creating request payload schemas, the synthesized schema was unnecessarily creating an additional schema layer.  This PR detects when a synthesized schema is effectively just a wrapper for another schema, and removes that wrapper.

Avoid wrapping request payload schemas

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidationLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorFromDefinitionFactory.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/linters/EmitEachSelectorValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/linters/EmitNoneSelectorValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/linters/emit-each-selector-requires-selectors.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/linters/emit-each-selector-requires-selectors.json

1. Require that selector is set and fail if not.
2. Gracefully handle errors encountered while loading validators.

Improve validation loading error messages

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/Smithy2OpenApi.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/Smithy2OpenApiTest.java

This PR fixes Smithy2OpenApi plugin by correctly setting the config on the converter during the plugin's execution.

Set config on OpenApiConverter in build plugin

---

CHANGELOG.md
docs/source/1.0/guides/building-models/build-config.rst
docs/source/1.0/spec/aws/aws-core.rst
docs/source/1.0/spec/core/constraint-traits.rst
smithy-build/src/main/java/software/amazon/smithy/build/ProjectionTransformer.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildPlugin.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/ExcludeShapesByTag.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/IncludeShapesByTag.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/RemoveUnusedShapes.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/apply-multiple-projections.json
smithy-build/src/test/resources/software/amazon/smithy/build/config-with-env.json
smithy-build/src/test/resources/software/amazon/smithy/build/simple-config.json

This commit removes alias functionality from SmithyBuildPlugin and
ProjectionTransformer. The aliases for existing transforms have been
removed. Documentation has been updated and entries for the
includeMetadata and excludeMetadata transforms were added.
This commit contains other assorted documentation fixes as well.

Remove legacy alias functionalities

---

smithy-model/src/jmh/java/software/amazon/smithy/model/jmh/Selectors.java
smithy-model/src/jmh/resources/software/amazon/smithy/model/jmh/test-model.json
smithy-model/src/jmh/resources/software/amazon/smithy/model/jmh/test-model.smithy
smithy-model/src/main/java/software/amazon/smithy/model/loader/AstModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

This commit adds a setting to disable model validation in the assembler,
and adds some new JMH benches to test loading the IDL/AST models
with/without validation (~92% of the time loading a model is spent
validating models, so I suspect that only applying validators if 1 or
more instances of a trait were found would help here).

Add ability to disable model validation

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultConfigSettings.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/ApiGatewayMapper.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CognitoUserPoolsConverter.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CorsHeader.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiMapper.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiProtocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/SecuritySchemeConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/security/AwsV4Converter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/security/HttpApiKeyAuthConverter.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/security/HttpApiKeyAuthConverterTest.java

This commit adds more arguments to OpenAPI conversion interfaces just to
hedge our bets in case we ever need the additional data.

Add more args to OpenAPI converters

---

README.md
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/converting-to-openapi.rst
smithy-aws-protocol-tests/build.gradle.kts

This PR updates the Gradle Plugin documentation with the new 0.5.0 version number.
ref: https://github.com/awslabs/smithy-gradle-plugin/pull/22

Update Gradle Plugin docs to 0.5.0

---

mkdocs

This commit updates the doc generation script to clear out the
/version/latest directory since it's not supposed to be there, and adds
a prompt for viewing the full diff.

Clean up mkdocs doc gen

---

smithy-cli/build.gradle.kts
smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java

This commit fixes the CLI help output alignment so that it doesn't trim
leading spaces, causing the output to be misaligned. It also updates the
runtime plugin used to build the CLI, and it automaticall generates a
class data share used to speed up running the CLI.

Fix CLI help format and optimize runtime

---

smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Colors.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Parser.java
smithy-cli/src/main/java/software/amazon/smithy/cli/SmithyCli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Validator.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/SelectCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/valid-model.smithy

This commit adds the select command to the CLI. This command is used to
print out the shapes in a model that match a selector, including the
ability to print out a JSON document containing the shape and the
variables captured when the shape was matched.
Several commands and bits of functionality were cleaned up to make it
easier to control writing things like validation to stderr or stdout.
When using the select command, only the matched shapes or JSON output
should be written to stdout, whereas validation info should be written
to stderr.
This commit also better organizes the output of --help so that arguments
available to all commands and that aren't as important as
command-specific arguments are shown at the end of the argument list
rather than the beginning. …

Add select command

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsPreflightIntegration.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/IntegrationTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/MockIntegrationTrait.java

This PR back ports efc981f3bbb724ddac244ebca7e8d951ad115ce2, part of #370, adding CONVERT_TO_TEXT to OPTIONS.

Backport CONVERT_TO_TEXT for OPTIONS

---

Dockerfile

Allows Smithy to be built and used as a Docker image.

Add a basic Dockerfile to Smithy

---

smithy-cli/src/main/java/software/amazon/smithy/cli/SmithyCli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/AstCommand.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/AstCommandTest.java
smithy-model/src/main/java/software/amazon/smithy/model/node/Node.java
smithy-model/src/test/java/software/amazon/smithy/model/node/DefaultNodeWriterTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeTest.java

This commit adds support for an `ast` command in the CLI to convert 0 or
more Smithy models into a JSON AST. This can be used to more easily
combine multiple models or for simply testing parser implementations.
This change also updates the default indentation for JSON pretty
printing to use 4 spaces instead of 2 since that's what is used
throughout the Smithy specification.

Add `ast` command and indent JSON 4 spaces

---

docs/source/1.0/spec/core/model-validation.rst
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.json
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

This fixes a bug where any `SourceException`s rasied after the model assembler began validation would result in validation getting skipped. This was due to the fact that the assembler calls `onEnd` in its visitor before validation AND whenever it catches that class of exception. `onEnd` will cache its result, so you can't simply call `onError` and guarantee it will be in the output.
This also updates a few tests that were accidentally doing this, as well as the documentation for the `suppress` trait which incorrectly called it `suppression`.

Fix bug allowing validation to be skipped

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java

Fix documentation example on putProperty for ModelAssembler

Fix putProperty doc example

---

CHANGELOG.md
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/service-with-required-path.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/service-with-required-path.openapi.json

This commit fixes an issue with the OpenAPI converter where path and
header parameters that are required would appear in the synthesized
object input with "required" properties that reference members that were
removed.

Fix OpenAPI required bug

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java

This commit updates the IDL parser to detect overly nested Node values
and throw a syntax exception when the stack gets too deep. This prevents
stack overflows and guards against a pathological case.

Prevent parsing overly deep Node values

---

docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/converting-to-openapi.rst
docs/source/1.0/guides/model-linters.rst
docs/source/conf.py

The library version of Smithy can now be injected anywhere into the
Sphinx documentation using a __smithy_version__ placeholder string. This
string is found and replaced using a source-read event pre-processor,
and it is replaced with the contents of the VERSION file at the root of
the project.

Preprocess documentation to inject lib version

---

docs/source/1.0/spec/core/behavior-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpChecksumRequiredTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-checksum-required-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-checksum-required-trait.json

- Adds support for httpChecksumRequired trait. 

Adds httpChecksumRequired trait

---

README.md
docs/source/1.0/guides/building-models/build-config.rst
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/building-models/index.rst
docs/source/1.0/spec/core/shapes.rst
docs/source/quickstart.rst

*Issue #, if available:* #437 & #446 & #447 & #448
This updates the README and quickstart guides to include more specific
examples on how to use the Gradle plugin to build models as well as
links to the examples directory in the plugin repository.
Also fixed some other minor doc issues.

Include more specific build examples and links

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mixed-security-service.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mixed-security-service.openapi.json

This ensures that if an operation explicitly removes authentication,
"security" is set to an empty list as opposed to simply being unset
as unset will result in the operation inheriting global configuration.

Set 'security' to empty list for unauthed ops

---

CHANGELOG.md
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/SchemaTest.java

Remove required entries when property is removed

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-checksum-required-trait.errors

Mark httpChecksumRequired trait unstable

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/apply-use-1.smithy

This commit fixes an issue where resolving a forward reference could
throw a ConcurrentModificationException when the resolution would
need to create another forward reference. For example, when applying
a trait to a shape defined in another file without importing the trait
or using its fully qualified shape ID, as done when applying a prelude
trait.

Fix an issue with double forward reference

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuild.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java
smithy-build/src/main/java/software/amazon/smithy/build/model/ProjectionConfig.java
smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildConfig.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/otherimports/d.json
smithy-build/src/test/resources/software/amazon/smithy/build/otherimports/smithy-build.json

This resolves all imports relative to the config file they're defined in. Previously it would resolve relative to the location of the last config file loaded.

Resolve all imports relative to their config

---

docs/source/quickstart.rst

Adds example operations and structures missing from quick start guide.
Fixes #460 

Update quick start guide to produce buildable model

---

docs/source/1.0/spec/core/shapes.rst
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedMemberOrder.java
smithy-diff/src/main/resources/META-INF/services/software.amazon.smithy.diff.DiffEvaluator
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedMemberOrderTest.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/node/ObjectNode.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/test/java/software/amazon/smithy/model/node/ObjectNodeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/StructureShapeTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/main-test.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/structures.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/unions.json

This change updates Smithy to make the order of structure members part
of the contract of structures and unions. We previously sorted these
members automatically. However, languages like C, C++, Rust and others
require the order of structures to be consistent, and new fields added
to the end to maintain ABI compatibility. This change adds that language
to the spec, updates the semantic model to use insertion order, updates
equality checks to ensure that members have the same order, and adds a
diff evaluator to detect a violation.

Make structure order part of the contract

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TargetValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator-suggestions.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator-suggestions.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/target-validator.errors
smithy-utils/src/main/java/software/amazon/smithy/utils/StringUtils.java

When an invalid shape ID target is encountered, a "Did you mean X?" list
of shape IDs are suggested if any shape IDs in a model have a Levenshtein
edit distance of less than 2 characters. The shape IDs with the lowest
distance from the invalid shape ID are suggested. Closes #464.
This change also updates the error message for "shape has a/an `X`
relationship..." so that is uses the appropriate indefinte articale
based on if the relation type starts with a vowel.

Provide suggestions for invalid shape ID targets

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

This CR adds an `addTrait` method to the model assembler, allowing for a resolved trait to be added to a target shape within the model.

Add addTrait method to ModelAssembler

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-restxml-protocol.rst
docs/source/1.0/spec/core/http-traits.rst
docs/source/1.0/spec/core/protocol-traits.rst
smithy-aws-protocol-tests/model/awsJson1_1/documents.smithy
smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
smithy-aws-protocol-tests/model/restJson1/documents.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/xml-protocols-do-not-support-documents.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/xml-protocols-do-not-support-documents.smithy
smithy-model/src/main/java/software/amazon/smithy/model/traits/ProtocolDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/NoInlineDocumentSupportValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/no-inline-document-support.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/no-inline-document-support.smithy

HTTP binding traits used invalid selectors that aren't actually
supported, particularly around document types. Document types today can
only be bound in the payload of an HTTP request. This change also add a
flag to protocol trait definitions that defines if the protocol supports
inline document types (along with built-in validation to detect when a
protcool says it doesn't support document types but a service uses
document types with the protocol). HTTP bindings previously stated that
only "application/json" media types found in HTTP headers are base64
encoded, however any string with a mediaType needs to be base64 encoded.

Add document validation and fix their HTTP binding

---

smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy

Updates the restJson1 protocol test to not expect `{}` as the request body. Instead the test expects no/empty request body. This matches the AWS SDK's expectation of REST-JSON with no input parameters when no document or payload binding are modeled on the input shape.
https://github.com/aws/aws-sdk-go-v2/blob/master/models/protocol_tests/input/rest-json.json#L724-L737

Update REST-JSON protocol test implicit request body case

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpLabelTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-request-response-validator.errors

We previously enforced that a structure member is required using
separate validation, but it should really be encoded in the selector.
This updates the selector, expected validation messages, and the
documentation to do so.

Make required trait part of httpLabel selector

---

docs/source/1.0/spec/core/lexical-structure.rst
docs/source/1.0/spec/core/traits.rst

This commit intends to clarify the differences between the IDL and JSON AST by defining the "semantic model" (as originally defined by Martin Fowler in [Domain Specific Languages](https://martinfowler.com/dslCatalog/semanticModel.html). Basically features that are present in the IDL that aren't present in the JSON AST (like control statements) aren't actually part of the semantic model.

Clarify the semantic model

---

smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy
smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy

Removes the protocol tests for HTTP Prefix Header deserialization, deserializing to an empty map vs null value. Null vs empty map will be SDK implementation specific distinction. If there was a way to model `empty` as an expectation that would encompass both null and empty but initialized map this test would be more portable.
Updates the empty input output serialization protocol test to expect empty payload not empty JSON object as the serialized result. It doesn't look like the REST-JSON protocol should be serializing empty JSON object when no members are serialized.

Update opinionated protocol tests to not describe optional behavior

---

smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/test-service.jsonschema.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

Use `title` to improve generated documentation for the `oneOf` union
strategy. Without `title` tools see an inlined (unnamed) object.
Fixes #483 
By submitting this pull request, I confirm that my contribution is made
under the terms of the Apache 2.0 license.

Use title for oneOf union strategy

---

docs/source/1.0/spec/core/lexical-structure.rst

The previous production grammar implied that you could only specify one
of the fixed sections at a time. This update now properly specifies that
each section follows the other, and each subsection then has optional
productions inside of them, meaning they can actually be omitted in an
IDL model file.

Fix IDL ABNF production

---

smithy-aws-protocol-tests/model/awsJson1_1/errors.smithy
smithy-aws-protocol-tests/model/awsJson1_1/main.smithy

This adds error tests for the json rpc protocol. The base tests assert that `__type` is checked, and extended tests are included for clients only to support the wide range of behaviors that existing services may exhibit.

Add error protocol tests for json rpc

---

docs/source/1.0/guides/style-guide.rst

We used to allow multiple namespaces in a single IDL file, but removed
this feature prior to 1.0. This change just removes a left-over
recommendation that suggests using a single namespace per/file (which is
now a requirement).

Remove old style guide namespace guidance

---

smithy-aws-protocol-tests/model/awsJson1_1/documents.smithy
smithy-aws-protocol-tests/model/awsJson1_1/kitchen-sink.smithy
smithy-aws-protocol-tests/model/awsQuery/input.smithy
smithy-aws-protocol-tests/model/ec2Query/input.smithy
smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/http-payload.smithy

Adds Content-Length as an expected header to be serialized in AWS protocol requests for structured and blob payloads.

Add Content-Length required header to request protocol tests

---

smithy-aws-protocol-tests/model/awsJson1_1/documents.smithy
smithy-aws-protocol-tests/model/awsJson1_1/enums.smithy
smithy-aws-protocol-tests/model/awsJson1_1/kitchen-sink.smithy
smithy-aws-protocol-tests/model/awsJson1_1/null.smithy

Updates the protocol tests for JSON 1.1 to include the Content-Type header for request and response serializations.

Add content-type to JSON 1.1 protocol tests

---

CHANGELOG.md
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrations.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.openapi.json

This fixes a bug where "passthroughBehavior" was misspelled as "passThroughBehavior" in the apigateway openapi output.

Fix casing of passthroughBehavior in openapi

---

CHANGELOG.md
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/multiline-comments.smithy

This fixes an issue where multiline doc comments would not work on
members due to the parser only consuming to the end of the current
line and then checking for the forward slashes. Since there will
usually be indentation here for members, the parsing ended too early.

Fix multiline doc comment parsing on members

---

docs/source/1.0/spec/core/protocol-traits.rst
smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

This commit clarifies what the mediaType trait is used for, the fact
that it's a design-time contract, and adds a missing header
serialization test to ensure that mediaType trait strings are base64
encoded.

Add clarifications on how to use mediaType trait

---

docs/source/1.0/spec/core/idl.rst
docs/source/1.0/spec/core/model.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/ParserUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeIdTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/invalid-unquoted-shape-id.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/shape-name-syntax2.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/shape-name-syntax3.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/use/use-invalid-namespace.smithy

These newly disallowed identifiers were never actually supported in
practice and are problematic on multiple levels:
1. An identifier like `_` or `__` are bad names that don't help users understand an API.
2. Identifiers like `_` are problematic for languages like Rust that use this character for pattern matching.

Disallow problematic identifiers

---

smithy-aws-protocol-tests/model/awsJson1_0/empty-input-output.smithy
smithy-aws-protocol-tests/model/awsJson1_0/errors.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_1/errors.smithy

This adds basic protocol tests for AWS JSON 1.0. In the future there will be a full set of tests, but for now there are only tests that cover the cases where it differs from 1.1, namely errors and content type.

Add protocol tests for Aws Json 1.0

---

smithy-aws-protocol-tests/model/restJson1/streaming.smithy

Fixes AWS REST-JSON protocol test for streaming with required length test operation to use correct URI path.

Fixup AWS REST-JSON streaming protocol test URI paths

---

smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeMapper.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java

*Issue #, if available:* NodeMapper does not support the functionality to turn off fromNode during deserialization.
*Description of changes:* Added functionality to NodeMapper to turn on and off fromNode for deserialization.

Disable NodeMapper fromNode during deserialization

---

smithy-aws-protocol-tests/model/awsQuery/input-maps.smithy

Query maps have order, but not all languages have ordered maps.
Those languages may choose to sort by key on serialization to
have a stable payload. Go does this, for instance. This updates
the query protocol tests to have maps in their params and bodies
be sorted to facilitate this strategy while keeping languages with
insertion ordered maps from having to do any extra work.

Sort query maps in protocol tests

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ArtifactDefinitions.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ArtifactMetadata.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ShapeLink.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TraceFile.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ArtifactDefinitionsTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ArtifactMetadataTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/ShapeLinkTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/TraceFileTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/definitions.json
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/service-with-shapeids.smithy
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/simple-service.smithy
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/trace-file.json
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/trace-for-model-validation.json
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/trace-for-simple-service-validation.json

*Issue #, if available:* Smithy lacks ability to trace artifacts backs to the models that generate them. 
*Description of changes:* These data objects provide the basic foundation to create, parse, write and validate a trace file. 

Add TraceFile data objects and validation

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-list-member-names.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-map-member-names.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-set-member-names.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-structure-member-names.errors

This commit simplifies how we detect and report on duplicate members in
aggregate shapes.

Improve dulplicate member handling

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/RenameShapes.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/RenameShapesTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/rename-with-resulting-errors.json

None of the other transformers raise validation errors when
they produce a model in an invalid state, so the rename transformer
shouldn't either. With this change a tool could attempt to resolve
any issue before the model is actually used.

Don't raise validation erros from renaming

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java

There was a check in the loader visitor around duplicate members that is
no longer necessary now that duplicate members are detected while
loading aggregate shapes. Beyond the removal of that if statement, this
change improves the readability of the conflict handling code and gives
more context as to why some conflicts are allowed.

Simplify conflict shape loading conflict handling

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidationEvent.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ValidationEventTest.java

Add fromNode to ValidationEvent

---

docs/source/1.0/spec/aws/aws-restxml-protocol.rst

The noErrorWrapping property of the aws.protocols#restXml trait is meant
to allow clients to work correctly with error responses from Amazon S3.
However, some of the text and documentation were wrong according to
https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html.

Fix noErrorWrapping docs

---

docs/source/1.0/spec/core/http-traits.rst
docs/source/1.0/spec/core/model.rst
docs/source/1.0/spec/core/protocol-traits.rst

Clarifies that the timestampFormat trait can override the default
formats used in HTTP binding traits, and that fractional precision is
optional.
Closes #521

Clarify timestamp formats

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/Prelude.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

The previous loading implementation required the prelude to be defined
before loading could occur. This had the consequence that much of the
prelude had to be defined in Java code rather than a prelude model.
Because loading was refactored recently, we can now define the entire
prelude in a Smithy model and simplify Prelude.java.

Simplify prelude loading

---

docs/source/1.0/spec/aws/amazon-apigateway.rst
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.openapi.json
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/IntegrationTrait.java
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-apigateway-traits/src/test/java/software/amazon/smithy/aws/apigateway/traits/IntegrationTraitTest.java

Currently, when converting the Smithy model to API Gateway for HTTP APIs, it fails because it doesn't configure the `payloadFormatVersion`. This change adds the payload format version to the IntegrationTrait.
The payload format version specifies the format of the data that API Gateway sends to an integration, and how API Gateway interprets the response. If you create an integration for HTTP APIs programmatically, you **must** specify a payloadFormatVersion. The supported values are 1.0 and 2.0.
*Issue #, if available:* No issue #
*Description of changes:* See commit message above. Added the payloadFormatVersion that is required as document here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html
By submitting this pull request, I confirm …

Add payloadFormatVersion to API Gateway Integration trait.

---

docs/source/1.0/spec/aws/aws-restxml-protocol.rst
smithy-aws-protocol-tests/model/restXml/errors.smithy

Rest-XML Protocol test for Invalid greeting error is modeled with an invalid XML response. 
This change fixes the invalid XML response, with correct xml closure tag.

fix rest-xml protocol test for Invalid greeting error 

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

CodeWriter can now configure the character used to start expressions in
the current state, making it easier to generate code for language that
give syntactic meaning to CodeWriter's default expression character,
'$'.

Make CodeWriter expressions configurable

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

This commit simplifies and improves how the CodeWriter handles the
automatic injection of newlines and indentation. Now, the *only* difference
between write() and writeInline() is that write() appends a newline
(there was previously a lot of special-cased code for writeInline).
* writeInline() now properly handles indentation when necessary (e.g., if
a previous call injected a newline). This includes a few edge cases
like if the first call to the CodeWriter is to writeInline() and uses
indentation.
* The character used for newlines is now tracked by the current state rather
than globally.
* Trailing newlines are now *always* inserted to the given text if enabled
There was a bug previously where they were not appended if the last call
on the CodeWriter was a writeInline(). This could …

Improve CodeWriter newlines and indentation

---

smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-aws-protocol-tests/model/restXml/document-xml-attributes.smithy

1. Adds few protocol test for rest xml deserializers to check behavior with xml preamble, comments, CDATA, white space, characters that need to be escaped are present in xml response body. 
2. Adds test cases for white space, character escaping when serializing into xml request body.

Adds restxml protocol test around xml preamble, CDATA, escaped characters

---

docs/source/1.0/guides/building-models/build-config.rst
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/spec/core/documentation-traits.rst
docs/source/1.0/spec/core/idl.rst
smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.json
smithy-build/src/main/java/software/amazon/smithy/build/transforms/ExcludeShapesByTrait.java
smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer
smithy-build/src/test/java/software/amazon/smithy/build/transforms/ExcludeShapesByTraitTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/internal-shapes.smithy
smithy-model/src/main/java/software/amazon/smithy/model/traits/InternalTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/InternalTraitTest.java

We've been using the "internal" tag to indicate that something is
internal only and should not be exposed to external consumers of a model
(i.e., people that don't work at the same company as the service team).
The original motivation for using tags and not traits was that there are
more dimensions to filtering shapes out of models than just internal vs
external. However, the internal/external split is so common that it
makes sense to make it a trait, which is more configurable and less
based on convention. Tags can still be used for filtering things out of
models (for example, an operation could be tagged so that it is only
exposed to a particular customer).
There are other cases where we migrated away from tags and moved to
traits like the `aws.api#controlPlane` and `aws.api#dataPlane` …

Make internal a trait and not just a tag

---

docs/source/1.0/spec/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java

The abbreviation property in aws.api#service was not actually supported
by the underlying Smithy model for the trait. We intended to remove this
from Smithy 1.0, but it was a miss. The abbreviation property is no
longer necessary since we now have the service ID property via sdkId.
The abbreviation property was also problematic since lots of entries
across services didn't make sense (like a value longer than the title).
Trying to define an abbreviation will emit a warning but will not break
builds (this is actually the current behavior too since it wasn't
defined in the model).

Remove abbreviation from aws.api#service docs

---

docs/source/1.0/spec/core/http-traits.rst
smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

The httpPrefixHeaders trait actually only supports string values in the
map (or a list/set of strings). A compliance test was added to test
extracting all headers with no prefix.

Fix httpPrefixHeaders selector

---

.gitignore
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

The operation updated with the property in the test [already had the trait applied.](https://github.com/awslabs/smithy/blob/34d51e3f7f9c351ed0867a816e082ba3ac56cc4c/smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.json#L34)

Add deprecated property for OpenAPI operations

---

docs/source/1.0/spec/core/idl.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/detects-bad-syntactic-shape-ids.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/detects-bad-syntactic-shape-ids.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/knowledge/bottom-up.smithy

Smithy will now emit a DANGER event when a syntactic shape ID is found that
does not resolve to a valid shape. This should help detect invalid
models during model validation.

Add validation for bad syntactic shape ID

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/use-operations/nested.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/use-operations/other.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/use-operations/service.smithy

Service shapes weren't correctly using forward reference resolution in
the IDL for operation bindings and resource bindings. This is because we
were eagerly taking the value out of a StringNode that uses a syntactic
shape ID before all of the shapes are resolved. This causes the
StringNode to assume that the shape ID is in the same namespace that it
was defined in, which can be incorrect when there are `use` statements
in effect. To address this, I've updated the optionalId and
optionalIdList methods used in the IDL loader to always use a dedicated
forward reference resolution callback independent of the callback used
in other places (like trait values). Now things like identifiers,
inputs, outputs, operation, and resource bindings are all handled in a
uniform way.
*Issue #, if …

Fix forward reference resolution of service shapes

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TopologicalIndex.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/TopologicalIndexTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/topological-sort.smithy
smithy-model/src/main/java/software/amazon/smithy/model/selector/PathFinder.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/PathFinderTest.java

Some languages require types to be defined before they're referenced, so
they need a reverse topological ordering of shapes. They also need to
know which shapes are recursive so that they can use forward
declarations before referencing recursive types. This commit adds a
TopologicalIndex to smithy-codegen-core to provide a stable ordered
reverse-topological set of shapes, and a set of recursive shapes along
with their recursive closures. This recursive closure may also be of
interest to code generators when deciding whether or not a recursive
reference needs to be boxed or not to compute a type's size at compile
time.

Add reverse-topological index

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpResponseCodeTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/HttpResponseCodeTraitTest.java

This commit adds the `httpResponseCode` trait that indicates that
a structure member represents an HTTP response status code.
Explicitly modeling this as a field can be helpful for services that
wish to provide different response codes for an operation, like 200
or 201 for a PUT operation.

Add httpResponseCode Prelude trait

---

build.gradle

We previously failed to build ther sourcesJar when calling `publishToMavenLocal`. This is now fixed and tested by publishing all JARs to maven local.

Fix gradle to not call invalid .get()

---

docs/source/1.0/spec/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/EventSourceValidator.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/EventSourceValidatorTest.java

This commit adds validation to help ensure that CloudTrail event source
values are configured correctly. If also clarifies that the
cloudTrailEventSource property contains the customer-facing value.

Add validation and clarification to event source

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TopologicalIndex.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/TopologicalIndexTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/topological-recursion.smithy
smithy-model/src/main/java/software/amazon/smithy/model/selector/PathFinder.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/PathFinderTest.java

This commit fixes a bug in TopologicalIndex where some forms of
recursion weren't detected, which resulted in a stack overflow. This was
because directly recursive shapes were found, but transitively recursive
shapes were not (shapes that are recursive on themselves, but enter into
a cycle because they reference recursive shapes). To address this,
TopologicalIndex was rewritten to just implement a DFS rather than try
to reuse PathFinder.

Fix TopologicalIndex

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginatedIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/PaginatedTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/PaginatedIndexTest.java

This updates the PaginatedIndex to properly support resolving paths.
The path resolution logic has been moved into PaginatedTrait since it
is also needed to perform validation and may someday be needed
elsewhere.

Support paths in PaginatedIndex

---

docs/source/1.0/guides/converting-to-openapi.rst

Updates the `Converting Smithy to OpenAPI` guide to document that the `aws.api#arn` trait does not influence the converted model.

Document arn trait support for OpenAPI

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/AbstractShapeBuilder.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/CollectionShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MapShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ListShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/MapShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SetShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/StructureShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/UnionShapeTest.java

This updates the shape builders to update member ids if the shape id
changes. This prevents a situation where changing the id would put
the shape into an invalid state. It also makes it extremely simple
to create a duplicate shape.

Update shape builders to update member ids

---

docs/source/1.0/spec/core/selectors.rst
smithy-model/src/main/java/software/amazon/smithy/model/selector/SelectorParser.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/TopDownSelector.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/TopDownSelectorTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/selector/recursive-resources.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/topdown-auth.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/selector/topdown-exclusive-traits.smithy

The topdown selector is used to match shapes hierarchically based on a match selector and optional disqualifier selector. This can be used to match shapes that are marked as controlPlane or dataPlane using
inheritance from resource/service bindings, match shapes that use httpBasic auth, etc.
*Note: This probably needs more docs, but I wanted to push it up to make sure it looks useful.*

Add :topdown selector to match hierarchically

---

smithy-aws-protocol-tests/model/awsJson1_0/empty-input-output.smithy
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy
smithy-aws-protocol-tests/model/restXml/document-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

Fix unbound operations/shapes in protocol tests

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/trace/TraceFile.java

Add missing javadoc @return statement for TraceFile `fromNode` method.

Add missing javadoc @return

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/CompositeModelFile.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

When a URL is imported with the model assembler, it will now strip off
leading "jar:" and "file:" prefixes in order to create a normalized
de-dupe key so that imports through URLs and through Path to the same
files are de-duped. This also offers better SourceLocation reporting for
files that are imported through a URL.

Normalize URL filenames for better reporting

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/trait-test-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/trait-test-b.smithy

Smithy-diff previously did not emit validation events when a trait was
added, removed, or changed unless the trait was marked with one of a few
special tags. This commit updates smithy-diff to emit a NOTE when a
trait is added or changed and a WARNING when a trait is removed. This
helps ensure that all trait changes are caught by smithy-diff, while
still allowing more granular control through the tags.

Emit events when traits are changed

---

smithy-aws-protocol-tests/model/restXml/document-structs.smithy

* Corrects test for `XmlEmptyStrings`.

fixes protocol test for XmlEmptyStrings

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/MetadataContainer.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/TraitContainer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/dedupe-models.smithy

While we previously de-duplicated models by filename/URL, we recently
removed support for de-duping models by location and equality. This can
happen, for example, when a Model is created through a ModelAssembler, and
then added back to another ModelAssembler. If the files that came
together to create the original model are added to the second
ModelAssembler, then the previous file-base de-dupe would not catch the
duplicate model and would fail in the assembler. This change updates
the ModelAssembler to also de-dupe shapes, trait value, and metadata
based on source location and equality. If one of these components
conflict, and the conflcit is exactly the same, and defined at the same
exact file/line/column, then the duplcate is ignored. Note that model
components with no source location …

De-depude model components by location and value

---

smithy-build/src/main/java/software/amazon/smithy/build/transforms/RemoveUnusedShapes.java

Adds missing word in docs for RemoveUnusedShapes transformer.

Fix missing word in RemoveUnusedShapes docs

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpMethodSemanticsValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-method-semantics-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-method-semantics-validator.json

Lots of clients don't support DELETE with a payload, and the spec calls
it out as having no defined semantics. The newly added event can be
suppressed if necessary, but this action functions as a way of essentially
"signing-off" on the risks associated with using a DELETE with a payload.

Emit DANGER event for DELETE with a payload

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/RemoveTraitDefinitions.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/RemoveTraitDefinitionsTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/remove-trait-definitions.json
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/retain-tagged-trait-definitions.json
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ScrubTraitDefinitions.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ModelTransformerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ScrubTraitDefinitionsTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/transform/test-model.json

This CR adds a transformer that removes trait definitions.  This enables sharing models where the trait versions may vary.  When consuming models produced by this plugin, it is necessary to assure that the requisite traits sources are imported.

Add transformer that removes trait definitions

---

smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/http-response-code.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json

This adds protocol tests for `httpResponseCode` in the aws protocol tests.

Add protocol tests for httpResponseCode

---

smithy-diff/src/main/java/software/amazon/smithy/diff/ChangedMetadata.java
smithy-diff/src/main/java/software/amazon/smithy/diff/ChangedShape.java
smithy-diff/src/main/java/software/amazon/smithy/diff/Differences.java
smithy-diff/src/main/java/software/amazon/smithy/diff/ModelDiff.java
smithy-diff/src/test/java/software/amazon/smithy/diff/ModelDiffTest.java

This change adds a lot more details to the result of a ModelDiff,
including access to the raw Differences between the models, access to
the old and new models through the Differences object, access to the old
validation events and new validation events, and access to the diff
events. Helper methods were added to ModelDiff.Result to detect which
validation events were introduced by a change,  which validation
events were resolved by a change, and if there are breaking changes in
the diff (e.g., events that are ERROR or DANGER). Note that any kind of
suppression of diff events would need to be applied and managed outside
of this helper functionality.
Added some missing equals and hashCode implementations.
By submitting this pull request, I …

Improve information available from diffs

---

smithy-cli/src/main/java/software/amazon/smithy/cli/BuildParameterBuilder.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/test/java/software/amazon/smithy/cli/BuildParameterBuilderTest.java

Use System's path separator for classpaths

---

config/checkstyle/checkstyle.xml
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/CloudFormationSubstitutionTest.java
smithy-build/src/main/java/software/amazon/smithy/build/plugins/SourcesPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/java/software/amazon/smithy/build/plugins/ConfigurableSmithyBuildPluginTest.java
smithy-build/src/test/java/software/amazon/smithy/build/plugins/SourcesPluginTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/BuildParameterBuilderTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/AstCommandTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/BuildCommandTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/SelectCommandTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/ValidateCommandTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/DefaultNodeWriterTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeDiffTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ContextualValidationEventFormatterTest.java
smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java
smithy-utils/src/test/java/software/amazon/smithy/utils/IoUtilsTest.java

Fix Checkstyle to work on Windows

---

smithy-aws-protocol-tests/build.gradle
smithy-cli/src/test/java/software/amazon/smithy/cli/BuildParameterBuilderTest.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/AstCommandTest.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

This change adds various fixes to Smithy and tests so that they now work on Windows. We'll need to configure our tests to automatically run on Windows to ensure there are no regressions here.

More windows fixes

---

docs/source/1.0/spec/aws/amazon-apigateway.rst

Remove extra word in authorizers documentation.

Remove extra word in authorizers documentation.

---

smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java
smithy-utils/src/test/java/software/amazon/smithy/utils/IoUtilsTest.java

Add a simple runCommand method to smithy-utils

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/FlattenNamespaces.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/FlattenNamespacesTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/flatten-namespaces.json
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/no-service.json

Adds flattenNamespaces transformer that flattens the namespaces of shapes connected to a specified service in a model into a target namespace.  Shapes that are not connected to the service will not be flattened, unless they have been tagged with a tag that has been included in the `includeTagged` configuration list.  Tagged shapes that conflict with an existing shape within the service closure will not be flattened.
Example configuration:
```
{
"version": "1.0",
"projections": {
"exampleProjection": {
"transforms": [
{
"name": "flattenNamespaces",
"args": {
"namespace": "ns.foo",
"service": "ns.foo#MyService,
"includeTagged": ["include", "conflict"],
}
}
]
}
}
}
```
Input model:
```
{
"smithy": "1.0",
"shapes": {
"ns.foo#MyService": {
"type": "service",
"version": "2017-01-19", …
```

Add flattenNamespaces transformer

---

smithy-utils/src/main/java/software/amazon/smithy/utils/TriConsumer.java
smithy-utils/src/test/java/software/amazon/smithy/utils/TriConsumerTest.java

This is a port of https://github.com/awslabs/smithy-go/blob/master/codegen/smithy-go-codegen/src/main/java/software/amazon/smithy/go/codegen/TriConsumer.java

Add TriConsumer

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/HttpBindingIndex.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/union-test.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/union-test.smithy

We had a case where if a union shape is marked with the httpPayload
trait, we wouldn't resolve a proper mediaType. This caused an NPE. The
code that determines the media type has been updated to treat unions
like structures, and a more helpful message was added in case a media
type can't be resolved at some point in the future.

Fix media type handling of unions as payloads

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/MediaTypeValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/mediatype-trait.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/mediatype-trait.json
smithy-utils/src/main/java/software/amazon/smithy/utils/MediaType.java
smithy-utils/src/test/java/software/amazon/smithy/utils/MediaTypeTest.java

Mediatypes

---

smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/SortMembers.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/SortMembersTest.java

Add SortMembers transform

---

docs/source/1.0/guides/converting-to-openapi.rst

Updates docs to wrap config params with double-ticks.
This was done in some places already, so this just catches a few examples to make this consistent.

Wrap config params in double-ticks

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/documentation-test.smithy

Add operation docs to OpenAPI conversion

---

smithy-model/src/main/java/software/amazon/smithy/model/neighbor/NeighborProvider.java

This method previously needed lots of intermediate representations
stored in memory to create a Map<ShapeId, List<RelationShip>> that
contains only unique relationships. It was done using Stream,
distinct, and groupingBy. However, when trying to load ridiculously
large models, that approach consume tons of heap. This approach
allocates as little as possible (I think), but does require creating
an ArrayList copy of a Set each time neighbors are returned.

Optimize reverse neighbors for memory

---

smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer

Fixed #572 
Registers the FlattenNamespaces transformer.

Register FlattenNamespaces transformer

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelValidator.java

When validating massive models, this line was causing out of memory
errors because it required keeping two copies of a validation events in
memory at once (one to aggregate and then one to copy into the result).
This change instead just uses a single list to aggregate the result, and
then mutates that list to add in any other events encountered while
building up validators.

Optimize validation event aggregation

---

docs/source/1.0/spec/core/constraint-traits.rst
docs/source/1.0/spec/core/model.rst

Map keys, set values, and union members do not support null.

Add some null value clarifications

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriter.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriterDelegator.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriterFactory.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/DocumentationWriter.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/ImportContainer.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/JavaStyleDocumentationWriterBuilder.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/UseShapeWriterObserver.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterDelegatorTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/JavaStyleDocumentationWriterBuilderTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/MyWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

CodegenWriter, CodegenWriterDelegator, et al. are meant to make it
easier to develop code generators that utilize Smithy's Symbol,
SymbolReference, and SymbolDependency abstractions.
CodegenWriterDelegator provides abstractions for creating and handing
out references to CodegenWriters while collecting all of the imports
needed for an entire project. CodegenWriter is used to write code,
symbols, documentation, and manage the imports needed for a specific
file. Other abstractions were added that make it easier to build-up and
compose CodegenWriters and delegators, for example, the
JavaStyleDocumentationWriter can make it easier to implement writing
documentation for programming languages that use Java-style comments. …

Add CodegenWriter abstractions

---

docs/source/1.0/spec/core/constraint-traits.rst

Clarify enum names and their usage

---

docs/source/1.0/spec/aws/amazon-apigateway.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/empty-custom-auth-type-authorizer.json

Allow the setting of an empty `customAuthType` to indicate that the `x-amazon-apigateway-authtype` extension should not be set to "custom". This is done to handle the current defaulting behavior instead of adding a flag. This is necessary to enable API Gateway's built-in API key validation.

Allow customAuthType defaulting to be disabled

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EntityShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ResourceShape.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/EntityShapeTest.java
smithy-utils/src/main/java/software/amazon/smithy/utils/MapUtils.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SetUtils.java
smithy-utils/src/test/java/software/amazon/smithy/utils/MapUtilsTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/SetUtilsTest.java

This commit updates service and operation shapes to maintain the order
in which operations and resources are defined in a Smithy model. Note
that resource lifecycle operation order is not maintained since those
are named operations that don't have any particular order in a model
like a list of operations, collectionOperations, or resources do.
To achieve this, I added a couple new helper methods to make copies of
Maps and Sets that maintains order.
Closes #591

Maintain order of operations and resources

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

This updates the `HttpApiKeyLocations` shape in the prelude so that each enum entry has a name attribute defined.

Add enum names  for httpApiKeyLocations

---

build.gradle
docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/plugins/SourcesPlugin.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java

Create empty manifest when no source models

---

docs/source/1.0/guides/converting-to-openapi.rst
docs/source/1.0/spec/aws/amazon-apigateway.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/custom-auth-type-authorizer.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/operation-http-api-key-security.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/operation-http-api-key-security.openapi.json

This commit adds support for enabling API Gateway's API key usage
plans. A non-custom httpApiKeyAuth based authorizer on an operation
will now be directly set on every operation in the OpenAPI document,
even if it's the same as the service level authorizer.

Support API Gateway API key usage plans

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/SensitiveTraitValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait-target.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait-target.smithy

Members should not be marked with the sensitive trait if they target
shapes marked as sensitive or shapes that are generally code-generated.
It is safer to define a complex type as sensitive rather than to reference
a complex type from a member marked as sensitive. This helps prevent issues
where the sensitive trait may get forgotten on the member even though a
structure/union/enum is inherently sensitive.

Validate sensitive trait targets

---

smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-protocol-tests/model/shared-types.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/EnumTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enum-trait-validation.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enum-trait-validation.json
smithy-mqtt-traits/src/test/resources/software/amazon/smithy/mqtt/traits/errorfiles/job-service.smithy

This adds a warning-level validation event for enums that do not use
the name property. It additionally updates all built in enums and
enums used for tests where the absense of the name isn't deliberate.

Add warning for enums without names

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaShapeVisitor.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/Schema.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java

Add JSON Schema support for patternProperties

---

docs/source/1.0/spec/aws/aws-json-1_0-protocol.rst
docs/source/1.0/spec/aws/aws-json-1_1-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst

I updated the link to 1.3.0—let me know if you'd prefer master or somewhere else. Currently, the link just 404s.

Fix broken link in docs to protocol tests

---

smithy-aws-protocol-tests/model/restJson1/json-maps.smithy

Some of the protocol tests assume that this map is sparse and will attempt to insert null values.

Add @sparse trait to JsonMapsInputOutputMap

---

smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterTest.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

The inline test is failing due to  (what I believe to be) a bug.
I have code that requires multiple integrations to all contribute a string to the same line in codegen output.  I use `CodeWriter.writeInLine()` but this produces no change in the codegen output.  This PR captures the bug.
I've added another test which passes which exercises `CodeWriter.write()` in addition to the breaking test.

Add tests for writing in sections.  

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

This commit adds a few utility methods to CodeWriter, making it easier
to prepend to a section, append to a section, and format text
independent of a call to write.
Closes #422

Add some utility methods to CodeWriter

---

docs/source/1.0/spec/core/behavior-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.json

This relaxes the constraints of pagination tokens to allow maps. This is intended to enable existing services in the wild and is not recommended for future services, so a DANGER validation event is emitted.

Allow pagination tokens to be maps

---

smithy-diff/src/main/java/software/amazon/smithy/diff/ChangedShape.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedMemberTarget.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedMemberTargetTest.java
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested1-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested1-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested2-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-invalid-nested2-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested1-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested1-b.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested2-a.smithy
smithy-diff/src/test/resources/software/amazon/smithy/diff/evaluators/changed-member-target-valid-nested2-b.smithy

The diff evaluator that detects changed members now contains much more
information when an incompatibility is detected. It also allows for some
new kinds of differences that are inconsequential (like a member that
targets a list that is exactly like the old list).

Improve diff evaluation of changed member targets

---

smithy-aws-protocol-tests/model/awsJson1_1/null.smithy
smithy-aws-protocol-tests/model/restJson1/json-lists.smithy
smithy-aws-protocol-tests/model/restJson1/json-maps.smithy
smithy-aws-protocol-tests/model/shared-types.smithy

We didn't update protocol tests after the sparse trait was added. This
commit updates protocol tests to take the sparse trait into account for
lists and maps.

Fix protocol tests for sparse traits

---

docs/source/1.0/spec/http-protocol-compliance-tests.rst

It wasn't clear how binary data is represented in params and body, so this CR intends to make it explicit, along with rationale.

Clarify binary data in protocol tests

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service-integer.openapi.json

This commit adds support for outputting an "integer" type instead
of a "number" type for byte, short, integer, and long shapes when
converting to OpenAPI.

Add support for OpenAPI integer type

---

docs/source/1.0/spec/aws/aws-auth.rst
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.auth.json
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-empty-name.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/auth/sigv4-empty-name.smithy

Require non-empty aws.auth#sigv4 name

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginatedIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/PaginationInfo.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/PaginatedTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/PaginatedIndexTest.java

Adds support for retrieving the full list of MemberShape paths for the @paginated.outputToken and @paginated.items paths. Currently marked the old methods as deprecated as to better indicate the more desirable retrievers a user should use.

Add methods for retrieving full paginator output token and item paths.

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/greedy-labels.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/greedy-labels.openapi.json

Services like API Gateway that use "greedy" labels require that bath
the segment and the corresponding parameter name contain a "+". We
previously included the "+" in the URI label but not in the parameter
name.

Fix greedy label param names in OpenAPI

---

smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/test/java/software/amazon/smithy/model/validation/ExamplesTraitValidatorTest.java

Fix an NPE when validating an examples trait

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/core/xml-traits.rst
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-maps.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy
smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/xml-protocols-do-not-support-documents.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

* The xmlNamespace trait can only be applied to simple types, list,
map, set, structure, union, and service shapes. We previously
allowed "*", but that includes resource and operation shapes where
the trait isn't actually used.
* aws.protocols#awsQuery and aws.protocols#ec2Query protocol traits
both now require that an xmlNamespace is set on the top-level
service shape they are applied to so that the namespace is
guaranteed to be known.
* Added various examples for how the xmlNamespace trait interacts
with flattened lists and maps.
* Add a protocol test suite named "restXmlWithNamespace" to test that
implementations add an xmlns to restXml services when necessary,
closing #616
By submitting this pull request, I confirm that my …

Clarify various aspects of xmlNamespace traits

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java

When an annotation trait isn't defined in the model but SPI can be found
for it, the error message is about providing a null value for an
AnnotationTrait when an object is expected, and that's confusing. This
change addresses this by assuming that an unknown annotation trait is an
object since that is the most common case (and because annotation traits can
never be null). This doesn't end up resulting in a clean model validation
result, but it gives better error messages about the trait not being defined.

Improve unknown annotation trait errors

---

docs/source/1.0/spec/waiters.rst
smithy-waiters/src/main/java/software/amazon/smithy/waiters/UniqueWaiterNamesValidator.java
smithy-waiters/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-waiters/src/test/resources/software/amazon/smithy/waiters/errorfiles/waiter-name-conflicts.errors
smithy-waiters/src/test/resources/software/amazon/smithy/waiters/errorfiles/waiter-name-conflicts.smithy

Ensure waiter names are unique across a service

---

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/enum-can-be-deprecated-and-tagged.smithy

This previously worked, but it would warn about the additional member.

Add missing deprecated member to enum definition

---

docs/source/1.0/spec/waiters.rst
smithy-waiters/src/main/java/software/amazon/smithy/waiters/Waiter.java
smithy-waiters/src/main/resources/META-INF/smithy/waiters.smithy
smithy-waiters/src/test/java/software/amazon/smithy/waiters/WaiterTest.java
smithy-waiters/src/test/resources/software/amazon/smithy/waiters/errorfiles/valid-waiters.smithy

We allow tags and deprecated on enum definitions, so I think it makes
sense on waiters too. Deprecated is particularly timely because of S3
recently making PUT, GET, LIST, etc strongly consistent.

Add tags and deprecated to waiters

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpHeaderTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-header-tchar-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-header-tchar-validator.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-request-response-validator.errors

Closes #614 and also removes a non-inclusive term from the same
validator.

Add HTTP header trait validation

---

smithy-aws-protocol-tests/model/awsQuery/xml-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-maps.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy

Fix AWS Query/Ec2Query response XML tag names

---

docs/source/1.0/spec/aws/amazon-apigateway.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/custom-auth-type-authorizer.json

There are valid use cases on an `@aws.apigateway#authorizors` entry for setting the `customAuthType` property without setting its `type` property. This enables that use case while still not defaulting the client extension to "custom" if the `type` is not set.

Allow setting customAuthType without type

---

docs/source/1.0/spec/waiters.rst

Use jitter in waiters and account for overflows

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/payloads.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service-integer.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

This updates the OpenAPI conversion to set an operation's `requestBody` as required if the operation has an `httpPayload` member and that member is required or if the operation has no `httpPayload` member but does have a required member bound to the document.

Set OpenAPI requestBody to required if necessary

---

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/OperationIndex.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/OperationIndexTest.java

Add more useful methods to OperationIndex

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsResponseHeaders.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrations.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/ApiGatewayMapper.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CorsHeader.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-explicit-options.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-additional-headers.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-custom-gateway-response-headers.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiMapper.java

This commit ensures that Access-Control-Expose-Headers is correctly
populated based on all of the headers used in an operation, including
any headers that might be  added manually during the OpenAPI conversion
independent of a Smithy shape.
I added a new ApiGatewayMapper method called postProcessOperation to
allow transformations to better control when they are applied, in
particular, transforms sometimes need to occur on an operation after the
things that the operation contains have been transformed. This was not
previously possible even with the ordering semantics that already exist.
This change was necessary in order to ensure that the correct CORs
headers are added to operations based on all of the transforms applied
to the operation, and it makes it easier to separate CORS headers …

Fix Access-Control-Expose-Headers

---

smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer

Registers the RemoveTraitDefinitions transformer.
Fixes the error of ```Unable to find a transform for 'removeTraitDefinitions' in the 'foo' projection.``` when trying to use this transformer.

Register RemoveTraitDefinitions transformer

---

smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/config-with-env.json

Any environment variable expansions in smithy-build.json that did not start at the beginning of the field resulted in dropping the character that preceded the ${NAME} placeholder.
Consider the following `smithy-build.json` example, with the environment variable of `FOO` was set to `BAZ`:
```
{
"version": "1.0",
"projections": {
"a": {
"transforms": [
{
"name": "includeShapesByTag",
"args": {
"tags": ["BAR${FOO}"]
}
}
]
}
}
}
```
Currently, this results in the shapes with the tag `BABAZ` being included, instead of `BARBAZ` as expected.
This CR corrects the expansion behavior to assure preceding characters are included appropriately.

Fix truncated environment variable expansions

---

docs/source/1.0/spec/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/ServiceTraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/test-model.json

This adds the endpointId property to the AWS service trait so that
endpoints may be constructed when given a region.

Add endpoint id property to service trait

---

docs/source/1.0/spec/waiters.rst

Clarify that empty arrays do not match allStringEquals.

Clarify matching allStringEquals on empty array

---

docs/source/1.0/spec/aws/aws-core.rst

Fixes wording and adds clarification to documentation for the `endpointPrefix` property of the `aws.api#service` trait.

Endpoint prefix docs fixes

---

docs/source/1.0/spec/aws/aws-core.rst

Fixes formatting for endpointPrefix documentation.

Fix endpointPrefix documentation formatting

---

.github/workflows/ci.yml
build.gradle
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/TestRunnerTest.java
smithy-aws-protocol-tests/build.gradle
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterDelegatorTest.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCase.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/InvalidSmithyModelLoaderRunnerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/IoUtilsTest.java

This adds windows to the CI matrix and applies some fixes to building and testing on windows.

Add windows CI testing

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultRestConfigSettings.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/ApiGatewayExtension.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultRestConfigSettingsTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/greedy-labels-for-rest.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/greedy-labels-for-rest.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/greedy-labels-name-parameter-without-suffix.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/greedy-labels-name-parameter-without-suffix.openapi.json

For OpenAPI, "greedy" labels need a corresponding name parameter, which was added in #641.
However, some vendors/tooling, including REST APIs for API Gateway, require that the name parameter exclude the "+" suffix in the generated name parameter.
This CR adds an option to configure OpenApiConfig to remove that suffix, which is then used as the default for REST APIs in smithy-aws-apigateway-openapi.

Fix openapi greedy param names for API Gateway REST APIs

---

docs/source/1.0/guides/building-models/gradle-plugin.rst

Fixes link to `projections` in Gradle plugin guide 

Fix projections doc link

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/ProtocolHttpPayloadValidator.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-protocols-do-not-support-list-set-map-payloads.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-protocols-do-not-support-list-set-map-payloads.smithy
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-request-response-validator.json

*Issue #, if available:* 
Resolves #636
This relaxes the http payload constraints so that it can be applied to members that target sets, lists, and maps. Since those targets aren't currently compatible with the AWS protocols, a validator was added that only applies if one of those protocol traits is applied.

Relax http payload constraints

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-json-1_0-protocol.rst
docs/source/1.0/spec/aws/aws-json-1_1-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-restjson1-protocol.rst
docs/source/1.0/spec/core/http-traits.rst

This adds a note to the aws protocol docs noting their stricter
requirements for the httpPayload trait.

Add note about httpPayload to aws docs

---

.github/workflows/ci.yml
CONTRIBUTING.md
README.md
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/spec/aws/aws-restjson1-protocol.rst
docs/source/1.0/spec/aws/aws-restxml-protocol.rst
docs/source/quickstart.rst
smithy-build/README.md

This PR updates references to the branch so that `main` can be used the default branch on this repository.

Refer to main branch

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OpenApi.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/OperationObject.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/consolidates-security-service.json

This commit updates the OpenAPI document and Operation object builders
to use sets for storing their security settings instead of lists. Each
entry in these collections can be safely made unique, as duplicates would
represent an "A or A" posture. Having multiple entries can cause issues
with consuming the output document.

Use sets for OpenAPI security settings

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrations.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrationsTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-additional-headers.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/invalid-integration-for-http-api.json

HTTP APIs on API Gateway [require](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-integration.html) that the `payloadFormatVersion` is set, either to `1.0` or `2.0`.  This CR adds validation to ensure that when converting to OpenAPI for use with API Gateway, the `aws.apigateway#integration` trait must have this property set when used with an HTTP API.  Use with an HTTP API is indicated by setting the `apiGatewayType` to `HTTP` when configuring the `openapi` plugin.

Add validation for payloadFormatVersion with HTTP APIs

---

smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy

Adds additional protocol tests for member bound to XML attribute within
a struct that also has an XML namespace.
Related to https://github.com/aws/smithy-go/pull/255, https://github.com/aws/aws-sdk-go-v2/pull/1034, https://github.com/aws/aws-sdk-go-v2/issues/1013

Add test case for XML Attribute with xml namespace on tag

---

smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy

This test is supposed to mimic s3, whose value for the equivalent trait is `xsi:type`.

Fix xmlName value in protocol test

---

docs/source/1.0/spec/core/protocol-traits.rst

The timestamp format specification is slightly incorrect–`IMF-fixdate` does not allow fractional seconds, but Smithy requires that fractional seconds are supported. This change updates the docs to reflect that change.

Correct timestamp format spec

---

smithy-aws-protocol-tests/model/restXml/document-unions.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

REST-XML was missing protocol tests for union serialization and deserialization. This change adds those tests.
Related to https://github.com/aws/aws-sdk-go-v2/issues/939

Add protocol test for Unions in REST-XML

---

docs/source/1.0/spec/aws/amazon-apigateway.rst

Fixes broken link to `mapping templates` API Gateway documentation.  Also fixes the casing on other instance of mapping templates link.

Fix mapping templates link

---

smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy

This fixes a test intended to exercise behavior of serializing an xml
namespace and namespaced attribute on a nested member. Previously the
member's xml namespace trait was applied to the target shape rather
than the member shape.

Fix xmlns + attr ser test

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/non-alphanumeric-content-names.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/non-alphanumeric-content-names.openapi.json

Some vendors, including Amazon API Gateway, require that shape names are alphanumeric only.
This PR assures that the synthesized `ResponseContent` and `RequestContent` shapes have alphanumeric names when the `alphanumericOnlyRefs` configuration setting has been set to `true`, as with `smithy-aws-apigateway-openapi`.  The descriptions on schemas are updated to match when non-alphanumeric characters have been removed.

Fix synthetic schema naming

---

docs/source/1.0/spec/http-protocol-compliance-tests.rst
smithy-aws-protocol-tests/model/awsJson1_0/errors.smithy
smithy-aws-protocol-tests/model/awsJson1_1/errors.smithy
smithy-aws-protocol-tests/model/awsQuery/input.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-maps.smithy
smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy
smithy-aws-protocol-tests/model/ec2Query/input.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy
smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy
smithy-aws-protocol-tests/model/restJson1/errors.smithy
smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restXml/document-lists.smithy
smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/document-structs.smithy
smithy-aws-protocol-tests/model/restXml/http-headers.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/AppliesTo.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMessageTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestsTrait.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpResponseTestsTrait.java
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/java/software/amazon/smithy/protocoltests/traits/TraitTest.java
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/test-with-appliesto.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/test-with-tags.smithy

This commit adds support for applying tags to individual test cases,
allowing them to be grouped much more granularly. It also adds support
for appliesTo, which allows test cases to indicate if they should only
be implemented by clients or servers. Test cases that do not define an
appliesTo member are to be implemented by both client and server
implementations.
Existing AWS protocol tests are updated to now utilize appliesTo rather
than adding tags to operations.

Add tags and appliesTo to protocol tests

---

smithy-aws-protocol-tests/model/awsJson1_0/empty-input-output.smithy
smithy-aws-protocol-tests/model/awsJson1_1/empty-operation.smithy
smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy
smithy-aws-protocol-tests/model/restJson1/errors.smithy
smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy

Closes #686
*Issue #, if available:* 686
This commit fixes various issues raised in #686. Some of this is related to just broken test cases (typically describing responses), and some of it is related to needing to indicate that a test case is meant to provide a client with an invalid response to ensure the client can gracefully handle it.

Fix protocol test issues

---

docs/source/1.0/spec/core/xml-traits.rst

Perhaps the colon is removed due to some escaping issue or whathave you, but in case not.

Fix uri formatting in xml example.

---

docs/source/1.0/spec/aws/glacier-customizations.rst
docs/source/1.0/spec/aws/index.rst
smithy-aws-protocol-tests/model/restJson1/services/glacier.smithy

This adds documentation and protocol tests for the customizations required to generate Glacier client.
For the protocol tests, I included a representative subset of the Glacier model with protocol tests added in. I'm unsure if this is the right strategy though. The other option would be to include the entire model. That would reduce the risk of excluding too much, but also potentially results in having some truly massive models buried in this repo.

Add docs/tests for Glacier customizations

---

docs/source/1.0/spec/http-protocol-compliance-tests.rst
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMessageTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/missing-vendor-params-shape.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/missing-vendor-params-shape.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/vendor-params-validation.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/vendor-params-validation.smithy

This commit adds a new member to HttpMessageTestCase based traits,
vendorParamsShape. When supplied, the parameters in vendorParams MUST
be compatible with the shape's definition.

Add support for validating vendorParams

---

docs/source/1.0/spec/aws/customizations/index.rst
docs/source/1.0/spec/aws/customizations/machinelearning-customizations.rst
docs/source/1.0/spec/http-protocol-compliance-tests.rst
smithy-aws-protocol-tests/model/awsJson1_1/services/machinelearning.smithy
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestCase.java
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-request-features.smithy

This adds the ability for the http request tests to model assertions
on the host. This can be useful for asserting that the endpoint trait
is properly supported, as well as allowing for testing things like
AWS clients' ability to resolve hosts based on the service id and
region.

Add host validation to http request tests

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-json.rst.template
docs/source/1.0/spec/aws/aws-query-protocol.rst
smithy-aws-protocol-tests/model/awsJson1_0/endpoints.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_1/endpoints.smithy
smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
smithy-aws-protocol-tests/model/awsQuery/endpoints.smithy
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/ec2Query/endpoints.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy
smithy-aws-protocol-tests/model/restJson1/endpoints.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restXml/endpoints.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json

This adds tests to the aws protocol tests to exercise the capabilities of the endpoint trait. It relies on this pr for the test updates: https://github.com/awslabs/smithy/pull/707 (so only the last commit matters)

Add protocol tests for the endpoint trait

---

smithy-aws-protocol-tests/model/aws-config.smithy

This  adds aws config definitions intended to be used alongside: https://github.com/awslabs/smithy/pull/702
It's not an exhaustive listing, but includes most of what should be needed for protocol tests.

Add config definitions for aws protocol tests

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedOperationError.java

Shape and Error in message is misplaced. Swapped it to correct places.

Fixed misplaced shapeId and errorId in error message

---

smithy-aws-protocol-tests/model/restXml/http-query.smithy

Updating protocol unit test to use `application/xml` instead of `xml`

fix: protocol tests, update bodyMediaType to application/xml

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTraitParser.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-operation-binding.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-operation-binding.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-resource-binding.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-resource-binding.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-service-binding.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-service-binding.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-trait-member-names.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-trait-member-names.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-trait-object-keys.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-trait-object-keys.smithy

This commit updates the Smithy IDL parsing to throw when duplicate
bindings or members are found in the following declarations: service,
resource, and operation shapes, applied structure traits, and applied
traits with members that are structures. This behavior is unsafe for
model writers and shouldn't be valid.

Throw syntax exceptions on duplicate bindings

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-restxml-protocol.rst

fix typo attrubute to attribute

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsToRestIntegrations.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrations.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/ApiGatewayExtension.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CorsHeader.java
smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CorsHttpIntegration.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/CorsHttpIntegrationTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors-wildcards.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/Context.java

This is a WIP PR to add support for CORS to API Gateway HTTP APIs. It still needs to be integration tested with an actual API Gateway API.

[WIP] Add support for CORS to API Gateway HTTP APIs

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
smithy-aws-protocol-tests/model/ec2Query/endpoints.smithy
smithy-aws-protocol-tests/model/restJson1/endpoints.smithy
smithy-aws-protocol-tests/model/restXml/endpoints.smithy

Fix multiple endpoint protocol tests

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/RenameShapes.java
smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer
smithy-build/src/test/java/software/amazon/smithy/build/transforms/RenameShapesTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/rename-shapes.json

Adds a `renamesShapes` transformer that can be used to rename shapes in a projection by configuration through smithy-build.

Add renameShapes transformer

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java

This commit adds support for aligning interpolated values with the
column in which the interpolation occurs. This ensures that any newlines
contained in the expanded text are automatically aligned with where the
interpolation occured, allowing for easy and more specific alignment of
generated code for things like method parameters.
Any brace interpolation syntax that ends with '|}' will now use
alignment.
For example:
```
CodeWriter writer = new CodeWriter();
writer.write("$1L() {\n" +
"    ${2L|}\n" +
"}", "method", "// this\n// is a test.");
```
Outputs:
```
method() {
// this
// is a test.
}
```

Add support for CodeWriter interpolation alignment

---

smithy-aws-protocol-tests/model/awsJson1_1/null.smithy
smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restJson1/json-structs.smithy
smithy-aws-protocol-tests/model/restJson1/streaming.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy

This updates the tests that handle null values in json / http
protocols to differentiate between client and server behavior.

Update null value serde tests for servers

---

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/SelectCommand.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ValidatorDefinition.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/Context.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/IdentitySelector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/Selector.java
smithy-model/src/main/java/software/amazon/smithy/model/selector/WrappedSelector.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/linters/EmitEachSelectorValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/IdentitySelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/SelectorTest.java
smithy-model/src/test/java/software/amazon/smithy/model/selector/TopDownSelectorTest.java

This commit improves the usability of Selectors by adding new methods to
the Selector interface and by deprecating its runner functionality. The
new methods include methods to stream matching shapes, stream matches,
and consume matches. Streaming matches and shapes requires a minimal
amount of buffering, and they provide the ability to more easily perform
checks like determine if any shapes in a model match a selector. If all
matching shapes are necessary, calling select is preferred. If consuming
matches can be done in a way that is push-based (e.g., writing to CLI
output), then using consumeMatches is preferred to matches.
The previous runner() method of Selector is now deprecated and just
delegates calls back to the Selector. runner() was initially intended to
allow for the …

Improve Selector usability

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst

Fix query list serialization examples

---

smithy-aws-apigateway-traits/src/main/resources/META-INF/smithy/aws.apigateway.json
smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json

Add missing documentation for some trait models

---

docs/source/quickstart.rst

The code within the quickstart does not work on windows due to an issue that has been solved in a later version of the plugin https://github.com/awslabs/smithy-gradle-plugin/issues/27. 
Updated the version listed in the quickstart. 

Updated plugin version in quickstart docs

---

docs/source/1.0/spec/core/constraint-traits.rst
docs/source/1.0/spec/core/documentation-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/RecommendedTrait.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/recommended/recommended-trait.smithy

This commit adds support for a `recommended` structure member trait.
> Indicates that a structure member SHOULD be set. This trait is useful when the majority of use cases for a structure benefit from providing a value for a member, but the member is not actually required or cannot be made required backward compatibly.

Add recommended trait

---

docs/requirements.txt
docs/setup.py

Upgrade Pygments to 2.7.4
Resolves CVE-2021-27291

Upgrade Pygments

---

smithy-aws-protocol-tests/model/restXml/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

Adds protocol test for serializing a payload, preferring the xmlName set on the member over the target when generating the wrapper name.

Prefer member xmlName for httpPayloads

---

README.md
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/converting-to-openapi.rst

Updates the README and docs to specify version `0.5.2` of the Smithy Gradle Plugin.

Update gradle plugin version

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy
smithy-aws-protocol-tests/model/restXml/http-query.smithy

This fixes an issue with the protocol tests for query maps where there was a string-string map that didn't include everything else that was in the test. To keep things simple I split it off into its own test.

Fix query string-string map protocol tests

---

smithy-aws-protocol-tests/model/restJson1/http-string-payload.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

*Description of changes:* There are no protocol tests for Strings or enum-marked-strings for restJson.
*Tests*: The Rust SDK passes these tests.

Add protocol tests for String & Enum HTTP payloads

---

smithy-aws-protocol-tests/model/restXml/http-query.smithy

* Update text Xml to match structure name
* It's expected that this will enable the test to pass if protocol implementation is compiliant
Response from @kstich from internal discussion:
```
It's possible, would need to validate by updating and running another SDK's tests. I think others might not be validating the name of the root node for the response when deserializing.
```

Update sample xml to match structure name for test.

---

smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json

Adds `name` property to the enum entries on the Condition Key Types.
This prevents the EnumNamesPresent validation warning from being emitted when applying the `aws.iam#defineConditionKeys` [trait](https://awslabs.github.io/smithy/1.0/spec/aws/aws-iam.html#aws-iam-defineconditionkeys-trait).

Add name property to ConditionKeyType enum

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/FlattenNamespaces.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/FlattenNamespacesTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/flatten-namespaces-with-renames.json

Adds support for service renames (#734) when using the `flattenNamespaces` transformer.
Any shapes that have been configured on the service to be renamed will also be flattened into the target namespace.

Support service renames when flattening namespaces

---

.github/CODEOWNERS

This adds a codeowners file that will automatically request reviews from the core contributors on each pr. We could make it more complicated but that doesn't seem necessary right now.

Add core contributors to PRs by default

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy
smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy

A number of tests for restJson1, notably tests that only set headers,
had the expected response body set to an empty string. These actually
would need to be empty json objects since restJson1 operations with
a defined output shape always need to send something. This just
removes the body entry in the tests since that behavior is covered
by more specific tests.

Remove falsely set empty bodies for restJson1

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/AdditionalPropertiesMapper.java
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/CoreExtension.java
smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/AdditionalPropertiesMapperTest.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/disable-caps-fooresource.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/complex-resource.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/queue-example.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/simple-service-aws.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/smithy-testservice-fooresource.cfn.json

This commit adds a CfnMapper that defaults the `additionalProperties`
property to `false` for named entries in a schema's `definitions` that
are of the `object` type. This is recommended behavior by CloudFormation
and, if not present, results in a warning when developing a resource.
Fixes #750 

Set additionalProperties false for CFN objects

---

smithy-build/src/main/java/software/amazon/smithy/build/transforms/FlattenNamespaces.java

This PR incorporates feedback left on #760.
Within the `FlattenNamespaces` transformer, the pair is destructured before calling the `applyServiceRenames` method to improve readability.

Destructure pair before calling method

---

build.gradle

Closes #763
Disables HTML doclint to allow builds to succeed on JDK15.
This works around inconsistencies between the HTML heading tag sequence validation between JDK15 and earlier versions.

Disable HTML doclint

---

.github/workflows/ci.yml

Updates CI to run builds on JDK15 and macOS.

Run CI on JDK15 and macOS

---

docs/source/1.0/spec/core/selectors.rst

Fixes the `selector_expression` entry in the selectors grammar documentation.

Fix ABNF selector_expression

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/node/internal/NodeHandler.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.smithy

Currently, numbers greater than 9223372036854775807 fail to be parsed from the IDL with `NumberFormatException`, even when the underlying implementation supports BigDecimal and BigInteger.
This PR updates the IdlModelParser and NodeHandler to use fall back to using `BigDecimal` or `BigInteger` where appropriate.

Parse numbers as BigDecimal or BigInteger when needed.

---

README.md

This fixes the ci bade link to point to: https://github.com/awslabs/smithy/workflows/ci.yml

Fix ci badge link

---

docs/source/1.0/spec/core/idl.rst

Fix comment ABNF

---

smithy-model/src/main/java/software/amazon/smithy/model/Model.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/boolean-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/collection-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/document-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/documentation-trait.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/metadata.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/number-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/object-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/optional-namespaces-are-stripped.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/service-shapes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/simple-shapes.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/string-traits.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/input.json
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/output/ns.primitives.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/multiple-namespaces/output/ns.structures.smithy

Version 1.1 of the IDL will include the optional comma update, but it
should also include as many other syntactic changes as we can to reduce
the number of bumps needed for the IDL (for example, mixins, sugar for
optional and required traits).

Start work towards version 1.1 of the IDL

---

smithy-aws-protocol-tests/model/restXml/document-maps.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

Add rest xml protocol tests for nested maps

---

docs/source/1.0/spec/core/endpoint-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HostLabelTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/host-request-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/host-request-validator.json

This updates the documentation and adds a warning for the case where a `hostPrefix` contains a host label but does not end in a period. This is potentially risky since it could change the domain to something that the modeler doesn't control. For example, a host label of `{foo}` combined with a configured endpoint `example.com` could result in a resolved host of `mistakeexample.com` when the modeler wanted it to resolve to `mistake.example.com`. If the modeler doesn't own EVERY domain suffixed by the configured endpoint then it is possible that customer data will be exposed.
Resolves #778 

Warn against potentially risky hostPrefixes

---

.github/workflows/ci.yml

This adds a CI step to run the documentation build. This should ensure that changes at least result in a successful build. It also uploads the docs built so you could look at them without having to build them yourself.

Add doc build to ci

---

docs/source/1.0/spec/core/http-traits.rst

This adds a textual description of how to handle conflicts between httpQueryParams and httpQuery

Add conflict resolution info to query param docs

---

docs/source/1.0/spec/core/constraint-traits.rst

Document precedence for constraint traits

---

smithy-aws-protocol-tests/model/restXml/http-payload.smithy
smithy-aws-protocol-tests/model/restXml/main.smithy

Adds a rest-xml protocol test to ensure that xml wrapper name is set using the xmlName applied on the structure itself.

Add structure xmlName wrapper test

---

smithy-aws-protocol-tests/model/restJson1/json-structs.smithy

I think this is a bug in the `RestJsonServersDontSerializeNullStructureValues` protocol codegen test.  There doesn't seem to be a member called "string", and I suspect the intention was to use `stringValue`.
If this is not the intent, please let me know.  Thanks!

Update RestJsonServersDontSerializeNullStructureValues body

---

smithy-aws-protocol-tests/model/restXml/document-lists.smithy

* Adds a test for ignoring the root element name since some services like S3 do not send a root element that matches the structure shape id from the model
* expanded the xml list test to include a flattened list of structures (we had an issue in Kotlin where the deserializer state got messed up by this case, maybe it helps someone else)

add restXml tests for flattened list of structures

---

README.md
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/converting-to-openapi.rst
docs/source/1.0/guides/generating-cloudformation-resources.rst
docs/source/quickstart.rst
smithy-aws-protocol-tests/build.gradle

Updates `smithy-aws-protocol-tests` to use version `0.5.3` of the [Smithy Gradle Plugin](https://github.com/awslabs/smithy-gradle-plugin).
Docs are also updated to recommend using this version.

Use plugin version 0.5.3

---

smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy

Fix xmlns issues in awsQuery tests

---

smithy-cli/build.gradle

The CLI previously used `-XX:TieredStopAtLevel=2` to limit the amount of
intermediate compilation the CLI would perform. This helps a little bit
with quicker startups in the CLI, but it also caused the CLI to perform
significantly slower for longer running tasks like validating hundreds
of thousands of models.

Remove TieredStopAtLevel from the CLI

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-additional-headers.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors-wildcards.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors.openapi.json
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/TimestampMapper.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service-integer.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

OpenAPI supports a format called "double" on the "number" type to indicate
that a number is a double precision floating point number. Timestamps
that use epoch-seconds have been updated to use this format so that
stricter JSON Schema validators don't error when they encounter
decimals. "double" is only added as a format when performing OpenAPI
conversions and are not added by default when performing JSON Schema
conversions.

Add "double" format to epoch-seconds timestamps

---

smithy-cli/src/main/java/software/amazon/smithy/cli/SmithyCli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/BuildCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/CommandUtils.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidateCommand.java
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Validator.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/ValidateCommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/validation-events.smithy
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

This commit closes #797
The CLI will now log validation events as they occur rather than waiting
until all events are encountered before writing them. This makes the CLI
a bit more responsive when validating hundreds of thousands of shapes.
Other improvements were added to the CLI output as well, including the
--severity parameter to set the minimum severity to display in output.
This can significantly cut down on noise when model files emit things <
DANGER.

Make CLI output improvements

---

docs/source/1.0/spec/core/http-traits.rst
smithy-aws-protocol-tests/model/restJson1/http-labels.smithy
smithy-aws-protocol-tests/model/restJson1/http-query.smithy

Two separate commits that increase coverage of percent encoding tests:
1. The current test actually admits buggy behavior where neither greedy nor non-greedy labels are escaped, a bug I know
impacts at least 1 SDK. This updates the test to include `/` in the non-greedy label to ensure that it is, in fact, escaped.
2. Add test for httpLabel/httpQuery escaping.
Smithy recently amended the HTTP label spec to clarify the set of characters that must be escaped. But, due to
a peculiarity of the spec, it Smithy omitted the `%` character from this set which definitely needs to be escaped.
This diff updates the spec and adds exhaustive test cases for both. These tests have been run on and pass the Rust SDK protocol test suite. (They also went the other way, I had 2 bugs …

Percent Encoding Test & Spec Enhancements

---

smithy-aws-protocol-tests/model/restXml/document-structs.smithy

Add protocol response test to cover XML escaping of literals as well as decimal & hexadecimal escape sequences.

Update Protocol Test with more complex XML Unescaping

---

smithy-aws-protocol-tests/model/restJson1/documents.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

Add more document type protocol tests

---

smithy-build/src/main/java/software/amazon/smithy/build/model/ConfigLoader.java
smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java

Unfortunately I couldn't really write a test for this since it relies on the config file existing in the in the current working directory.
Fixes #811

Set baseImportPath to . when config parent is empty

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java

* Fix typo
* Describe section behavior in terms of scope rather than effect.

Fix typo and change word to better describe behavior (IMO)

---

smithy-aws-protocol-tests/model/awsQuery/empty-input-output.smithy
smithy-aws-protocol-tests/model/awsQuery/endpoints.smithy
smithy-aws-protocol-tests/model/awsQuery/input-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/input-maps.smithy
smithy-aws-protocol-tests/model/awsQuery/input.smithy
smithy-aws-protocol-tests/model/ec2Query/empty-input-output.smithy
smithy-aws-protocol-tests/model/ec2Query/endpoints.smithy
smithy-aws-protocol-tests/model/ec2Query/input-lists.smithy
smithy-aws-protocol-tests/model/ec2Query/input.smithy

This removes all the newlines from query formatted bodies in the AWS
protocol tests. While these made the tests easier to read, they
weren't actually valid since a client sending a body formatted that
way would encounter errors.
EC2 formats their docs that way, but they [make it clear](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Query-Requests.html) that it's just for readability:
> To make these example requests even easier to read, AWS documentation may present them in the following format:

Remove extraneous newlines from query tests

---

smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-json.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-json.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-xml.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-xml.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/valid-json.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/valid-xml.smithy

This commit updates protocol test validators to ensure that known media
types for XML and JSON contain valid content.
Closes #821

Validate known media types in protocol tests

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst

- Clarify protocol HTTP request behavior
- Remove all non-flattened query names since EC2 Query automatically flattens
all collections and maps in requests (as opposed to AWS Query where you have to
opt in to flattening with `@xmlFlattened`)
- Fix query capitalization in examples
- Remove nested `Result` tag from response documentation
- Add `Response` wrapper to error response example

Improve EC2 Query spec documentation

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-serialization.rst.template
docs/source/1.0/spec/aws/aws-restxml-protocol.rst

TODO in a followup commit: make similar changes to the ec2Query protocol
documentation.
Closes #767
Closes #345

Better describe AWS XML protocols

---

.github/CODEOWNERS

Remove chasecoa from codeowners

---

docs/source/1.0/guides/converting-to-openapi.rst
docs/source/1.0/guides/generating-cloudformation-resources.rst
docs/source/implementations.rst
docs/source/index.rst
docs/themes/smithy/landing.html

Add description of what exists today

---

settings.gradle
smithy-validation-model/build.gradle
smithy-validation-model/model/smithy.framework.validation.smithy

Server SDKs need a common, framework-level definition of a validation error
that service authors can opt into.

Add a model for validation errors

---

smithy-aws-protocol-tests/model/restJson1/json-maps.smithy

Adds a test to exersize a nested set within a map for `restJson1` protocol.  I had implemented some serialization code but forgot about nested Sets.  Protocol tests as-is didn't catch this case.
* `./gradlew test`

Add test for map of sets to restJson protocol test.

---

.github/workflows/ci.yml
Dockerfile
build.gradle
docs/source/implementations.rst
gradle/wrapper/gradle-wrapper.properties
smithy-cli/build.gradle
smithy-jmespath/src/test/java/software/amazon/smithy/jmespath/ast/LiteralExpressionTest.java

This commit adds support for cross platform builds of the CLI using
jlink via each support version of JDK 16 of Amazon Corretto (we'll bump
to JDK 17 when it's available). Each supported build target is built by
downloading the appropriate JDK from Corretto and running jlink.
The Dockerfile has been updated to now use the prebuilt binary for
linux-x86_64, and will now use application class data sharing to improve
CLI startup time in the Docker container.
A couple dependencies were updated, including Gradle, in order to build
on JDK 16. JDK 16 also complained about creating an explicitly boxed
value, so that was addressed too.
Future work should include building signed tar.gz and zip files, creating a
Mac pkg file via jpackage, and creating an msi via jpackage. …

Setup cross platform builds of the CLI

---

smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-xml-with-dtd.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/invalid-xml-with-dtd.smithy

Disallow loading DTDs, etc. in protocol tests

---

smithy-aws-protocol-tests/model/awsQuery/endpoints.smithy
smithy-aws-protocol-tests/model/awsQuery/input-lists.smithy
smithy-aws-protocol-tests/model/awsQuery/input-maps.smithy
smithy-aws-protocol-tests/model/ec2Query/input-lists.smithy

We ran into an issue with our serializer implementation on a real service (SES) that had a nested structure with list input (specifically [SendEmailRequest.Destination$ToAddresses](https://github.com/aws/aws-sdk-go-v2/blob/main/codegen/sdk-codegen/aws-models/ses.2010-12-01.json#L1834). I've added tests for both lists and maps (double check for correctness). Also there appears to be a broken test unless I'm mistaken, I've fixed that as well. 
- Adds tests lists/maps in a nested structure
- Fix the expected version of the `AwsQueryEndpointTrait` test

add new awsQuery tests for nested structs and fix endpoint test

---

docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-query-serialization.rst.template

This fixes the query serialization docs for ec2Query:
* Lists are always flat
* Maps are undefined

Fix list and map ec2 query serialization docs

---

docs/source/1.0/spec/core/constraint-traits.rst

I'm not sure if OWASP is the best resource for this sort of thing, or what our preferred references are to link to.

Add a warning about expensive pattern constraints

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CloudFormationSubstitution.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/CloudFormationSubstitutionTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cloudformation-substitutions.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-not-performed.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-performed.json

CloudFormation variables can be parameter names, resource logical IDs
or resource attributes.
* Parameter names: can be alphanumeric or pseudo-parameters, which can
be prefixed with "AWS::"
* Resource logical IDs: can be alphanumeric.
* Resource attributes: specified as resourceLogicalId.attributeName,
where attributeName is also alphanumeric.
This change was needed as part of https://github.com/adamthom-amzn/smithy-typescript-ssdk-demo/pull/28

Tighten substitution pattern for Fn::Sub

---

docs/source/1.0/guides/style-guide.rst
docs/source/1.0/spec/aws/aws-cloudformation.rst
docs/source/1.0/spec/aws/aws-core.rst
docs/source/1.0/spec/core/behavior-traits.rst
docs/source/1.0/spec/core/constraint-traits.rst
docs/source/1.0/spec/core/documentation-traits.rst
docs/source/1.0/spec/core/endpoint-traits.rst
docs/source/1.0/spec/core/http-traits.rst
docs/source/1.0/spec/core/idl.rst
docs/source/1.0/spec/core/index.rst
docs/source/1.0/spec/core/model.rst
docs/source/1.0/spec/core/protocol-traits.rst
docs/source/1.0/spec/core/resource-traits.rst
docs/source/1.0/spec/core/stream-traits.rst
docs/source/1.0/spec/core/type-refinement-traits.rst
docs/source/1.0/spec/mqtt.rst
docs/source/1.0/spec/waiters.rst
docs/source/quickstart.rst
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/multiple-required-exclamations.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/required-sugar-test.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/required-sugar.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/required-sugar.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/required-trait.smithy

Marking a structure member as required is a big deal, and it should be
something that's more visually apparent than the current `@required`
trait that can blend in with the rest of the traits applied to a
member.
This commit introduces sugar for applying the required trait to
structure members by suffixing a member with "!". This is semantically
equivalent to applying the trait using `@required` before the member or
using an `apply` statement with `@required`.
By applying the required trait using `!`, the vertical space needed to
define most structures should be reduced, making structures easier to
read.

Add IDL sugar for applying the required trait

---

docs/source/1.0/spec/http-protocol-compliance-tests.rst
smithy-aws-protocol-tests/model/restJson1/endpoint-paths.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

Sometimes, a service will have a path prefix that is not modeled. This adds a
test that ensures REST-JSON clients will properly take that path into account.

Add a protocol test for endpoints that contain path prefixes

---

smithy-aws-protocol-tests/model/awsQuery/xml-errors.smithy

Updates the protocol test to _not_ include the `<Message>` parameter which isn't present in the model.

Remove unused `Message` field from ComplexError

---

docs/source/1.0/spec/aws/aws-core.rst
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/CleanClientDiscoveryTraitTransformer.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryIndex.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryInfo.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryValidator.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/CleanClientDiscoveryTraitTransformerTest.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryIndexTest.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryTraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/endpoint-error.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/endpoint-error.smithy

Make clientEndpointDiscoveryTrait error optional

---

smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/OpenApiJsonAdd.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/mappers/OpenApiJsonAddTest.java

Using the jsonAdd feature with the Smithy to OpenAPI converter is
probably never what you actually want to do. It means that clients,
servers, and other artifacts generated from the Smithy model don't know
about the shapes being defined only in OpenAPI. This PR adds a severe
log warning when this is detected.

Warn when using jsonAdd with schemas

---

docs/source/1.0/spec/core/model.rst

This pull request fixes an apparent typo in the spec, where `#` was used instead of `$`.
I also changed the formatting slightly to bring it in line with other parts of the document.

Fix typos in spec about member shape IDs

---

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/CloudFormationSubstitution.java
smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/CloudFormationSubstitutionTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cloudformation-substitutions.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-not-performed.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/substitution-performed.json

This reverts commit fd5731f73a59ddbfe550a186ba654bed11e0efa0.
https://github.com/awslabs/smithy/pull/842 was made with the assumption that in the Smithy model, the strings that need Fn::Sub contain the final values as CloudFormation expects. It did not consider that those string could contain placeholder literals, like `<lambdaFunction>` or `{{REPLACEME}}` that could be post-processed by something like the CDK to generate the values as CloudFormation expects.

Revert "Tighten substitution pattern for Fn::Sub (#842)"

---

docs/source/1.0/guides/converting-to-openapi.rst

This fixes an issue where a code block wasn't showing up [here](https://awslabs.github.io/smithy/1.0/guides/converting-to-openapi.html#generate-openapi-setting-supportnonnumericfloats).

Fix broken code block in docs

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

On the server side, `@httpQueryParams` holds all of the query parameter values
in the request, so if any of the query parameters has a list value, then
`@httpQueryParams` must target a map with a list value, otherwise a 400 will be
thrown during deserialization, instead of discarding excess query param values.
An alternative solution could be to adjust SSDK behavior where `@httpQueryParams` would only receive query parameter values that were not otherwise explicitly bound to a structure member.
Prior art in this area is for the service to truncate to the last specified query parameter value when binding all query parameters to a map of strings, and since that's not at all a desirable behavior, and this doesn't change what gets put on the wire, we have …

Adjust query string parameter tests for servers

---

smithy-aws-protocol-tests/model/restXml/document-structs.smithy

Adds protocol tests covering whitespace that surrounds text elements as well as whitespace-only elements.
Tested against the Rust SDK.

add whitespace protocol tests for restXML

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpMethodSemanticsValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-method-semantics-validator.json

https://datatracker.ietf.org/doc/html/rfc5789#section-2
> PATCH is neither safe nor idempotent as defined by [RFC2616], Section
9.1.
>A PATCH request can be issued in such a way as to be idempotent,
which also helps prevent bad outcomes from collisions between two
PATCH requests on the same resource in a similar time frame.
Collisions from multiple PATCH requests may be more dangerous than
PUT collisions because some patch formats need to operate from a
known base-point or else they will corrupt the resource.  Clients
using this kind of patch application SHOULD use a conditional request
such that the request will fail if the resource has been updated
since the client last …

Remove warning when PATCH is idempotent

---

smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeSerializers.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java

This updates NodeMapper so that it can properly set source location on traits that use the AbstractTraitBuilder. Unfortunately the fix implemented here is a hack that looks for that specific case, and the same root cause may bite us elsewhere.
The true root cause is that our [default deserializer is unable to resolve generics](https://github.com/awslabs/smithy/blob/main/smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java#L434). AbstractTraitBuilder generically defines the return value of the setter `sourceLocation` to `B extends AbstractTraitBuilder`. When we use reflection to look at the return type, all we see is `AbstractTraitBuilder`. We *can* also get the type variable, but actually resolving it will take a decent amount of effort as that …

Update NodeMapper to handle Trait sourceLocation

---

smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/AuthorizersTrait.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/IntegrationTrait.java
smithy-aws-apigateway-traits/src/main/java/software/amazon/smithy/aws/apigateway/traits/MockIntegrationTrait.java
smithy-aws-cloudformation-traits/src/main/java/software/amazon/smithy/aws/cloudformation/traits/CfnResourceTrait.java
smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/DefineConditionKeysTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ArnReferenceTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ArnTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/auth/CognitoUserPoolsTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/auth/SigV4Trait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientDiscoveredEndpointTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/AwsProtocolTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AuthDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AuthTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EndpointTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExternalDocumentationTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpApiKeyAuthTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpErrorTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/IdRefTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/LengthTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ProtocolDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/RangeTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ReferencesTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/RetryableTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/TraitDefinition.java
smithy-model/src/test/java/software/amazon/smithy/model/traits/RetryableTraitTest.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpRequestTestsTrait.java

The sourceLocation should propogate from
1. TraitService.createTrait -> Trait
2. Trait -> createNode
3. Trait -> toBuilder
Across traits, this wasn't done consistently.

Fix sourceLocation propagation in Traits

---

smithy-aws-protocol-tests/model/restJson1/http-checksums.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

Adds a test for [httpChecksumRequired](https://awslabs.github.io/smithy/1.0/spec/core/behavior-traits.html#httpchecksumrequired-trait) trait

add httpChecksumRequired test

---

docs/source/1.0/spec/core/auth-traits.rst

* Update to auth docs that I believe mistakenly provide 'service' where 'operation' was intended.  If I misunderstood the point of the sentence kindly close the PR.

Fix wording of sentence describing enheritance behavior of auth trait

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedEnumTrait.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ChangedEnumTraitTest.java

(none)
When calculating Smithy diffs, enum value insertions should be flagged as errors because they can cause backwards incompatibility concerns when enum ordinals are used for iterating, serialization, etc. Enum values appended to the end of the existing set of values should not be errors.

Flag enum insertions as errors

---

smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestDefinition.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestTestsTrait.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestTestsValidator.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedResponseBodyDefinition.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedResponseDefinition.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ParameterizedHttpMalformedRequestTestCase.java
smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/UniqueProtocolTestCaseIdValidator.java
smithy-protocol-test-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-protocol-test-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-malformed-request-features.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-malformed-request-features.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-malformed-request-parameters.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-malformed-request-parameters.smithy
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-malformed-request-response.errors
smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/detects-invalid-malformed-request-response.smithy

Sets up the trait and serialization/deserialization of all of its members. This
trait allows server implementations to generate tests that reject invalid
requests before those requests are bound to a Smithy-generated implementation
class, or before the deserialized request is handed off to application code.
I'm going to keep this in draft mode for feedback while I work on generating tests from it to make sure this is actually useful.

Initial implementation of @httpMalformedRequestTests

---

docs/source/1.0/spec/core/behavior-traits.rst

Missed in https://github.com/awslabs/smithy/pull/843
httpChecksum.response should be a list

fix(docs): httpChecksum.response should be a list

---

smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-blob.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-boolean.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-byte.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-double.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-float.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-integer.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-list.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-long.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-map.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-request-body.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-set.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-short.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-union.smithy

Most of the numeric type tests are based on each other; if you've read one integral one and one floating-point one, you've read them all.

Some initial malformed request tests

---

docs/source/1.0/spec/core/http-traits.rst

Add note about structurally exclusive for httpQueryParams

---

smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-body.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-header.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-path.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-query.smithy

This is basically a really verbose matrix test. There are four files: one for body, header, query, and path. Each has three operations: one for whatever the default is for that type of member, and two more for the other two formats that aren't the default. The tests are essentially the same in every location, modulo formatting and where the value is injected. This is probably overkill, but it ensures that we don't have a server implementation where the validation of timestamps varies based on location.

Malformed request tests for timestamps

---

docs/smithy/__init__.py
docs/smithy/traitindex.py
docs/source/1.0/spec/aws/amazon-apigateway.rst
docs/source/1.0/spec/aws/aws-auth.rst
docs/source/1.0/spec/aws/aws-cloudformation.rst
docs/source/1.0/spec/aws/aws-core.rst
docs/source/1.0/spec/aws/aws-ec2-query-protocol.rst
docs/source/1.0/spec/aws/aws-iam.rst
docs/source/1.0/spec/aws/aws-json-1_0-protocol.rst
docs/source/1.0/spec/aws/aws-json-1_1-protocol.rst
docs/source/1.0/spec/aws/aws-query-protocol.rst
docs/source/1.0/spec/aws/aws-restjson1-protocol.rst
docs/source/1.0/spec/aws/aws-restxml-protocol.rst
docs/source/1.0/spec/core/auth-traits.rst
docs/source/1.0/spec/core/behavior-traits.rst
docs/source/1.0/spec/core/constraint-traits.rst
docs/source/1.0/spec/core/documentation-traits.rst
docs/source/1.0/spec/core/endpoint-traits.rst
docs/source/1.0/spec/core/http-traits.rst
docs/source/1.0/spec/core/protocol-traits.rst
docs/source/1.0/spec/core/resource-traits.rst
docs/source/1.0/spec/core/stream-traits.rst
docs/source/1.0/spec/core/type-refinement-traits.rst
docs/source/1.0/spec/core/xml-traits.rst
docs/source/1.0/spec/http-protocol-compliance-tests.rst
docs/source/1.0/spec/index.rst
docs/source/1.0/spec/mqtt.rst
docs/source/1.0/spec/waiters.rst

This adds an index of all existing traits to the specifications page. This makes it way easier to find the docs for a trait you know about without having to figure out what class of trait it is, or whether it lives in aws or somewhere else.
If you wanna see what it looks like, reminder that the doc build ci thing uploads the docs it built.

Add index of all traits

---

smithy-aws-protocol-tests/model/restJson1/empty-input-output.smithy
smithy-aws-protocol-tests/model/restJson1/http-payload.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-accept.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-content-type.smithy
smithy-aws-protocol-tests/model/shared-types.smithy

This adds malformed request tests for asserting content type and accept header behavior

Add malformed content-type / accept tests

---

docs/source/1.0/spec/core/documentation-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/traits/ExamplesTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExamplesTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/traits/ExamplesTraitTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/examples-trait-validator.json

This commit adds the ability to specify an error in the examples
trait. The error specified must be bound to the operation the trait
is applied to.
Resolves #736 

Add error support to examples trait

---

docs/source/1.0/spec/core/constraint-traits.rst
docs/source/1.0/spec/core/model.rst
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/ServiceIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AuthTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/CorsTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/UniqueItemsTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/AuthTraitValidator.java
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java

This deprecates the `uniqueItems` trait in favor of having ordered sets. Note: this PR is currently against the `idl-1.1` branch.

Make sets ordered

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

CodeWriter now support multi-character newlines like '\r\n'.

Add mutli-character newlines support in CodeWriter

---

.github/CODEOWNERS

This adds @DavidOgunsAWS to the codeowners so he'll be automatically added to PRs.

Add David to codeowners

---

smithy-aws-protocol-tests/model/restJson1/http-payload.smithy

This moves a pair of protocol tests from response to request, where they should have been from the start. 

Move accept/content-type protocol tests

---

smithy-aws-protocol-tests/model/awsJson1_0/endpoint-paths.smithy
smithy-aws-protocol-tests/model/awsJson1_0/main.smithy
smithy-aws-protocol-tests/model/awsJson1_1/endpoint-paths.smithy
smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
smithy-aws-protocol-tests/model/awsQuery/endpoint-paths.smithy
smithy-aws-protocol-tests/model/awsQuery/main.smithy
smithy-aws-protocol-tests/model/ec2Query/endpoint-paths.smithy
smithy-aws-protocol-tests/model/ec2Query/main.smithy

Followup to https://github.com/awslabs/smithy-typescript/pull/406. Add protocol test for RPC protocols path prefix support.

add test for rpc protocol path preix

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-path.smithy

In attempting to test rejection of a named timezone in a path parameter,
[Europe/Paris], the slash was accidentally left unencoded, which turned
it into a test of the URI matcher, instead of the timestamp deserializer.

Fix escaping in malformed request test

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/CoreExtension.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiMapper.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUriPrefix.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/mappers/RemoveUriPrefixTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mappers/remove-uri-prefix.smithy

Removes a prefix from paths derived from modeled Smithy operations. This can be useful when operations in a Smithy model include a prefix in the `uri` of the `http` trait to specify a version or "stage" of the API, but you need to integrate with gateways like Amazon API Gateway that expect to own placing this prefix onto the paths defined in OpenAPI models.
For example, if every operation in a Smithy model starts with "/v1", the following configuration would strip "/v1" from the beginning of every OpenAPI path generated from them:
```json
{
"version": "1.0",
"plugins": {
"openapi": {
"service": "smithy.example#Weather",
"removeUriPrefix": "/v1"
}
}
}
```

Add removeUriPrefix to OpenAPI converter

---

smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-blob.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-string.smithy

This adds more base64 tests, including ones for strings that use
mediaType in places where they need to be encoded.

Add more base64 malformed request tests

---

.github/CODEOWNERS

This updates the codeowners config to use a team so we don't have
to keep changing this file.

Use team for CODEOWNERS file

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildConfig.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/java/software/amazon/smithy/build/model/SmithyBuildConfigTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/unknown-plugin-ignored.json

smithy-build previously just logged an info when a build plugin couldn't
be found on the classpath. This was a bad user experience for actually
using Smithy. The requirement to be able to ignore a missing build
plugin is really an edge case for build tools that want to be able to
build just models and ignore other plugins, so those tools should opt-in
to that behavior instead. Just logging was way too subtle for diagnosing
issues with config files and dependencies.

Fail by default when a build plugin can't be found

---

smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java
smithy-cli/src/main/java/software/amazon/smithy/cli/LoggingUtil.java
smithy-cli/src/main/java/software/amazon/smithy/cli/SmithyCli.java
smithy-cli/src/test/java/software/amazon/smithy/cli/CliTest.java

This commit updates the CLI to use a nicer log message format, and to
also properly configure JUL when a logging level is given. We need to
later make changes to the Gradle plugin to enable configuring the CLI
loggers.

Fix how the CLI logs

---

docs/source/1.0/spec/aws/aws-query-protocol.rst

Fix typo in docs about awsQueryError's trait selector

---

docs/source/1.0/guides/building-models/build-config.rst
smithy-build/src/main/java/software/amazon/smithy/build/transforms/ChangeTypes.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/ChangeTypesTest.java
smithy-model/src/main/java/software/amazon/smithy/model/node/DefaultNodeDeserializers.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeDeserializationException.java
smithy-model/src/main/java/software/amazon/smithy/model/node/NodeMapper.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/AbstractShapeBuilder.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/CollectionShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/EntityShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeType.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ChangeShapeType.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/MapShapes.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformException.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java
smithy-model/src/main/java/software/amazon/smithy/model/transform/ReplaceShapes.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeMapperTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTypeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ChangeShapeTypeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ReplaceShapesTest.java

This commit updates the NodeMapper to properly handle generic type
parameters, even for types that have more than one generic type. The
concrete use case this now allows for is that you can deserialize into a
Map where the key is something other than a String.

Fix NodeMapper handling of generic params

---

docs/source/1.0/spec/core/model.rst
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ServiceShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ModelSerializerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ServiceShapeTest.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java

Not all use cases for Smithy modelt s can provide a service version. For
example, when using Smithy to generate libraries, not client/server
interactions, there's not really a version negotiation, so no version is
necessary in the model definition.

Make setting a service version optional

---

.github/workflows/ci.yml

setup-java v2 is the latest version
https://github.com/actions/setup-java/blob/main/README.md

ci: use setup-java v2

---

docs/source/1.0/spec/core/http-traits.rst

The spec says that URI patterns 'MUST NOT contain a fragment (i.e.
"#")'. Therefore, saying later that 'Labels MUST NOT appear in the
fragment' is confusing and redundant.

docs: delete unnecessary condition on URI path labels

---

smithy-build/src/main/java/software/amazon/smithy/build/ProjectionTransformer.java
smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/main/java/software/amazon/smithy/build/TransformContext.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/Apply.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/BackwardCompatHelper.java
smithy-build/src/main/java/software/amazon/smithy/build/transforms/ConfigurableProjectionTransformer.java

TransformContext's queued projections were a side effect of transformer
execution, and TransformContext instances were not maintained throughout
projection execution. In particular, BackwardCompatHelper would create a new
instance of TransformContext for its subclasses, but relying on a side effect
of transformation was dangerous in any case.
This adds a new method to ProjectionTransformer that explicitly models
composition of transforms by returning the names of projections to be run
subsequently. It is defaulted to an empty list.

Refactor queued projections

---

designs/inline-io.md

Add design for inline operation input/output shapes

---

docs/source/1.0/spec/core/http-traits.rst

*Issue #, if available:* #956
This commit documents how members with the `@httpQueryParams` trait
applied should be parsed in the presence of query string parameters that
do and do not have values specified.

Clarify parsing of `@httpQueryParams` members

---

smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.openapi.json
smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/CfnConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConfig.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConverter.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/JsonSchemaConverterTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/multiple-closures-with-conflicting-shapes.json

When creating JSONSchema from a Smithy model, any two conflicting shapes with
the same unqualified name would cause the process to fail, when in most cases
the conflict is only important if it occurs between two shapes connected to
the service in question.
CloudFormation resource schema generation must consider additional shapes
via @cfnResource's additionalSchemas property. This property is read by
the CFN index and subsequently discarded, so I simply disabled the more
narrowly-scoped conflict detection for CFN specifically. This can be removed
once shapes can be connected directly to a service.

Scope conflict detection more narrowly in JSONSchema conversion

---

docs/source/1.0/spec/aws/aws-core.rst
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/unsupported-http-checksum.smithy
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTraitValidator.java
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/HttpChecksumTraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-header-conflicts.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-member-enums.errors
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-member-enums.smithy
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.smithy

Update httpChecksum trait to uppercase algorithms

---

smithy-build/src/main/java/software/amazon/smithy/build/transforms/FilterSuppressions.java
smithy-build/src/test/java/software/amazon/smithy/build/transforms/FilterSuppressionsTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/namespaces.unchanged.json
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/namespaces.unchanged.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/noSuppressions.removeUnused.json
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/noSuppressions.removeUnused.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/noSuppressions.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/traits.eventIdAllowList.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/traits.removeUnused.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/transforms/filtersuppressions/traits.smithy

*Issue:*
FilterSuppressions uses builder.addShape [here](https://github.com/awslabs/smithy/blob/6ace7180592717eced4c01b5c317d68b9602c968/smithy-build/src/main/java/software/amazon/smithy/build/transforms/FilterSuppressions.java#L296) ) to update the traits on all shapes, including member shapes. However,  [`builder.addShape`](https://github.com/awslabs/smithy/blob/6ace7180592717eced4c01b5c317d68b9602c968/smithy-model/src/main/java/software/amazon/smithy/model/Model.java#L888-L889) does not support updating member shapes
directly.
Instead use ReplaceShapes which handles replacing member shapes too.
*Testing:*
Updated the traits.smithy test cases to cover the member case. They failed before this change.
By submitting this pull request, I confirm that my …

Fix filterSuppressions handling of members

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java

Ensure InputStreams in loader are closed

---

docs/source/1.0/spec/core/auth-traits.rst
docs/source/1.0/spec/core/constraint-traits.rst

Issue:
A couple of instances of incorrect documentation.
1. Fixes the trait selector for `@length` documentation to match what is currently defined in the prelude.smithy.
2. Fixes the incorrect example for `@auth` traits and how effective authentication schemes are determined. This documentation has also been expanded to make it clearer.  These examples can be verified correct by applying the following patch:
```
diff --git a/smithy-model/src/test/java/software/amazon/smithy/model/knowledge/ServiceIndexTest.java b/smithy-model/src/test/java/software/amazon/smithy/model/knowledge/ServiceIndexTest.java
index c36e335eb..a7a50748f 100644
--- a/smithy-model/src/test/java/software/amazon/smithy/model/knowledge/ServiceIndexTest.java
+++ …
```

Correct documentation for @length and @auth traits

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy

RFC 7230 sec 3.2.6 defines header values as potentially quoted strings, which
makes commas in header values unambiguous. It's also the only way to escape a
reserved character. This adds a test for list values with a comma and for list
values with escaped double quotes.

Add tests for quoted strings in headers

---

smithy-aws-protocol-tests/model/restJson1/http-content-type.smithy

https://github.com/aws/aws-sdk-js-v3/issues/3058
RestJsonTestPayloadStructure and RestJsonHttpWithHeadersButNoPayload had a `testId` param but no assertion for X-Amz-Test-Id header. Made the params/headers match.
*Testing:*
Regenerated test in aws-sdk-js-v3 and confirmed it fixes https://github.com/aws/aws-sdk-js-v3/issues/3058.

Fix http-content-type protocol tests with mismatched params/headers

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/auth/CognitoUserPoolsTrait.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/AwsProtocolTrait.java
smithy-build/src/main/java/software/amazon/smithy/build/ProjectionResult.java
smithy-model/src/main/java/software/amazon/smithy/model/Model.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/main/java/software/amazon/smithy/model/node/ArrayNode.java
smithy-model/src/main/java/software/amazon/smithy/model/node/Node.java
smithy-model/src/main/java/software/amazon/smithy/model/node/ObjectNode.java
smithy-model/src/main/java/software/amazon/smithy/model/node/internal/NodeHandler.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/AbstractShapeBuilder.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/EntityShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/NamedMembersShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/OperationShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ResourceShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ServiceShape.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AuthDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/EnumTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/ProtocolDefinitionTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/StringListTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/TraitDefinition.java
smithy-utils/src/main/java/software/amazon/smithy/utils/BuilderRef.java
smithy-utils/src/main/java/software/amazon/smithy/utils/DefaultBuilderRef.java
smithy-utils/src/main/java/software/amazon/smithy/utils/FunctionalUtils.java
smithy-utils/src/test/java/software/amazon/smithy/utils/BuilderRefTest.java
smithy-waiters/src/main/java/software/amazon/smithy/waiters/WaitableTrait.java
smithy-waiters/src/main/java/software/amazon/smithy/waiters/Waiter.java

This commit reduces the number of copies builders need to make when
building up immutable objects.

Reduce builder copies using a managed reference

---

README.md
docs/source/1.0/guides/building-models/gradle-plugin.rst
docs/source/1.0/guides/converting-to-openapi.rst
docs/source/1.0/guides/generating-cloudformation-resources.rst
docs/source/quickstart.rst
smithy-aws-protocol-tests/build.gradle
smithy-validation-model/build.gradle

Update the packages and docs to use the 0.6.0 version of smithy-gradle-plugin.

Use gradle plugin version 0.6.0

---

docs/source/1.0/spec/core/constraint-traits.rst

This is an update to [doc changes](https://github.com/awslabs/smithy/pull/988/files#diff-7b0b60de09d6316cd65e2b1ec7e75869eb84627fad7e6549f5834de4515bfa1d) made in https://github.com/awslabs/smithy/pull/988

Update @length trait documentation regarding collection shapes

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/CompositeModelFile.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/UnreferencedShapes.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidatedResult.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidationUtils.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ExclusiveStructureMemberTraitValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PrivateAccessValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/SensitiveTraitValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitTargetValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/UnreferencedShapeValidator.java

This commit attempts to cut down on the amount of allocations used when
validating Smithy models, including limiting the use of Streams in core
APIs, no longer copying validation events passed to ValidatedResult, and
no longer caching the result of every selector used in trait defintions
when evaluating trait targets.

Reduce allocations and garbage

---

designs/operation-input-output-and-unit-types.md
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

This commit removes documentation from the Unit shape in the prelude.
This is done to encourage tagged union members that target the Unit
shape to add their own member-specific documentation rather than to rely
on inheriting documentation from the Unit shape.

Remove documentation from Unit shape

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/Version.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/dupe-operation-binding.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/excess-operation-keys.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/excess-operation-keys.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/control-version-defined-twice.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-error.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-io-in-explicit-1-0.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-io-in-implicit-1-0.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-name-override.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-single-error.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/inline-structure-member.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/inline-io/walrus-operator-in-node.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/doc-comments.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/doc-comments.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/custom-suffix.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/custom-suffix.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/inline-io.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/inline-io.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/inline-io.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/service-shapes.smithy

This is an implementation of: #962

implementation of inlined operation input / output shapes

---

build.gradle

https://github.com/awslabs/smithy/issues/1006
Our javadocs are broken due to JDK bug
https://bugs.openjdk.java.net/browse/JDK-8215291 which is fixed in JDK 12.
We can work around it by specifying --no-module-directories when generating
javadocs.

Fix javadoc search links

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/doc-comments.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/custom-suffix.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/inline-io.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/inline-io/inline-io.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/idl-serialization/cases/inline-io.smithy

This updates inlined IO shapes to automatically include the input and output traits.

Add input and output traits with inlined IO

---

docs/source/1.0/spec/core/http-traits.rst

Adding another case for clarity.

Add doc for missing segment when greedy label in middle

---

smithy-aws-protocol-tests/model/restJson1/http-labels.smithy
smithy-aws-protocol-tests/model/restJson1/main.smithy

Characters like (, ) and + can be present, unescaped, in a path segment but
cause problems for protocol implementations that use regular expressions to
process paths. This adds a simple protocol test to help discover problems
with these implementations.

Add a test for regex expressions in path segments

---

docs/source/implementations.rst

Add Kotlin and Swift to https://awslabs.github.io/smithy/implementations.html#code-generators

Add links to Kotlin and Swift generators

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/mappers/prefix-headers.smithy

This commit removes support for binding the httpPrefixHeaders trait
to a map with a value targeting a list of strings.
This behavior isn't actually supported in practice by any client
or server implementations. It is also extremely difficult to support
not only because HTTP headers have no hard requirement on a common
grammar (see Set-Cookie), but also because many HTTP cliens can't
reliably control whether headers are sent in a single header field
or across multiple header fields.

Remove support for http prefix header maps of lists

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/AddedDefaultTrait.java
smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/RemovedRequiredTrait.java
smithy-diff/src/main/resources/META-INF/services/software.amazon.smithy.diff.DiffEvaluator
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/AddedDefaultTraitTest.java
smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/RemovedRequiredTraitTest.java

You can only add the @default trait to replace the @required trait. You
can only remove the @required trait if it's replaced by the @default
trait or if the containing structure has the @input trait.

Add @required and @default smithy-diff support

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy

*Issue #, if available:* 
https://github.com/awslabs/smithy/issues/1015
*Description of changes:* 
This reverts the change made for timestamp headers in https://github.com/awslabs/smithy/pull/986
The `http-date` timestampFormat is unambigous in terms of where commas
are located, so do not need escaping according to RFC 7230 sec 3.2.6.

Revert escape changes for timestamp header serialization

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/BigDecimalShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/BigIntegerShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/BlobShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/BooleanShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ByteShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/DocumentShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/DoubleShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/FloatShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/IntegerShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ListShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/LongShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MapShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/MemberShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/OperationShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ResourceShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ServiceShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SetShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShortShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/StringShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/StructureShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/TimestampShape.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/UnionShape.java

This was previously stored in an instance variable, but the shape type
is constant per/shape, so that's unnecessary, and it can be returned by
implementing getShapeType in each subclass.

Move getType of shape to subclass method

---

docs/source/1.0/spec/core/model.rst
docs/source/1.0/spec/core/selectors.rst
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/TopologicalIndexTest.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/DeconflictingStrategy.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/JsonSchemaConverter.java
smithy-jsonschema/src/main/java/software/amazon/smithy/jsonschema/RefStrategy.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/DeconflictingStrategyTest.java
smithy-jsonschema/src/test/java/software/amazon/smithy/jsonschema/DefaultRefStrategyTest.java
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/test-service.json
smithy-jsonschema/src/test/resources/software/amazon/smithy/jsonschema/test-service.jsonschema.json
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/OperationIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/neighbor/NeighborVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/OperationShape.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/service-with-nonconflicting-unit.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/service-with-nonconflicting-unit.smithy
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/nonconflicting-unit.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/nonconflicting-unit.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service-integer.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

Prevents Unit from being added to the service closure if it is only used by operation inputs and/or outputs, and
special-cases Unit for both operations and unions in JSONSchema conversion.

Make adoption of Unit easier for existing models

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy

Discovered this issue while upgrading smithy-rs to Smithy 1.15. It seems Smithy is parsing `""""b,c","\"def\"",a"""` as `"b,c",""def"",a` instead of the `"b,c","\"def\"",a` that the test intends. Whether or not this is a parsing bug in the Smithy IDL, I'm not sure.
Tested this fix against smithy-rs after making the code changes necessary to support quotes in the header lists.

Fix quoted string headers restJson1 protocol test

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

It's sometimes easier to deal with comma separated values by just always
throwing a ", " at the end of each element in the list, even for the
last element. The unwrite() method allows you to remove the last text
written to the CodeWriter if it matches a given substring. This
allows, for example, ", " to be "unwritten" to removing the trailing
comma without having to first check if the last text written was a
trailing comma. This is similar to Ruby's chomp() method.

Add unwrite() to CodeWriter to help with CSVs

---

smithy-aws-protocol-tests/model/restJson1/unions.smithy

The method and URI were wrong, likely due to copy/paste errors.

Fix RestJsonInputUnionWithUnitMember

---

docs/source/1.0/spec/core/behavior-traits.rst

Some of the recommendations in the previous pagination specification
were too hard to implement in practice. These changes mirror some of
the internal pagination guidance changes made in AWS over the years.

Update pagination descriptions

---

config/checkstyle/checkstyle.xml
docs/source/1.0/guides/model-linters.rst
smithy-linters/src/main/java/software/amazon/smithy/linters/RepeatedShapeNameValidator.java
smithy-linters/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.ValidatorService
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/repeated-shape-name-exact.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/repeated-shape-name-exact.smithy
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/repeated-shape-name.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/repeated-shape-name.json
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/stuttered-shape-name.errors

This adds a configuration option to the repeating shape name validator to specify that it should be an exact match rather than a prefix check.
This also deprecates the old validator in favor of the new one due to its less than ideal name.

Add exact match configuration to repeated shape name validator

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/AbstractValidator.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpBindingsMissingValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-bindings-missing-validator-warning.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-bindings-missing-validator-warning.json

HttpBindingsMissing emits an ERROR event for all services that have
inconsistently @http traited operations, but not all protocols support @http.
This change inspects the list of supported traits for every protocol trait
applied to the service, and if none of them support the http trait, then
HttpBindingsMissing is emitted at WARNING, instead of ERROR.

Reduce HttpBindingsMissing severity for non-REST services

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/DefaultValueInUpdateValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-patch-by-name-with-default.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-patch-by-name-with-default.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-resource-update-with-default.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-resource-update-with-default.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-update-by-name-with-default.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/default-value-in-update/finds-update-by-name-with-default.smithy

Partial update style operations should not use default values in their
top-level input members because it makes it impossible for the service
to know if the member was provided explicitly and meant to update the
value, or if the value was automatically set to its default zero value.

Warn when update operations use default values

---

smithy-aws-protocol-tests/model/restJson1/http-headers.smithy

I'm not sure how I missed this when working on https://github.com/awslabs/smithy/pull/1035 (I suspect human error with test exclusions), but the response test is also broken. Tested this fix against smithy-rs.

Fix quoted string headers restJson1 response protocol test

---

smithy-jmespath/src/main/java/software/amazon/smithy/jmespath/TypeChecker.java
smithy-jmespath/src/test/java/software/amazon/smithy/jmespath/TypeCheckerTest.java
smithy-waiters/src/test/resources/software/amazon/smithy/waiters/errorfiles/input-output-and-bug-test.smithy

The result of the LHS is returned if it is falsey. The previous
implementation incorrectly passed the result of LHS to RHS.

Fix JMESPath and evaluation

---

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/AwsClientNullableIndex.java
smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ClientOptionalTrait.java
smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/AwsClientNullableIndexTest.java
smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/ClientOptionalTraitTest.java
smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/client-optional-trait.smithy
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/NullableIndex.java

This trait helps existing AWS services transition from the more relaxed
semantics they've previously had around nullability to a future where
nullability can be relied on for things like code generation and
deserialization.

Add aws.api#clientOptional trait

---

designs/operation-input-output-and-unit-types.md
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

This trait should not have been `@internal`. The intent wasn't to make it considered internal only, but rather than no other shape can apply it other than `smithy.api#Unit`.

Remove @internal from @unitType trait

---

docs/source/1.0/spec/core/behavior-traits.rst

Add outputToken value clarification for clients

---

designs/mixins.md
docs/source/1.0/spec/core/idl.rst
docs/source/1.0/spec/core/json-ast.rst
docs/source/1.0/spec/core/model.rst
docs/source/1.0/spec/core/selectors.rst
docs/source/1.0/spec/core/type-refinement-traits.rst

This adds documentation for inline io and mixins. This documentation was mostly pulled from the design docs, but was updated in a number of places to better fit with the rest of the smithy docs.

Add docs for inline io and mixins

---

docs/source/1.0/guides/index.rst
docs/source/1.0/guides/migrationg-idl-1-to-2.rst
docs/source/1.0/spec/core/json-ast.rst

This is based off of #1064, so only the last commit here needs to be looked at.

Migration guide

---

docs/source/1.0/guides/migrating-idl-1-to-2.rst

There was a typo in the filename for the migration guide, as well as a broken ref. Not sure how I didn't catch those before.

Fix migration guide file name

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

It's sometimes useful to create other CodeWriters to do some work that
uses the same settings as another CodeWriter. The `copySettingsFrom`
method of CodeWriter takes another CodeWriter and copies its global and
state settings into itself.
This change also updates formatters registered with a CodeWriter to be
per/state. This means that if a formatter is added in a specific state,
then what that state is popped, the formatter is also removed and the
CodeWriter returns to its original state.

Add getters and ability to copy settings between CodeWriters

---

docs/source/1.0/spec/core/stream-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/StreamingTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-blob-without-httppayload.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-blob-without-httppayload.smithy

Protocols that support HTTP binding can only stream a blob if it is the payload
of the request or response. The streaming trait validator will now fail models
where a service ultimately references a streaming blob and the member is not
marked as @httpPayload.
Fixes https://github.com/awslabs/smithy/issues/1075

Tighten validation around @streaming blobs

---

docs/source/1.0/spec/core/http-traits.rst

https://github.com/awslabs/smithy/issues/1071
Existing implementations of restJson1 have diverging behavior for query
parameters with multiple values depending on whether @httpQuery or
@httpQueryParams is used. This updates the docs to use SHOULD to describe
the preferred, but not mandatory, behavior.

Add docs for deserialization of ambiguous query params

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriter.java

When the doc writer is just an anonymous lambda function, it makes sense
to hide it away in the parent implementation. But when it's a class that
satisifies the interface, there may be additional things on it that the
subclasses or callers will want to use. For example, a doc formatter.

Expose CodegenWriter's doc writer

---

smithy-aws-protocol-tests/model/restJson1/unions.smithy

Response tests, when generated for servers, rely on invoking an operation
and mocking a response from application code, but there is no member for
request data in a response test. Removing @required allows the operation to be
invoked.

Remove @required from protocol test input

---

docs/source/1.0/spec/core/constraint-traits.rst

docs: fix example trait for the `idRef` example

---

docs/source/1.0/spec/core/constraint-traits.rst

Some customers have seen failures because of not escaping the backslash.
I added it as a Note, and after the existing Warning/Important.
This is what it would look like

Add note about escaping backslash in pattern trait

---

smithy-aws-protocol-tests/model/restJson1/validation/malformed-length.smithy

*Issue #, if available:* https://github.com/awslabs/smithy/issues/1090
Server implementations that naively use code units instead of code points to
evaluate length constraints will give incorrect results. This adds parameters
to the existing string length tests that use multi-code-unit characters to
generate strings that will meet the constraints if code units are counted,
but properly fail the constraints if code points are counted.
I tested this by running them without the fixes in https://github.com/awslabs/smithy-typescript/pull/510 and observing that they fail, and then running them with the fixes and observing that they pass.

Add multi-code-unit characters to length validation tests

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriter.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterTest.java

CodegenWriter is supposed to be an opinionated implementation of
CodeWriter that automatically brings Symbols and imports together with a
CodeWriter. This commit adds a built-in "T" formatter for handling
Symbol and SymbolReference objects. This should work for most Smithy
codegen implementations, but the ones that it doesn't can either
override the "T" formatter or not use CodegenWriter.

Add built-in support for Symbol formatting

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-set.smithy

Sets of blobs, dates and documents are all valid, and may not be easily
supported in all targeted server languages.

Add malformed request tests for more set types

---

smithy-build/src/main/java/software/amazon/smithy/build/SmithyBuildImpl.java
smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-build/src/test/resources/software/amazon/smithy/build/test-bad-trait-serializer-config.json
smithy-build/src/test/resources/software/amazon/smithy/build/test-bad-trait-serializer-import.smithy
smithy-build/src/test/resources/software/amazon/smithy/build/test-bad-trait-serializer.smithy
smithy-utils/src/main/java/software/amazon/smithy/utils/SmithyBuilder.java
smithy-utils/src/test/java/software/amazon/smithy/utils/SmithyBuilderTest.java

When a SmithyBuilder implementation is missing a required property, the
name of the class that was missing the property will be included in the
error message. This is derived by looking at the stacktrace on error, so
it's an inference. But even an inference of the builder class is better
than having no idea which builder encountered an error when the stack
trace of the IllegalStateException is elided for whatever reason.

Improve SmithyBuilder error messages

---

smithy-aws-protocol-tests/model/restJson1/http-query.smithy

From a server perspective, `params` is the expected output after request
deserialization. Since `queryParamsMapOfStringList` is bound with
`@httpQueryParams` to the query string, its value must be present and
derived from the input `queryParams` field of the request test.

Fix some RestJson query string protocol request tests for servers

---

docs/source/1.0/spec/core/constraint-traits.rst

Since Smithy defines string shapes to be UTF-8 encoded, it is more
correct for the spec to explicitly say the `length` trait counts the
number of Unicode scalar values when applied to strings.

docs: `length` trait counts number of Unicode scalar values for strings

---

smithy-build/src/main/java/software/amazon/smithy/build/PluginContext.java
smithy-build/src/main/java/software/amazon/smithy/build/TransformContext.java
smithy-build/src/main/java/software/amazon/smithy/build/model/ProjectionConfig.java
smithy-build/src/main/java/software/amazon/smithy/build/model/SmithyBuildConfig.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolDependency.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolReference.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/TypedPropertiesBag.java

This commit makes use of BuilderRef to reduce copies of lists, maps, and
sets created from builders. Most builders are one-time-use, so this
prevents needing to allocate a copy of lists/maps/sets created from
builders and instead has the builder create copies at the point in which
a copied reference is reused.

Reduce copies in codegen-core and build

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriter.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/CodegenWriterTest.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriterDebugInfo.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterDebugInfoTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

This commit introduces typed properties for CodeWriter, allowing context
properties to be retrieved and assert they are a specific type.
While implementing this, I realized that if there is a type mismatch, it
could be hard to track down where in the process of writing code the error
occurred. So this commit also introduces some open debugging facilities
to CodeWriter that includes information about the state of the
CodeWriter (a '/' delimited path to the current state in the stack of
pushed states), the last N lines of code written (defaults to 2), and
any additional metadata subclasses want to introduce. This information
is then presented when CodeWriterDebugInfo is cast to a string.
Most exceptions thrown by CodeWriter will now include this debug output. …

Add debug info and typed context to CodeWriter

---

docs/source/1.0/guides/building-models/build-config.rst

* All model _names_ referenced by the manifest, may be confused with shape names. All model _files_ seems clearer.
* _building_ a projection seems clearer than _applying_ a projection. And matches the earlier sentence - _When building the source projection_.

Clarify doc about sources plugin

---

docs/source/1.0/spec/aws/aws-restjson1-protocol.rst

This updates the error serialization docs for restJson1 to call out what new server implementations must do vs what clients must accept.

Update restJson1 error serialization docs

---

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriterFormatterContainer.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

CodeWriter's formatter was rewritten to make it easier to understand, maintain, and evolve. As part of this evolution, this change adds the ability to pass a Runnable into a CodeWriter 'C' formatter (meaning "call"). When encountered, CodeWriter will invoke the Runnable and expect it to make calls to mutate the writer. Any text written is captured and used as the parameter value. This allows larger templates to be defined but still delegate functionality to separate methods. When coupled with text blocks in newer versions of Java, this largely makes things like openBlock/closeBlock irrelevant.
This change also is technically backward incompatible because it removes the ability to register a CodeWriter formatter using '[',']', '{', '}', '|', '<', '>'. Registering a formatter with these …

Rewrite code writer formatting to allow for Runnable evaluation

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/DependencyTracker.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/DependencyTrackerTest.java
smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/dependencies-test.json

This tracker can be used to manage and query dependencies, to track
dependencies that need to be used at runtime by generated code, and load
dependencies from a JSON file.

Add DependencyTracker for symbols

---

docs/source/1.0/spec/core/http-traits.rst
smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy

Clarify defaulting behavior of response code binding

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/CodegenContext.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/IntegrationTopologicalSort.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyCodegenSettings.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyIntegration.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/IntegrationTopologicalSortTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SmithyIntegrationTest.java

Codegen integrations typically all follow a similar format -- they
provide hooks for modifying the code generator and are discovered using
SPI. This commit adds a base interface for codegen integrations and
settings objects. The integration object is as minimal as possible
whill still providing some utility and conformity across
implementations, and the settings object just provides a minimal
`getService` method. Each Java implementation of Smithy codegen has such
a method in their settings object, and so does the Kotlin based Rust
generator.
The integration interface is very simimlar to both TypeScript and Go
integrations, though not exactly the same as either. The TypeScript
generator passes the entire PluginContext to preprocessModel, but that
is never actually needed and makes it …

Add interface for codegen integration and settings

---

smithy-build/src/test/java/software/amazon/smithy/build/SmithyBuildTest.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java

Fix incorrect warning for service errors property

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/DocWriter.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/JavaStyleDocumentationWriterBuilder.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/SymbolWriter.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/IntegrationTopologicalSortTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SmithyIntegrationTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/MySimpleWriter.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/writer/SymbolWriterTest.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/SimpleCodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/SimpleCodeWriterTest.java

Adding a parent of CodeWriter that changed the return type of its methods, even
though those returned objects were always in practice the same type as they had
been before, broke binary backwards compatibility for consumers of CodeWriter.
This forks CodeWriter back to its previous state, mostly, and adds a new
default extension of AbstractCodeWriter called TypedCodeWriter. Current
consumers of CodeWriter will continue to work, and have access to some new
features, such as the C formatter (though their Consumer will receive an
AbstractCodeWriter, not CodeWriter), and will keep onSectionPrepend and
onSectionAppend, but not have access to typed sections.
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Fix CodeWriter backwards compatibility

---

smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

There was an edge case where contents written to nested sections of
captured sections would be swallowed due to how code writer lazily
created StringBuilders. This change ensures that the root writer and
every interceptable writer always define a StringBuilder to ensure no
text is omitted.

Ensure code writer always has a StringBuilder

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java

The `resetDoesNotBarf` test would throw NPE before the change and now passes.

Reset ModelAssembler's validationEventListener to default

---

docs/source/1.0/guides/style-guide.rst
docs/source/1.0/spec/core/idl.rst
docs/source/1.0/spec/core/model.rst

Since sensitive trait on member is going to be disallowed in IDL 2.0, updating the 1.0 docs to remove examples with such usage.

(docs): Remove use of sensitive trait on members in doc examples

---

CHANGELOG.md
smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/SimpleCodeWriterTest.java

After calling .popState(), if the popped state required a newline + indent,
but the state being restored had not required an indent, we would lose the
popped state's required indent and emit the next line incorrectly.

Fix indentation bug in AbstractCodeWriter

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/ImportContainer.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolWriter.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/WriterDelegator.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriterFactory.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/DocWriter.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/package-info.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/MySimpleWriter.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolWriterTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/WriterDelegatorTest.java

The previous classes for CodegenWriter, CodegenWriterDelegator, and
ImportContainer were in the `@SmithyUnstableApi` package, `writer`. This
package relied on the now defunct `CodeWriter` (replaced by
`AbstractCodeWriter`). After learning more about how these abstractions
are being used and now that they need to be updated to use
`AbstractCodeWriter` instead, CodegenWriter has been obsoleted by
SymbolWriter, ImportContainer is obsoleted by a class of the same name
in the parent package, and CodegenWriterDelegator by WriterDelegator.

Create new classes for writing and delegation

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlNodeParser.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlTraitParser.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/IdlModelLoaderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/trait-locations.smithy

This fixes trait source locations from the IDL to start at the trait
itself rather than at the start of the trait's node definition. This
is particularly important for annotation traits where the source
location previously pointed to the column *after* the trait, which
doesn't necessarily even exist.
The following shows where the source location used to point:
```
@annotation
^
@annotationWithParens()
^
@listTrait(["foo"])
^
@structuredTrait({
^
"foo": "bar"
})
@structuredTraitWithoutBraces(
foo: "bar"
^
)
@primitiveTrait(true)
^
```
And this shows where they point now:
```
@annotation
^
@annotationWithParens()
^
@listTrait(["foo"])
^
@structuredTrait({
^
"foo": "bar"
})
@structuredTraitWithoutBraces(
^
foo: "bar"
)
@primitiveTrait(true)
^
```
By submitting this pull request, I confirm …

Fix trait source locations

---

docs/source/implementations.rst

Adding a link to smithy4s, a code generator and build tooling for Scala

Add smithy4s client/server codegen and sbt plugin

---

docs/source/1.0/guides/model-linters.rst
smithy-linters/src/main/java/software/amazon/smithy/linters/NoninclusiveTermsValidator.java
smithy-linters/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.ValidatorService
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter-append.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter-append.json
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter-override.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter-override.json
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter.errors
smithy-linters/src/test/resources/software/amazon/smithy/linters/errorfiles/noninclusive-term-filter.json
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/TextIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/TextInstance.java

* Adding validator to catch usage of non-inclusive words in the text of a Smithy model
* Since the list of non-inclusive words is statically small, those are hard coded
* The full text scanner internal to the validator can be abstracted further so a single pass over the model runs multiple validators more efficiently.
*TODO:*
Testing so far has been local. Follow up commit will add checked-in unit tests

Add inclusive words filter

---

smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeFormatter.java
smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriterFormatterContainer.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeFormatterTest.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

AbstractCodeWriter now supports Mustache-like behavior by allowing conditions and loops to be evaluated in templates. Note that this does disallow using '/', '?', '^', and '#' as formatters.
Conditions are defined using `${?foo}` where "foo" is the writer named parameter to evaluate. `?` is used to check if a value is truthy.
The following template with a "foo" value set to "Noid":
```
${?foo}
Hello, ${foo:L}!
${/foo}
```
Evaluates to:
```
Hello, Noid!
```
`^` can be used to check if a value is falsey. The following template with no set "baz" value:
```
${?baz}
Yes baz
${/baz}
${^baz}
No baz
${/baz}
```
Evaluates to:
```
No baz
```
A variable is falsey if it is Boolean false, an empty Iterable, an empty Optional, an empty Map, or an empty String. A variable is truthy if it is not falsey. …

Add support for conditions and loops to AbstractCodeWriter

---

smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/trait-locations.smithy

*Issue: *
Failing unit test has a Smithy 1.0 model that applies the @sensitive trait to a member which is no longer valid.
* Remove @sensitive trait from member.

Remove sensitive trait from member target that is no longer valid.

---

Dockerfile

The current Dockerfile expects a pre-built CLI artifact and does not bundle trait JARs.
- Compile Smithy CLI and traits in separate Docker stage
- Include trait jars in exec stage
To build:
`docker build -t smithy .`
Then, given I'm in a directory with some Smithy files:
```
./main.smithy
./user.smithy
```
To print AST:
`docker run --rm -v $PWD:/models smithy ast -d /smithy/lib/traits /models`

chore: Expand Dockerfile support

---

docs/source/1.0/spec/core/stream-traits.rst

We have no use case of a server needing to be constrained by
requiresLength. We can always expand this trait later if needed since
it's an annotation trait.
Closes #1086

Document that requiresLength only impacts requests

---

docs/source/1.0/spec/core/protocol-traits.rst
smithy-aws-protocol-tests/model/restJson1/unions.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/JsonNameValidator.java
smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/json-name.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/jsonName-conflict.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/jsonName-conflict.json

Allow jsonName trait on union members

---

smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/trait-locations.smithy

This re-adds a test case for annotation trait source locations without parens. It also adds in a detailed explanation of what the cases are doing since it wasn't clear before.

Re-add annotation trait location test case

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy

While HTTP response codes are only documented as between 100 and 599, various applications use custom codes > 500. This commit ensures that the code of the http trait is in the range of 100 and 999.

Validate that http.code is between 100 and 999

---

docs/source/1.0/spec/core/stream-traits.rst
smithy-aws-protocol-tests/model/restJson1/streaming.smithy
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/StreamingTraitValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/requiresLength-validator.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/requiresLength-validator.json

This commit does not allow using the requiresLength trait with streaming
blobs used in output shapes. We can lift this restriction in the future
if a use case ever arises, but by forbidding this use case now,
implementations are free to treat blobs marked with the requiresLength
trait as a specialization of a stream that affects the generated type.

Forbid using requiresLength with output

---

docs/Makefile
docs/README.md

Use python3 and pip3 to build docs.

Use python3 for building docs

---

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/DeprecatedTraitValidator.java

This validator previously looked for anything marked as deprecated then
checked to see if anything used that shape as a trait. However, the
intent was to find traits that are deprecated and applied to a shape.
The previous behavior would attempt to check if any shape, including
members, were applied as traits to shapes, which is impossible.

Optimize deprecated trait validation

---

docs/source/1.0/spec/aws/aws-core.rst
docs/source/1.0/spec/aws/aws-iam.rst
docs/source/1.0/spec/aws/customizations/s3-customizations.rst
docs/source/1.0/spec/core/idl.rst
docs/source/1.0/spec/core/traits/http-traits.rst.template
docs/source/1.0/spec/mqtt.rst

Omits commas to match updated model style guide: `Omit commas everywhere except in traits or node values defined on a single line.`

Omit commas to match style guide

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-blob.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-string.smithy

While `YmxvyG=` is _technically_ invalid base64 according to the spec
(its Unicode code point length is not divisible by 4), it can always be
unambiguously decoded, even over a network protocol that concatenates
base64-encoded strings and that would hence require padding characters.
Some off the shelf base 64 implementations, like the canonical `base64`
Rust crate (https://docs.rs/base64/latest/base64/), decode this case
successfully.

Remove invalid but extant base64 protocol test case

---

.github/workflows/ci.yml

This updates the CI to upload the test artifacts when there's failures. `-Plog-tests` is nice and all, but there's more context we're missing out on.

Upload test artifacts

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java

The settings deserialized from the provided helper method are useful for
providing the service shape ID to CodegenDirector.

Return deserialized settings from CodegenDirector

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-blob.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-string.smithy

This reverts commit e7d090c9992ec453b776359bb72ffe5c88601c80.
Based on the followup discussion in the original PR https://github.com/awslabs/smithy/pull/1168

Revert "Remove invalid but extant base64 protocol test case"

---

settings.gradle

gradlePluginPortal() uses jcenter which takes time to get latest releases. Using mavenCentral will make them available sooner.
The CI was seeing failures before this change, but is fixed by this.

Add mavenCentral as plugin reposiroty

---

smithy-model/src/main/java/software/amazon/smithy/model/FromSourceLocation.java
smithy-model/src/main/java/software/amazon/smithy/model/SourceLocation.java
smithy-model/src/test/java/software/amazon/smithy/model/SourceLocationTest.java

This CR implements Comparable on SourceLocation and adds a `compare` static method to FromSourceLocation for comparing SourceLocations.
This can be used to compare and sort shapes or traits, replacing the `SourceLocationSorter` and `TraitSorter` added in https://github.com/awslabs/smithy/pull/1175. It will also be used to sort shapes in the Smithy Language Server (https://github.com/awslabs/smithy-language-server/pull/35).

Implement comparable, add static compare method

---

docs/source/implementations.rst

This adds some clarification for the generator implementations table. For one, it wasn't super clear whether language was the target language or the generator language. But also, the aws rust generator code is in smithy-rs rather than aws-sdk-ust.
Closes #1190

Clarify implemenation table in docs

---

smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

It's sometimes useful to know where in a code generator a line of code generated text came from. Enabling stack trace comments will output the last relevant stack trace information caused text to appear in the code writer's output.
```
MyCustomWriter writer = new MyCustomWriter();
writer.enableStackTraceComments(true); // <- this is new
writer.writeWithNoFormatting("Hello 1");
writer.write("Hello 2");
writer.indent().write("Hello 3. ");
writer.writeInline("Hello 4. ");
writer.writeInline("Hello 5. ");
System.out.println(writer.toString());
```
Outputs:
```
/* software.amazon.smithy.utils.CodeWriterTest.writesDebugInfoOnEachLine(CodeWriterTest.java:1367) */ Hello 1
/* software.amazon.smithy.utils.CodeWriterTest.writesDebugInfoOnEachLine(CodeWriterTest.java:1368) */ Hello 2
/* …
```

Add stack trace comment support to code writer

---

docs/source/1.0/spec/core/constraint-traits.rst
docs/source/implementations.rst
docs/source/index.rst
docs/source/ts-ssdk/error-handling.rst
docs/source/ts-ssdk/handlers.rst
docs/source/ts-ssdk/index.rst
docs/source/ts-ssdk/introduction.rst
docs/source/ts-ssdk/supported-endpoints.rst
docs/source/ts-ssdk/validation.rst

[Intro](https://github.com/adamthom-amzn/smithy/blob/adb848d4851e3ad168c70e592854b97525685157/docs/source/ts-ssdk/introduction.rst)
[Handlers](https://github.com/adamthom-amzn/smithy/blob/adb848d4851e3ad168c70e592854b97525685157/docs/source/ts-ssdk/handlers.rst)
[Error Handling](https://github.com/awslabs/smithy/blob/adb848d4851e3ad168c70e592854b97525685157/docs/source/ts-ssdk/error-handling.rst)
[Endpoints](https://github.com/adamthom-amzn/smithy/blob/adb848d4851e3ad168c70e592854b97525685157/docs/source/ts-ssdk/supported-endpoints.rst)
[Validation](https://github.com/adamthom-amzn/smithy/blob/adb848d4851e3ad168c70e592854b97525685157/docs/source/ts-ssdk/validation.rst)

Add initial docs for TypeScript SSDK

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/Symbol.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SymbolTest.java

Add helper to convert Symbol to SymbolReference

---

docs/source/1.0/guides/migrating-idl-1-to-2.rst
docs/source/1.0/spec/core/traits/behavior-traits.rst.template
docs/source/1.0/spec/core/traits/http-traits.rst.template
smithy-aws-protocol-tests/model/restJson1/services/glacier.smithy
smithy-aws-protocol-tests/model/restJson1/streaming.smithy
smithy-cli/src/main/java/software/amazon/smithy/cli/commands/Upgrade1to2Command.java
smithy-cli/src/test/java/software/amazon/smithy/cli/commands/Upgrade1to2CommandTest.java
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/http-payload.v1.smithy
smithy-cli/src/test/resources/software/amazon/smithy/cli/commands/upgrade/cases/http-payload.v2.smithy
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelUpgrader.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/StreamingTraitValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/knowledge/HttpBindingIndexTest.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelUpgraderTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/requiresLength-validator.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-blob-without-httppayload.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-default-required.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-default-required.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/streaming-trait.json
smithy-model/src/test/resources/software/amazon/smithy/model/loader/upgrade/all-1.0/main.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/loader/upgrade/all-1.0/upgraded.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/streaming-service.smithy

Streaming blobs have always had an implicit default value, and this pr makes that status explicit by requiring that such members have either the required or the default trait.
1.0 models will have the default trait applied automatically, but it must be explicitly added in 2.0 models.

Make streaming blobs required/default

---

docs/source/1.0/spec/core/model-validation.rst

Add missing comma to EmitEachSelector validator example.

Add missing comma to EmitEachSelector example

---

smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java
smithy-model/src/test/java/software/amazon/smithy/model/shapes/ModelSerializerTest.java
smithy-model/src/test/resources/software/amazon/smithy/model/shapes/ast-serialization/cases/enums.json

This is an idl-2.0 specific patch since this happens much more frequently with `@enum` upgrades. This is present in `main`, but much less impactful without model upgrades -- I'll make a patch there as well if it's believed to be necessary.

Don't serialize empty traits blocks

---

smithy-model/src/main/java/software/amazon/smithy/model/node/NodeDiff.java
smithy-model/src/test/java/software/amazon/smithy/model/node/NodeDiffTest.java

Sort events in NodeDiff for ease of use

---

smithy-aws-protocol-tests/model/restJson1/main.smithy
smithy-aws-protocol-tests/model/restJson1/validation/sensitive-validation.smithy

Also suppresses a warning that we know is coming in a separate test for `@sensitive`.

Bind PostUnionWithJsonName protocol test operation

---

docs/source/1.0/spec/core/model.rst
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ShapeRecursionValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/union-cant-be-fully-recursive.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/union-cant-be-fully-recursive.smithy

Forbid fully recursive unions

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-accept.smithy

MalformedAcceptWithGenericString targets a Blob, while it should test the behavior with a String payload

Fix MalformedAcceptWithGenericString

---

smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java

This commit allows getters of any currently associated CodeSection to be
used as named parameters in AbstractCodeWriter templates. The context
bag is checked first, and if not found, methods of the associated
CodeSection, if present, are checked (x() and then getX()).

Add support for CodeSection named parameters

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/java/software/amazon/smithy/model/knowledge/HttpBindingIndex.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpResponseCodeSemanticsValidator.java
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-request-response-validator.json
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-response-code-semantics-validator-204.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-response-code-semantics-validator-204.smithy

And also mention that violating the HTTP spec in general is asking for a
bad time.
Closes #1244

Prevent bodies for 204/205 responses

---

docs/source/1.0/spec/core/documentation-traits.rst

Smithy validation doesn't allow type mismatch anywhere.
Updated the example in the documentation accordingly.

update @examples doc example to avoid type mismatch

---

docs/source/1.0/guides/building-models/gradle-plugin.rst

Based on the SmithyExtension code [here](https://github.com/awslabs/smithy-gradle-plugin/blob/eebf9c3a964519f6c1890e89e8857c1e47b1a0e6/src/main/java/software/amazon/smithy/gradle/SmithyExtension.java#L34), the right configuration name should be `allowUnknownTraits`.

chore(docs): fix allow unknown traits flag

---

docs/source/1.0/spec/core/http-traits.rst
smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/httpprefixheaders-on-sparse-map.errors
smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/httpprefixheaders-on-sparse-map.smithy

Disallow sparse maps with httpPrefixHeaders

---

smithy-cli/src/main/java/software/amazon/smithy/cli/SmithyCli.java

Exiting on 0 was causing issues in other tools that expected to use the
CLI in a thread.

Do not use System.exit(0) since 0 is the default

---

smithy-aws-protocol-tests/model/restJson1/http-response-code.smithy

*Issue #, if available:* in smithy-rs, https://github.com/awslabs/smithy-rs/issues/1229
Add tests for http response code. These tests ensure that
* `@required` and `@httpResponseCode` are correctly handled
* `@http`'s code is used in place of `@httpResponseCode` when the latter is not used

Http response code

---

docs/source/1.0/spec/aws/aws-json.rst.template

Remove jsonName note from awsJson protocols

---

build.gradle

This PR adds a build task that copies the maven metadata to `maven-metadata.xml` in the `.m2` repository.
Currently, the `publishToMavenLocal` task writes maven metadata to `maven-metadata-local.xml`. Some downstream tools, including Coursier only look for `maven-metadata.xml` when resolving dependencies from the `.m2` repository.
This task will run after `publishToMavenLocal` to make the same metadata available in both `maven-metadata-local.xml` and `maven-metadata.xml`.

Copy maven metadata on local publish

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/CodegenContext.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SmithyIntegration.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/ContextualDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CreateContextDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CustomizeDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/DirectedCodegen.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateEnumDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateErrorDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateResourceDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateServiceDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateStructureDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateUnionDirective.java
smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/ShapeDirective.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/IntegrationTopologicalSortTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/SmithyIntegrationTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/TestContext.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/TestIntegration.java

This PR has 2 commits.
The 1st commit, only made `SmithyIntegration`s available from CreateContextDirective, so subclasses
of CodegenContext can access it. But it likely can be made part of parent CodegenContext interface.
The 2nd commit, made it part of CodegenContext interface. ~~This requires another generic parameter to be added in multiple places.~~ Avoided adding generic parameter to CodegenContext by defining the method as `List<? extends SmithyIntegration<S, W, ?>> integrations();` where subclasses can return more specific `List<MyIntegration> integrations();`

Make SmithyIntegrations available from CodegenContext

---

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java

Generating shapes before generating Service level code that references those shapes seems like the better way to go and addresses https://github.com/awslabs/smithy-typescript/pull/548#discussion_r907869868.
Also fixes LOGGER name and adding a log line to indicate beginning of actual code generation logic.

Generate shapes before generating Service

---

docs/source/1.0/spec/core/idl.rst

The first one aligns the contents of the Smithy idl example with the
JSON AST, the second one removes the escape of the new line to align
the example with the output shown below.

Fix two typos in the specification doc

---

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/RequiredMapper.java
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/required-output.cfn.json
smithy-aws-cloudformation/src/test/resources/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/integ/required-output.smithy

*Description of changes:* This change excludes from the CFN schema required element all shape members that even though are marked as `@required` in the model are only used in output operations.

Do not map required members that are only used for output

---

smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/CorsTest.java
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-additional-headers.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors-wildcards.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/http-api-cors.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.openapi.json
smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations.openapi.json
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapperTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/adds-json-document-bodies.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/aws-rest-json-uses-jsonname.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/non-alphanumeric-content-names.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/synthesizes-contents.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json

*Issue #, if available:* #1274
*Description of changes:* When we create the JSON schema for open-api we were setting the format int32/int64 if the shape type is integer or long regardless of which type we were mapping to. This is not correct if we do not also map the type to the custom OpenAPI's integer type, as controlled by the `useIntegerType`  configuration setting, which if not set will map the type to "number" instead which cannot use these formats according to the [specification](https://swagger.io/specification/#data-types).  To fix the issue we need to only emit the format when we also map the type to "integer".

Set the int32/int64 format only when the type is mapped to integer

---

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ChangedMemberOrder.java

Remove Rust from the list of languages impacted by the changed member order issue
Remove Rust from the list of impacted languages under changed member order

Minor semantic correction

---

docs/source/1.0/guides/converting-to-openapi.rst

#1296
Update namespace of Weather service in OpenAPI converter guide to match the namespace of Weather service previously shown in Quick Start guide.

Modify namespace of Weather service in OpenAPI guide to match Quick Start documentation.

---

smithy-model/src/main/java/software/amazon/smithy/model/loader/FullyResolvedModelFile.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelAssembler.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelUpgrader.java
smithy-model/src/main/java/software/amazon/smithy/model/loader/Version.java
smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
smithy-model/src/test/java/software/amazon/smithy/model/transform/ChangeShapeTypeTest.java

The handling of unknown model versions for built shapes needs
to make no assumptions about the version of provided shapes.
Instead, it should use the UNKNOWN version which allows for any
kind of 1.0 or 2.0 trait/shape, but still attempts to convert
1.0 -> 2.0 compatible models when loading shapes. This was a
little haphazard before and we exposed controls to set the
assumed parsed version that have now been removed. I don't think
there's a reasonable use case where automated tooling will set
that right now.

Handle unknown model versions for built-shapes

---

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-path.smithy
smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-timestamp-query.smithy

*Issue #, if available:* #1315
*Description of changes:* Encode a space in the URI of test RestJsonPathTimestampDefaultRejectsDifferent8601Formats (case 13)

Encode space in test

---

docs/source/1.0/spec/core/idl.rst

https://github.com/awslabs/smithy/issues/1249
Remove optionality of `use_section` and `shape_statements` in `shape_section`.

Remove optionals in shape_section

---

smithy-model/src/main/java/software/amazon/smithy/model/Model.java
smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
smithy-model/src/main/java/software/amazon/smithy/model/traits/AbstractTrait.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TraitTargetValidator.java

I was doing some profiling and saw lots of string
computations caused by recomputing equals and hashcode.
This adds a cache for the hashCode of Shape and takes
advantage of the caching used for Trait and Shape when
performing equals checks.
I also don't think the cost of computing a canonical
class name is needed compared to using Class#getName
for Model's blackboard data structure.
Finally, I saw we were creating a Stream and not using it.

Add minor perf improvements

---

smithy-aws-iam-traits/src/main/resources/META-INF/smithy/aws.iam.json

Also adds the missing "ARRAY_OF_NUMERIC" variant from documentation.

Add documentation to IAM trait enums

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiVersion.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiJsonSchemaMapper.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverterTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/nullability-and-format.smithy
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/openapi-3-0-2.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/openapi-3-1-0.openapi.json

*Issue number:*
#985 
- Adds `version` OpenAPI config setting.
- If `version` is set to `"3.1.0"`, then handles nullability and format keyword differently.
- Nullable keyword does not get added to JSON Schema & adds a `type` extension of array value with `null` value, which overrides existing `String type` property in `Schema.java`. 
- Swap `format` keyword with `contentEncoding` keyword for file payloads.

Add OpenAPI 3.1 support to Smithy2OpenAPI - nullability & format keyword

---

smithy-model/src/main/java/software/amazon/smithy/model/neighbor/NeighborVisitor.java
smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TargetValidator.java
smithy-model/src/test/java/software/amazon/smithy/model/neighbor/NeighborVisitorTest.java

Mixin relationships can exist on any shape but we only created
a relationship for structure and union. This also attempts to
ensure that the list of relationships is created with sufficient
capacity to avoiding needing to resize the array as rels are
computed and added.

Add missing mixin relationships

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-openapi/src/main/java/software/amazon/smithy/openapi/OpenApiConfig.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiConverter.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test-use-oneof.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test-use-properties.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/error-code-collision-test.smithy

#1265 
- Add new OpenAPI config setting ``disableOneOf``.
- Combines response objects that share same HTTP status code before adding them to ``Map<String, ResponseObject> responses`` of ``OperationObject`` to prevent overwrites from happening.
- Test case + input / output files.
- Add documentation to existing OpenAPI converter guide regarding new config setting ``disableOneOf``.
_Internal:_
[Design doc](https://quip-amazon.com/BOTiANUdbNNu/Smithy2OpenAPI-Improvement-Project#temp:C:aMfab7e781fe5474397ab83a5d64)

Adds support for [multiple error response objects with same HTTP status code] to Smithy2OpenAPI.

---

docs/source/1.0/guides/converting-to-openapi.rst
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/OpenApiProtocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AbstractRestProtocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1Protocol.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/ExampleObject.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/MediaTypeObject.java
smithy-openapi/src/main/java/software/amazon/smithy/openapi/model/ParameterObject.java
smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/examples-test.openapi.json
smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/protocols/examples-test.smithy

Issue Number:
#921 
***Files changed:***
**OpenApiProtocol.java**
Just the contract of `createOperation()` method to include examples conversion, so implementers know that logic for examples conversion belongs in protocol specific implementation.
**AbstractRestProtocol.java**
Where all of conversion logic is located. Five methods created: `createExamples(), createErrorExamples()  createBodyExamples(), createErrorBodyExamples()` with a helper method `filter()`. Comments describe what they do.
**ExampleObject.java**
Smithy Example object's fields are populated into an instance of ExampleObject, thereby "converting" from Smithy to OpenAPI. I.e., ExampleObject.java is the OpenAPI model object equivalent of Smithy's Example.
**MediaTypeObject.java + ParameterObject.java**
Added these two …

Add @examples trait conversion to Smithy2OpenAPI converter for REST protocols.
