docs/source/guides/building-models/build-config.rst
=> Fix spelling error

aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java
=> Fix checkstyle issue

docs/source/spec/core.rst, smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/trait-definitions.json, smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/trait-definitions.smithy
=> Update docs to show trait selector is not required

docs/source/spec/core.rst, smithy-model/src/main/java/software/amazon/smithy/model/traits/RetryableTrait.java, smithy-model/src/main/java/software/amazon/smithy/model/traits/StreamingTrait.java, smithy-model/src/main/resources/software/amazon/smithy/model/loader/smithy-prelude-traits.json, smithy-model/src/test/java/software/amazon/smithy/model/traits/StreamingTraitTest.java
=> Extend streaming and retrtable traits with properties

build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst
=> Bump to 0.6.0

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java, smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java, smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLoader.java, smithy-model/src/test/java/software/amazon/smithy/model/loader/LoaderVisitorTest.java, smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
=> Make IDL able to handle partial parsing

smithy-build/src/main/java/software/amazon/smithy/build/PluginContext.java, smithy-build/src/main/java/software/amazon/smithy/build/plugins/SourcesPlugin.java
=> Expose sources functionality

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java
=> Optimize shape ID parsing

aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.api.json, docs/source/spec/aws-core.rst
=> Update and document aws.api#data trait

docs/source/spec/language-specification.rst, smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLexer.java
=> Remove "-" from the docs for unquoted strings

mkdocs
=> Automate documentation publishing

build.gradle.kts
=> Update license plaintext name in POM

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/duplicate-member-names.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/duplicate-member-names.smithy
=> Prevent duplicate member definitions

docs/source/quickstart.rst, docs/source/spec/core.rst, docs/source/spec/event-streams.rst, docs/source/spec/http.rst, docs/source/spec/selectors.rst, docs/themes/smithy/landing.html
I noticed the link to the full example on the front page wasn't working, so I
had a look at the docs and found a handful of other issues to fix.
=> Fix misc documentation issues

smithy-build/src/test/java/software/amazon/smithy/build/Test1SerialPlugin.java, smithy-build/src/test/java/software/amazon/smithy/build/Test2SerialPlugin.java
=> Fix serial plugin test race condition

aws/smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizers.java, aws/smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddAuthorizersTest.java, aws/smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/AddIntegrationsTest.java, aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/basic-authorizers.json, aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.json, aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/integrations-without-credentials.openapi.json, aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/AuthorizerDefinition.java, aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/apigateway/IntegrationTrait.java, aws/smithy-aws-traits/src/main/resources/META-INF/smithy/aws.apigateway.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/apigateway/errorfiles/invalid-authorizers.json, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst, docs/source/spec/amazon-apigateway.rst
This PR contains multiple commits for fixes to API Gateway integration points. It also bumps the package versions to 0.9.2
=> Apig fixes

CHANGELOG.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst
=> Bump version to 0.9.3

smithy-model/src/test/java/software/amazon/smithy/model/loader/ModelAssemblerTest.java
=> Fix creation of symlinks in tests

docs/source/spec/core.rst
=> Remove @collection reference from docs

build.gradle.kts
=> Update mavenCentral publish url

aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryValidator.java, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/endpoint-operation-unbound.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/errorfiles/invalid-endpoint-structure.errors, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/errorfiles/invalid-endpoint-structure.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/errorfiles/invalid-input-shape.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/errorfiles/no-endpoints-member.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/multiple-configured-services.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/no-configured-operations.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/no-operation-discovery.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/service-not-configured.json, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/clientendpointdiscovery/test-model.json, docs/source/spec/aws-core.rst
=> Update CachePeriod to CachePeriodInMinutes

aws/smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json, smithy-openapi/src/main/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJsonProtocol.java, smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.json, smithy-openapi/src/test/resources/software/amazon/smithy/openapi/fromsmithy/test-service.openapi.not-inlined.json
=> Update default timestamp format for aws.rest-json

CHANGELOG.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst
=> Bump version to 0.9.4

docs/source/guides/building-models/gradle-plugin.rst
=> Fix smithy-build.json typo (closes #188)

CHANGELOG.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst
=> Bump version to 0.9.5

smithy-utils/src/main/java/software/amazon/smithy/utils/IoUtils.java, smithy-utils/src/test/java/software/amazon/smithy/utils/IoUtilsTest.java
=> Add helpers for loading class resources

smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestSuite.java
This commit updates the SmithyTestSuite runner to use an
ExecutorService rather than a parallel stream to have finer control over
how tests are executed, including the ability to set a custom
ExecutorService.
=> Execute test cases in parallel

docs/source/spec/event-streams.rst
=> Fix event stream message serialization example

aws/smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/SdkServiceIdValidator.java, aws/smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/TestRunnerTest.java, aws/smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/sdk-id.json
=> Relax aws sdk id validation for ApiGatewayManagementApi

smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java, smithy-protocol-test-traits/src/test/resources/software/amazon/smithy/protocoltests/traits/errorfiles/all-request-features.smithy
=> Allow nulls in protocol tests

CHANGELOG.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst, smithy-codegen-freemarker/README.md
=> Bump version to 0.9.6

smithy-aws-protocol-tests/model/json-rpc-1-1/main.json
=> Add AWS JSON 1.1 protocol tests

smithy-aws-protocol-tests/model/query/empty-input-output.smithy, smithy-aws-protocol-tests/model/query/input-lists.smithy, smithy-aws-protocol-tests/model/query/input-maps.smithy, smithy-aws-protocol-tests/model/query/input.smithy, smithy-aws-protocol-tests/model/query/main.smithy, smithy-aws-protocol-tests/model/query/xml-errors.smithy, smithy-aws-protocol-tests/model/query/xml-lists.smithy, smithy-aws-protocol-tests/model/query/xml-maps.smithy, smithy-aws-protocol-tests/model/query/xml-structs.smithy, smithy-aws-protocol-tests/model/rest-xml/document-lists.smithy, smithy-aws-protocol-tests/model/rest-xml/document-maps.smithy, smithy-aws-protocol-tests/model/rest-xml/document-structs.smithy, smithy-aws-protocol-tests/model/rest-xml/http-headers.smithy, smithy-aws-protocol-tests/model/rest-xml/http-labels.smithy, smithy-aws-protocol-tests/model/rest-xml/http-payload.smithy, smithy-aws-protocol-tests/model/rest-xml/http-query.smithy, smithy-aws-protocol-tests/model/shared-types.smithy
=> Add AWS query protocol tests

smithy-aws-protocol-tests/model/rest-json/empty-input-output.smithy, smithy-aws-protocol-tests/model/rest-json/endpoint-host-trait.smithy, smithy-aws-protocol-tests/model/rest-json/errors.smithy, smithy-aws-protocol-tests/model/rest-json/http-headers.smithy, smithy-aws-protocol-tests/model/rest-json/http-labels.smithy, smithy-aws-protocol-tests/model/rest-json/http-payload.smithy, smithy-aws-protocol-tests/model/rest-json/http-prefix-headers.smithy, smithy-aws-protocol-tests/model/rest-json/http-query.smithy, smithy-aws-protocol-tests/model/rest-json/json-lists.smithy, smithy-aws-protocol-tests/model/rest-json/json-maps.smithy, smithy-aws-protocol-tests/model/rest-json/json-structs.smithy, smithy-aws-protocol-tests/model/rest-json/main.smithy
=> Add rest-json protocol tests

smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/empty-input-output.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/input-lists.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/input.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/main.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/xml-errors.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/xml-lists.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/ec2-query/xml-structs.smithy, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/manifest, smithy-aws-protocol-tests/src/main/resources/META-INF/smithy/query/xml-errors.smithy
=> Add aws.ec2 protocol tests

CHANGELOG.md, README.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst, smithy-codegen-freemarker/README.md
=> Bump version to 0.9.7

build.gradle.kts
=> Update Maven uri for HTTPS

build.gradle.kts
=> Simplify build.gradle.kts

smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCase.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestSuite.java, smithy-model/src/test/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCaseTest.java
=> Properly format test case results

smithy-model/src/main/java/software/amazon/smithy/model/loader/SmithyModelLexer.java, smithy-model/src/test/java/software/amazon/smithy/model/loader/SmithyModelLexerTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/loader/valid/traits.json
=> Fix dropping one character text block lines

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java
=> Add missing javadoc to IDL serializer

smithy-build/src/main/java/software/amazon/smithy/build/transforms/AbstractTraitRemoval.java
=> Add smithy-build trait namespace use warning

smithy-aws-protocol-tests/model/rest-json/http-labels.smithy, smithy-aws-protocol-tests/model/rest-xml/http-labels.smithy
=> Use %20 for label spaces

docs/source/quickstart.rst, docs/source/spec/core.rst, docs/source/spec/index.rst, docs/source/spec/language-specification.rst, docs/themes/smithy/landing.html, docs/themes/smithy/static/default.css_t
This commit makes various fixes and minor changes to both documentation
content and styling.
=> Tidy up docs

docs/source/spec/aws-restjson1-protocol.rst, docs/source/spec/core.rst, smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
=> Add restJson1 spec and minor tweaks

docs/source/spec/core/index.rst, docs/source/spec/index.rst
=> Rename core spec to smithy

docs/themes/smithy/landing.html
=> Make minor tweaks to the landing page

build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst, smithy-codegen-freemarker/README.md
Note: This does not include a full changelog and is not an indicator that this branch currently contains all changes for a version 1.0.0 release.
=> Bump version to 1.0.0

docs/source/spec/aws/aws-core.rst
=> Update aws.api#data data classification docs

docs/source/spec/core/lexical-structure.rst
=> Clarify control statements

smithy-model/src/main/java/software/amazon/smithy/model/Model.java, smithy-model/src/main/java/software/amazon/smithy/model/SourceLocation.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/AbstractShapeBuilder.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java
=> Minor tweaks

smithy-aws-apigateway-openapi/src/test/java/software/amazon/smithy/aws/apigateway/openapi/PayloadsTest.java, smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/payloads.json, smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/payloads.openapi.json
This PR adds additional testing for httpPayload traits when targeting a structure.
=> Test API Gateway httpPayload trait targeting structures

smithy-model/src/main/java/software/amazon/smithy/model/neighbor/UnreferencedShapes.java, smithy-model/src/main/java/software/amazon/smithy/model/neighbor/UnreferencedTraitDefinitions.java, smithy-model/src/main/java/software/amazon/smithy/model/neighbor/Walker.java, smithy-model/src/main/java/software/amazon/smithy/model/selector/RecursiveNeighborSelector.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ModelSerializer.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java, smithy-model/src/main/java/software/amazon/smithy/model/transform/ModelTransformer.java, smithy-model/src/test/java/software/amazon/smithy/model/neighbor/WalkerTest.java, smithy-utils/src/main/java/software/amazon/smithy/utils/FunctionalUtils.java
This commit also adds a helper method that reuses a constant Predicate
that always returns true.
=> Make neighbor traversal lazy

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/BlobLengthPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/CollectionLengthPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/FilteredPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/IdRefPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/MapLengthPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/MemberAndShapeTraitPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/PatternTraitPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringEnumPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/StringLengthPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampFormatPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/TimestampValidationStrategy.java
=> Emit node validation events with locations

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderVisitor.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShapeId.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeIdTest.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeTest.java
=> Add prioritized least recently added ShapeId cache

CHANGELOG.md, smithy-aws-apigateway-traits/README.md, smithy-aws-iam-traits/README.md, smithy-aws-protocol-tests/model/restJson1/endpoint-host-trait.smithy, smithy-aws-protocol-tests/model/restJson1/http-headers.smithy, smithy-aws-protocol-tests/model/restJson1/http-labels.smithy, smithy-aws-protocol-tests/model/restJson1/http-payload.smithy, smithy-aws-protocol-tests/model/restJson1/http-prefix-headers.smithy, smithy-aws-protocol-tests/model/restJson1/http-query.smithy, smithy-aws-protocol-tests/model/restXml/endpoint-host-trait.smithy, smithy-aws-protocol-tests/model/restXml/http-headers.smithy, smithy-aws-protocol-tests/model/restXml/http-labels.smithy, smithy-aws-protocol-tests/model/restXml/http-payload.smithy, smithy-aws-protocol-tests/model/restXml/http-prefix-headers.smithy, smithy-aws-protocol-tests/model/restXml/http-query.smithy, smithy-aws-traits/README.md
=> Fix various link and changelog issues

CHANGELOG.md
Corrects CHANGELOG date for 1.0.0 release
=> Fix 1.0.0 CHANGELOG date

docs/source/1.0/spec/core/lexical-structure.rst
=> Fix start_comment ABNF

CHANGELOG.md, docs/source/1.0/spec/core/http-traits.rst, smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude-traits.smithy
=> Allow document to be httpPayload target

CHANGELOG.md, build.gradle.kts, docs/source/guides/building-models/gradle-plugin.rst, docs/source/guides/converting-to-openapi.rst, smithy-codegen-freemarker/README.md
=> Bump version to 0.9.10

docs/source/quickstart.rst
=> Fix instance where current version was not being used

docs/themes/smithy/landing.html, docs/themes/smithy/layout.html, docs/themes/smithy/static/default.css_t, docs/themes/smithy/static/pygments.css, docs/themes/smithy/theme.conf
=> Update site color schemes and theme

docs/source/1.0/spec/core/lexical-structure.rst, docs/source/1.0/spec/core/shapes.rst
=> Make clarifications in spec

docs/source/1.0/guides/building-models/build-config.rst, docs/source/1.0/guides/building-models/index.rst
=> Clarify build tools

docs/README.md, docs/source/1.0/spec/core/http-traits.rst
* Update broken link to Sphinx project.
* Add link to endpoint trait spec upon first mention of endpoint in http protocol spec.
* Update description of endpoint based on PR feedback.
* Update wording of endpoint URI clarification based on PR feedback.
This PR is a re-do of https://github.com/awslabs/smithy/pull/463 due to some cyclic issue w/ git I was unable to rebase cleanly and so cherry picked into a new branch from head.
=> minor doc updates

smithy-model/src/main/java/software/amazon/smithy/model/neighbor/Walker.java
=> Return a stable order for the shape walker

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/trace/TracingSymbolProvider.java, smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/trace/TracingSymbolProviderTest.java
*Issue #, if available:* Lack of model traceability.
*Description of changes:* Added trace file creation abstractions.
=> Tracefile creation rebased

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/trace/package-info.java
*Issue #, if available:* Trace file classes are unstable.
*Description of changes:* Marked trace file classes as unstable.
=> Add SmithyUnstableApi trait to trace file objects

smithy-aws-protocol-tests/model/awsQuery/xml-lists.smithy, smithy-aws-protocol-tests/model/awsQuery/xml-maps.smithy, smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy, smithy-aws-protocol-tests/model/ec2Query/xml-lists.smithy, smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy, smithy-aws-protocol-tests/model/restXml/document-lists.smithy, smithy-aws-protocol-tests/model/restXml/document-maps.smithy, smithy-aws-protocol-tests/model/restXml/document-structs.smithy
* Adds protocol tests for self closing tag and empty xml tag
=> adds protocol tests for self closing tag and empty xml tag

smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysTrait.java, smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/RequiredActionsTrait.java, smithy-model/src/main/java/software/amazon/smithy/model/traits/StringListTrait.java, smithy-model/src/main/java/software/amazon/smithy/model/traits/TagsTrait.java, smithy-model/src/test/java/software/amazon/smithy/model/traits/TagsTraitTest.java
=> Ensure SourceLocations are on all StringListTrait traits

docs/source/1.0/spec/core/model.rst, docs/themes/smithy/landing.html, docs/themes/smithy/layout.html, docs/themes/smithy/static/default.css_t, docs/themes/smithy/static/pygments.css
=> Tweak styles, tagline, and underline links

docs/themes/smithy/static/default.css_t
=> Tweak header color and underline thickness

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/PaginatedTraitValidator.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/paginated-trait-test.errors
=> Downgrade page size required validator to warning

docs/source/1.0/spec/core/constraint-traits.rst
=> Clarify enum values cannot be empty

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
=> Add diff removal error for idempotencyToken trait

docs/source/1.0/spec/core/auth-traits.rst, docs/source/1.0/spec/core/idl.rst
=> Fix auth and node examples

docs/source/1.0/spec/waiters.rst
=> Clarify waiter retries example docs

smithy-utils/src/main/java/software/amazon/smithy/utils/CodeWriter.java, smithy-utils/src/test/java/software/amazon/smithy/utils/CodeWriterTest.java
=> Fix popState to honor expression start char

docs/source/1.0/spec/core/constraint-traits.rst
=> Clarify pattern trait matching

docs/source/1.0/spec/core/http-traits.rst
Add clarifications and examples to several HTTP traits, most importantly
to the httpLabel and httpQuery traits. These traits were updated so that
they require percent-encoding all reserved characters defined in
RFC3986. This is the behavior in use today by all AWS SDKs and protocol
tests, and if we ever need to support reserved characters in query strings
or labels, additional configuration or traits can be added.
=> Cleanup HTTP trait spec

docs/source/1.0/guides/generating-cloudformation-resources.rst, smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/CfnConfig.java, smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/CfnConfigTest.java
Also fixes a piece of incorrect documentation in the guide related to `jsonAdd`.
=> Fix an issue loading jsonAdd map from config

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/CfnConfig.java
=> Remove unused logger

config/checkstyle/checkstyle.xml
Update checkstyle to allow 2021 copyright
=> Update checkstyle to allow 2021 copyright

CONTRIBUTING.md
=> Remove CLA line from CONTRIBUTING.md

docs/source/1.0/spec/aws/aws-restxml-protocol.rst, smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.json
=> Update rest xml protocol docs

smithy-waiters/src/main/resources/META-INF/smithy/waiters.smithy
=> Add missing shape documentation for waiters

config/checkstyle/suppressions.xml
Updates checkstyle suppressions configuration to use current domain.
=> Update suppressions configuration

smithy-build/src/main/java/software/amazon/smithy/build/transforms/FlattenNamespaces.java, smithy-build/src/test/java/software/amazon/smithy/build/transforms/FlattenNamespacesTest.java
Fixes Config class docs and removes unused imports on test.
=> flattenNamespaces transform fixes

smithy-build/src/main/java/software/amazon/smithy/build/transforms/RenameShapes.java
=> Add final designation to RenameShapes transform

docs/source/1.0/spec/core/http-traits.rst, docs/themes/smithy/static/default.css_t
=> Make minor style tweaks to docs

docs/source/1.0/spec/core/model.rst
=> Add guidance on limiting namespaces per model

smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService
Re-alphabetizes the TraitService entries.
=> Re-order TraitService entries

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/NullableIndex.java, smithy-model/src/test/java/software/amazon/smithy/model/knowledge/NullableIndexTest.java
*Description of changes:* Add Document types to the list of inherently boxed shapes
=> Bugfix: Documents are inherently boxed

build.gradle, smithy-model/build.gradle
=> Fix Gradle 7 builds

smithy-aws-protocol-tests/model/restXml/http-payload.smithy
=> fix nested xml test

docs/source/1.0/spec/core/model.rst
This commit adds a little more context to document types and moves
merging models, model metadata, and node values to the bottom of the spec.
These sections previously came before defining shapes and traits, but
they're very much in the weeds for someone just trying to read the spec.
=> Make minor spec refactor and additions

docs/source/implementations.rst
=> Correct language used to implement Rust codegen

README.md
=> Point README.md links to the 1.0 Smithy guide

smithy-aws-protocol-tests/model/awsJson1_1/json-structs.smithy, smithy-aws-protocol-tests/model/awsQuery/xml-structs.smithy, smithy-aws-protocol-tests/model/ec2Query/xml-structs.smithy, smithy-aws-protocol-tests/model/restJson1/json-structs.smithy, smithy-aws-protocol-tests/model/restXml/document-structs.smithy
ec2 doesn't have the wrapper in the output.
=> Fix ec2 xml nan/infinity protocol test case bodies

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddCorsToGatewayResponses.java, smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-model.openapi.json, smithy-aws-apigateway-openapi/src/test/resources/software/amazon/smithy/aws/apigateway/openapi/cors-with-additional-headers.openapi.json
This adds the additional exposed headers to the default gateway reponses for cors.
=> Add exposed headers to gateway responses

smithy-aws-protocol-tests/model/restJson1/endpoint-paths.smithy, smithy-aws-protocol-tests/model/restJson1/http-query.smithy, smithy-aws-protocol-tests/model/restXml/http-query.smithy, smithy-aws-protocol-tests/model/restXml/services/s3.smithy
=> Fix various protocol test issues

docs/source/1.0/spec/core/behavior-traits.rst, smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTraitValidator.java, smithy-aws-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.errors, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/http-checksum-trait.json, smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpChecksumProperty.java, smithy-model/src/main/java/software/amazon/smithy/model/traits/HttpChecksumTrait.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpChecksumTraitValidator.java, smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.traits.TraitService, smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy, smithy-model/src/test/java/software/amazon/smithy/model/traits/HttpChecksumTraitTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-checksum-trait.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-checksum-trait.json
Status: Needs review
Description of changes:
[x] Adds httpChecksum trait to smithy.
[x] Adds test cases and docs
Replaces https://github.com/awslabs/smithy/pull/741
=> Adds httpChecksum trait support

designs/mixins.md
=> Add proposal for mixins

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EntityShape.java
=> Update EntityShape docs for clarity of use

docs/source/1.0/spec/core/stream-traits.rst, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/event-stream-with-errors.smithy
=> Clarify that event streams contain modeled errors

smithy-aws-protocol-tests/model/restJson1/malformedRequests/malformed-string.smithy
Some copy-paste mess ups fixed from the original PR.
=> Fix misconfigured malformed request tests

.github/workflows/ci.yml
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action
=> ci: enable Gradle wrapper validation

.github/workflows/ci.yml
=> chore(ci): use JDK 17

smithy-aws-cloudformation/src/main/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/RequiredMapper.java, smithy-aws-cloudformation/src/test/java/software/amazon/smithy/aws/cloudformation/schema/fromsmithy/mappers/RequiredMapperTest.java
=> Use name instead of path for CFN required

docs/source/1.0/spec/aws/aws-core.rst, docs/source/1.0/spec/aws/aws-iam.rst, smithy-aws-iam-traits/src/main/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndex.java, smithy-aws-iam-traits/src/test/java/software/amazon/smithy/aws/iam/traits/ConditionKeysIndexTest.java, smithy-aws-iam-traits/src/test/resources/software/amazon/smithy/aws/iam/traits/successful-condition-keys.smithy
=> Use iamResource name for condition keys

docs/source/1.0/spec/http-protocol-compliance-tests.rst, smithy-protocol-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
=> Documentation for httpMalformedRequestTests

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/ServiceValidator.java
=> De-dupe validation around conflicting names

smithy-cli/build.gradle
=> Use JDK 17 with smithy-cli

smithy-cli/build.gradle
=> Add apple silicon target for smithy cli

designs/default-zero-value.md
=> Add default trait design doc

docs/source/1.0/spec/aws/aws-json.rst.template, smithy-aws-protocol-tests/model/awsJson1_0/errors.smithy, smithy-aws-protocol-tests/model/awsJson1_1/errors.smithy, smithy-aws-protocol-tests/model/awsJson1_1/kitchen-sink.smithy, smithy-aws-protocol-tests/model/awsJson1_1/main.smithy
=> The awsJson protocols do not support jsonName trait

smithy-utils/src/main/java/software/amazon/smithy/utils/MapUtils.java, smithy-utils/src/test/java/software/amazon/smithy/utils/MapUtilsTest.java
=> Optimize MapUtils slightly

.github/workflows/ci.yml
=> Run CI on the IDL 2.0 branch

gradle/wrapper/gradle-wrapper.properties
=> gradle 7.3.3

smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/HttpMalformedRequestDefinition.java
=> Add non-optional method for malformed request test uri

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/protocols/ProtocolHttpPayloadValidator.java, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/protocols/aws-protocols-do-not-support-list-set-map-payloads.errors
=> Clarify aws http payload binding error

CHANGELOG.md
=> Update 1.18.1 changelog.

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/SensitiveTraitValidator.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait-target.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/sensitive-trait-target.smithy
=> Add warning for all sensitive trait on members

docs/source/1.0/guides/migrating-idl-1-to-2.rst, docs/source/1.0/spec/core/idl.rst, docs/source/1.0/spec/core/json-ast.rst, docs/source/1.0/spec/core/model.rst, docs/source/1.0/spec/core/traits.rst, docs/source/1.0/spec/core/traits/constraint-traits.rst.template, docs/source/1.0/spec/core/traits/type-refinement-traits.rst.template
This adds docs for the new enum shapes.
=> Add enum shape documentation

docs/source/1.0/spec/core/idl.rst, docs/source/1.0/spec/core/model.rst
=> Address doc feedback in #1032

docs/source/1.0/guides/converting-to-openapi.rst
=> Document which OpenAPI version is supported

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/HttpUriFormatValidator.java, smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-uri-format-invalid.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/http-uri-format-invalid.json
=> Validate that http uri uses ASCII characters

docs/source/1.0/spec/core/idl.rst, smithy-model/src/main/java/software/amazon/smithy/model/loader/AstModelLoader.java, smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelLoader.java, smithy-model/src/main/java/software/amazon/smithy/model/loader/Version.java
=>  Remove references to version 1.1 

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriter.java, smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriterDelegator.java, smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/writer/CodegenWriterFactory.java
*Description of changes:* Fix some deprecated classes without alternatives. Most deprecations use the doc annotation exclusively instead of mentioning it at the root—I updated these to match.
=> cleanup some deprecations without alternatives

docs/source/1.0/spec/core/selectors.rst
=> Clarify docs to say 'Attribute selectors' instead of 'Selector attributes'

docs/source/1.0/spec/core/constraint-traits.rst
=> Fix rst syntax for uniqueItems warning

smithy-model/src/main/java/software/amazon/smithy/model/knowledge/TextIndex.java, smithy-model/src/test/java/software/amazon/smithy/model/knowledge/TextIndexTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/knowledge/text-index.smithy
=> Make TestIndex tolerate synthetic traits

docs/source/1.0/guides/evolving-models.rst
Resolves https://github.com/awslabs/smithy/issues/1204
=> Add link to Smithy Diff from Evolving Models guide

smithy-model/src/main/java/software/amazon/smithy/model/selector/PathFinder.java, smithy-model/src/test/java/software/amazon/smithy/model/selector/PathFinderTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/selector/path-finder-recursion.json
=> Prevent infinite traversal in PathFinder

mkdocs
Fixes incorrect reference to pip3 and changes
diff command to correctly show new pages.
=> Fix mkdocs

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java, smithy-codegen-core/src/test/java/software/amazon/smithy/codegen/core/directed/CodegenDirectorTest.java, smithy-codegen-core/src/test/resources/software/amazon/smithy/codegen/core/directed/needs-sorting.smithy
=> Topologically sort shapes in directed codegen

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolWriter.java, smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CreateSymbolProviderDirective.java, smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateEnumDirective.java, smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/GenerateStructureDirective.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/BigDecimalShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/BigIntegerShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/BlobShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/BooleanShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ByteShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/DocumentShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/DoubleShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/FloatShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/IntegerShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ListShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/LongShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/MapShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/MemberShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/OperationShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ResourceShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ServiceShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/SetShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/ShortShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/StringShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/StructureShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/TimestampShape.java, smithy-model/src/main/java/software/amazon/smithy/model/shapes/UnionShape.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/ShapeVisitorDefaultTest.java, smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java
=> Fix typos and minor refactoring to rename some variables

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/SymbolWriter.java
=> Remove incorrect DocumentationWriter reference

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/UnionValidator.java, smithy-model/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, smithy-model/src/test/java/software/amazon/smithy/model/transform/ChangeShapeTypeTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/union-requires-members.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/union-requires-members.smithy
=> Validate unions have > 0 members

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
=> Use SymbolProvider.cache

smithy-codegen-core/src/main/java/software/amazon/smithy/codegen/core/directed/CodegenDirector.java
=> Encapsulate Walker inside generateShapesInService

designs/default-zero-value.md
=> Fix typo in date

smithy-cli/src/main/java/software/amazon/smithy/cli/Cli.java, smithy-cli/src/main/java/software/amazon/smithy/cli/CliError.java
=> Handle possible errors when restoring CLI logging

docs/source/1.0/spec/core/idl.rst
Fix broken mixins ref in target elision section.
=> Fix mixins ref

CHANGELOG.md
=> Fix release date for 1.22.0

docs/source-2.0/aws/aws-cloudformation.rst
Updated the docs summary for cfnDefaultValue to give more context on the _why_ and _when_ of this trait's usage/meaning. Also, provided a more meaningful resource example instead of the bar/foo example resource so it's more clear. 
=> Updating docs and example for cfnDefaultValue

README.md
Fixes location of favicon asset in README
=> Fix favicon location

README.md
Adds version statement to model in README.
=> Add version statement to model

README.md
=> Update README links to IDL 2.0

docs/source-2.0/guides/migrating-idl-1-to-2.rst, docs/source-2.0/index.rst, docs/source-2.0/spec/json-ast.rst
https://github.com/awslabs/smithy/issues/1343
=> Smithy 2.0 doc fixes

docs/source-2.0/guides/migrating-idl-1-to-2.rst, docs/source-2.0/quickstart.rst
Fixed some code highlighting issues in migration guide.
Fixed version number in sample `smithy-build.json` in quickstart.
=> Minor doc fixes

docs/README.md
Removed steps that were no longer supported by Makefile as of ba8d2f436566c888777ba119d53ecc854dffee69.
=> Update docs README

smithy-model/src/main/java/software/amazon/smithy/model/transform/ChangeShapeType.java, smithy-model/src/test/java/software/amazon/smithy/model/transform/ChangeShapeTypeTest.java
=> Ignore type changes to same type

CHANGELOG.md
=> Changelog for 1.25.0 release

docs/source-2.0/guides/migrating-idl-1-to-2.rst
=> Fix typo in migration guide

designs/defaults-and-model-evolution.md
=> Add some clarifications to revised default value design doc

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderTraitMap.java, smithy-model/src/main/java/software/amazon/smithy/model/loader/Version.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/DeprecatedTraitValidator.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/enum-can-be-deprecated-and-tagged.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enums/enum-shapes.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/enums/enum-trait-validation.errors
=> Only emit deprecation of enum trait in 2.0 models

docs/source-2.0/spec/streaming.rst
=> Remove unnecessary streamId from stream example

smithy-utils/src/main/java/software/amazon/smithy/utils/AbstractCodeWriter.java
The example for $C did not compile.
=> Minor fix to AbstractCodeWriter documentation

CHANGELOG.md
Amend changelog for 1.26.3 with additional commits.
=> Amend changelog for 1.26.3

docs/source-1.0/spec/core/behavior-traits.rst, docs/source-2.0/spec/behavior-traits.rst
=> Clarify service-level pagination configuration

docs/source-1.0/spec/core/idl.rst, docs/source-2.0/spec/idl.rst
=> Clarify that metadata has no namespace

smithy-aws-protocol-tests/model/restJson1/http-accept.smithy
*Issue #, if available:* https://github.com/awslabs/smithy/issues/1332
*Description of changes:* Add protocol tests for the new ACCEPT header behavior. 
=> Add tests for ACCEPT *

CHANGELOG.md
N/A
Update CHANGELOG.md for 1.26.5.
Referencing this PR: https://github.com/awslabs/smithy/pull/1538
=> Update CHANGELOG.md for 1.26.5

build.gradle, smithy-cli/build.gradle, smithy-cli/src/it/java/software/amazon/smithy/cli/MavenResolverTest.java, smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/aws-model/smithy-build.json, smithy-cli/src/it/resources/software/amazon/smithy/cli/projects/maven-auth/smithy-build.json, smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ClasspathCommand.java, smithy-cli/src/main/java/software/amazon/smithy/cli/commands/WarmupCommand.java
=> Attempt to fix CLI JAR publishing

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
N/A.
Update `paginated` trait `/items` path breaking change rule.
- [Smithy "Breaking change rules" documentation](https://smithy.io/2.0/spec/model.html#breaking-change-rules)
=> Update paginated trait /items breaking change rule

CHANGELOG.md
=> Update 1.27.0 changelog

docs/source-1.0/spec/core/model.rst, docs/source-2.0/spec/model.rst
N/A.
Fix typo for NOTE under breaking change rules.
=> Fix typo for NOTE under breaking change rules

smithy-diff/src/main/java/software/amazon/smithy/diff/evaluators/ModifiedTrait.java, smithy-diff/src/test/java/software/amazon/smithy/diff/evaluators/ModifiedTraitTest.java
This commit adds the DiffType and TraitId to the ValidationEventId emitted by the ModifiedTrait diff evaluator.
=> Add details to ModifiedTrait event id

smithy-model/src/main/java/software/amazon/smithy/model/shapes/EnumShape.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/EnumShapeTest.java
This fixes https://github.com/awslabs/smithy-language-server/issues/81
=> Add source location to Enum synthetic trait

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/validators/AuthSchemesValidator.java, smithy-rules-engine/src/main/resources/software/amazon/smithy/rulesengine/testutil/valid-rules/beta-auth-scheme.json, smithy-rules-engine/src/main/resources/software/amazon/smithy/rulesengine/testutil/valid-rules/manifest.txt, smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/IntegrationTest.java, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-standalone-validation-rules/beta-auth-scheme-missing-field.json, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/invalid-standalone-validation-rules/beta-auth-scheme-missing-field.json5
Relax rule engine validation to support test auth schemes
=> relax rule engine auth scheme validation to allow beta- prefix

smithy-protocols-traits/src/main/resources/META-INF/smithy/smithy.protocols.rpcv2.smithy
=> Make rpcv2 StringList @private

.github/workflows/sdk-codegen-ci.yml
Add smithy rust sdk to `sdk-codegen-ci.yml`
=> Add smithy rust sdk to sdk-codegen-ci.yml

smithy-protocols-traits/src/main/java/software/amazon/smithy/protocols/traits/Rpcv2Trait.java, smithy-protocols-traits/src/test/java/software/amazon/smithy/protocols/traits/Rpcv2TraitTest.java
=> Run code formatter

.github/workflows/ci.yml
=> Enable CI on rpcv2 branch

.gitignore, smithy-protocols-traits/src/main/java/software/amazon/smithy/protocols/traits/Rpcv2Trait.java, smithy-protocols-traits/src/main/java/software/amazon/smithy/protocols/traits/Rpcv2TraitValidator.java, smithy-protocols-traits/src/main/resources/META-INF/services/software.amazon.smithy.model.validation.Validator, smithy-protocols-traits/src/test/java/software/amazon/smithy/protocols/traits/Rpcv2TraitTest.java, smithy-protocols-traits/src/test/java/software/amazon/smithy/protocols/traits/TestRunnerTest.java, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/cbor-wire-format.errors, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/cbor-wire-format.smithy, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/eventStreamHttp-matches-http.errors, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/eventStreamHttp-matches-http.smithy
=> Implement Rpcv2TraitValidator and tests

smithy-model/src/main/java/software/amazon/smithy/model/traits/DefaultTrait.java
=> Fix javadoc for DefaultTrait

smithy-protocols-traits/src/main/java/software/amazon/smithy/protocols/traits/Rpcv2TraitValidator.java, smithy-protocols-traits/src/main/resources/META-INF/smithy/smithy.protocols.rpcv2.smithy, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/cbor-wire-format.errors, smithy-protocols-traits/src/test/resources/software/amazon/smithy/protocols/traits/errorfiles/cbor-wire-format.smithy
=> Move some validation to trait definition

smithy-aws-protocol-tests/model/restJson1/validation/malformed-uniqueItems.smithy
This PR updates the uniqueItems validation message protocol tests to make the message more direct.
=> Update validation message for uniqueItems

smithy-model/src/main/java/software/amazon/smithy/model/validation/validators/TargetValidator.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/resource-identifiers/resource-identifiers.json
=> Allow enum shapes as resource identifiers

smithy-aws-protocol-tests/model/awsJson1_1/datetime-offsets.smithy, smithy-aws-protocol-tests/model/awsJson1_1/fractional-seconds.smithy, smithy-aws-protocol-tests/model/restJson1/http-accept.smithy
=> Fix various protocol test warnings

docs/source-2.0/implementations.rst
Add smithy-rs to list of server implementations.
=> Add Rust server implementation

docs/source-1.0/guides/evolving-models.rst, docs/source-2.0/guides/evolving-models.rst
=> Add compatibility note to evolving models

README.md
=> Add language info to code fences in README

docs/source-1.0/spec/aws/aws-ec2-query-protocol.rst, docs/source-1.0/spec/aws/aws-json.rst.template, docs/source-1.0/spec/aws/aws-query-protocol.rst, docs/source-1.0/spec/aws/aws-restjson1-protocol.rst, docs/source-1.0/spec/aws/aws-restxml-protocol.rst, docs/source-2.0/aws/protocols/aws-ec2-query-protocol.rst, docs/source-2.0/aws/protocols/aws-json.rst.template, docs/source-2.0/aws/protocols/aws-query-protocol.rst, docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst, docs/source-2.0/aws/protocols/aws-restxml-protocol.rst
=> Add requestCompression to protocol supported traits

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/RangeTraitPlugin.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/detects-default-out-of-range.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/validators/defaults/detects-default-out-of-range.smithy
This reverts commit e6b3f309e7aa249e64eace143f9cc56f8bf7f29e.
=> Revert "Add hierarchical IDs for DefaultTrait collisions (#1754)"

docs/source-2.0/implementations.rst
=> Add smithy-dafny to code generators table

docs/source-2.0/spec/idl.rst
Fixes issue with recent grammar changes where when rendered, productions would extend past the margin.
=> Fix grammar rendering

smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturedToken.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/Formatter.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/SortUseStatements.java, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/awkward-comments.formatted.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/awkward-comments.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/section-statement-blank-lines.formatted.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/section-statement-blank-lines.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/sorts-use-statements-with-comments.formatted.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/sorts-use-statements-with-comments.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/sorts-use-statements.formatted.smithy, smithy-syntax/src/test/resources/software/amazon/smithy/syntax/formatter/sorts-use-statements.smithy
=> Sort use statements automatically when formatting

smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java
Should not include the tree node if not present.
=> Fix namespace statement parsing

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/FormatCommand.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturedToken.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/CapturingTokenizer.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/Formatter.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTree.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTreeLeaf.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/TokenTreeNode.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeCursor.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/TreeType.java, smithy-syntax/src/main/java/software/amazon/smithy/syntax/package-info.java, smithy-syntax/src/test/java/software/amazon/smithy/syntax/ParseAndFormatTest.java, smithy-syntax/src/test/java/software/amazon/smithy/syntax/TokenTreeNodeTest.java, smithy-syntax/src/test/java/software/amazon/smithy/syntax/TokenTreeTest.java, smithy-syntax/src/test/java/software/amazon/smithy/syntax/TreeCursorTest.java
Minor changes to different docs and APIs for smithy-syntax
=> Prep API for release

build.gradle, config/checkstyle/checkstyle.xml, gradle/wrapper/gradle-wrapper.properties, smithy-model/src/main/java/software/amazon/smithy/model/knowledge/IdentifierBindingIndex.java
=> Unblock Gradle 8 upgrade

docs/source-2.0/guides/building-models/build-config.rst
=> Remove out of date SNAPSHOT limitation

config/spotbugs/filter.xml, smithy-model/src/main/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCase.java, smithy-model/src/test/java/software/amazon/smithy/model/validation/testrunner/SmithyTestCaseTest.java
=> Improve message for invalid .errors entries

smithy-model/src/main/java/software/amazon/smithy/model/pattern/SmithyPattern.java, smithy-model/src/main/java/software/amazon/smithy/model/pattern/UriPattern.java, smithy-model/src/test/java/software/amazon/smithy/model/pattern/SmithyPatternTest.java
=> Improve segment parsing errors with offsets

docs/source-1.0/spec/aws/aws-core.rst, docs/source-2.0/aws/aws-core.rst, smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
Improve docId getter and documentation. Following up on post-merge comments from https://github.com/smithy-lang/smithy/pull/1863.
=> Improve docId getter and documentation

build.gradle
=> Include resource files in source jars

smithy-build/src/main/java/software/amazon/smithy/build/plugins/SourcesPlugin.java
=> Fix a potential resource leak

smithy-diff/README.md, smithy-diff/src/main/java/software/amazon/smithy/diff/ModelDiff.java, smithy-diff/src/test/java/software/amazon/smithy/diff/ModelDiffTest.java, smithy-diff/src/test/resources/software/amazon/smithy/diff/suppressions-a.smithy, smithy-diff/src/test/resources/software/amazon/smithy/diff/suppressions-b.smithy, smithy-model/src/main/java/software/amazon/smithy/model/loader/ModelValidator.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/ValidationEventDecorator.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/suppressions/ModelBasedEventDecorator.java, smithy-model/src/test/java/software/amazon/smithy/model/validation/suppressions/ModelBasedEventDecoratorTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/validation/suppressions/bad-severityOverrides.smithy, smithy-model/src/test/resources/software/amazon/smithy/model/validation/suppressions/bad-suppressions.smithy
=> Add support for suppressions to smithy-diff

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
Emit warning on addition of @required trait, as this could be indicative of a backwards incompatible change, even if nullability remains unchanged
=> Emit warning on addition of @required trait.

.github/workflows/stale-issues.yml
*Description of changes:* Add workflow to handle long running issues and auto-close given labels and time windows.
=> Add workflow to handle long running issues

.github/workflows/update-brew.yml
Update the update-brew workflow to use the updated repository URL.
=> Update release_prefix for migrated repo

docs/source-2.0/spec/idl.rst
=> Clarify how trait values are provided in IDL

smithy-aws-protocol-tests/model/restJson1/validation/malformed-pattern.smithy
=> Fix ReDOS malformed request test

docs/source-2.0/aws/aws-auth.rst
=> Clarify AWS + optional auth checking

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/evaluation/value/Value.java, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/literal/IntegerLiteral.java
=> Remove deprecated NumberNode method use

docs/source-2.0/aws/aws-auth.rst
=> Move sigv4 specific note to trait docs

smithy-aws-endpoints/src/test/resources/software/amazon/smithy/rulesengine/aws/language/functions/errorfiles/valid/is-virtual-hostable-s3-bucket.smithy, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/IsValidHostLabel.java, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/valid/valid-hostlabel.smithy
Add test cases to isValidHostLabel and isVirtualHostableS3Bucket
=> Add test cases to isValidHostLabel and isVirtualHostableS3Bucket

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/traits/CleanEndpointTestOperationInput.java, smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/traits/CleanEndpointTestOperationInputTest.java
=> Retain endpointTests trait if all cases removed

.github/workflows/update-brew.yml
=> Add token to checkout action in brew workflow

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/parameters/Parameter.java
=> Add missing template  override method

docs/source-2.0/additional-specs/rules-engine/parameters.rst
=> Add important notice for required contextParams

docs/source-2.0/aws/aws-core.rst, docs/source-2.0/spec/model-validation.rst, docs/source-2.0/spec/type-refinement-traits.rst
=> Add missing trait anchors

docs/source-2.0/aws/aws-endpoints-region.rst, docs/source-2.0/aws/index.rst
Add declarative endpoints traits documentation
=> Add declarative endpoints traits documentation

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/clientendpointdiscovery/ClientEndpointDiscoveryValidator.java, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/no-operations.errors, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/no-operations.smithy, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/unbound-operations.errors, smithy-aws-traits/src/test/resources/software/amazon/smithy/aws/traits/errorfiles/clientendpointdiscovery/unbound-operations.smithy
Adds extra event id subparts to ClientEndpointDiscovery
=> Add extra event id subparts to ClientEndpointDiscovery.

smithy-aws-endpoints/src/main/resources/software/amazon/smithy/rulesengine/aws/language/functions/partition/partitions.json
Sync partitions.json from released SDK version.
=> Sync partitions.json from released SDK version

smithy-build/src/main/java/software/amazon/smithy/build/PluginContext.java, smithy-build/src/test/java/software/amazon/smithy/build/PluginContextTest.java
=> Fix null pointer exception in PluginContext.toBuilder

smithy-model/src/main/java/software/amazon/smithy/model/validation/node/NodeValidatorPlugin.java, smithy-model/src/main/java/software/amazon/smithy/model/validation/node/UniqueItemsPlugin.java, smithy-model/src/test/java/software/amazon/smithy/model/validation/NodeValidationVisitorTest.java, smithy-model/src/test/resources/software/amazon/smithy/model/validation/node-validator.json
=> Add NodeValidationVisitor plugin for @uniqueItems

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/SdkServiceIdValidator.java, smithy-aws-traits/src/test/java/software/amazon/smithy/aws/traits/SdkServiceIdValidatorTest.java
Relax the service name validation to allow service names with just one character.
=> Relax the service name validation to allow one char names

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/traits/EndpointModifierIndex.java, smithy-aws-endpoints/src/test/java/software/amazon/smithy/rulesengine/aws/traits/EndpointModifierIndexTest.java
=> Fix toShapeId call in EndpointModifierIndex

docs/source-2.0/additional-specs/index.rst, docs/source-2.0/additional-specs/smoke-tests.rst, smithy-smoke-test-traits/src/main/resources/META-INF/smithy/smithy.test.smithy
=> Add docs page for smoke tests

docs/source-2.0/aws/protocols/aws-restjson1-protocol.rst, docs/source-2.0/aws/protocols/aws-restxml-protocol.rst, smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy
=> Add httpChecksumRequired to aws protocols

docs/source-2.0/aws/rules-engine/built-ins.rst, smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsBuiltIns.java, smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/language/functions/AwsRuleSetExtension.java, smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/validators/RuleSetAwsBuiltInValidator.java
Adds a new AWS Builtin for AccoutnIdEndpointMode.
=> Add builtin for AccountIdEndpointMode

smithy-model/src/main/java/software/amazon/smithy/model/validation/NodeValidationVisitor.java, smithy-protocol-test-traits/src/main/java/software/amazon/smithy/protocoltests/traits/ProtocolTestCaseValidator.java, smithy-smoke-test-traits/src/main/java/software/amazon/smithy/smoketests/traits/SmokeTestCaseValidator.java
Very minor API cleanup to NodeValidationVisitor to remove a TODO
=> Move allowOptionalNull to Feature

smithy-model/src/main/java/software/amazon/smithy/model/transform/ReplaceShapes.java, smithy-model/src/test/java/software/amazon/smithy/model/transform/ReplaceShapesTest.java
This commit further optimizes the ReplaceShapes transformer since it's used so heavily, even when loading models. This change also fixes a bug in how member removal was handled where members removed from enum and intEnum shapes were still left around as detached members in the updated Model.
=> Account for enum member removal and optimize

smithy-aws-endpoints/src/main/java/software/amazon/smithy/rulesengine/aws/validators/AwsSpecialCaseEndpointValidator.java, smithy-aws-protocol-tests/model/awsJson1_1/main.smithy, smithy-openapi/src/test/java/software/amazon/smithy/openapi/fromsmithy/protocols/AwsRestJson1ProtocolTest.java
=> Fix several minor warnings when building

smithy-model/src/main/java/software/amazon/smithy/model/loader/IdlModelLoader.java, smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/enums/enum-with-duplicates.smithy, smithy-model/src/test/resources/software/amazon/smithy/model/loader/invalid/enums/intEnum-with-duplicates.smithy
=> Fail when (int)enum conflicts are detected

smithy-cli/src/main/java/software/amazon/smithy/cli/commands/ValidationEventFormatOptions.java, smithy-cli/src/test/java/software/amazon/smithy/cli/commands/DiffCommandTest.java, smithy-cli/src/test/java/software/amazon/smithy/cli/commands/ValidateCommandTest.java
=> Fix CSV headers after moving line and column

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
This fixes some casing problems. The bad casing wasn't released, so nobody is broken by this change.
---
=> Fix casing of inferInlineIoSuffixes option

docs/source-2.0/guides/building-codegen/configuring-the-generator.rst, docs/source-2.0/guides/evolving-models.rst
* Fixes two minor formatting issues I found when looking at the docs.
* Locally built docs and confirmed formatting issues were resolved. 
---
=> Fix minor formatting issues

smithy-aws-protocol-tests/model/restXml/services/s3.smithy, smithy-build/src/main/java/software/amazon/smithy/build/processor/SmithyAnnotationProcessor.java
Clean up warnings when building the Smithy repository.
Fix issues and reduce noise when building.
Did a clean build and validated docs.
---
=> Minor build fixes

smithy-aws-protocol-tests/model/rpcV2/defaults.smithy
Add default value tests to ensure the client/server fills in default values when serializing/deserializing.
=> Add default value tests

README.md, docs/source-2.0/conf.py
This reverts commit 28c55df2f01ca42b9a836f09ab6f3be7f93f8566.
Reverts previous commit that added survey banner now that banner has been up for a month.
N/A
---
=> Remove survey banner

.github/workflows/ci.yml
=> Remove RPCv2 CI config

smithy-aws-protocol-tests/model/restXml/http-payload.smithy
=> Remove content-type from no XML body test

CONTRIBUTING.md
=> Add license header to CONTRIBUTING doc

smithy-model/src/main/resources/software/amazon/smithy/model/loader/prelude.smithy
Leftover from an apparent rename in #2156.
---
=> Fix referenced trait name

smithy-model/src/main/java/software/amazon/smithy/model/loader/LoaderShapeMap.java, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/detects-ignorable-duplicates.errors, smithy-model/src/test/resources/software/amazon/smithy/model/errorfiles/loader/detects-ignorable-duplicates.smithy
Resolves #2194 in combination with [severity overrides](https://smithy.io/2.0/spec/model-validation.html#severity-overrides)
* Unit tests
---
=> Emit NOTE on ignored duplicate shape

smithy-aws-apigateway-openapi/src/main/java/software/amazon/smithy/aws/apigateway/openapi/AddDefaultConfigSettings.java
opeanapi -> openapi
* What do these changes do? Fixes typo in logging message
* Why are they important? Typo bugged me when I was building
* How did you test these changes? N/A
---
=> Fix Typo in AddDefaultConfigSettings.java

smithy-aws-protocol-tests/model/restJson1/defaults.smithy, smithy-aws-protocol-tests/model/restJson1/main.smithy, smithy-aws-protocol-tests/model/restJson1/nested-defaults.smithy
Add defaults tests for restJson1 similar to AwsJson1_0 and CBOR
In smithy-ruby, not sure how to test here.
n/a
---
=> Add defaults tests for restJson1

smithy-aws-protocol-tests/model/restXml/services/s3.smithy
=> Fix issues with S3 dot segment tests

docs/source-2.0/additional-specs/rules-engine/specification.rst
=> Fix typo in endpoint tree rule docs

smithy-protocol-tests/model/rpcv2Cbor/cbor-structs.smithy
=> Remove debug urls

docs/source-2.0/guides/model-translations/converting-to-openapi.rst
Fix a minor grammatical error in the documentation.
They're not.
Didn't.
---
=> Fix a minor grammatical error

smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ArnIndex.java, smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/ServiceTrait.java
=> Fix legacy arn trait name usage

docs/Makefile, docs/source-2.0/guides/smithy-build-json.rst
=> Add note on smithy-build.json comments

docs/source-2.0/conf.py
- Removes banner added by #2344 
- Check generated doc files in CI
---
=> Remove hiring announcement

CHANGELOG.md
=> Update version 1.51.0 changelog

.github/workflows/make-docs.yml
Fix for https://github.com/smithy-lang/smithy/actions/runs/10706127088/job/29683307637
---
=> Do recursive copy to safely publish javadoc

smithy-aws-protocol-tests/model/restXml/main.smithy
=> Attach protocol test operation to service

docs/source-2.0/spec/json-ast.rst
=> Fix calling service version required in AST

docs/source-2.0/spec/json-ast.rst
=> Fix resource type typo in AST docs

docs/source-2.0/aws/aws-core.rst
This includes updates to the default checksum behavior associated with the use of this trait. 
---
=> Update the httpChecksum trait spec

docs/source-2.0/additional-specs/mqtt.rst
=> Expand MQTT acronym

docs/source-2.0/additional-specs/protocols/smithy-rpc-v2.rst, smithy-protocol-tests/model/rpcv2Cbor/cbor-lists.smithy, smithy-protocol-tests/model/rpcv2Cbor/cbor-maps.smithy, smithy-protocol-tests/model/rpcv2Cbor/cbor-structs.smithy, smithy-protocol-tests/model/rpcv2Cbor/defaults.smithy, smithy-protocol-tests/model/rpcv2Cbor/empty-input-output.smithy
=> Require an Accept header for RPCv2 requests

.gitignore, smithy-aws-traits/src/main/java/software/amazon/smithy/aws/traits/HttpChecksumTrait.java, smithy-aws-traits/src/main/resources/META-INF/smithy/aws.protocols.smithy
=> Add checksum algorithm to model enum

CHANGELOG.md
=> Bump version to 1.52.0

smithy-aws-protocol-tests/model/awsJson1_0/main.smithy, smithy-aws-protocol-tests/model/awsJson1_1/main.smithy, smithy-aws-protocol-tests/model/restJson1/main.smithy, smithy-aws-protocol-tests/model/shared-types.smithy, smithy-protocol-tests/model/shared-types.smithy
=> Add unbound operation validator for protocol tests

smithy-model/src/main/java/software/amazon/smithy/model/transform/CreateDedicatedInputAndOutput.java
Reduce build noise by downgrading log statement to `fine` level from `info`.
---
=> Downgrade noisy log statement

smithy-model/src/main/java/software/amazon/smithy/model/shapes/Shape.java
=> typo in shapeToBuilder comment

docs/source-2.0/java/quickstart.rst
=> Fix formatting error in quickstart.rst

docs/source-2.0/java/client/customization.rst, docs/source-2.0/java/client/generating-clients.rst, docs/source-2.0/java/client/plugins.rst
Corrects a number of minor issues with client guide rendering.
---
=> Touchup client guide rendering

docs/source-2.0/languages/java/client/dynamic-client.rst, docs/source-2.0/languages/java/client/index.rst, docs/source-2.0/languages/java/client/plugins.rst
Updates the Smithy-Java client guide based on initial feedback. 
Changes: 
- Move dynamic clients and codegen integrations later
- correct User-agent component table
- Update dynamic client guide.
---
=> Update layout of client guide based on feedback

smithy-model/src/main/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializer.java, smithy-model/src/test/java/software/amazon/smithy/model/shapes/SmithyIdlModelSerializerTest.java
=> Fix documentation being duplicated with dynamic doc trait

docs/source-2.0/guides/model-translations/converting-to-openapi.rst
Documents #2504 
Resolves #2481 
---
=> Document OpenAPI enumStrategy setting

smithy-build/src/main/resources/META-INF/services/software.amazon.smithy.build.ProjectionTransformer
The list is now sorted lexicographically as well to make it easier to maintain.
---
=> Add FlattenAndRemoveMixins to service provider

smithy-utils/src/main/java/software/amazon/smithy/utils/StringUtils.java
- Updates a handful of http links to https
---
=> Update http links to https in smithy-utils javadocs

docs/landing-page/public/locales/en/translation.json
=> Fix typo in landing page

smithy-aws-protocol-tests/model/restXmlWithNamespace/main.smithy
Aligned the tests to use the approach as other XML tests.
* Tested with the Smithy Kotlin SDK
---
=> Align restXml with namespace setup test with others

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/evaluation/value/Value.java
=> Fix bad endpoint Value javadoc links

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/evaluation/value/EndpointValue.java, smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/value/EndpointValueTest.java
=> Fix node loading and serialization of endpoint value

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/ParseUrl.java
First, I copied the IP address detection code from https://github.com/aws/aws-sdk-java-v2/blob/93f914840a071fb162693d1ebd753803281253cf/codegen/src/main/resources/software/amazon/awssdk/codegen/rules2/RuleUrl.java.resource#L58-L111 This should be much more performant than catching integer parsing errors.
I also exposed this method and the method for normalizing a path as a public utility method. This will allow me to use the method directly in smithy-java.
* Issue #, if applicable (see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for a list of …
=> Add public static utilities to ParseUrl

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/IsValidHostLabel.java, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/Substring.java
Adds static methods I can use in smithy-java for substring and isValidHostLabel. Improves isValidHostLabel performance.
---
=> Add static methods for more endpoint rules functions

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/ParseUrl.java
=> Avoid StringBuilder in normalizePath

smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/IsValidHostLabel.java, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/Substring.java
=> Improve rules functions

CHANGELOG.md
Update changelog to reflect the revert of PR #2666 
---
=> Update changelog to reflect the revert

docs/source-2.0/spec/model.rst
- Correct wording in documentation
---
=> Add missing important word in model.rst

docs/source-2.0/additional-specs/rules-engine/standard-library.rst, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/CoreExtension.java, smithy-rules-engine/src/main/java/software/amazon/smithy/rulesengine/language/syntax/expressions/functions/Split.java, smithy-rules-engine/src/test/java/software/amazon/smithy/rulesengine/language/syntax/functions/SplitTest.java, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-split-cannot-be-empty.errors, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/invalid/invalid-split-cannot-be-empty.smithy, smithy-rules-engine/src/test/resources/software/amazon/smithy/rulesengine/language/errorfiles/valid/split.smithy
=> Add split function to rules engine
